{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inputViewController"},{"kind":"text","text":" "},{"kind":"internalParam","text":"ivc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","preciseIdentifier":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController","text":"KeyboardInputViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"spaceDragGestureHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DragGestureHandler","preciseIdentifier":"s:14KeyboardKitPro18DragGestureHandlerP","text":"DragGestureHandler"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"spaceDragSensitivity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SpaceDragSensitivity","preciseIdentifier":"s:14KeyboardKitPro20SpaceDragSensitivityO","text":"SpaceDragSensitivity"},{"kind":"text","text":" = .medium)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"inputViewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view controller to use."}]}]},{"name":"spaceDragGestureHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A custom space drag gesture handler, if any."}]}]},{"name":"spaceDragSensitivity","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The space drag sensitivity to use, by default "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SpaceDragSensitivity\/medium"},{"type":"text","text":"."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/init(inputviewcontroller:spacedraggesturehandler:spacedragsensitivity:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/init(inputViewController:spaceDragGestureHandler:spaceDragSensitivity:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Create a standard keyboard action handler, using a view"},{"type":"text","text":" "},{"type":"text","text":"controller to setup all dependencies."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inputViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardInputViewController","preciseIdentifier":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"spaceDragGestureHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DragGestureHandler","preciseIdentifier":"s:14KeyboardKitPro18DragGestureHandlerP"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"spaceDragSensitivity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SpaceDragSensitivity","preciseIdentifier":"s:14KeyboardKitPro20SpaceDragSensitivityO"},{"kind":"text","text":")"}],"title":"init(inputViewController:spaceDragGestureHandler:spaceDragSensitivity:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:14KeyboardKitPro08StandardA13ActionHandlerC19inputViewController016spaceDragGestureF00jK11SensitivityAcA0a5InputhI0C_AA0klF0_pSgAA05SpacekM0Otcfc","modules":[{"name":"KeyboardKitPro"}]},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler"]]},"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SpaceDragSensitivity/medium":{"role":"symbol","title":"SpaceDragSensitivity.medium","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"medium"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SpaceDragSensitivity\/medium","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/spacedragsensitivity\/medium"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/DragGestureHandler":{"role":"symbol","title":"DragGestureHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DragGestureHandler"}],"abstract":[{"type":"text","text":"This protocol can be implemented by classes that can handle"},{"type":"text","text":" "},{"type":"text","text":"drag gestures from a start position to a current one."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DragGestureHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DragGestureHandler"}],"url":"\/documentation\/keyboardkitpro\/draggesturehandler"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"role":"symbol","title":"KeyboardInputViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardInputViewController"}],"abstract":[{"type":"text","text":"This class extends "},{"type":"codeVoice","code":"UIInputViewController"},{"type":"text","text":" with KeyboardKit"},{"type":"text","text":" "},{"type":"text","text":"specific functionality."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardInputViewController"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","title":"KeyboardKitPro","abstract":[{"type":"text","text":"KeyboardKit Pro helps you build custom keyboard extensions for iOS and iPadOS."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler/init(inputViewController:spaceDragGestureHandler:spaceDragSensitivity:)":{"role":"symbol","title":"init(inputViewController:spaceDragGestureHandler:spaceDragSensitivity:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inputViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardInputViewController","preciseIdentifier":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"spaceDragGestureHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DragGestureHandler","preciseIdentifier":"s:14KeyboardKitPro18DragGestureHandlerP"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"spaceDragSensitivity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SpaceDragSensitivity","preciseIdentifier":"s:14KeyboardKitPro20SpaceDragSensitivityO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Create a standard keyboard action handler, using a view"},{"type":"text","text":" "},{"type":"text","text":"controller to setup all dependencies."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/init(inputViewController:spaceDragGestureHandler:spaceDragSensitivity:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/init(inputviewcontroller:spacedraggesturehandler:spacedragsensitivity:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SpaceDragSensitivity":{"role":"symbol","title":"SpaceDragSensitivity","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SpaceDragSensitivity"}],"abstract":[{"type":"text","text":"This enum can be used to change the drag sensitivity of the"},{"type":"text","text":" "},{"type":"text","text":"spacebar."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SpaceDragSensitivity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SpaceDragSensitivity"}],"url":"\/documentation\/keyboardkitpro\/spacedragsensitivity"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler":{"role":"symbol","title":"StandardKeyboardActionHandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StandardKeyboardActionHandler"}],"abstract":[{"type":"text","text":"This standard keyboard action handler is used by default by"},{"type":"text","text":" "},{"type":"text","text":"KeyboardKit and provides a standard way of handling actions."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StandardKeyboardActionHandler"}],"url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title","value":"KeyboardInputViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments","value":[{"kind":"identifier","text":"KeyboardInputViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1StandardKeyboardActionHandler\/title","value":"StandardKeyboardActionHandler"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1StandardKeyboardActionHandler\/fragments","value":[{"kind":"identifier","text":"StandardKeyboardActionHandler"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}