{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkitpro\/gesturebutton\/keyboardstate(from:)"]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/GestureButton","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/GestureButton\/View-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"View.keyboardState(from:)"},{"type":"text","text":"."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardState","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardInputViewController","preciseIdentifier":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController"},{"kind":"text","text":") -> "},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"},{"text":"\n","kind":"text"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/GestureButton\/keyboardState(from:)"},"deprecationSummary":[{"inlineContent":[{"text":"Use the non-controller based modifier instead.","type":"text"}],"type":"paragraph"}],"metadata":{"platforms":[],"extendedModule":"SwiftUICore","modules":[{"name":"KeyboardKitPro","relatedModules":["SwiftUICore"]}],"roleHeading":"Instance Method","externalID":"s:7SwiftUI4ViewP14KeyboardKitProE13keyboardState4fromQrAD0d5InputC10ControllerC_tF::SYNTHESIZED::s:14KeyboardKitPro13GestureButtonV","symbolKind":"method","title":"keyboardState(from:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"keyboardState","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"KeyboardInputViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}]},"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/GestureButton":{"url":"\/documentation\/keyboardkitpro\/gesturebutton","title":"GestureButton","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/GestureButton","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GestureButton"}],"kind":"symbol","abstract":[{"text":"This button can be used to trigger gesture-based actions.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"GestureButton","kind":"identifier"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","url":"\/documentation\/keyboardkitpro","abstract":[{"type":"text","text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI."}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","title":"KeyboardKitPro","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/GestureButton/View-Implementations":{"abstract":[],"type":"topic","url":"\/documentation\/keyboardkitpro\/gesturebutton\/view-implementations","title":"View Implementations","kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/GestureButton\/View-Implementations"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"type":"topic","title":"KeyboardInputViewController","kind":"symbol","role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"KeyboardInputViewController","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","navigatorTitle":[{"kind":"identifier","text":"KeyboardInputViewController"}],"abstract":[{"text":"This is the main input controller in a KeyboardKit-based","type":"text"},{"type":"text","text":" "},{"text":"keyboard extension.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/GestureButton/keyboardState(from:)":{"abstract":[],"url":"\/documentation\/keyboardkitpro\/gesturebutton\/keyboardstate(from:)","deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"keyboardState"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController","kind":"typeIdentifier","text":"KeyboardInputViewController"},{"kind":"text","text":") -> "},{"text":"some","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"}],"title":"keyboardState(from:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/GestureButton\/keyboardState(from:)","type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title","value":"KeyboardInputViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments","value":[{"kind":"identifier","text":"KeyboardInputViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/navigatorTitle","value":[{"text":"KeyboardInputViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}