{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/GestureButton\/withEnvironment(fromController:)"},"variants":[{"paths":["\/documentation\/keyboardkitpro\/gesturebutton\/withenvironment(fromcontroller:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"View.withEnvironment(fromController:)"},{"type":"text","text":"."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"withEnvironment"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromController"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController","text":"KeyboardInputViewController"},{"text":") -> ","kind":"text"},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"},{"text":"\n","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"metadata":{"symbolKind":"method","modules":[{"relatedModules":["SwiftUICore"],"name":"KeyboardKitPro"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withEnvironment"},{"text":"(","kind":"text"},{"text":"fromController","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"KeyboardInputViewController","preciseIdentifier":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController"},{"kind":"text","text":") -> "},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}],"platforms":[],"roleHeading":"Instance Method","role":"symbol","extendedModule":"SwiftUICore","title":"withEnvironment(fromController:)","externalID":"s:7SwiftUI4ViewP14KeyboardKitProE15withEnvironment14fromControllerQrAD0d5InputcJ0C_tF::SYNTHESIZED::s:14KeyboardKitPro13GestureButtonV"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/GestureButton","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/GestureButton\/View-Implementations"]]},"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/GestureButton/withEnvironment(fromController:)":{"deprecated":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/GestureButton\/withEnvironment(fromController:)","title":"withEnvironment(fromController:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"withEnvironment","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromController"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"KeyboardInputViewController","preciseIdentifier":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"}],"kind":"symbol","abstract":[],"url":"\/documentation\/keyboardkitpro\/gesturebutton\/withenvironment(fromcontroller:)","type":"topic","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/GestureButton/View-Implementations":{"abstract":[],"type":"topic","url":"\/documentation\/keyboardkitpro\/gesturebutton\/view-implementations","title":"View Implementations","kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/GestureButton\/View-Implementations"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"type":"topic","title":"KeyboardInputViewController","kind":"symbol","role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"KeyboardInputViewController","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","navigatorTitle":[{"kind":"identifier","text":"KeyboardInputViewController"}],"abstract":[{"text":"This is the main input controller in a KeyboardKit-based","type":"text"},{"type":"text","text":" "},{"text":"keyboard extension.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/GestureButton":{"url":"\/documentation\/keyboardkitpro\/gesturebutton","title":"GestureButton","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/GestureButton","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GestureButton"}],"kind":"symbol","abstract":[{"text":"This button can be used to trigger gesture-based actions.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"GestureButton","kind":"identifier"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","url":"\/documentation\/keyboardkitpro","abstract":[{"type":"text","text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI."}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","title":"KeyboardKitPro","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"KeyboardInputViewController","op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"KeyboardInputViewController"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments"},{"value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/navigatorTitle","op":"replace"}]}]}