{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unmarkText"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/keyboardkitpro\/previewtextdocumentproxy\/unmarktext()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/previewtextdocumentproxy\/unmarktext()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/unmarkText()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UITextDocumentProxy.unmarkText()"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unmarkText"},{"kind":"text","text":"()"}],"title":"unmarkText()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@KeyboardKitPro@objc(cs)PreviewTextDocumentProxy(im)unmarkText","modules":[{"name":"KeyboardKitPro"}],"navigatorTitle":[{"kind":"identifier","text":"unmarkText"}]},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy"]]},"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/PreviewTextDocumentProxy/unmarkText()":{"role":"symbol","title":"unmarkText()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unmarkText"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/unmarkText()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unmarkText"}],"url":"\/documentation\/keyboardkitpro\/previewtextdocumentproxy\/unmarktext()"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/PreviewTextDocumentProxy":{"role":"symbol","title":"PreviewTextDocumentProxy","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviewTextDocumentProxy"}],"abstract":[{"type":"text","text":"This document proxy can be used in SwiftUI previews."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PreviewTextDocumentProxy"}],"url":"\/documentation\/keyboardkitpro\/previewtextdocumentproxy"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","title":"KeyboardKitPro","abstract":[{"type":"text","text":"KeyboardKit Pro helps you build custom keyboard extensions for iOS and iPadOS."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"unmarkText"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unmarkText"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"unmarkText"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1unmarkText()\/title","value":"unmarkText"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1unmarkText()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unmarkText"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy\/title","value":"PreviewTextDocumentProxy"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy\/fragments","value":[{"kind":"identifier","text":"PreviewTextDocumentProxy"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}