{"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In KeyboardKit, the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction"},{"type":"text","text":" enum defines a set of keyboard-specific actions that can be bound to buttons and handled with a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit will by default create a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler"},{"type":"text","text":" and apply it to the input controller’s "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/keyboardActionHandler"},{"type":"text","text":". You can replace it with a custom handler to customize how actions are handled."}]},{"anchor":"Action-types","level":2,"type":"heading","text":"Action types"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction"},{"type":"text","text":" enum can be grouped into categories. The descriptions below are the standard behaviors when actions are handled with a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler"},{"type":"text","text":"."}]},{"anchor":"Inputs","level":4,"type":"heading","text":"Inputs"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/character(_:)"},{"type":"text","text":" - inserts a text character when released."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/characterMargin(_:)"},{"type":"text","text":" - inserts a text character when released, rendered as empty space."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/emoji(_:)"},{"type":"text","text":" - inserts an emoji when released."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/space"},{"type":"text","text":" - inserts a space when released and moves the cursor when long pressed."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/tab"},{"type":"text","text":" - inserts a tab when released."}]}]}]},{"anchor":"Actions","level":4,"type":"heading","text":"Actions"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/backspace"},{"type":"text","text":" - deletes backwards when pressed, and repeats that action until it’s released."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/dismissKeyboard"},{"type":"text","text":" - dismisses the keyboard when released."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/emojiCategory(_:)"},{"type":"text","text":" - can be used to show a specific emoji category."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/keyboardType(_:)"},{"type":"text","text":" - changes the keyboard type when pressed."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/moveCursorBackward"},{"type":"text","text":" - moves the input cursor back one step when released."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/moveCursorForward"},{"type":"text","text":" - moves the input cursor forward one step when released."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/nextKeyboard"},{"type":"text","text":" - triggers the keyboard switcher action when tapped and long pressed."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/nextLocale"},{"type":"text","text":" - triggers the locale switcher action when long pressed and released."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/shift(currentCasing:)"},{"type":"text","text":" - changes the alphabetic keyboard casing when released and double tapped."}]}]}]},{"anchor":"System","level":4,"type":"heading","text":"System"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/command"},{"type":"text","text":" - represents a command (⌘) key."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/control"},{"type":"text","text":" - represents a control (⌃) key."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/dictation"},{"type":"text","text":" - represents a dictation key."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/escape"},{"type":"text","text":" - represents an escape (esc) key."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/function"},{"type":"text","text":" - represents a function (fn) key."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/option"},{"type":"text","text":" - represents an option (⌥) key."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/primary(_:)"},{"type":"text","text":" - represents a primary button, e.g. "},{"type":"codeVoice","code":"return"},{"type":"text","text":", "},{"type":"codeVoice","code":"go"},{"type":"text","text":", "},{"type":"codeVoice","code":"search"},{"type":"text","text":" etc."}]}]}]},{"anchor":"Custom","level":4,"type":"heading","text":"Custom"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/custom(named:)"},{"type":"text","text":" - a custom action that you can handle in any way you want."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/image(description:keyboardImageName:imageName:)"},{"type":"text","text":" - can be used to refer to an image asset."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/none"},{"type":"text","text":"- a “no action” placeholder action."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/settings"},{"type":"text","text":" - a custom action that can be used to e.g. show a settings screen."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/systemImage(description:keyboardImageName:imageName:)"},{"type":"text","text":" - can be used to refer to a system image (SF Symbol)."}]}]}]},{"anchor":"How-to-handle-keyboard-actions","level":2,"type":"heading","text":"How to handle keyboard actions"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Keyboard actions can be handled with a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler"},{"type":"text","text":", which is a protocol that can be implemented by any class that can be used to handle keyboard actions."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can trigger actions programmatically by calling "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler\/handle(_:on:)"},{"type":"text","text":" with a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardGesture"},{"type":"text","text":" and a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction"},{"type":"text","text":":"}]},{"type":"codeListing","syntax":"swift","code":["class MyClass {","","    init(actionHandler: KeyboardActionHandler) {","        self.actionHandler = actionHandler","    }","","    private let actionHandler: KeyboardActionHandler","","    func stopEditingText() {","        actionHandler.handle(.release, on: .dismissKeyboard)","    } ","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Keyboard actions can also be triggered by keyboard-specific gestures that are applied to buttons. If you use a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboard"},{"type":"text","text":", action gestures will be automatically applied to the various buttons."}]},{"anchor":"How-to-create-a-custom-action-handler","level":2,"type":"heading","text":"How to create a custom action handler"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can create a custom "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler"},{"type":"text","text":" to customize how keyboard actions are handled, or to handle actions that have no default behavior."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can create a custom action handler by inheriting the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler"},{"type":"text","text":" base class, which gives you a lot of functionality for free, or by implementing "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler"},{"type":"text","text":" from scratch."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For instance, here is a custom action handler that inherits "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler"},{"type":"text","text":" and extends it with the capabilities to copy and save images:"}]},{"type":"codeListing","syntax":"swift","code":["class MyActionHandler: StandardKeyboardActionHandler {","    ","    public init(inputViewController: KeyboardInputViewController) {","        super.init(inputViewController: inputViewController)","    }","    ","    override func action(","        for gesture: KeyboardGesture, ","        on action: KeyboardAction","    ) -> KeyboardAction.GestureAction? {","        let standard = super.action(for: gesture, on: action)","        switch gesture {","        case .longPress: return longPressAction(for: action) ?? standard","        case .release: return releaseAction(for: action) ?? standard","        default: return standard","        }","    }","    ","    func longPressAction(for action: KeyboardAction) -> KeyboardAction.GestureAction? {","        switch action {","        case .image(_, _, let imageName): return { [weak self] _ in self?.saveImage(named: imageName) }","        default: return nil","        }","    }","    ","    func releaseAction(for action: KeyboardAction) -> KeyboardAction.GestureAction? {","        switch action {","        case .image(_, _, let imageName): return { [weak self] _ in self?.copyImage(named: imageName) }","        default: return nil","        }","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To use this action handler instead of the standard one, just set the input controller’s "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/keyboardActionHandler"},{"type":"text","text":" to the new handler:"}]},{"type":"codeListing","syntax":"swift","code":["class MyKeyboardViewController: KeyboardInputViewController {","","    override func viewDidLoad() {","        keyboardActionHandler = MyActionHandler(inputViewController: self)","        super.viewDidLoad()","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This will make KeyboardKit use your custom implementation instead of the standard one."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/keyboardkitpro\/actions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/actions"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This article describes the KeyboardKit action engine and how to use it."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Actions","role":"article","modules":[{"name":"KeyboardKitPro"}]},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"seeAlsoSections":[{"title":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Appearance","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Extensions","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Routing","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/RTL","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings"],"generated":true}],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/image(description:keyboardImageName:imageName:)":{"role":"symbol","title":"KeyboardAction.image(description:keyboardImageName:imageName:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":"("},{"kind":"externalParam","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"keyboardImageName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"imageName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Can be used to refer to an image asset."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/image(description:keyboardImageName:imageName:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/image(description:keyboardimagename:imagename:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard":{"role":"article","title":"Keyboard","abstract":[{"type":"text","text":"This article describes the KeyboardKit keyboard types and how to use them."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboard"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/option":{"role":"symbol","title":"KeyboardAction.option","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"option"}],"abstract":[{"type":"text","text":"Represents an option (⌥) key."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/option","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/option"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts":{"role":"article","title":"Callouts","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/callouts"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SystemKeyboard":{"role":"symbol","title":"SystemKeyboard","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SystemKeyboard"}],"abstract":[{"type":"text","text":"This keyboard can be used to create alphabetic, numeric and"},{"type":"text","text":" "},{"type":"text","text":"symbolic keyboards that mimic the native iOS keyboard."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SystemKeyboard"}],"url":"\/documentation\/keyboardkitpro\/systemkeyboard"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback":{"role":"article","title":"Feedback","abstract":[{"type":"text","text":"This article describes the KeyboardKit feedback engine and how to use it to trigger audio and haptic feedback."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/feedback"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy-Extensions":{"role":"article","title":"Proxy Extensions","abstract":[{"type":"text","text":"This article describes how KeyboardKit extends "},{"type":"codeVoice","code":"UITextDocumentProxy"},{"type":"text","text":" with a lot of additional functionality."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Extensions","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/proxy-extensions"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/none":{"role":"symbol","title":"KeyboardAction.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[{"type":"text","text":"A placeholder action that does nothing and should not be rendered."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/none","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/none"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/tab":{"role":"symbol","title":"KeyboardAction.tab","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tab"}],"abstract":[{"type":"text","text":"Inserts a tab when released."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/tab","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/tab"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization":{"role":"article","title":"Localization","abstract":[{"type":"text","text":"This article describes the KeyboardKit localization model and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/localization"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/emojiCategory(_:)":{"role":"symbol","title":"KeyboardAction.emojiCategory(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"emojiCategory"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"EmojiCategory","preciseIdentifier":"s:14KeyboardKitPro13EmojiCategoryO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Can be used to show a specific emoji category."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/emojiCategory(_:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/emojicategory(_:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/systemImage(description:keyboardImageName:imageName:)":{"role":"symbol","title":"KeyboardAction.systemImage(description:keyboardImageName:imageName:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"keyboardImageName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"imageName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Can be used to refer to a system image (SF Symbol)."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/systemImage(description:keyboardImageName:imageName:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/systemimage(description:keyboardimagename:imagename:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/RTL":{"role":"article","title":"RTL","abstract":[{"type":"text","text":"KeyboardKit supports RTL (right-to-left) locales, which means that it supports locales like "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale\/arabic"},{"type":"text","text":",  "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale\/persian"},{"type":"text","text":" etc."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/RTL","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/rtl"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/characterMargin(_:)":{"role":"symbol","title":"KeyboardAction.characterMargin(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"characterMargin"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Inserts a text character when released, but is rendered as empty space."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/characterMargin(_:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/charactermargin(_:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","title":"KeyboardKitPro","abstract":[{"type":"text","text":"KeyboardKit Pro helps you build custom keyboard extensions for iOS and iPadOS."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete":{"role":"article","title":"Autocomplete","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/autocomplete"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardGesture":{"role":"symbol","title":"KeyboardGesture","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardGesture"}],"abstract":[{"type":"text","text":"This enum defines the various ways a user can interact with"},{"type":"text","text":" "},{"type":"text","text":"keyboard actions, using KeyboardKit’s built-in interactions."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardGesture","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardGesture"}],"url":"\/documentation\/keyboardkitpro\/keyboardgesture"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Appearance":{"role":"article","title":"Appearance","abstract":[{"type":"text","text":"This article describes the KeyboardKit appearance engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Appearance","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/appearance"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/character(_:)":{"role":"symbol","title":"KeyboardAction.character(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"character"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Inserts a text character when released."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/character(_:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/character(_:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/escape":{"role":"symbol","title":"KeyboardAction.escape","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"escape"}],"abstract":[{"type":"text","text":"Represents an escape (esc) key."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/escape","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/escape"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/dictation":{"role":"symbol","title":"KeyboardAction.dictation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dictation"}],"abstract":[{"type":"text","text":"Represents a dictation key."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/dictation","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/dictation"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardActionHandler/handle(_:on:)":{"role":"symbol","title":"handle(_:on:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"KeyboardGesture","preciseIdentifier":"s:14KeyboardKitPro0A7GestureO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardAction","preciseIdentifier":"s:14KeyboardKitPro0A6ActionO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Handle a certain "},{"type":"codeVoice","code":"gesture"},{"type":"text","text":" on a certain "},{"type":"codeVoice","code":"action"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler\/handle(_:on:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardactionhandler\/handle(_:on:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/command":{"role":"symbol","title":"KeyboardAction.command","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"command"}],"abstract":[{"type":"text","text":"Represents a command (⌘) key."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/command","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/command"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/nextLocale":{"role":"symbol","title":"KeyboardAction.nextLocale","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextLocale"}],"abstract":[{"type":"text","text":"Triggers the locale switcher action when long pressed and released."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/nextLocale","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/nextlocale"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/keyboardActionHandler":{"role":"symbol","title":"keyboardActionHandler","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardActionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardActionHandler","preciseIdentifier":"s:14KeyboardKitPro0A13ActionHandlerP"}],"abstract":[{"type":"text","text":"This action handler is used to handle actions that will"},{"type":"text","text":" "},{"type":"text","text":"be triggered when the keyboard is being."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/keyboardActionHandler","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/keyboardactionhandler"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/function":{"role":"symbol","title":"KeyboardAction.function","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"function"}],"abstract":[{"type":"text","text":"Represents a function (fn) key."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/function","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/function"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Previews":{"role":"article","title":"Previews","abstract":[{"type":"text","text":"This article describes how KeyboardKit makes it easy to preview keyboard-specific views."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/previews"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/primary(_:)":{"role":"symbol","title":"KeyboardAction.primary(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"primary"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ReturnType","preciseIdentifier":"s:14KeyboardKitPro0A6ActionO10ReturnTypeO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Represents a primary return button, e.g. "},{"type":"codeVoice","code":"return"},{"type":"text","text":", "},{"type":"codeVoice","code":"go"},{"type":"text","text":", "},{"type":"codeVoice","code":"search"},{"type":"text","text":" etc."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/primary(_:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/primary(_:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards":{"role":"article","title":"External Keyboards","abstract":[{"type":"text","text":"This article describes the KeyboardKit external keyboard engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/external-keyboards"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/keyboardType(_:)":{"role":"symbol","title":"KeyboardAction.keyboardType(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardType"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"KeyboardType","preciseIdentifier":"s:14KeyboardKitPro0A4TypeO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Changes the keyboard type when pressed."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/keyboardType(_:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/keyboardtype(_:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/emoji(_:)":{"role":"symbol","title":"KeyboardAction.emoji(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"emoji"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Emoji","preciseIdentifier":"s:14KeyboardKitPro5EmojiV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Inserts an emoji when released."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/emoji(_:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/emoji(_:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/control":{"role":"symbol","title":"KeyboardAction.control","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"control"}],"abstract":[{"type":"text","text":"Represents a control (⌃) key."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/control","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/control"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/settings":{"role":"symbol","title":"KeyboardAction.settings","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"settings"}],"abstract":[{"type":"text","text":"A custom action that can be used to e.g. show a settings screen."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/settings","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/settings"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Input":{"role":"article","title":"Input","abstract":[{"type":"text","text":"This article describes the KeyboardKit input set engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/input"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/backspace":{"role":"symbol","title":"KeyboardAction.backspace","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"backspace"}],"abstract":[{"type":"text","text":"Deletes backwards when pressed, and repeats until released."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/backspace","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/backspace"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/custom(named:)":{"role":"symbol","title":"KeyboardAction.custom(named:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"custom"},{"kind":"text","text":"("},{"kind":"externalParam","text":"named"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A custom action that you can handle in any way you want."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/custom(named:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/custom(named:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction":{"role":"symbol","title":"KeyboardAction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardAction"}],"abstract":[{"type":"text","text":"This enum defines keyboard-specific actions that correspond"},{"type":"text","text":" "},{"type":"text","text":"to actions that can be found on various keyboards."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardAction"}],"url":"\/documentation\/keyboardkitpro\/keyboardaction"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/space":{"role":"symbol","title":"KeyboardAction.space","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"space"}],"abstract":[{"type":"text","text":"Inserts a space when released and moves the cursor when long pressed."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/space","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/space"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/shift(currentCasing:)":{"role":"symbol","title":"KeyboardAction.shift(currentCasing:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"shift"},{"kind":"text","text":"("},{"kind":"externalParam","text":"currentCasing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardCase","preciseIdentifier":"s:14KeyboardKitPro0A4CaseO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Changes the keyboard type to "},{"type":"codeVoice","code":".alphabetic(.uppercased)"},{"type":"text","text":" when released and "},{"type":"codeVoice","code":".capslocked"},{"type":"text","text":" when double tapped."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/shift(currentCasing:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/shift(currentcasing:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardActionHandler":{"role":"symbol","title":"KeyboardActionHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardActionHandler"}],"abstract":[{"type":"text","text":"This protocol can be implemented by classes that can handle"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction"},{"type":"text","text":" events."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardActionHandler"}],"url":"\/documentation\/keyboardkitpro\/keyboardactionhandler"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLocale/arabic":{"role":"symbol","title":"KeyboardLocale.arabic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"arabic"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale\/arabic","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardlocale\/arabic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/dismissKeyboard":{"role":"symbol","title":"KeyboardAction.dismissKeyboard","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissKeyboard"}],"abstract":[{"type":"text","text":"Dismisses the keyboard when released."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/dismissKeyboard","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/dismisskeyboard"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler":{"role":"symbol","title":"StandardKeyboardActionHandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StandardKeyboardActionHandler"}],"abstract":[{"type":"text","text":"This standard keyboard action handler is used by default by"},{"type":"text","text":" "},{"type":"text","text":"KeyboardKit and provides a standard way of handling actions."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StandardKeyboardActionHandler"}],"url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/moveCursorBackward":{"role":"symbol","title":"KeyboardAction.moveCursorBackward","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveCursorBackward"}],"abstract":[{"type":"text","text":"Moves the input cursor back one step when released."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/moveCursorBackward","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/movecursorbackward"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLocale/persian":{"role":"symbol","title":"KeyboardLocale.persian","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"persian"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale\/persian","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardlocale\/persian"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/nextKeyboard":{"role":"symbol","title":"KeyboardAction.nextKeyboard","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextKeyboard"}],"abstract":[{"type":"text","text":"Represents a keyboard switcher (🌐) button and triggers the keyboard switch action when long pressed and released."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/nextKeyboard","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/nextkeyboard"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/moveCursorForward":{"role":"symbol","title":"KeyboardAction.moveCursorForward","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveCursorForward"}],"abstract":[{"type":"text","text":"Moves the input cursor forward one step when released."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/moveCursorForward","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/movecursorforward"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures":{"role":"article","title":"Gestures","abstract":[{"type":"text","text":"This article describes the KeyboardKit gesture engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/gestures"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout":{"role":"article","title":"Layouts","abstract":[{"type":"text","text":"This article describes the KeyboardKit keyboard layout engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/layout"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Settings":{"role":"article","title":"Settings","abstract":[{"type":"text","text":"This article describes the KeyboardKit settings utilities and how to use them."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/settings"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis":{"role":"article","title":"Emojis","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji model and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/emojis"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Routing":{"role":"article","title":"Routing","abstract":[{"type":"text","text":"This article describes how KeyboardKit adds ways for you to route text from the main app to other text fields within the keyboard."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Routing","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/routing"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Appearance","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Extensions","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Routing","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/RTL","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1StandardKeyboardActionHandler\/title","value":"StandardKeyboardActionHandler"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1StandardKeyboardActionHandler\/fragments","value":[{"kind":"identifier","text":"StandardKeyboardActionHandler"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}