{"kind":"article","metadata":{"images":[{"identifier":"Page.png","type":"card"}],"color":{"standardColorIdentifier":"blue"},"role":"article","modules":[{"name":"KeyboardKitPro"}],"roleHeading":"Article","title":"Actions"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"variants":[{"paths":["\/documentation\/keyboardkitpro\/actions-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/actions-article"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit action engine."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"seeAlsoSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Colors-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Images-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"generated":true,"title":"Features"}],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"content","content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"inlineContent":[{"type":"text","text":"In KeyboardKit, the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","isActive":true},{"type":"text","text":" enum defines keyboard-specific actions, that can be triggered by the keyboard or by code, and handled with a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler","isActive":true},{"text":".","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"👑 ","type":"text"},{"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","type":"reference","isActive":true},{"type":"text","text":" extends the action handler, and makes it register the most recently used emojis in a way that automatically updates the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiCategory\/frequent","isActive":true},{"type":"text","text":" category. Information about Pro features can be found at the end of this article."}]},{"anchor":"Keyboard-actions","level":2,"type":"heading","text":"Keyboard actions"},{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction"},{"text":" enum defines many keyboard-specific actions, for instance:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/character(_:)","isActive":true,"type":"reference"},{"type":"text","text":" - triggers a character text insertion."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/backspace"},{"text":" - triggers a backspace deletion.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/dismissKeyboard","isActive":true},{"text":" - dismisses the keyboard.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/diacritic(_:)","isActive":true},{"text":" - trigger a diacritic text insertion.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/keyboardType(_:)","isActive":true},{"type":"text","text":" - changes the keyboard type."}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/nextKeyboard","isActive":true,"type":"reference"},{"text":" - triggers the system keyboard switcher.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/nextLocale","type":"reference","isActive":true},{"text":" - triggers the locale switcher action.","type":"text"}]}]}],"type":"unorderedList"},{"inlineContent":[{"type":"text","text":"See the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","isActive":true,"type":"reference"},{"text":" for a list of all available action types.","type":"text"}],"type":"paragraph"},{"text":"Keyboard action handlers","level":2,"type":"heading","anchor":"Keyboard-action-handlers"},{"type":"paragraph","inlineContent":[{"text":"In KeyboardKit, a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler"},{"type":"text","text":" can be used to handle actions, autocomplete, and to trigger audio & haptic feedback."}]},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit automatically creates an instance of ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/StandardHandler","type":"reference","isActive":true},{"type":"text","text":" and injects it into "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","isActive":true,"type":"reference"},{"type":"text","text":". You can replace it at any time, as described further down."}]},{"text":"How to trigger keyboard actions","level":2,"anchor":"How-to-trigger-keyboard-actions","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit automatically triggers actions when a user interacts with the keyboard, or when certain system events happen. You can intercept these actions with a custom action handler, to perform any logic you want."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can trigger actions programmatically by calling any of the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler\/handle(_:on:)","isActive":true,"type":"reference"},{"type":"text","text":" functions to trigger an action with an optional gesture:"}]},{"syntax":"swift","code":["func doStuff(with handler: KeyboardActionHandler) {","    handler.handle(.backspace)","    handler.handle(.press, on: .character(\"a\")","    handler.handle(.release, on: .dismissKeyboard)","}"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"text":"Keyboard actions can also be triggered by a keyboard ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Button","isActive":true,"type":"reference"},{"text":" or by applying the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/View\/keyboardButton(_:)","type":"reference"},{"text":" view modifier to any view:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["Text(\"Button\")","    .keyboardButton(...)"]},{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboard","isActive":true},{"type":"text","text":" applies this modifier to all its buttons, to make them support gestures for press, release, long press, repeat, etc."}]},{"text":"How to handle autocomplete suggestions","anchor":"How-to-handle-autocomplete-suggestions","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler","isActive":true},{"type":"text","text":" can also handle "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/Suggestion","isActive":true,"type":"reference"},{"type":"text","text":"s, which are triggered when tapping items in an autocomplete toolbar:"}]},{"type":"codeListing","code":["func doStuff(with handler: KeyboardActionHandler) {","    let suggestion = Autocomlete.Suggestion(text: \"Hello\")","    handler.handle(suggestion)","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This will by default insert the suggestion into the text document proxy and reset autocomplete state. You can customize this behavior by creating a custom action handler."}]},{"type":"heading","anchor":"How-to-create-a-custom-action-handler","text":"How to create a custom action handler","level":2},{"type":"paragraph","inlineContent":[{"text":"You can create a custom ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler","isActive":true,"type":"reference"},{"type":"text","text":" to customize how certain actions are handled, and to handle actions that don’t have any default handling, like "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/image","isActive":true},{"type":"text","text":"."}]},{"inlineContent":[{"text":"You can implement ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler","type":"reference"},{"text":" from scratch, or inherit and customize the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/StandardHandler","isActive":true},{"type":"text","text":". For instance, here’s a custom action handler that inherits "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/StandardHandler"},{"text":" and prints when space is pressed:","type":"text"}],"type":"paragraph"},{"code":["class CustomActionHandler: StandardActionHandler {","","    open override func handle(","        _ gesture: KeyboardGesture, ","        on action: KeyboardAction","    ) {","        if gesture == .press && action == .space {","            print(\"Pressed space!\")","        }","        super.handle(gesture, on: action) ","    }","}"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To use this handler instead of the standard one, just inject it into "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","isActive":true,"type":"reference"},{"type":"text","text":":"}]},{"type":"codeListing","syntax":"swift","code":["class KeyboardViewController: KeyboardInputViewController {","","    override func viewDidLoad() {","        services.actionHandler = CustomActionHandler(inputViewController: self)","        super.viewDidLoad()","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This will make KeyboardKit use your custom implementation instead of the standard one."}]},{"level":2,"text":"👑 KeyboardKit Pro","type":"heading","anchor":"👑-KeyboardKit-Pro"},{"inlineContent":[{"overridingTitleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","isActive":true,"type":"reference","overridingTitle":"KeyboardKit Pro"},{"type":"text","text":" injects an "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/StandardHandler\/emojiRegistrationAction","type":"reference","isActive":true},{"type":"text","text":" function into the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/StandardHandler"},{"type":"text","text":" and uses it to automatically register emojis as you use them, which will automatically update the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiCategory\/frequent","isActive":true},{"text":" ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiCategory","isActive":true,"type":"reference"},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"text":"This means that the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboard","type":"reference","isActive":true},{"type":"text","text":" is automatically updated with the most recently used emojis when emoji actions are triggered."}],"type":"paragraph"}]}],"references":{"Page.png":{"variants":[{"url":"\/images\/Page.png","traits":["1x","light"]}],"alt":"Page icon","type":"image","identifier":"Page.png"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/dismissKeyboard":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"dismissKeyboard","kind":"identifier"}],"abstract":[{"type":"text","text":"Dismisses the keyboard when released."}],"url":"\/documentation\/keyboardkitpro\/keyboardaction\/dismisskeyboard","title":"KeyboardAction.dismissKeyboard","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/dismissKeyboard"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation-Article":{"kind":"article","title":"Dictation","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","url":"\/documentation\/keyboardkitpro\/dictation-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/backspace":{"abstract":[{"type":"text","text":"Deletes backwards when pressed, and repeats until released."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"backspace","kind":"identifier"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/backspace","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/backspace","title":"KeyboardAction.backspace"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Essentials":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials","kind":"article","type":"topic","abstract":[{"text":"This article describes the essential parts of KeyboardKit.","type":"text"}],"title":"Essentials","url":"\/documentation\/keyboardkitpro\/essentials","role":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/nextKeyboard":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/nextKeyboard","title":"KeyboardAction.nextKeyboard","url":"\/documentation\/keyboardkitpro\/keyboardaction\/nextkeyboard","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A system keyboard switcher that triggers on release and long press."}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextKeyboard","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/StandardHandler/emojiRegistrationAction":{"title":"emojiRegistrationAction","url":"\/documentation\/keyboardkitpro\/keyboardaction\/standardhandler\/emojiregistrationaction","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/StandardHandler\/emojiRegistrationAction","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"emojiRegistrationAction"},{"kind":"text","text":": (("},{"text":"Emoji","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro5EmojiV"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"abstract":[{"text":"The action to use to register emojis, if any.","type":"text"}],"type":"topic","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy-Article":{"kind":"article","images":[{"type":"card","identifier":"Page.png"}],"title":"Proxy Utilities","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","url":"\/documentation\/keyboardkitpro\/proxy-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit proxy engine and its utilities."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Device-Article":{"kind":"article","title":"Device Utilities","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit device utilities."}],"url":"\/documentation\/keyboardkitpro\/device-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"kind":"article","images":[{"type":"card","identifier":"Page.png"}],"title":"Layout","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}],"url":"\/documentation\/keyboardkitpro\/layout-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Text-Input-Article":{"kind":"article","images":[{"type":"card","identifier":"Page.png"}],"title":"Text Input Support","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit text input engine."}],"url":"\/documentation\/keyboardkitpro\/text-input-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AI-Article":{"type":"topic","url":"\/documentation\/keyboardkitpro\/ai-article","abstract":[{"text":"This article describes the KeyboardKit AI support capabilities.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","title":"AI Support","images":[{"type":"card","identifier":"Page.png"}],"kind":"article","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Navigation-Article":{"kind":"article","images":[{"type":"card","identifier":"Page.png"}],"title":"Navigation","role":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/navigation-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit navigation engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Previews-Article":{"kind":"article","images":[{"type":"card","identifier":"Page.png"}],"title":"Previews","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit preview engine."}],"url":"\/documentation\/keyboardkitpro\/previews-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Settings-Article":{"kind":"article","images":[{"type":"card","identifier":"Page.png"}],"title":"Settings","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","url":"\/documentation\/keyboardkitpro\/settings-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit settings engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards-Article":{"kind":"article","images":[{"type":"card","identifier":"Page.png"}],"title":"External Keyboards","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","url":"\/documentation\/keyboardkitpro\/external-keyboards-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit external keyboard engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/nextLocale":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Triggers a locale switcher action on release and menu on long press.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"nextLocale","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardaction\/nextlocale","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/nextLocale","title":"KeyboardAction.nextLocale"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","kind":"article","type":"topic","abstract":[{"text":"This article describes the KeyboardKit gesture engine.","type":"text"}],"title":"Gestures","url":"\/documentation\/keyboardkitpro\/gestures-article","role":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/EmojiCategory/frequent":{"abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"frequent","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiCategory\/frequent","title":"EmojiCategory.frequent","role":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/emojicategory\/frequent"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Colors-Article":{"kind":"article","images":[{"identifier":"Page.png","type":"card"}],"title":"Colors","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Colors-Article","abstract":[{"text":"This article describes the KeyboardKit color engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/colors-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction":{"kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardaction","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"KeyboardAction","kind":"identifier"}],"title":"KeyboardAction","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardAction"}],"abstract":[{"text":"This enum defines keyboard-specific actions, and is also","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"serving as a namespace for keyboard action-related types."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Styling-Article":{"kind":"article","images":[{"identifier":"Page.png","type":"card"}],"title":"Styling","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","url":"\/documentation\/keyboardkitpro\/styling-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit styling engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AutocompleteService":{"url":"\/documentation\/keyboardkitpro\/autocompleteservice","navigatorTitle":[{"text":"AutocompleteService","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutocompleteService"}],"type":"topic","title":"AutocompleteService","abstract":[{"type":"text","text":"This protocol can be implemented by any classes that can"},{"type":"text","text":" "},{"type":"text","text":"perform autocomplete as the user types."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteService","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"kind":"article","images":[{"type":"card","identifier":"Page.png"}],"title":"Callouts","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","url":"\/documentation\/keyboardkitpro\/callouts-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"kind":"article","images":[{"identifier":"Page.png","type":"card"}],"title":"Localization","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","abstract":[{"text":"This article describes the KeyboardKit localization engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/localization-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/StandardHandler":{"title":"KeyboardAction.StandardHandler","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"StandardHandler"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"StandardHandler","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardaction\/standardhandler","abstract":[{"type":"text","text":"This class provides a standard way to handle actions"},{"text":" ","type":"text"},{"text":"that are triggered by the keyboard.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/StandardHandler","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Host-Article":{"title":"Host Utilities","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","images":[{"type":"card","identifier":"Page.png"}],"url":"\/documentation\/keyboardkitpro\/host-article","abstract":[{"type":"text","text":"This article describes how KeyboardKit can identify the host application."}],"role":"article","type":"topic","kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/character(_:)":{"abstract":[{"text":"Inserts a text character when released.","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"character","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"KeyboardAction.character(_:)","type":"topic","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardaction\/character(_:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/character(_:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/EmojiCategory":{"title":"EmojiCategory","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"EmojiCategory"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"EmojiCategory","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/emojicategory","abstract":[{"text":"This enum defines the standard emoji categories, as well as","type":"text"},{"text":" ","type":"text"},{"text":"their emojis.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiCategory","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Status-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","kind":"article","type":"topic","title":"Status","abstract":[{"text":"This article describes the KeyboardKit status engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/status-article","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/services":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","title":"services","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"services","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V","text":"Keyboard"},{"kind":"text","text":"."},{"text":"Services","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V8ServicesC"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/services","abstract":[{"type":"text","text":"The default set of keyboard-specific services."}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/App-Article":{"kind":"article","images":[{"identifier":"Page.png","type":"card"}],"title":"App Utilities","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","url":"\/documentation\/keyboardkitpro\/app-article","abstract":[{"text":"This article describes the KeyboardKit app-specific utilities.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Images-Article":{"kind":"article","images":[{"type":"card","identifier":"Page.png"}],"title":"Images","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Images-Article","url":"\/documentation\/keyboardkitpro\/images-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit keyboard image engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardActionHandler/handle(_:on:)":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler\/handle(_:on:)","abstract":[{"text":"Handle a certain keyboard action gesture.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handle"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A13ActionHandlerP7Gesturea","text":"Gesture","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"on","kind":"externalParam"},{"kind":"text","text":": "},{"text":"KeyboardAction","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A6ActionO"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardactionhandler\/handle(_:on:)","required":true,"kind":"symbol","title":"handle(_:on:)","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Button":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Button","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Button","title":"Keyboard.Button","abstract":[{"text":"This view mimics a native keyboard button.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboard\/button","navigatorTitle":[{"text":"Button","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","kind":"article","type":"topic","title":"Emojis","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"url":"\/documentation\/keyboardkitpro\/emojis-article","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete/Suggestion":{"url":"\/documentation\/keyboardkitpro\/autocomplete\/suggestion","navigatorTitle":[{"kind":"identifier","text":"Suggestion"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Suggestion","kind":"identifier"}],"type":"topic","title":"Autocomplete.Suggestion","abstract":[{"text":"This struct represents a suggestion that is returned","type":"text"},{"type":"text","text":" "},{"type":"text","text":"by an "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteService","isActive":true,"type":"reference"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/Suggestion","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","kind":"article","type":"topic","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"title":"Feedback","url":"\/documentation\/keyboardkitpro\/feedback-article","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUI/View/keyboardButton(_:)":{"role":"symbol","kind":"symbol","type":"topic","title":"keyboardButton(_:)","deprecated":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/View\/keyboardButton(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"keyboardButton","kind":"identifier"},{"kind":"text","text":"("},{"text":"Keyboard","preciseIdentifier":"s:14KeyboardKitPro0A0V","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V11ButtonStyleV","text":"ButtonStyle"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}],"url":"\/documentation\/keyboardkitpro\/swiftui\/view\/keyboardbutton(_:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/image":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"image","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"s:7SwiftUI5ImageV"},{"text":"?","kind":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardaction\/image","abstract":[{"type":"text","text":"The image to which the action refers, if any."}],"title":"image","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","url":"\/documentation\/keyboardkitpro","type":"topic","title":"KeyboardKitPro","abstract":[{"type":"text","text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI."}],"role":"collection","kind":"symbol"},"https://github.com/KeyboardKit/KeyboardKitPro":{"type":"link","titleInlineContent":[{"text":"KeyboardKit Pro","type":"text"}],"url":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","title":"KeyboardKit Pro","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SystemKeyboard":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SystemKeyboard"}],"navigatorTitle":[{"text":"SystemKeyboard","kind":"identifier"}],"title":"SystemKeyboard","kind":"symbol","abstract":[{"text":"This keyboard can be used to mimic a native iOS keyboard.","type":"text"}],"role":"symbol","url":"\/documentation\/keyboardkitpro\/systemkeyboard","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboard","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/EmojiKeyboard":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboard","url":"\/documentation\/keyboardkitpro\/emojikeyboard","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"EmojiKeyboard"}],"abstract":[{"type":"text","text":"This view mimics a native emoji keyboard."}],"role":"symbol","title":"EmojiKeyboard","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EmojiKeyboard"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/diacritic(_:)":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"diacritic","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Keyboard","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A0V9DiacriticV","kind":"typeIdentifier","text":"Diacritic"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"A diacritic action, that will replace any previous match when release."}],"url":"\/documentation\/keyboardkitpro\/keyboardaction\/diacritic(_:)","title":"KeyboardAction.diacritic(_:)","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/diacritic(_:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardActionHandler":{"type":"topic","navigatorTitle":[{"text":"KeyboardActionHandler","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardactionhandler","kind":"symbol","abstract":[{"type":"text","text":"This protocol can be implemented by any classes that can"},{"text":" ","type":"text"},{"text":"handle triggered ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction"},{"text":" events.","type":"text"}],"title":"KeyboardActionHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardActionHandler"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/keyboardType(_:)":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Changes the keyboard type when pressed.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"keyboardType","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V","text":"Keyboard"},{"text":".","kind":"text"},{"text":"KeyboardType","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V0A4TypeO"},{"text":")","kind":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardaction\/keyboardtype(_:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/keyboardType(_:)","title":"KeyboardAction.keyboardType(_:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete-Article":{"kind":"article","images":[{"identifier":"Page.png","type":"card"}],"title":"Autocomplete","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","url":"\/documentation\/keyboardkitpro\/autocomplete-article","abstract":[{"text":"This article describes the KeyboardKit autocomplete engine.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Themes-Article":{"images":[{"identifier":"Page.png","type":"card"}],"title":"Themes","abstract":[{"text":"This article describes the KeyboardKit theme engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/themes-article","kind":"article","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Colors-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Images-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"generated":true,"title":"Features"}],"path":"\/seeAlsoSections"}]}]}