{"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","interfaceLanguage":"swift"},"metadata":{"title":"AI Support","modules":[{"name":"KeyboardKitPro"}],"roleHeading":"Article","role":"article","images":[{"type":"card","identifier":"Page.png"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"article","abstract":[{"text":"This article describes the KeyboardKit AI support capabilities.","type":"text"}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"title":"Articles","anchor":"Articles"}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"variants":[{"paths":["\/documentation\/keyboardkitpro\/ai-article"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkitpro\/ai-article"]}],"sections":[],"primaryContentSections":[{"content":[{"level":2,"type":"heading","anchor":"overview","text":"Overview"},{"inlineContent":[{"type":"text","text":"Apple’s native keyboard APIs lack many features that are needed to build AI-based features, for instance to read an entire document to perform tasks like spellchecking & proofreading, or to let users type text within the keyboard itself."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"👑 "},{"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","type":"reference","isActive":true},{"type":"text","text":" unlocks these capabilities to make it possible to read the full document and type in a text field within the keyboard."}],"type":"paragraph"},{"anchor":"Full-Document-Reader","text":"Full Document Reader","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Apple’s native text document proxy doesn’t return all the text within the document. It instead cuts off the available text at any time, e.g. at the previous or next paragraph. This makes it hard to provide AI-based features that require more context."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro therefore unlocks "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/UIKit\/UITextDocumentProxy\/fullDocumentContext(config:)"},{"type":"text","text":" proxy extensions that let you read "},{"type":"strong","inlineContent":[{"text":"all","type":"text"}]},{"type":"text","text":" text from the proxy:"}]},{"code":["let proxy = keyboardContext.textDocumentProxy","let result = try await proxy.fullDocumentContext()"],"syntax":"swift","type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This will provide you with all the text before and after the input cursor, as well as an aggregate of all the available text in the document."}]},{"inlineContent":[{"type":"text","text":"See the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","isActive":true},{"text":" article for more information.","type":"text"}],"type":"paragraph"},{"anchor":"Next-Word-Prediction","type":"heading","text":"Next Word Prediction","level":2},{"type":"paragraph","inlineContent":[{"text":"Apple’s native text prediction utilities stopped supporting next word prediction in iOS 16. It instead only provides predictions on already typed text, without any (known) way to get next word predictions.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro therefore unlocks ways to perform next word prediction via 3rd party AI services. The easiest way to enable next word prediction, is to add a Claude- or OpenAI-based "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/NextWordPredictionRequest","isActive":true},{"type":"text","text":" to your "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp"},{"text":":","type":"text"}]},{"syntax":"swift","type":"codeListing","code":["extension KeyboardApp {","","    static var keyboardKitDemo: KeyboardApp {","        KeyboardApp(","            ...","            autocomplete: .init(","                nextWordPredictionRequest: .claude(apiKey: \"your-key-here\")","            )","        )","    }","}"]},{"inlineContent":[{"text":"Users can then enable ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/isNextWordPredictionEnabled","isActive":true,"type":"reference"},{"type":"text","text":" to allow the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/LocalAutocompleteService","isActive":true,"type":"reference"},{"type":"text","text":" to perform predictions."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"See the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","isActive":true,"type":"reference"},{"text":" article for more information and important considerations.","type":"text"}],"type":"paragraph"},{"type":"heading","anchor":"Text-Input","text":"Text Input","level":2},{"inlineContent":[{"type":"text","text":"Apple’s native input controller & text document proxy don’t let you type in text fields within the keyboard. Instead, text will be sent to the main app even if a text field in the keyboard is focused. This makes it hard to let user perform AI-based prompting within the keyboard."}],"type":"paragraph"},{"inlineContent":[{"text":"KeyboardKit Pro therefore unlocks ways to let users type within a keyboard extension, without needing you to write any additional code:","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["extension MyView: View {","","    @EnvironmentObject var context: KeyboardContext","","    @State var text = \"\"","","    var body: some View {","        KeyboardTextField(","            text: $text, ","            keyboardContext: context","        )","    }","}"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The keyboard-specific text components will automatically manage text routing and only take proxy ownership while they are focused."}]},{"type":"paragraph","inlineContent":[{"text":"See the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","isActive":true},{"text":" article for more information.","type":"text"}]}],"kind":"content"}],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis-Article":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","role":"article","kind":"article","images":[{"identifier":"Page.png","type":"card"}],"title":"Emojis","url":"\/documentation\/keyboardkitpro\/emojis-article","abstract":[{"text":"This article describes the KeyboardKit emoji engine.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Text-Input-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","role":"article","kind":"article","type":"topic","images":[{"type":"card","identifier":"Page.png"}],"url":"\/documentation\/keyboardkitpro\/text-input-article","title":"Text Input","abstract":[{"type":"text","text":"This article describes the KeyboardKit text input engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"url":"\/documentation\/keyboardkitpro\/layout-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}],"title":"Layout","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","kind":"article","images":[{"type":"card","identifier":"Page.png"}],"type":"topic","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"url":"\/documentation\/keyboardkitpro","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","type":"topic","role":"collection","title":"KeyboardKitPro","abstract":[{"text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI.","type":"text"}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete/LocalAutocompleteService":{"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LocalAutocompleteService"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/LocalAutocompleteService","abstract":[{"type":"text","text":"This service can perform on-device autocomplete, and"},{"type":"text","text":" "},{"type":"text","text":"also perform additional operations and predictions."}],"title":"Autocomplete.LocalAutocompleteService","url":"\/documentation\/keyboardkitpro\/autocomplete\/localautocompleteservice","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocalAutocompleteService"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation-Article":{"images":[{"type":"card","identifier":"Page.png"}],"type":"topic","title":"Dictation","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","url":"\/documentation\/keyboardkitpro\/dictation-article","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Settings-Article":{"url":"\/documentation\/keyboardkitpro\/settings-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","title":"Settings","abstract":[{"type":"text","text":"This article describes the KeyboardKit settings engine and its available settings."}],"type":"topic","images":[{"identifier":"Page.png","type":"card"}],"role":"article","kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Status-Article":{"type":"topic","abstract":[{"text":"This article describes the KeyboardKit status engine.","type":"text"}],"role":"article","images":[{"identifier":"Page.png","type":"card"}],"title":"Status","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","url":"\/documentation\/keyboardkitpro\/status-article","kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Previews-Article":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","url":"\/documentation\/keyboardkitpro\/previews-article","title":"Previews","kind":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"text":"This article describes the KeyboardKit preview engine.","type":"text"}],"role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback-Article":{"url":"\/documentation\/keyboardkitpro\/feedback-article","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"title":"Feedback","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","kind":"article","images":[{"type":"card","identifier":"Page.png"}],"type":"topic","role":"article"},"https://github.com/KeyboardKit/KeyboardKitPro":{"title":"KeyboardKit Pro","type":"link","titleInlineContent":[{"text":"KeyboardKit Pro","type":"text"}],"url":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"title":"Localization","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","role":"article","kind":"article","url":"\/documentation\/keyboardkitpro\/localization-article","images":[{"identifier":"Page.png","type":"card"}],"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit localization engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete/NextWordPredictionRequest":{"url":"\/documentation\/keyboardkitpro\/autocomplete\/nextwordpredictionrequest","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"NextWordPredictionRequest","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/NextWordPredictionRequest","abstract":[{"type":"text","text":"This type can be used to enable next word prediction."}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NextWordPredictionRequest"}],"title":"Autocomplete.NextWordPredictionRequest"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete-Article":{"title":"Autocomplete","type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","url":"\/documentation\/keyboardkitpro\/autocomplete-article","kind":"article","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/UIKit/UITextDocumentProxy/fullDocumentContext(config:)":{"url":"\/documentation\/keyboardkitpro\/uikit\/uitextdocumentproxy\/fulldocumentcontext(config:)","kind":"symbol","abstract":[{"text":"Get the full document context from the proxy.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/UIKit\/UITextDocumentProxy\/fullDocumentContext(config:)","role":"symbol","title":"fullDocumentContext(config:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fullDocumentContext"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Proxy","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro5ProxyV"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro5ProxyV25FullDocumentConfigurationV","text":"FullDocumentConfiguration"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","text":"Proxy","preciseIdentifier":"s:14KeyboardKitPro5ProxyV"},{"text":".","kind":"text"},{"text":"FullDocumentResult","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro5ProxyV18FullDocumentResultV"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"images":[{"identifier":"Page.png","type":"card"}],"title":"Callouts","url":"\/documentation\/keyboardkitpro\/callouts-article","role":"article","abstract":[{"text":"This article describes the KeyboardKit callout engine.","type":"text"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"KeyboardApp","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This type can be used to define important properties for","type":"text"},{"text":" ","type":"text"},{"text":"your app, and is also a namespace for app-based features.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardApp"}],"url":"\/documentation\/keyboardkitpro\/keyboardapp","title":"KeyboardApp","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AutocompleteSettings/isNextWordPredictionEnabled":{"title":"isNextWordPredictionEnabled","url":"\/documentation\/keyboardkitpro\/autocompletesettings\/isnextwordpredictionenabled","role":"symbol","abstract":[{"text":"Whether next word prediction is enabled, by default ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isNextWordPredictionEnabled"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/isNextWordPredictionEnabled","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy-Article":{"title":"Proxy Utilities","images":[{"type":"card","identifier":"Page.png"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit proxy engine and its utilities."}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","url":"\/documentation\/keyboardkitpro\/proxy-article","type":"topic","kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards-Article":{"images":[{"type":"card","identifier":"Page.png"}],"title":"External Keyboards","url":"\/documentation\/keyboardkitpro\/external-keyboards-article","role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit external keyboard engine."}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/App-Article":{"type":"topic","abstract":[{"text":"This article describes the KeyboardKit app-specific utilities.","type":"text"}],"role":"article","images":[{"type":"card","identifier":"Page.png"}],"title":"App Utilities","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","url":"\/documentation\/keyboardkitpro\/app-article","kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Host-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","role":"article","kind":"article","type":"topic","images":[{"type":"card","identifier":"Page.png"}],"url":"\/documentation\/keyboardkitpro\/host-article","title":"Host Application","abstract":[{"type":"text","text":"This article describes how KeyboardKit Pro can identify and use the host application."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Device-Article":{"url":"\/documentation\/keyboardkitpro\/device-article","abstract":[{"text":"This article describes the KeyboardKit device utilities.","type":"text"}],"title":"Device Utilities","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","kind":"article","images":[{"type":"card","identifier":"Page.png"}],"type":"topic","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures-Article":{"title":"Gestures","url":"\/documentation\/keyboardkitpro\/gestures-article","images":[{"identifier":"Page.png","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit gesture engine."}],"role":"article","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Navigation-Article":{"images":[{"type":"card","identifier":"Page.png"}],"title":"Navigation","url":"\/documentation\/keyboardkitpro\/navigation-article","role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit navigation engine."}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Styling-Article":{"type":"topic","abstract":[{"text":"This article describes the KeyboardKit styling engine.","type":"text"}],"role":"article","images":[{"identifier":"Page.png","type":"card"}],"title":"Styling","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","url":"\/documentation\/keyboardkitpro\/styling-article","kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"url":"\/documentation\/keyboardkitpro\/actions-article","abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"title":"Actions","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","kind":"article","images":[{"identifier":"Page.png","type":"card"}],"type":"topic","role":"article"},"Page.png":{"alt":"Page icon","type":"image","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png","traits":["1x","light"]}],"identifier":"Page.png"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Themes-Article":{"type":"topic","abstract":[{"text":"This article describes the KeyboardKit Pro theme engine.","type":"text"}],"role":"article","images":[{"identifier":"Page.png","type":"card"}],"title":"Themes","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article","url":"\/documentation\/keyboardkitpro\/themes-article","kind":"article"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Articles","generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"anchor":"Articles"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}