{"variants":[{"paths":["\/documentation\/keyboardkitpro\/app-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/app-article"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"inlineContent":[{"type":"text","text":"KeyboardKit has app-specific utilities to help you build a great main app for your keyboard, sync data between the app & keyboard, etc."}],"type":"paragraph"},{"inlineContent":[{"text":"👑 ","type":"text"},{"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","isActive":true,"type":"reference"},{"text":" unlocks a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAppView","isActive":true,"type":"reference"},{"text":" that can be used to set up the main app, as well as app-specific screen templates that let you set up a complete main app with just a few lines of code.","type":"text"}],"type":"paragraph"},{"text":"Keyboard App","level":2,"type":"heading","anchor":"Keyboard-App"},{"inlineContent":[{"type":"text","text":"You can create an app-specific "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","isActive":true},{"type":"text","text":" value to define and set up your app and keyboard. See the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started-Article","isActive":true},{"type":"text","text":" & "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","isActive":true},{"type":"text","text":" articles for more information."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp"},{"type":"text","text":" is also a namespace for app-related types & views, like "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/HomeScreen"},{"type":"text","text":", "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/SettingsScreen"},{"type":"text","text":" and "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/LocaleScreen"},{"type":"text","text":"."}],"type":"paragraph"},{"text":"Keyboard App View","level":2,"type":"heading","anchor":"Keyboard-App-View"},{"inlineContent":[{"text":"A ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAppView","isActive":true},{"text":" can be used as the root view of the main app, as described in the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started-Article","isActive":true},{"text":" article. It will set up keyboard features, make the settings ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/store","isActive":true},{"text":" sync data between the app and keyboard, register your KeyboardKit Pro license, if any, etc.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The  "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAppView","type":"reference"},{"type":"text","text":" will also inject observable keyboard "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/State","type":"reference"},{"type":"text","text":" types into the view environment, to let you access them like this:"}],"type":"paragraph"},{"code":["struct ContentView: View {","","    @EnvironmentObject var keyboardContext: KeyboardContext","","    var body: View {","        ...","    }","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"type":"text","text":"Unlike the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","isActive":true,"type":"reference"},{"type":"text","text":", the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAppView","isActive":true,"type":"reference"},{"type":"text","text":" will also inject a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStatusContext","isActive":true,"type":"reference"},{"type":"text","text":", to provide you with observable keyboard status."}],"type":"paragraph"},{"type":"thematicBreak"},{"text":"👑 KeyboardKit Pro","level":2,"type":"heading","anchor":"%F0%9F%91%91-KeyboardKit-Pro"},{"inlineContent":[{"isActive":true,"type":"reference","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","overridingTitleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"overridingTitle":"KeyboardKit Pro"},{"text":" unlocks ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp"},{"text":"-specific screens that let you quickly add keyboard-related features to your main app target.","type":"text"}],"type":"paragraph"},{"type":"tabNavigator","tabs":[{"title":"HomeScreen","content":[{"type":"row","columns":[{"size":1,"content":[{"inlineContent":[{"type":"image","identifier":"app-homescreen"}],"type":"paragraph"}]},{"size":1,"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/HomeScreen"},{"type":"text","text":" can be used as the main screen of a keyboard app, to let you quickly get your main app up and running."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The screen shows the main app icon, a keyboard status section, links to settings screens, custom header and footer views, etc."}]}]}],"numberOfColumns":2}]},{"title":"SettingsScreen","content":[{"type":"row","numberOfColumns":2,"columns":[{"size":1,"content":[{"inlineContent":[{"type":"image","identifier":"app-settingsscreen"}],"type":"paragraph"}]},{"size":1,"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/SettingsScreen"},{"type":"text","text":" can be used as the main settings screen of a keyboard app, or in a keyboard extension."}]},{"type":"paragraph","inlineContent":[{"text":"The screen lists various keyboard settings, grouped by type. All changes are automatically persisted and synced to the keyboard.","type":"text"}]}]}]}]},{"title":"LocaleScreen","content":[{"type":"row","numberOfColumns":2,"columns":[{"content":[{"inlineContent":[{"type":"image","identifier":"app-localescreen"}],"type":"paragraph"}],"size":1},{"content":[{"inlineContent":[{"text":"A ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/LocaleScreen","type":"reference","isActive":true},{"text":" can be used as the language settings screen in a keyboard app, or in a keyboard extension.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"The screen lists all added and all available locales, and lets users add and reorganize locales, change keyboard layouts, etc.","type":"text"}],"type":"paragraph"}],"size":1}]}]},{"title":"ThemeScreen","content":[{"numberOfColumns":2,"columns":[{"size":1,"content":[{"type":"paragraph","inlineContent":[{"identifier":"app-themescreen","type":"image"}]}]},{"size":1,"content":[{"inlineContent":[{"type":"text","text":"A "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/ThemeScreen","type":"reference","isActive":true},{"type":"text","text":" can be used as a main theme picker screen of a keyboard app, or in a keyboard extension."}],"type":"paragraph"},{"inlineContent":[{"text":"The screen list available themes in shelves, and will by default set the main, persisted ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardThemeSettings\/theme","type":"reference"},{"text":" when a theme is tapped.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Since you may not want to support themes in your keyboard, this screen is opt-in when using a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/HomeScreen","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}]}],"type":"row"}]}]},{"inlineContent":[{"text":"All screens have view modifiers to let you toggle the visibility of certain parts of the screen, and style and localize them to fit your needs:","type":"text"}],"type":"paragraph"},{"code":["NavigationView {","    KeyboardApp.HomeScreen(","        app: .myApp,","        appIcon: Image(.icon),","        header: {},","        footer: textFieldSection","    )","    .navigationTitle(\"KeyboardKit\")","}",".keyboardAppHomeScreenLocalization(","    .init(keyboardSectionFooter: \"Here's a custom footer text.\")",")",".keyboardAppHomeScreenStyle(","    .init(appIconSize: 150)",")",".keyboardAppHomeScreenVisibility(","    .init(keyboardSection: true)",")",".navigationViewStyle(.stack)"],"type":"codeListing","syntax":"swift"},{"content":[{"inlineContent":[{"type":"text","text":"You must use an App Group for settings to sync between your app and its keyboard. See the "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","type":"reference"},{"type":"text","text":" article for more information."}],"type":"paragraph"}],"name":"Important","type":"aside","style":"important"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article"},"kind":"article","metadata":{"title":"App Utilities","modules":[{"name":"KeyboardKitPro"}],"roleHeading":"Article","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"seeAlsoSections":[{"anchor":"Articles","title":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article"],"generated":true}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardThemeSettings/theme":{"kind":"symbol","title":"theme","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardThemeSettings\/theme","url":"\/documentation\/keyboardkitpro\/keyboardthemesettings\/theme","role":"symbol","abstract":[{"text":"The current theme, if any.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"theme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardTheme","preciseIdentifier":"s:14KeyboardKitPro0A5ThemeV"},{"kind":"text","text":"?"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAppView":{"title":"KeyboardAppView","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardappview","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardAppView","kind":"identifier"}],"abstract":[{"type":"text","text":"This view can be used as the root view of a keyboard app,"},{"text":" ","type":"text"},{"text":"to set up KeyboardKit for a certain ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp"},{"text":".","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"KeyboardAppView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAppView"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards-Article":{"role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","url":"\/documentation\/keyboardkitpro\/external-keyboards-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"title":"External Keyboards"},"app-settingsscreen":{"alt":"KeyboardApp.SettingsScreen","type":"image","identifier":"app-settingsscreen","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/app-settingsscreen.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation-Article":{"abstract":[{"text":"This article describes the KeyboardKit dictation engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/dictation-article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","type":"topic","images":[{"identifier":"Page.png","type":"card"}],"role":"article","title":"Dictation"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller","navigatorTitle":[{"text":"KeyboardInputViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"This is the main input controller in a KeyboardKit-based"},{"type":"text","text":" "},{"type":"text","text":"keyboard extension."}],"role":"symbol","title":"KeyboardInputViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardInputViewController","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","type":"topic","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"url":"\/documentation\/keyboardkitpro","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"type":"topic","title":"KeyboardKitPro","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback-Article":{"images":[{"identifier":"Page.png","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","url":"\/documentation\/keyboardkitpro\/feedback-article","type":"topic","role":"article","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"kind":"article","title":"Feedback"},"app-themescreen":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/app-themescreen.jpg"}],"alt":"KeyboardApp.SettingsScreen","identifier":"app-themescreen","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Getting-Started-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started-Article","type":"topic","abstract":[{"type":"text","text":"This guide describes how to get started with KeyboardKit."}],"kind":"article","images":[{"identifier":"Page.png","type":"card"}],"url":"\/documentation\/keyboardkitpro\/getting-started-article","role":"article","title":"Getting Started"},"app-localescreen":{"alt":"KeyboardApp.SettingsScreen","type":"image","identifier":"app-localescreen","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/app-localescreen.jpg","traits":["1x","light"]}]},"Page.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png"}],"alt":"Page icon","identifier":"Page.png","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"abstract":[{"text":"This article describes the KeyboardKit layout engine.","type":"text"}],"title":"Layout","kind":"article","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","url":"\/documentation\/keyboardkitpro\/layout-article","type":"topic","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp/ThemeScreen":{"kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardapp\/themescreen","abstract":[{"type":"text","text":"This screen can be used as the keyboard theme picker"},{"type":"text","text":" "},{"type":"text","text":"in a keyboard app or its keyboard extension."}],"navigatorTitle":[{"text":"ThemeScreen","kind":"identifier"}],"title":"KeyboardApp.ThemeScreen","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/ThemeScreen","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ThemeScreen","kind":"identifier"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Host-Article":{"kind":"article","role":"article","images":[{"identifier":"Page.png","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","url":"\/documentation\/keyboardkitpro\/host-article","type":"topic","title":"Host Application","abstract":[{"type":"text","text":"This article describes how KeyboardKit Pro can identify and use the host application."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp/SettingsScreen":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsScreen"}],"title":"KeyboardApp.SettingsScreen","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"This screen can be used as a main settings screen in"},{"type":"text","text":" "},{"type":"text","text":"a keyboard app or its keyboard extension."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/SettingsScreen","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SettingsScreen"}],"url":"\/documentation\/keyboardkitpro\/keyboardapp\/settingsscreen"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"role":"article","url":"\/documentation\/keyboardkitpro\/localization-article","abstract":[{"text":"This article describes the KeyboardKit localization engine.","type":"text"}],"type":"topic","title":"Localization","images":[{"identifier":"Page.png","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AI-Article":{"abstract":[{"text":"This article describes the KeyboardKit AI support capabilities.","type":"text"}],"role":"article","type":"topic","kind":"article","images":[{"identifier":"Page.png","type":"card"}],"url":"\/documentation\/keyboardkitpro\/ai-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","title":"AI Support"},"https://github.com/KeyboardKit/KeyboardKitPro":{"type":"link","url":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","title":"KeyboardKit Pro","titleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp":{"url":"\/documentation\/keyboardkitpro\/keyboardapp","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardApp"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardApp"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","role":"symbol","type":"topic","abstract":[{"type":"text","text":"This type can be used to define important properties for"},{"type":"text","text":" "},{"type":"text","text":"your app, and is also a namespace for app-based features."}],"title":"KeyboardApp"},"app-homescreen":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/app-homescreen.jpg"}],"alt":"KeyboardApp.HomeScreen","identifier":"app-homescreen","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp/LocaleScreen":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/LocaleScreen","abstract":[{"text":"This screen can be used as the main locale screen in","type":"text"},{"text":" ","type":"text"},{"text":"a keyboard app or its keyboard extension.","type":"text"}],"navigatorTitle":[{"text":"LocaleScreen","kind":"identifier"}],"title":"KeyboardApp.LocaleScreen","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocaleScreen","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardapp\/localescreen"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures-Article":{"type":"topic","images":[{"identifier":"Page.png","type":"card"}],"kind":"article","url":"\/documentation\/keyboardkitpro\/gestures-article","role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit gesture engine."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","title":"Gestures"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardSettings/store":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/store","title":"store","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardsettings\/store","role":"symbol","abstract":[{"type":"text","text":"The store that will be used by library settings."}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"store","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSUserDefaults","text":"UserDefaults","kind":"typeIdentifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"title":"Callouts","kind":"article","url":"\/documentation\/keyboardkitpro\/callouts-article","role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Settings-Article":{"title":"Settings","images":[{"type":"card","identifier":"Page.png"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit settings engine and its available settings."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","url":"\/documentation\/keyboardkitpro\/settings-article","role":"article","kind":"article","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis-Article":{"url":"\/documentation\/keyboardkitpro\/emojis-article","type":"topic","title":"Emojis","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"text":"This article describes the KeyboardKit emoji engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","kind":"article","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Input-Article":{"title":"Input","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","url":"\/documentation\/keyboardkitpro\/input-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}],"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit input engine."}],"role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/State":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/State","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"State","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"This type specifies global keyboard state.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboard\/state","role":"symbol","navigatorTitle":[{"text":"State","kind":"identifier"}],"title":"Keyboard.State"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Navigation-Article":{"abstract":[{"text":"This article describes the KeyboardKit navigation engine.","type":"text"}],"title":"Navigation","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","images":[{"identifier":"Page.png","type":"card"}],"role":"article","url":"\/documentation\/keyboardkitpro\/navigation-article","kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardStatusContext":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStatusContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardStatusContext"}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardStatusContext"}],"kind":"symbol","title":"KeyboardStatusContext","url":"\/documentation\/keyboardkitpro\/keyboardstatuscontext","abstract":[{"type":"text","text":"This class has observable, keyboard status-related state."}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"images":[{"identifier":"Page.png","type":"card"}],"title":"Actions","url":"\/documentation\/keyboardkitpro\/actions-article","kind":"article","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}],"url":"\/documentation\/keyboardkitpro\/autocomplete-article","type":"topic","title":"Autocomplete","role":"article","images":[{"identifier":"Page.png","type":"card"}],"kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Essentials-Article":{"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","url":"\/documentation\/keyboardkitpro\/essentials-article","kind":"article","title":"Essentials","abstract":[{"text":"This article describes the essential parts of KeyboardKit.","type":"text"}],"images":[{"type":"card","identifier":"Page.png"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp/HomeScreen":{"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HomeScreen","kind":"identifier"}],"navigatorTitle":[{"text":"HomeScreen","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/HomeScreen","url":"\/documentation\/keyboardkitpro\/keyboardapp\/homescreen","abstract":[{"type":"text","text":"This screen can be used as the main home screen in a"},{"type":"text","text":" "},{"type":"text","text":"keyboard app, and looks a bit like the Settings app."}],"title":"KeyboardApp.HomeScreen"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Device-Article":{"role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","url":"\/documentation\/keyboardkitpro\/device-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit device utilities."}],"title":"Device Utilities"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article"],"generated":true,"title":"Articles","anchor":"Articles"}],"path":"\/seeAlsoSections","op":"replace"},{"value":"KeyboardInputViewController","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"KeyboardInputViewController"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"KeyboardInputViewController"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}