{"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In KeyboardKit, a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAppearance"},{"type":"text","text":" defines the styles, texts, icons etc. for different parts of the keyboard. It can adapt styles depending on "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction"},{"type":"text","text":" etc., which gives you a lot of flexibility."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit will by default create a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardAppearance"},{"type":"text","text":" and apply it to the input controller "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/keyboardAppearance"},{"type":"text","text":". You can replace it with a custom appearance to customize how your keyboard looks."}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro"},{"type":"text","text":" specific features are described at the end of this document."}]},{"anchor":"Appearance-vs-styles-vs-themes","level":2,"type":"heading","text":"Appearance vs. styles vs. themes"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You may find yourself confused by the appearance terminology, as we talk about appearances, styles and themes, so let’s clarity what they are and how they are used."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAppearance"},{"type":"text","text":" is a dynamic style provider, that returns various styles (and more) for various parts of the keyboard, such as a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardButtonStyle"},{"type":"text","text":". With dynamic, means that it can return different styles for different actions, if dark mode is enabled etc. so you have full control over every little button."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro adds the concept of a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme"},{"type":"text","text":", which is a way to define static styles. Themes make it a lot easier to define, reuse and share styles, but are not dynamic like a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAppearance"},{"type":"text","text":" can be."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro adds a theme-based "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardThemeAppearance"},{"type":"text","text":" that uses a theme to define styles. You can override this class to customize things further and make use of the dynamic capabilites of the appearance, while also making use of the power of themes."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can mix and match appearances, styles and themes as you see fit."}]},{"anchor":"Resources--Assets","level":2,"type":"heading","text":"Resources & Assets"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit comes with colors and images that make it easy to create native-looking keyboards."}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"Image"},{"type":"text","text":" has a bunch of static, keyboard-specific images, e.g. "},{"type":"codeVoice","code":".keyboardBackspace"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"Color"},{"type":"text","text":" has a bunch of static, keyboard-specific colors, e.g. "},{"type":"codeVoice","code":".standardButtonBackgroundColor(for:)"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction"},{"type":"text","text":" and other types have standard images, texts and colors, for instance:"}]}]}]},{"type":"codeListing","syntax":"swift","code":["let context = KeyboardContext()","let image = KeyboardAction.command.standardButtonImage(for: context) \/\/ Command icon","let text = KeyboardAction.space.standardButtonText(for: context)     \/\/ Localized \"space\""]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Have a look at the "},{"type":"codeVoice","code":"Sources\/Resources"},{"type":"text","text":" and "},{"type":"codeVoice","code":"Sources\/Appearance"},{"type":"text","text":" folders for more information."}]},{"anchor":"Styles","level":2,"type":"heading","text":"Styles"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"Appearance"},{"type":"text","text":" namespace defines general styles, such as "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardButtonStyle"},{"type":"text","text":", while other namespaces define more contextual styles, such as how the "},{"type":"codeVoice","code":"Emojis"},{"type":"text","text":" namespace defines an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboardStyle"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Any style can be modified as long as it’s a "},{"type":"codeVoice","code":"var"},{"type":"text","text":". For instance, here we adjust the standard "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutStyle"},{"type":"text","text":" to use a red background:"}]},{"type":"codeListing","syntax":"swift","code":["var style = CalloutStyle.standard","style.backgroundColor = .red","CalloutStyle.standard = style"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Almost all styles have a "},{"type":"codeVoice","code":".standard"},{"type":"text","text":" style that you can replace with a custom style to change the global style of that component."}]},{"anchor":"How-to-create-a-custom-appearance","level":2,"type":"heading","text":"How to create a custom appearance"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can create a custom "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAppearance"},{"type":"text","text":" to customize the style of various buttons or callouts, as well as texts, images etc."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can either inherit "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardAppearance"},{"type":"text","text":" to get a lot of functionality for free and customize the parts you want, or implement the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAppearance"},{"type":"text","text":" protocol from scratch."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For instance, here’s a custom appearance that inherits "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardAppearance"},{"type":"text","text":" and makes all input buttons red:"}]},{"type":"codeListing","syntax":"swift","code":["class MyKeyboardAppearance: StandardKeyboardAppearance {","    ","    override func buttonStyle(","        for action: KeyboardAction,","        isPressed: Bool","    ) -> KeyboardButtonStyle {","        let style = super.buttonStyle(for: action, isPressed: isPressed)","        if !action.isInputAction { return style }","        style.backgroundColor = .red","        return style","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To use this appearance instead of the standard one, just set the input controller’s "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/keyboardAppearance"},{"type":"text","text":" to the new appearance:"}]},{"type":"codeListing","syntax":"swift","code":["class MyKeyboardViewController: KeyboardInputViewController {","","    override func viewDidLoad() {","        keyboardAppearance = MyKeyboardAppearance()","        super.viewDidLoad()","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This will make KeyboardKit use your custom appearance instead of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardAppearance"},{"type":"text","text":"."}]},{"anchor":"👑-Pro-features","level":2,"type":"heading","text":"👑 Pro features"},{"type":"paragraph","inlineContent":[{"overridingTitleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"isActive":true,"type":"reference","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","overridingTitle":"KeyboardKit Pro"},{"type":"text","text":" unlocks a theme engine that makes it a LOT easier to define styles for a keyboard."}]},{"anchor":"Themes","level":3,"type":"heading","text":"Themes"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme"},{"type":"text","text":" struct defines a bunch of styles, such as button and background styles. It comes with a bunch of pre-defined themes, which you can use as is or use as templates to create custom themes."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardThemeAppearance"},{"type":"text","text":" appearance inherits "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardAppearance"},{"type":"text","text":" and can be created with any theme, for instance:"}]},{"type":"codeListing","syntax":"swift","code":["override func viewWillSetupKeyboard() {","    super.viewWillSetupKeyboard()","","    \/\/ Setup KeyboardKit Pro, using a demo-specific view","    try? setupPro(withLicenseKey: \"KEY\") { _ in","        keyboardAppearance = KeyboardThemeAppearance(","            theme: .cottonCandy,","            keyboardContext: keyboardContext)","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Since the theme engine requires KeyboardKit Pro, you must register it "},{"type":"emphasis","inlineContent":[{"type":"text","text":"after"}]},{"type":"text","text":" setting up your license. You can inherit this appearance to customize a base theme even further."}]},{"anchor":"Pre-defined-themes","level":3,"type":"heading","text":"Pre-defined themes"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro comes with a set of pre-defined themes, which you can access with "},{"type":"codeVoice","code":"KeyboardTheme.{ID}"},{"type":"text","text":":"}]},{"type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"ID"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Preview"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":".cottonCandy"}]}],[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"cotton-candy-500.png"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":".neonNights"}]}],[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"neon-nights-500.png"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":".tron"}]}],[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"tron-500.png"}]}]]],"header":"row"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/keyboardkitpro\/appearance"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/appearance"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Appearance","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This article describes the KeyboardKit appearance engine and how to use it."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Appearance","role":"article","modules":[{"name":"KeyboardKitPro"}]},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"seeAlsoSections":[{"title":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Extensions","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Routing","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/RTL","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings"],"generated":true}],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout":{"role":"article","title":"Layouts","abstract":[{"type":"text","text":"This article describes the KeyboardKit keyboard layout engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/layout"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardTheme":{"role":"symbol","title":"KeyboardTheme","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardTheme"}],"abstract":[{"type":"text","text":"This struct defines a keyboard-specific theme, which can be"},{"type":"text","text":" "},{"type":"text","text":"used together with a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardThemeAppearance"},{"type":"text","text":" to control"},{"type":"text","text":" "},{"type":"text","text":"the colors and overall style of a keyboard."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardTheme"}],"url":"\/documentation\/keyboardkitpro\/keyboardtheme"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAppearance":{"role":"symbol","title":"KeyboardAppearance","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardAppearance"}],"abstract":[{"type":"text","text":"This protocol can be implemented by classes that can define"},{"type":"text","text":" "},{"type":"text","text":"styles and appearances for different parts of a keyboard."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAppearance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardAppearance"}],"url":"\/documentation\/keyboardkitpro\/keyboardappearance"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy-Extensions":{"role":"article","title":"Proxy Extensions","abstract":[{"type":"text","text":"This article describes how KeyboardKit extends "},{"type":"codeVoice","code":"UITextDocumentProxy"},{"type":"text","text":" with a lot of additional functionality."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Extensions","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/proxy-extensions"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization":{"role":"article","title":"Localization","abstract":[{"type":"text","text":"This article describes the KeyboardKit localization model and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/localization"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Settings":{"role":"article","title":"Settings","abstract":[{"type":"text","text":"This article describes the KeyboardKit settings utilities and how to use them."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/settings"},"neon-nights-500.png":{"alt":"Neon Nights","type":"image","identifier":"neon-nights-500.png","variants":[{"url":"\/images\/neon-nights-500.png","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback":{"role":"article","title":"Feedback","abstract":[{"type":"text","text":"This article describes the KeyboardKit feedback engine and how to use it to trigger audio and haptic feedback."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/feedback"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/EmojiKeyboard":{"role":"symbol","title":"EmojiKeyboard","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmojiKeyboard"}],"abstract":[{"type":"text","text":"This view can be used as an emoji keyboard and will list an"},{"type":"text","text":" "},{"type":"text","text":"emoji collection using the provided configuration."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EmojiKeyboard"}],"url":"\/documentation\/keyboardkitpro\/emojikeyboard"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete":{"role":"article","title":"Autocomplete","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/autocomplete"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards":{"role":"article","title":"External Keyboards","abstract":[{"type":"text","text":"This article describes the KeyboardKit external keyboard engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/external-keyboards"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction":{"role":"symbol","title":"KeyboardAction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardAction"}],"abstract":[{"type":"text","text":"This enum defines keyboard-specific actions that correspond"},{"type":"text","text":" "},{"type":"text","text":"to actions that can be found on various keyboards."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardAction"}],"url":"\/documentation\/keyboardkitpro\/keyboardaction"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts":{"role":"article","title":"Callouts","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/callouts"},"https://github.com/KeyboardKit/KeyboardKitPro":{"title":"KeyboardKit Pro","titleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"type":"link","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","url":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis":{"role":"article","title":"Emojis","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji model and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/emojis"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/keyboardAppearance":{"role":"symbol","title":"keyboardAppearance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardAppearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardAppearance","preciseIdentifier":"s:14KeyboardKitPro0A10AppearanceP"}],"abstract":[{"type":"text","text":"This appearance can be used to customize the keyboard’s"},{"type":"text","text":" "},{"type":"text","text":"design, such as its colors, fonts etc."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/keyboardAppearance","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/keyboardappearance"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLocale/arabic":{"role":"symbol","title":"KeyboardLocale.arabic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"arabic"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale\/arabic","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardlocale\/arabic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Input":{"role":"article","title":"Input","abstract":[{"type":"text","text":"This article describes the KeyboardKit input set engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/input"},"tron-500.png":{"alt":"Tron","type":"image","identifier":"tron-500.png","variants":[{"url":"\/images\/tron-500.png","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Previews":{"role":"article","title":"Previews","abstract":[{"type":"text","text":"This article describes how KeyboardKit makes it easy to preview keyboard-specific views."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/previews"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard":{"role":"article","title":"Keyboard","abstract":[{"type":"text","text":"This article describes the KeyboardKit keyboard types and how to use them."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboard"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardThemeAppearance":{"role":"symbol","title":"KeyboardThemeAppearance","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardThemeAppearance"}],"abstract":[{"type":"text","text":"This appearance inherits "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardAppearance"},{"type":"text","text":" and"},{"type":"text","text":" "},{"type":"text","text":"applies style overrides from the provided "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardThemeAppearance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardThemeAppearance"}],"url":"\/documentation\/keyboardkitpro\/keyboardthemeappearance"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Routing":{"role":"article","title":"Routing","abstract":[{"type":"text","text":"This article describes how KeyboardKit adds ways for you to route text from the main app to other text fields within the keyboard."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Routing","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/routing"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardAppearance":{"role":"symbol","title":"StandardKeyboardAppearance","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StandardKeyboardAppearance"}],"abstract":[{"type":"text","text":"This standard appearance returns styles that replicates the"},{"type":"text","text":" "},{"type":"text","text":"look of a native system keyboard."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardAppearance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StandardKeyboardAppearance"}],"url":"\/documentation\/keyboardkitpro\/standardkeyboardappearance"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext":{"role":"symbol","title":"KeyboardContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardContext"}],"abstract":[{"type":"text","text":"This class provides keyboard extensions with contextual and"},{"type":"text","text":" "},{"type":"text","text":"observable information about the keyboard extension itself."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardContext"}],"url":"\/documentation\/keyboardkitpro\/keyboardcontext"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/EmojiKeyboardStyle":{"role":"symbol","title":"EmojiKeyboardStyle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmojiKeyboardStyle"}],"abstract":[{"type":"text","text":"This style can be applied to emoji keyboard views, like the"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboard"},{"type":"text","text":" or "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiCategoryKeyboard"},{"type":"text","text":" to customize"},{"type":"text","text":" "},{"type":"text","text":"things like the font, number of rows, item spacing etc."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboardStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EmojiKeyboardStyle"}],"url":"\/documentation\/keyboardkitpro\/emojikeyboardstyle"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardButtonStyle":{"role":"symbol","title":"KeyboardButtonStyle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardButtonStyle"}],"abstract":[{"type":"text","text":"This style defines the style of a system keyboard button."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardButtonStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardButtonStyle"}],"url":"\/documentation\/keyboardkitpro\/keyboardbuttonstyle"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/RTL":{"role":"article","title":"RTL","abstract":[{"type":"text","text":"KeyboardKit supports RTL (right-to-left) locales, which means that it supports locales like "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale\/arabic"},{"type":"text","text":",  "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale\/persian"},{"type":"text","text":" etc."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/RTL","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/rtl"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLocale/persian":{"role":"symbol","title":"KeyboardLocale.persian","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"persian"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale\/persian","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardlocale\/persian"},"cotton-candy-500.png":{"alt":"Cotton Candy","type":"image","identifier":"cotton-candy-500.png","variants":[{"url":"\/images\/cotton-candy-500.png","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/CalloutStyle":{"deprecated":true,"role":"symbol","title":"CalloutStyle","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CalloutStyle"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CalloutStyle"}],"url":"\/documentation\/keyboardkitpro\/calloutstyle"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/EmojiCategoryKeyboard":{"role":"symbol","title":"EmojiCategoryKeyboard","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmojiCategoryKeyboard"}],"abstract":[{"type":"text","text":"This keyboard lists all emojis from a selected category, as"},{"type":"text","text":" "},{"type":"text","text":"well as a menu that lets the user select a new category and"},{"type":"text","text":" "},{"type":"text","text":"change back to an alphabetic keyboard."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiCategoryKeyboard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EmojiCategoryKeyboard"}],"url":"\/documentation\/keyboardkitpro\/emojicategorykeyboard"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures":{"role":"article","title":"Gestures","abstract":[{"type":"text","text":"This article describes the KeyboardKit gesture engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/gestures"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","title":"KeyboardKitPro","abstract":[{"type":"text","text":"KeyboardKit Pro helps you build custom keyboard extensions for iOS and iPadOS."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions":{"role":"article","title":"Actions","abstract":[{"type":"text","text":"This article describes the KeyboardKit action engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/actions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Extensions","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Routing","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/RTL","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}