{"seeAlsoSections":[{"generated":true,"anchor":"Articles","title":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"]}],"primaryContentSections":[{"content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"text":"Autocomplete is an important part of the typing experience, where word suggestions can be presented in a toolbar above the keyboard as the user types, and incorrectly text can be autocorrected.","type":"text"}]},{"inlineContent":[{"type":"text","text":"In KeyboardKit, an "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteService","isActive":true,"type":"reference"},{"type":"text","text":" can provide suggestions and predictions to the main "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteContext"},{"type":"text","text":". Unlike other services, there is no standard autocomplete service in the open-source SDK."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"👑 ","type":"text"},{"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","isActive":true,"type":"reference"},{"text":" unlocks a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/LocalAutocompleteService","type":"reference","isActive":true},{"text":" and a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/RemoteAutocompleteService","isActive":true},{"type":"text","text":", next character prediction, next word prediction, etc. Information about Pro features can be found further down."}]},{"level":2,"type":"heading","text":"Namespace","anchor":"Namespace"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit has an ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete"},{"text":" namespace with autocomplete-related types, like a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/Suggestion"},{"text":" model, a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/Toolbar"},{"type":"text","text":" view, etc."}]},{"anchor":"Context","text":"Context","level":2,"type":"heading"},{"inlineContent":[{"text":"KeyboardKit has an ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteContext","isActive":true},{"type":"text","text":" that provides observable autocomplete state, and auto-persisted "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteContext\/settings-swift.property"},{"type":"text","text":" that can be used to customize the autocomplete behavior."}],"type":"paragraph"},{"inlineContent":[{"text":"KeyboardKit automatically creates an instance of this class, injects it into ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state","isActive":true,"type":"reference"},{"type":"text","text":" and updates it whenever autocomplete is performed."}],"type":"paragraph"},{"anchor":"Services","level":2,"type":"heading","text":"Services"},{"inlineContent":[{"text":"In KeyboardKit, an ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteService","type":"reference","isActive":true},{"type":"text","text":" can provide suggestions when the user types and the text input cursor moves in the text."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit doesn’t have a standard autocomplete service, as it has for other service types. Instead, it injects a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteService\/disabled","type":"reference","isActive":true},{"text":" service into ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","type":"reference"},{"type":"text","text":" until you set up "},{"type":"reference","overridingTitle":"KeyboardKit Pro","overridingTitleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","isActive":true},{"text":" or inject your own service implementation.","type":"text"}]},{"level":2,"text":"Settings","type":"heading","anchor":"Settings"},{"inlineContent":[{"type":"text","text":"KeyboardKit has an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings"},{"type":"text","text":" type with autocomplete-related settings. The context "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteContext\/settings-swift.property","type":"reference","isActive":true},{"type":"text","text":" is used by default."}],"type":"paragraph"},{"type":"heading","anchor":"Views","level":2,"text":"Views"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete","isActive":true,"type":"reference"},{"type":"text","text":" namespace has autocomplete-specific views, that can be used to mimic native autocomplete toolbars and items."}]},{"type":"tabNavigator","tabs":[{"content":[{"columns":[{"size":1,"content":[{"type":"paragraph","inlineContent":[{"identifier":"autocompletetoolbar","type":"image"}]}]},{"content":[{"inlineContent":[{"text":"The autocomplete ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/Toolbar","isActive":true},{"type":"text","text":" can be used to show autocomplete suggestions as the user types."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"The view can be styled with a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/ToolbarStyle","isActive":true,"type":"reference"},{"type":"text","text":", which is applied with the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/autocompleteToolbarStyle(_:)"},{"type":"text","text":" modifier. It can also use completely custom views."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This view is used as the standard toolbar by the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","type":"reference","isActive":true},{"text":". You can style it with a global style modifier.","type":"text"}]}],"size":1}],"numberOfColumns":2,"type":"row"}],"title":"Toolbar"}]},{"type":"thematicBreak"},{"level":2,"type":"heading","anchor":"%F0%9F%91%91-KeyboardKit-Pro","text":"👑 KeyboardKit Pro"},{"inlineContent":[{"isActive":true,"type":"reference","overridingTitle":"KeyboardKit Pro","overridingTitleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro"},{"type":"text","text":" unlocks a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/LocalAutocompleteService","isActive":true,"type":"reference"},{"type":"text","text":" and a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/RemoteAutocompleteService","type":"reference","isActive":true},{"type":"text","text":", and injects a local service into "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","type":"reference","isActive":true},{"text":" when you set up KeyboardKit Pro. You can inherit both classes to customize their functionality.","type":"text"}],"type":"paragraph"},{"type":"heading","anchor":"Local-Autocomplete","text":"Local Autocomplete","level":3},{"inlineContent":[{"type":"text","text":"The "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/LocalAutocompleteService","type":"reference"},{"text":" performs local on-device autocomplete. It supports many locales, works offline, doesn’t require Full Access, and can integrate with system services like the local lexicon.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The service supports the following languages, per platform:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"iOS\/iPadOS\/visionOS:","type":"text"}]},{"type":"text","text":" Arabic, Arabic, Najdi, Bulgarian (Bulgaria), Czech (Czechia), Danish (Denmark), Dutch (Netherlands), English (Australia), English (Canada), English (India), English (New Zealand), English (Singapore), English (South Africa), English (United Kingdom), English (United States), Finnish (Finland), French (France), German (Germany), Greek (Greece), Hebrew (Israel), Hindi, Hungarian (Hungary), Icelandic (Iceland), Indonesian (Indonesia), Irish (Ireland), Italian (Italy), Lithuanian (Lithuania), Norwegian Bokmål (Norway), Norwegian Nynorsk, Polish (Poland), Portuguese (Brazil), Portuguese (Portugal), Punjabi, Romanian (Romania), Russian (Russia), Slovenian (Slovenia), Spanish (Mexico), Spanish (Spain), Swedish (Sweden), Telugu, Turkish (Türkiye), Ukrainian (Ukraine), Vietnamese (Vietnam)"}]}]},{"content":[{"inlineContent":[{"inlineContent":[{"text":"macOS:","type":"text"}],"type":"strong"},{"text":" Arabic, Arabic, Najdi, Bulgarian, Czech, Danish, Dutch, English, English (Australia), English (Canada), English (India), English (Japan), English (New Zealand), English (Singapore), English (South Africa), English (United Kingdom), Finnish, French, German, Greek, Hebrew, Hindi, Hungarian, Icelandic, Indonesian, Irish, Italian, Korean, Lithuanian, Norwegian Bokmål, Norwegian Nynorsk, Polish, Portuguese (Brazil), Portuguese (Portugal), Punjabi, Romanian, Russian, Slovenian, Spanish, Swedish, Telugu, Turkish, Ukrainian, Vietnamese**","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"watchOS: Not available."}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can inject a custom "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/NextWordPredictionRequest"},{"type":"text","text":" into the service to make it perform next word predictions with an external AI service. Read more below."}]},{"level":3,"anchor":"Remote-Autocomplete","text":"Remote Autocomplete","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/RemoteAutocompleteService","type":"reference"},{"type":"text","text":" can be used to perform autocomplete by integrating with any external API. It requires that the device is online, and requires Full Access to be able to make network requests."}]},{"type":"paragraph","inlineContent":[{"text":"You create a remote autocomplete service by defining the API URL, any potential headers or query parameters, as well as a result type.","type":"text"}]},{"anchor":"Next-Character-Prediction","level":3,"type":"heading","text":"Next Character Prediction"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/LocalAutocompleteService"},{"text":" and ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/RemoteAutocompleteService","type":"reference"},{"text":" perform next-character predictions on their results.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This information is used by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView"},{"type":"text","text":" to slightly increase the tap area of more probable keys, to reduce the risk of typing error."}]},{"type":"heading","text":"Next Word Prediction","level":3,"anchor":"Next-Word-Prediction"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Apple’s native text prediction utilities stopped supporting next word prediction in iOS 16. It instead only provides predictions on already typed text, without any (known) way to get next word predictions."}]},{"inlineContent":[{"type":"text","text":"KeyboardKit Pro therefore unlocks ways to perform next word prediction via 3rd party AI services. The easiest way to enable next word prediction, is to add a Claude- or OpenAI-based "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/NextWordPredictionRequest","isActive":true},{"text":" to your ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp"},{"type":"text","text":":"}],"type":"paragraph"},{"type":"codeListing","code":["extension KeyboardApp {","","    static var keyboardKitDemo: KeyboardApp {","        KeyboardApp(","            ...","            autocomplete: .init(","                nextWordPredictionRequest: .claude(apiKey: ...)","            )","        )","    }","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can use these pre-defined requests to integrate with Claude or OpenAI, by providing an API key and any optional customizations:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/NextWordPredictionRequest\/claude(apiKey:apiUrl:anthropicVersion:model:maxTokens:systemPrompt:)","type":"reference","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/NextWordPredictionRequest\/openAI(apiKey:apiUrl:apiKeyHeader:apiKeyValuePrefix:model:maxTokens:systemPrompt:)"},{"type":"text","text":"."}],"type":"paragraph"}]}]},{"type":"paragraph","inlineContent":[{"text":"You can also let your users select which next word prediction request to use, with their own private API key. Read more further down.","type":"text"}]},{"name":"Important","type":"aside","style":"important","content":[{"inlineContent":[{"type":"text","text":"AI-based next word prediction requires Full Access. It’s disabled by default, to avoid sending typed text to 3rd parties without the user’s explicit consent. When a user has given its explicit content, you can enable it with "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/isNextWordPredictionEnabled"},{"text":".","type":"text"}],"type":"paragraph"}]},{"text":"User-Specific Next Word Prediction","anchor":"User-Specific-Next-Word-Prediction","level":3,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can let your users use their own next word prediction integrations, use their own API key and pay for their own data consumption."}]},{"inlineContent":[{"text":"Just give your users a way to define a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/nextWordPredictionRequestType"},{"text":" and a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/nextWordPredictionRequestApiKey","isActive":true,"type":"reference"},{"type":"text","text":". "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings","isActive":true,"type":"reference"},{"text":" will then provide you with a properly configured ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/nextWordPredictionRequest","isActive":true,"type":"reference"},{"text":" for that information.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"KeyboardKit Pro’s ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/SettingsScreen","isActive":true,"type":"reference"},{"type":"text","text":" has a visibility setting to show a next word prediction section. This section is hidden by default."}],"type":"paragraph"},{"type":"thematicBreak"},{"anchor":"How-to","level":2,"type":"heading","text":"How to…"},{"anchor":"perform-autocomplete","text":"…perform autocomplete","level":3,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","isActive":true,"type":"reference"},{"type":"text","text":" will automatically call "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardController\/performAutocomplete()","type":"reference","isActive":true},{"text":" whenever the keyboard text changes, or the input cursor is moved, after which it updates the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/State\/autocompleteContext","type":"reference","isActive":true},{"text":" with the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Services\/autocompleteService"},{"type":"text","text":" result."}]},{"inlineContent":[{"type":"text","text":"You can configure the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/State\/autocompleteContext"},{"text":", override the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController"},{"text":"’s autocomplete properties and functions, and replace the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Services\/autocompleteService"},{"text":" with a custom service, to customize the autocomplete behavior.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","isActive":true},{"type":"text","text":" automatically adds an autocomplete "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/Toolbar","type":"reference","isActive":true},{"text":" to list ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteContext\/suggestions"},{"text":" and provide extra top space for callouts.","type":"text"}],"type":"paragraph"},{"level":3,"type":"heading","text":"…create a custom autocomplete service","anchor":"create-a-custom-autocomplete-service"},{"inlineContent":[{"type":"text","text":"You can create a custom autocomplete service to customize the autocomplete behavior or integrate with 3rd party services. You can the implement "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteService","isActive":true},{"type":"text","text":" protocol from scratch, or inherit and customize any "},{"overridingTitle":"KeyboardKit Pro","overridingTitleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","isActive":true,"type":"reference"},{"text":" service:","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["class CustomAutocompleteService: Autocomplete.LocalAutocompleteService {","","    override func autocompleteSuggestions(","        for text: String","    ) async throws -> [Autocomplete.Suggestion] {","        let original = super.autocompleteSuggestions(for: text)","        let reversed = original.reversed()","        return Array(reversed)","    }","}"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"To use this service instead of the standard one, just inject it into "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","type":"reference","isActive":true},{"type":"text","text":" by replacing its "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Services\/autocompleteService"},{"type":"text","text":" property:"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["class KeyboardViewController: KeyboardInputViewController {","","    override func viewDidLoad() {","        super.viewDidLoad()","        services.autocompleteService = CustomAutocompleteService()","        setup(for: .myApp)  \/\/ See the getting-started guide","    }","}"]},{"inlineContent":[{"text":"This will make KeyboardKit use your custom autocomplete service instead of the standard one.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"text":"This article describes the KeyboardKit autocomplete engine.","type":"text"}],"sections":[],"metadata":{"role":"article","images":[{"identifier":"Page.png","type":"card"}],"roleHeading":"Article","title":"Autocomplete","modules":[{"name":"KeyboardKitPro"}]},"kind":"article","hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkitpro\/autocomplete-article"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkitpro\/autocomplete-article"]}],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","interfaceLanguage":"swift"},"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures-Article":{"abstract":[{"text":"This article describes the KeyboardKit gesture engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","images":[{"type":"card","identifier":"Page.png"}],"title":"Gestures","type":"topic","kind":"article","role":"article","url":"\/documentation\/keyboardkitpro\/gestures-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/State/autocompleteContext":{"url":"\/documentation\/keyboardkitpro\/keyboard\/state\/autocompletecontext","abstract":[{"type":"text","text":"The autocomplete context to use."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"autocompleteContext","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro19AutocompleteContextC","text":"AutocompleteContext"}],"title":"autocompleteContext","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/State\/autocompleteContext","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AutocompleteContext/suggestions":{"abstract":[{"type":"text","text":"The suggestions to present to the user."}],"title":"suggestions","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteContext\/suggestions","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"suggestions","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro12AutocompleteV","text":"Autocomplete"},{"kind":"text","text":"."},{"text":"Suggestion","preciseIdentifier":"s:14KeyboardKitPro12AutocompleteV10SuggestionV","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/autocompletecontext\/suggestions"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete/Suggestion":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Suggestion","kind":"identifier"}],"title":"Autocomplete.Suggestion","kind":"symbol","url":"\/documentation\/keyboardkitpro\/autocomplete\/suggestion","navigatorTitle":[{"text":"Suggestion","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/Suggestion","role":"symbol","abstract":[{"text":"This type represents an autocomplete suggestion that","type":"text"},{"text":" ","type":"text"},{"text":"is returned by an ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteService","isActive":true},{"type":"text","text":"."}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Themes-Article":{"abstract":[{"text":"This article describes the KeyboardKit Pro theme engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article","images":[{"type":"card","identifier":"Page.png"}],"title":"Themes","type":"topic","kind":"article","role":"article","url":"\/documentation\/keyboardkitpro\/themes-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis-Article":{"title":"Emojis","url":"\/documentation\/keyboardkitpro\/emojis-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"kind":"article","type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"autocompletetoolbar":{"identifier":"autocompletetoolbar","type":"image","alt":"AutocompleteToolbar","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/autocompletetoolbar.jpg"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Navigation-Article":{"title":"Navigation","url":"\/documentation\/keyboardkitpro\/navigation-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","abstract":[{"text":"This article describes the KeyboardKit navigation engine.","type":"text"}],"kind":"article","type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUICore/View/autocompleteToolbarStyle(_:)":{"kind":"symbol","type":"topic","abstract":[{"text":"Apply a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/ToolbarStyle","isActive":true},{"text":".","type":"text"}],"title":"autocompleteToolbarStyle(_:)","url":"\/documentation\/keyboardkitpro\/swiftuicore\/view\/autocompletetoolbarstyle(_:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/autocompleteToolbarStyle(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autocompleteToolbarStyle","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Autocomplete","preciseIdentifier":"s:14KeyboardKitPro12AutocompleteV"},{"kind":"text","text":"."},{"text":"ToolbarStyle","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro12AutocompleteV12ToolbarStyleV"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"kind":"text","text":" "},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AutocompleteSettings/isNextWordPredictionEnabled":{"abstract":[{"type":"text","text":"Whether next word prediction is enabled, by default "},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","title":"isNextWordPredictionEnabled","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isNextWordPredictionEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/isNextWordPredictionEnabled","url":"\/documentation\/keyboardkitpro\/autocompletesettings\/isnextwordpredictionenabled"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AutocompleteSettings":{"navigatorTitle":[{"kind":"identifier","text":"AutocompleteSettings"}],"url":"\/documentation\/keyboardkitpro\/autocompletesettings","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings","kind":"symbol","abstract":[{"text":"This type provides autocomplete-related settings.","type":"text"}],"type":"topic","role":"symbol","title":"AutocompleteSettings","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"AutocompleteSettings","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AutocompleteContext/settings-swift.property":{"url":"\/documentation\/keyboardkitpro\/autocompletecontext\/settings-swift.property","title":"settings","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"settings"},{"kind":"text","text":": "},{"text":"AutocompleteSettings","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro20AutocompleteSettingsV"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteContext\/settings-swift.property","role":"symbol","abstract":[{"text":"Auto-persisted autocomplete settings.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/state":{"role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/state","type":"topic","title":"state","abstract":[{"text":"Keyboard-specific state.","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14KeyboardKitPro0A0V","text":"Keyboard","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"State","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V5StateC"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete/RemoteAutocompleteService":{"abstract":[{"type":"text","text":"This class can perform remote API-based autocomplete,"},{"text":" ","type":"text"},{"type":"text","text":"by calling any REST-based API."}],"kind":"symbol","type":"topic","title":"Autocomplete.RemoteAutocompleteService","url":"\/documentation\/keyboardkitpro\/autocomplete\/remoteautocompleteservice","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RemoteAutocompleteService"}],"navigatorTitle":[{"text":"RemoteAutocompleteService","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/RemoteAutocompleteService"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Styling-Article":{"images":[{"type":"card","identifier":"Page.png"}],"title":"Styling","role":"article","type":"topic","kind":"article","abstract":[{"text":"This article describes the KeyboardKit styling engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","url":"\/documentation\/keyboardkitpro\/styling-article"},"https://github.com/KeyboardKit/KeyboardKitPro":{"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","titleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"type":"link","url":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","title":"KeyboardKit Pro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AutocompleteSettings/nextWordPredictionRequestApiKey":{"abstract":[{"text":"A custom, user-specified next word predicton request API key.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextWordPredictionRequestApiKey","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","url":"\/documentation\/keyboardkitpro\/autocompletesettings\/nextwordpredictionrequestapikey","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/nextWordPredictionRequestApiKey","type":"topic","title":"nextWordPredictionRequestApiKey","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Settings-Article":{"abstract":[{"text":"This article describes the KeyboardKit settings engine and its available settings.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","images":[{"type":"card","identifier":"Page.png"}],"title":"Settings","type":"topic","kind":"article","role":"article","url":"\/documentation\/keyboardkitpro\/settings-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation-Article":{"title":"Dictation","url":"\/documentation\/keyboardkitpro\/dictation-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"kind":"article","type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards-Article":{"abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","images":[{"type":"card","identifier":"Page.png"}],"title":"External Keyboards","type":"topic","kind":"article","role":"article","url":"\/documentation\/keyboardkitpro\/external-keyboards-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete/LocalAutocompleteService":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LocalAutocompleteService","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"LocalAutocompleteService"}],"abstract":[{"text":"This service can perform on-device autocomplete, and","type":"text"},{"type":"text","text":" "},{"text":"also perform next character predictions.","type":"text"}],"kind":"symbol","title":"Autocomplete.LocalAutocompleteService","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/LocalAutocompleteService","type":"topic","url":"\/documentation\/keyboardkitpro\/autocomplete\/localautocompleteservice"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy-Article":{"abstract":[{"text":"This article describes the KeyboardKit proxy engine and its utilities.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","images":[{"type":"card","identifier":"Page.png"}],"title":"Proxy Utilities","type":"topic","kind":"article","role":"article","url":"\/documentation\/keyboardkitpro\/proxy-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardController/performAutocomplete()":{"required":true,"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Perform an autocomplete operation.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"performAutocomplete"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardController\/performAutocomplete()","title":"performAutocomplete()","url":"\/documentation\/keyboardkitpro\/keyboardcontroller\/performautocomplete()"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AI-Article":{"images":[{"identifier":"Page.png","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","title":"AI Support","abstract":[{"text":"This article describes the KeyboardKit AI support capabilities.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/ai-article","role":"article","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp":{"url":"\/documentation\/keyboardkitpro\/keyboardapp","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"KeyboardApp","kind":"identifier"}],"title":"KeyboardApp","abstract":[{"text":"This type can be used to define important properties for","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"your app, and is also a namespace for app-based features."}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","navigatorTitle":[{"kind":"identifier","text":"KeyboardApp"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete/NextWordPredictionRequest/claude(apiKey:apiUrl:anthropicVersion:model:maxTokens:systemPrompt:)":{"abstract":[{"type":"text","text":"Create a Claude-based next word prediction request."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"claude"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"apiKey"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"apiUrl","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"anthropicVersion"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"model","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"maxTokens","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"systemPrompt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"text":"Autocomplete","preciseIdentifier":"s:14KeyboardKitPro12AutocompleteV","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"s:14KeyboardKitPro12AutocompleteV25NextWordPredictionRequestV","text":"NextWordPredictionRequest","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","title":"claude(apiKey:apiUrl:anthropicVersion:model:maxTokens:systemPrompt:)","url":"\/documentation\/keyboardkitpro\/autocomplete\/nextwordpredictionrequest\/claude(apikey:apiurl:anthropicversion:model:maxtokens:systemprompt:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/NextWordPredictionRequest\/claude(apiKey:apiUrl:anthropicVersion:model:maxTokens:systemPrompt:)","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete/NextWordPredictionRequest":{"abstract":[{"type":"text","text":"This type can be used to enable next word prediction."}],"title":"Autocomplete.NextWordPredictionRequest","navigatorTitle":[{"text":"NextWordPredictionRequest","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/NextWordPredictionRequest","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NextWordPredictionRequest"}],"kind":"symbol","url":"\/documentation\/keyboardkitpro\/autocomplete\/nextwordpredictionrequest"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"abstract":[{"text":"This article describes the KeyboardKit localization engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","images":[{"identifier":"Page.png","type":"card"}],"title":"Localization","type":"topic","kind":"article","role":"article","url":"\/documentation\/keyboardkitpro\/localization-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","images":[{"type":"card","identifier":"Page.png"}],"title":"Layout","type":"topic","kind":"article","role":"article","url":"\/documentation\/keyboardkitpro\/layout-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Previews-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit preview engine."}],"url":"\/documentation\/keyboardkitpro\/previews-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","kind":"article","type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}],"title":"Previews"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete/ToolbarStyle":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/ToolbarStyle","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ToolbarStyle"}],"kind":"symbol","navigatorTitle":[{"text":"ToolbarStyle","kind":"identifier"}],"abstract":[{"type":"text","text":"This style can be used to modify the visual style of"},{"type":"text","text":" "},{"type":"text","text":"the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/Toolbar","isActive":true},{"text":" component.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/autocomplete\/toolbarstyle","title":"Autocomplete.ToolbarStyle","type":"topic","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Services/autocompleteService":{"url":"\/documentation\/keyboardkitpro\/keyboard\/services\/autocompleteservice","kind":"symbol","abstract":[{"type":"text","text":"The autocomplete service to use."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Services\/autocompleteService","title":"autocompleteService","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"autocompleteService","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro19AutocompleteServiceP","text":"AutocompleteService"}],"role":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AutocompleteContext":{"abstract":[{"type":"text","text":"This class has observable states and persistent settings"},{"type":"text","text":" "},{"type":"text","text":"for keyboard autocomplete."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutocompleteContext","kind":"identifier"}],"navigatorTitle":[{"text":"AutocompleteContext","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteContext","type":"topic","url":"\/documentation\/keyboardkitpro\/autocompletecontext","kind":"symbol","role":"symbol","title":"AutocompleteContext"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AutocompleteSettings/nextWordPredictionRequest":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/nextWordPredictionRequest","title":"nextWordPredictionRequest","abstract":[{"type":"text","text":"Try to build a next word prediction request from the"},{"text":" ","type":"text"},{"type":"text","text":"selected request type and provided API key, if any."}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nextWordPredictionRequest"},{"kind":"text","text":": "},{"text":"Autocomplete","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro12AutocompleteV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro12AutocompleteV25NextWordPredictionRequestV","text":"NextWordPredictionRequest"},{"kind":"text","text":"?"}],"url":"\/documentation\/keyboardkitpro\/autocompletesettings\/nextwordpredictionrequest","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardView":{"title":"KeyboardView","navigatorTitle":[{"text":"KeyboardView","kind":"identifier"}],"type":"topic","abstract":[{"text":"This view can be used to mimic a native iOS keyboard.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardview","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardView","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"title":"Callouts","url":"\/documentation\/keyboardkitpro\/callouts-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"kind":"article","type":"topic","role":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Status-Article":{"title":"Status","url":"\/documentation\/keyboardkitpro\/status-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit status engine."}],"kind":"article","type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AutocompleteService":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteService","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AutocompleteService","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/autocompleteservice","title":"AutocompleteService","abstract":[{"text":"This protocol can be implemented by any type that can be","type":"text"},{"type":"text","text":" "},{"text":"used perform autocomplete as the user types.","type":"text"}],"navigatorTitle":[{"text":"AutocompleteService","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete/NextWordPredictionRequest/openAI(apiKey:apiUrl:apiKeyHeader:apiKeyValuePrefix:model:maxTokens:systemPrompt:)":{"abstract":[{"text":"Create an OpenAI-based next word prediction request.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/autocomplete\/nextwordpredictionrequest\/openai(apikey:apiurl:apikeyheader:apikeyvalueprefix:model:maxtokens:systemprompt:)","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openAI","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"apiKey"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"apiUrl"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"apiKeyHeader"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"apiKeyValuePrefix"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"model","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"maxTokens","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"systemPrompt","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:14KeyboardKitPro12AutocompleteV","text":"Autocomplete","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"NextWordPredictionRequest","preciseIdentifier":"s:14KeyboardKitPro12AutocompleteV25NextWordPredictionRequestV","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/NextWordPredictionRequest\/openAI(apiKey:apiUrl:apiKeyHeader:apiKeyValuePrefix:model:maxTokens:systemPrompt:)","title":"openAI(apiKey:apiUrl:apiKeyHeader:apiKeyValuePrefix:model:maxTokens:systemPrompt:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Text-Input-Article":{"title":"Text Input","url":"\/documentation\/keyboardkitpro\/text-input-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit text input engine."}],"kind":"article","type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit action engine."}],"kind":"article","url":"\/documentation\/keyboardkitpro\/actions-article","title":"Actions","role":"article","type":"topic","images":[{"type":"card","identifier":"Page.png"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"url":"\/documentation\/keyboardkitpro","abstract":[{"text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","kind":"symbol","title":"KeyboardKitPro","role":"collection"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback-Article":{"role":"article","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"kind":"article","title":"Feedback","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","url":"\/documentation\/keyboardkitpro\/feedback-article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AutocompleteSettings/nextWordPredictionRequestType":{"type":"topic","abstract":[{"text":"A custom, user-specified next word predicton request type.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/nextWordPredictionRequestType","role":"symbol","title":"nextWordPredictionRequestType","url":"\/documentation\/keyboardkitpro\/autocompletesettings\/nextwordpredictionrequesttype","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nextWordPredictionRequestType"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro12AutocompleteV","text":"Autocomplete","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"NextWordPredictionRequestType","preciseIdentifier":"s:14KeyboardKitPro12AutocompleteV29NextWordPredictionRequestTypeO","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Host-Article":{"title":"Host Application","url":"\/documentation\/keyboardkitpro\/host-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","abstract":[{"type":"text","text":"This article describes how KeyboardKit Pro can identify and use the host application."}],"kind":"article","type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"kind":"symbol","navigatorTitle":[{"text":"KeyboardInputViewController","kind":"identifier"}],"role":"symbol","title":"KeyboardInputViewController","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","abstract":[{"type":"text","text":"This is the main input controller in a KeyboardKit-based"},{"type":"text","text":" "},{"text":"keyboard extension.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardInputViewController"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Device-Article":{"title":"Device Utilities","url":"\/documentation\/keyboardkitpro\/device-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit device utilities."}],"kind":"article","type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp/SettingsScreen":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/SettingsScreen","role":"symbol","abstract":[{"text":"This screen can be used as a main settings screen in","type":"text"},{"type":"text","text":" "},{"type":"text","text":"a keyboard app or its keyboard extension."}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SettingsScreen"}],"navigatorTitle":[{"kind":"identifier","text":"SettingsScreen"}],"title":"KeyboardApp.SettingsScreen","url":"\/documentation\/keyboardkitpro\/keyboardapp\/settingsscreen"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete/Toolbar":{"role":"symbol","abstract":[{"type":"text","text":"This toolbar can be added above the keyboard to show"},{"type":"text","text":" "},{"type":"text","text":"autocomplete suggestions as the user types."}],"url":"\/documentation\/keyboardkitpro\/autocomplete\/toolbar","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete\/Toolbar","kind":"symbol","navigatorTitle":[{"text":"Toolbar","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Toolbar","kind":"identifier"}],"type":"topic","title":"Autocomplete.Toolbar"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/services":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"services"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Keyboard","preciseIdentifier":"s:14KeyboardKitPro0A0V"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Services","preciseIdentifier":"s:14KeyboardKitPro0A0V8ServicesC"}],"kind":"symbol","abstract":[{"text":"Keyboard-specific services.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","title":"services","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/services","role":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete":{"title":"Autocomplete","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Autocomplete","kind":"identifier"}],"navigatorTitle":[{"text":"Autocomplete","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/autocomplete","abstract":[{"type":"text","text":"This namespace contains autocomplete-related types."}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/App-Article":{"title":"App Utilities","url":"\/documentation\/keyboardkitpro\/app-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}],"kind":"article","type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AutocompleteService/disabled":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteService\/disabled","type":"topic","url":"\/documentation\/keyboardkitpro\/autocompleteservice\/disabled","title":"disabled","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disabled"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Create a disabled service instance."}],"conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" is ","type":"text"},{"type":"codeVoice","code":"Autocomplete.DisabledAutocompleteService"},{"text":".","type":"text"}]}},"Page.png":{"identifier":"Page.png","type":"image","alt":"Page icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png","traits":["1x","light"]}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"anchor":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"title":"Articles"}]},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title","value":"KeyboardInputViewController","op":"replace"},{"value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/navigatorTitle","value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}