{"metadata":{"role":"article","color":{"standardColorIdentifier":"blue"},"images":[{"type":"card","identifier":"Page.png"}],"roleHeading":"Article","modules":[{"name":"KeyboardKitPro"}],"title":"Callouts"},"seeAlsoSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"title":"Features","anchor":"Features","generated":true}],"primaryContentSections":[{"content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"inlineContent":[{"type":"text","text":"Callouts are an important part of the typing experience, where input callouts can show the currently pressed key and action callouts can show secondary actions when certain keys are long pressed."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit has ways to automatically show an ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/InputCallout"},{"type":"text","text":" when the user types, and has a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutService","isActive":true},{"type":"text","text":" protocol that can provide actions to present in an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/ActionCallout"},{"text":" when long pressing certain keys.","type":"text"}]},{"inlineContent":[{"text":"👑 ","type":"text"},{"type":"reference","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","isActive":true},{"text":" unlocks localized services for all locales. Information about Pro features can be found at the end of this article.","type":"text"}],"type":"paragraph"},{"type":"heading","level":2,"text":"Callouts Namespace","anchor":"Callouts-Namespace"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts","isActive":true,"type":"reference"},{"type":"text","text":" namespace that contains callout-related types and views. For instance, an "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/InputCallout","isActive":true},{"type":"text","text":" can present the currently pressed character while an "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/ActionCallout","isActive":true,"type":"reference"},{"type":"text","text":" can present secondary actions when long pressing a key."}]},{"type":"heading","anchor":"Callout-Context","level":2,"text":"Callout Context"},{"inlineContent":[{"type":"text","text":"KeyboardKit has an observable "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutContext","isActive":true},{"text":" class that provides observable input and action callout state, such as the currently pressed key or the callout actions to present.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"KeyboardKit automatically creates an instance of this class and injects it into ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state","isActive":true,"type":"reference"},{"text":", then updates this context when keys are pressed.","type":"text"}],"type":"paragraph"},{"text":"Callout Services","anchor":"Callout-Services","level":2,"type":"heading"},{"inlineContent":[{"text":"In KeyboardKit, a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutService"},{"text":" can be used to provide secondary callout actions for any key, which are then presented when a key with actions is long pressed.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"KeyboardKit automatically creates an instance of ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/StandardService","isActive":true},{"type":"text","text":" and injects it into "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services"},{"text":". You can replace it at any time, as described further down, or inject localized services into it.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"You can easily resolve various ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutService","isActive":true,"type":"reference"},{"text":" implementations with these shorthands, sorted by relevance:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutService\/standard(keyboardContext:baseService:localizedServices:feedbackService:)","isActive":true,"type":"reference"}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutService\/localized(for:)","isActive":true},{"type":"text","text":" (👑 KeyboardKit Pro)"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutService\/disabled"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutService\/preview"}]}]}],"type":"unorderedList"},{"text":"How to show input and action callouts","anchor":"How-to-show-input-and-action-callouts","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","type":"reference","isActive":true},{"text":" and ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Button"},{"text":" will automatically apply the proper view extensions to make input and action callouts work, so you don’t have to do anything to make action and input callouts work.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"For other views, you can apply the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/keyboardCalloutContainer(calloutContext:keyboardContext:)","type":"reference","isActive":true},{"type":"text","text":" view extension to make any view act as the container of input and action callouts:"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["MyKeyboard()","    .keyboardCalloutContainer(...)"]},{"inlineContent":[{"text":"This will bind a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutContext","isActive":true},{"type":"text","text":" to the view and apply "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/ActionCallout","isActive":true,"type":"reference"},{"type":"text","text":" and "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/InputCallout","isActive":true,"type":"reference"},{"text":" views that will show as it changes.","type":"text"}],"type":"paragraph"},{"text":"How to create a custom callout service","anchor":"How-to-create-a-custom-callout-service","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can create a custom "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutService","type":"reference","isActive":true},{"type":"text","text":" to customize which secondary callout actions to show for different "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","isActive":true},{"text":"s.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"You can implement the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutService","isActive":true,"type":"reference"},{"text":" protocol from scratch, or inherit and customize ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/BaseService"},{"text":" or ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/StandardService"},{"type":"text","text":" to get a lot of functionality for free, for instance:"}]},{"syntax":"swift","code":["class CustomCalloutService: Callouts.StandardService {","    ","    override func calloutActions(for action: KeyboardAction) -> [KeyboardAction] {","        var actions = super.calloutActions(for: action)","        \/\/ Perform any modifications here","        return actions","    }","}"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/StandardService"},{"text":" and ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/ProService","isActive":true},{"type":"text","text":" base classes have different functions that you can override, and the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","isActive":true,"type":"reference"},{"type":"text","text":" model also provodes ways to define actions."}]},{"inlineContent":[{"text":"To use your custom service instead of the standard one, just inject it into ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","type":"reference"},{"type":"text","text":" by replacing its "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Services\/calloutService","type":"reference"},{"type":"text","text":" property:"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["class KeyboardViewController: KeyboardInputViewController {","","    override func viewDidLoad() {","        super.viewDidLoad()","        services.calloutService = CustomCalloutService()","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This will make KeyboardKit use your custom implementation instead of the standard one."}]},{"level":2,"text":"How to customize the callouts for a specific locale","type":"heading","anchor":"How-to-customize-the-callouts-for-a-specific-locale"},{"inlineContent":[{"text":"If a service inherits ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/StandardService"},{"type":"text","text":", you can use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutService\/tryRegisterLocalizedService(_:)"},{"text":" or the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Services"},{"type":"text","text":" convenient "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Services\/tryRegisterLocalizedCalloutService(_:)","type":"reference"},{"text":" to register a custom service for a certain ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale","isActive":true},{"text":".","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"For instance, this is how you could make KeyboardKit Pro use  a custom service for ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale\/german","isActive":true},{"type":"text","text":":"}]},{"syntax":"swift","type":"codeListing","code":["class MyCustomGermanService: KeyboardLayout.ProService.German { ... } ","","class KeyboardViewController: KeyboardInputViewController {","","    override func viewDidLoad() {","        super.viewDidLoad()","        services.tryRegisterLocalizedCalloutService(","            try! MyCustomGermanService() ","        )","    }","}"]},{"inlineContent":[{"type":"text","text":"This makes it easy to replace the default service for a certain locale in KeyboardKit Pro, where you can subclass "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/ProService"},{"text":" or any localized Pro service, and make customizations to it.","type":"text"}],"type":"paragraph"},{"level":2,"anchor":"Views","type":"heading","text":"Views"},{"inlineContent":[{"type":"text","text":"The "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts","type":"reference"},{"type":"text","text":" namespace has callout-specific views, that can be used to mimic the native iOS & iPadOS input and action callouts."}],"type":"paragraph"},{"type":"tabNavigator","tabs":[{"content":[{"inlineContent":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/ActionCallout"},{"type":"text","text":" view mimics a native action callout, and can present secondary actions when a keyboard key is long-pressed:"}],"type":"paragraph"},{"columns":[{"content":[],"size":1},{"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"actioncallout"}]}],"size":3},{"size":1,"content":[]}],"type":"row","numberOfColumns":5},{"type":"paragraph","inlineContent":[{"text":"The view can be styled with a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/ActionCalloutStyle","isActive":true},{"type":"text","text":", which is applied with the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/actionCalloutStyle(_:)","isActive":true},{"text":" view modifier.","type":"text"}]}],"title":"Callouts.ActionCallout"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/InputCallout","type":"reference"},{"type":"text","text":" view mimics a native input callout, which can be used to show the currently pressed key as the user types:"}]},{"numberOfColumns":5,"columns":[{"size":1,"content":[]},{"content":[{"inlineContent":[{"type":"image","identifier":"inputcallout"}],"type":"paragraph"}],"size":3},{"size":1,"content":[]}],"type":"row"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The view can be styled with a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/InputCalloutStyle"},{"text":", which can be applied with the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/inputCalloutStyle(_:)"},{"type":"text","text":" view modifier."}]}],"title":"Callouts.InputCallout"}]},{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","isActive":true},{"text":" automatically registers everything needed to automatically show these callouts.","type":"text"}],"type":"paragraph"},{"text":"👑 KeyboardKit Pro","type":"heading","level":2,"anchor":"%F0%9F%91%91-KeyboardKit-Pro"},{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","overridingTitle":"KeyboardKit Pro","overridingTitleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"isActive":true},{"type":"text","text":" unlocks a localized "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutService","type":"reference","isActive":true},{"text":" for every locale in your license, which will be injected as localized services into the main ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Services\/calloutService"},{"type":"text","text":" when a valid license is registered."}]},{"type":"heading","text":"Pro Callout Services","anchor":"Pro-Callout-Services","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks a localized "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/ProService","type":"reference","isActive":true},{"type":"text","text":" for every locale in your license. They are injected into the main "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Services\/calloutService"},{"text":" when a valid license is registered.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"You can access any localized service in your license like this, after successfully registering your license key:","type":"text"}]},{"code":["let service = try Callouts.ProService.Swedish()"],"type":"codeListing","syntax":"swift"},{"content":[{"type":"paragraph","inlineContent":[{"text":"These services will throw a license error if their locales are not included in the license.","type":"text"}]}],"type":"aside","name":"Important","style":"important"},{"type":"heading","text":"How to customize a Pro service","level":3,"anchor":"How-to-customize-a-Pro-service"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can inherit and customize any "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/ProService","type":"reference","isActive":true},{"type":"text","text":" in your license, then manually register your service after setting up KeyboardKit Pro for your "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","isActive":true,"type":"reference"},{"type":"text","text":", or with a license key:"}]},{"syntax":"swift","type":"codeListing","code":["class CustomService: Callouts.ProService.Swedish {","","    \/\/ Override any functions you want here...","}","","class KeyboardController: KeyboardInputViewController {","","    override func viewDidLoad() {","        super.viewDidLoad()","        setupPro(for: .myApp) { license in","            setupCustomService()","        } ","    }","","    func setupCustomService() {","        do {","            let service = try CustomService()","            try services.calloutService.tryRegisterLocalizedService(service)","        } catch {","            print(error)","        }","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This is useful for when you want to make modifications to a single locale’s callout actions, but keep all other locales the same."}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkitpro\/callouts-article"]},{"paths":["\/documentation\/keyboardkitpro\/callouts-article"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","abstract":[{"text":"This article describes the KeyboardKit callout engine.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"references":{"inputcallout":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/inputcallout.jpg"}],"alt":"InputCallout","type":"image","identifier":"inputcallout"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/App-Article":{"title":"App Utilities","abstract":[{"text":"This article describes the KeyboardKit app-specific utilities.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","url":"\/documentation\/keyboardkitpro\/app-article","role":"article","type":"topic","images":[{"identifier":"Page.png","type":"card"}],"kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLocale":{"url":"\/documentation\/keyboardkitpro\/keyboardlocale","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardLocale","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"This enum defines KeyboardKit-supported locales and is a"},{"type":"text","text":" "},{"text":"namespace for locale-elated types.","type":"text"}],"title":"KeyboardLocale","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardLocale"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Status-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","url":"\/documentation\/keyboardkitpro\/status-article","title":"Status","role":"article","images":[{"type":"card","identifier":"Page.png"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit status engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/CalloutService/standard(keyboardContext:baseService:localizedServices:feedbackService:)":{"type":"topic","role":"symbol","url":"\/documentation\/keyboardkitpro\/calloutservice\/standard(keyboardcontext:baseservice:localizedservices:feedbackservice:)","kind":"symbol","abstract":[{"type":"text","text":"Create a standard callout service."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"standard","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"keyboardContext"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14KeyboardKitPro0A7ContextC","kind":"typeIdentifier","text":"KeyboardContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"baseService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CalloutService","preciseIdentifier":"s:14KeyboardKitPro14CalloutServiceP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"localizedServices"},{"text":": [","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro8CalloutsV15StandardServiceC016LocalizedCalloutF0a","text":"LocalizedCalloutService"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"feedbackService"},{"kind":"text","text":": "},{"text":"FeedbackService","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro15FeedbackServiceP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Self"}],"title":"standard(keyboardContext:baseService:localizedServices:feedbackService:)","conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"text":" is ","type":"text"},{"code":"Callouts.StandardService","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutService\/standard(keyboardContext:baseService:localizedServices:feedbackService:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Previews-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","url":"\/documentation\/keyboardkitpro\/previews-article","title":"Previews","role":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit preview engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts/InputCalloutStyle":{"navigatorTitle":[{"kind":"identifier","text":"InputCalloutStyle"}],"url":"\/documentation\/keyboardkitpro\/callouts\/inputcalloutstyle","kind":"symbol","title":"Callouts.InputCalloutStyle","type":"topic","role":"symbol","abstract":[{"type":"text","text":"This style can be used to modify the visual style of"},{"type":"text","text":" "},{"type":"text","text":"the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/InputCallout"},{"text":" component.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/InputCalloutStyle","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"InputCalloutStyle"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardView":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardView","kind":"identifier"}],"title":"KeyboardView","abstract":[{"type":"text","text":"This view can be used to mimic a native iOS keyboard."}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardView"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardview","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/CalloutService/tryRegisterLocalizedService(_:)":{"abstract":[{"type":"text","text":"Try to register a localized service, which will then"},{"text":" ","type":"text"},{"text":"be used for the locale it specifies.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tryRegisterLocalizedService"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CalloutService","preciseIdentifier":"s:14KeyboardKitPro14CalloutServiceP"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutService\/tryRegisterLocalizedService(_:)","url":"\/documentation\/keyboardkitpro\/calloutservice\/tryregisterlocalizedservice(_:)","title":"tryRegisterLocalizedService(_:)","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"images":[{"identifier":"Page.png","type":"card"}],"role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/actions-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit action engine."}],"title":"Actions"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts/BaseService":{"title":"Callouts.BaseService","url":"\/documentation\/keyboardkitpro\/callouts\/baseservice","abstract":[{"text":"This is a base class for callout services.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/BaseService","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BaseService","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"BaseService","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","title":"External Keyboards","role":"article","type":"topic","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit external keyboard engine."}],"images":[{"identifier":"Page.png","type":"card"}],"url":"\/documentation\/keyboardkitpro\/external-keyboards-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","title":"Layout","role":"article","abstract":[{"text":"This article describes the KeyboardKit layout engine.","type":"text"}],"images":[{"type":"card","identifier":"Page.png"}],"url":"\/documentation\/keyboardkitpro\/layout-article","kind":"article","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Button":{"abstract":[{"type":"text","text":"This view mimics a native keyboard button."}],"type":"topic","title":"Keyboard.Button","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Button","url":"\/documentation\/keyboardkitpro\/keyboard\/button","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Button"}],"navigatorTitle":[{"kind":"identifier","text":"Button"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete-Article":{"images":[{"type":"card","identifier":"Page.png"}],"role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/autocomplete-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}],"title":"Autocomplete"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts/StandardService":{"title":"Callouts.StandardService","role":"symbol","url":"\/documentation\/keyboardkitpro\/callouts\/standardservice","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/StandardService","kind":"symbol","abstract":[{"type":"text","text":"This service class provides a standard way to handle"},{"type":"text","text":" "},{"type":"text","text":"keyboard callouts."}],"navigatorTitle":[{"text":"StandardService","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StandardService"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUICore/View/actionCalloutStyle(_:)":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/actionCalloutStyle(_:)","title":"actionCalloutStyle(_:)","role":"symbol","abstract":[{"type":"text","text":"Apply a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/ActionCalloutStyle","isActive":true,"type":"reference"},{"text":".","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionCalloutStyle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Callouts","preciseIdentifier":"s:14KeyboardKitPro8CalloutsV"},{"kind":"text","text":"."},{"text":"ActionCalloutStyle","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro8CalloutsV18ActionCalloutStyleV"},{"kind":"text","text":") -> "},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"url":"\/documentation\/keyboardkitpro\/swiftuicore\/view\/actioncalloutstyle(_:)","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts/ActionCallout":{"role":"symbol","abstract":[{"type":"text","text":"This callout can show secondary actions in a callout."}],"navigatorTitle":[{"kind":"identifier","text":"ActionCallout"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActionCallout"}],"url":"\/documentation\/keyboardkitpro\/callouts\/actioncallout","kind":"symbol","type":"topic","title":"Callouts.ActionCallout","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/ActionCallout"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/CalloutService":{"type":"topic","title":"CalloutService","url":"\/documentation\/keyboardkitpro\/calloutservice","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutService","abstract":[{"type":"text","text":"This protocol can be implemented by any type that can be"},{"text":" ","type":"text"},{"text":"used to perform callout-related actions.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CalloutService"}],"navigatorTitle":[{"kind":"identifier","text":"CalloutService"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","title":"Localization","role":"article","type":"topic","kind":"article","abstract":[{"text":"This article describes the KeyboardKit localization engine.","type":"text"}],"images":[{"identifier":"Page.png","type":"card"}],"url":"\/documentation\/keyboardkitpro\/localization-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUICore/View/inputCalloutStyle(_:)":{"abstract":[{"type":"text","text":"Apply a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/InputCalloutStyle","isActive":true},{"text":".","type":"text"}],"title":"inputCalloutStyle(_:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/inputCalloutStyle(_:)","role":"symbol","kind":"symbol","url":"\/documentation\/keyboardkitpro\/swiftuicore\/view\/inputcalloutstyle(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inputCalloutStyle"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro8CalloutsV","text":"Callouts","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro8CalloutsV17InputCalloutStyleV","text":"InputCalloutStyle"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Settings-Article":{"url":"\/documentation\/keyboardkitpro\/settings-article","kind":"article","title":"Settings","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit settings engine."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","type":"topic","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Essentials-Article":{"images":[{"identifier":"Page.png","type":"card"}],"kind":"article","url":"\/documentation\/keyboardkitpro\/essentials-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","role":"article","title":"Essentials","abstract":[{"type":"text","text":"This article describes the essential parts of KeyboardKit."}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLocale/german":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"german","kind":"identifier"}],"title":"KeyboardLocale.german","url":"\/documentation\/keyboardkitpro\/keyboardlocale\/german","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale\/german","abstract":[],"kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Host-Article":{"images":[{"identifier":"Page.png","type":"card"}],"role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/host-article","abstract":[{"type":"text","text":"This article describes how KeyboardKit can identify the host application."}],"title":"Host Utilities"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/CalloutService/preview":{"url":"\/documentation\/keyboardkitpro\/calloutservice\/preview","title":"preview","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutService\/preview","abstract":[],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preview"},{"text":": ","kind":"text"},{"text":"CalloutService","preciseIdentifier":"s:14KeyboardKitPro14CalloutServiceP","kind":"typeIdentifier"}],"kind":"symbol","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" is ","type":"text"},{"type":"codeVoice","code":"KeyboardPreviews.PreviewCalloutService"},{"type":"text","text":"."}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts":{"kind":"symbol","title":"Callouts","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts","navigatorTitle":[{"kind":"identifier","text":"Callouts"}],"url":"\/documentation\/keyboardkitpro\/callouts","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Callouts"}],"abstract":[{"text":"This namespace contains callout-related types.","type":"text"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/CalloutService/localized(for:)":{"abstract":[{"text":"Get the default callout service for a certain locale.","type":"text"}],"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" is "},{"type":"codeVoice","code":"Callouts.ProService"},{"type":"text","text":"."}]},"kind":"symbol","title":"localized(for:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutService\/localized(for:)","url":"\/documentation\/keyboardkitpro\/calloutservice\/localized(for:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"localized","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A6LocaleO","kind":"typeIdentifier","text":"KeyboardLocale"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"Self"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","url":"\/documentation\/keyboardkitpro\/dictation-article","title":"Dictation","role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts/InputCallout":{"type":"topic","title":"Callouts.InputCallout","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"InputCallout"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"InputCallout","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/InputCallout","abstract":[{"text":"This callout can show the pressed char in a callout.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/callouts\/inputcallout"},"actioncallout":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/actioncallout.jpg"}],"alt":"ActionCallout","type":"image","identifier":"actioncallout"},"https://github.com/KeyboardKit/KeyboardKitPro":{"url":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","title":"KeyboardKit Pro","titleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"type":"link","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/CalloutContext":{"url":"\/documentation\/keyboardkitpro\/calloutcontext","title":"CalloutContext","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutContext","abstract":[{"type":"text","text":"This class has observable, callout-related state."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CalloutContext","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CalloutContext"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","url":"\/documentation\/keyboardkitpro","abstract":[{"type":"text","text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI."}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","title":"KeyboardKitPro","kind":"symbol"},"Page.png":{"alt":"Page icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png"}],"type":"image","identifier":"Page.png"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUICore/View/keyboardCalloutContainer(calloutContext:keyboardContext:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardCalloutContainer"},{"text":"(","kind":"text"},{"text":"calloutContext","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CalloutContext","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro14CalloutContextC"},{"text":", ","kind":"text"},{"text":"keyboardContext","kind":"externalParam"},{"kind":"text","text":": "},{"text":"KeyboardContext","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A7ContextC"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/keyboardCalloutContainer(calloutContext:keyboardContext:)","url":"\/documentation\/keyboardkitpro\/swiftuicore\/view\/keyboardcalloutcontainer(calloutcontext:keyboardcontext:)","type":"topic","title":"keyboardCalloutContainer(calloutContext:keyboardContext:)","abstract":[{"text":"Setup the view as an keyboard callout container.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Themes-Article":{"images":[{"type":"card","identifier":"Page.png"}],"role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/themes-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit Pro theme engine, which can be used to style the entire keyboard with a single theme."}],"title":"Themes"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts/ProService":{"abstract":[{"type":"text","text":"This class is inherited by all Pro services and also"},{"text":" ","type":"text"},{"text":"serves as a namespace for Pro service types.","type":"text"}],"navigatorTitle":[{"text":"ProService","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProService"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/ProService","url":"\/documentation\/keyboardkitpro\/callouts\/proservice","title":"Callouts.ProService"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures-Article":{"images":[{"identifier":"Page.png","type":"card"}],"role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/gestures-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit gesture engine."}],"title":"Gestures"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Services/tryRegisterLocalizedCalloutService(_:)":{"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Services\/tryRegisterLocalizedCalloutService(_:)","abstract":[{"text":"Try to register a localized service, which will then","type":"text"},{"type":"text","text":" "},{"type":"text","text":"be used for the locale it specifies."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tryRegisterLocalizedCalloutService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro14CalloutServiceP","text":"CalloutService"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/keyboardkitpro\/keyboard\/services\/tryregisterlocalizedcalloutservice(_:)","title":"tryRegisterLocalizedCalloutService(_:)","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AI-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","url":"\/documentation\/keyboardkitpro\/ai-article","title":"AI Support","role":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit AI support capabilities."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Text-Input-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","url":"\/documentation\/keyboardkitpro\/text-input-article","title":"Text Input","role":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit text input engine, which lets you type within the keyboard extension."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts/ActionCalloutStyle":{"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"ActionCalloutStyle","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ActionCalloutStyle","kind":"identifier"}],"abstract":[{"type":"text","text":"This style can be used to modify the visual style of"},{"type":"text","text":" "},{"type":"text","text":"the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/ActionCallout","isActive":true},{"type":"text","text":" component."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts\/ActionCalloutStyle","kind":"symbol","title":"Callouts.ActionCalloutStyle","url":"\/documentation\/keyboardkitpro\/callouts\/actioncalloutstyle"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","url":"\/documentation\/keyboardkitpro\/keyboardapp","navigatorTitle":[{"kind":"identifier","text":"KeyboardApp"}],"title":"KeyboardApp","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"This type can be used to define important app properties,"},{"text":" ","type":"text"},{"type":"text","text":"and is also a namespace for KeyboardKit Pro app features."}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardApp"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","url":"\/documentation\/keyboardkitpro\/proxy-article","title":"Proxy Utilities","role":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit proxy engine and its utilities."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Navigation-Article":{"title":"Navigation","abstract":[{"type":"text","text":"This article describes the KeyboardKit navigation engine."}],"type":"topic","role":"article","images":[{"type":"card","identifier":"Page.png"}],"url":"\/documentation\/keyboardkitpro\/navigation-article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Services/calloutService":{"type":"topic","kind":"symbol","title":"calloutService","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calloutService","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro14CalloutServiceP","text":"CalloutService"}],"abstract":[{"text":"The callout service to use.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Services\/calloutService","url":"\/documentation\/keyboardkitpro\/keyboard\/services\/calloutservice","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction":{"type":"topic","title":"KeyboardAction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"KeyboardAction","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardaction","abstract":[{"type":"text","text":"This enum defines keyboard-specific actions, and is also"},{"text":" ","type":"text"},{"text":"a namespace for keyboard action-related types.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardAction"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Device-Article":{"kind":"article","url":"\/documentation\/keyboardkitpro\/device-article","type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit device utilities."}],"title":"Device Utilities","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis-Article":{"images":[{"type":"card","identifier":"Page.png"}],"role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/emojis-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"title":"Emojis"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Services":{"url":"\/documentation\/keyboardkitpro\/keyboard\/services","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Services","title":"Keyboard.Services","type":"topic","abstract":[{"type":"text","text":"This type specifies global keyboard services."}],"navigatorTitle":[{"text":"Services","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Services"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/state":{"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/state","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Keyboard","preciseIdentifier":"s:14KeyboardKitPro0A0V","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V5StateC","text":"State"}],"abstract":[{"type":"text","text":"The default set of keyboard-specific state."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state","type":"topic","kind":"symbol","title":"state"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback-Article":{"images":[{"type":"card","identifier":"Page.png"}],"role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/feedback-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit feedback engine."}],"title":"Feedback"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/services":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"services"},{"kind":"text","text":": "},{"text":"Keyboard","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A0V8ServicesC","text":"Services","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/services","title":"services","role":"symbol","abstract":[{"type":"text","text":"The default set of keyboard-specific services."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/CalloutService/disabled":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"disabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"title":"disabled","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutService\/disabled","type":"topic","abstract":[{"text":"Create a disabled callout service.","type":"text"}],"conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" is ","type":"text"},{"code":"Callouts.DisabledService","type":"codeVoice"},{"text":".","type":"text"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"url":"\/documentation\/keyboardkitpro\/calloutservice\/disabled","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Styling-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","url":"\/documentation\/keyboardkitpro\/styling-article","title":"Styling","role":"article","images":[{"type":"card","identifier":"Page.png"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit styling engine."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","op":"add","value":null},{"value":[{"title":"Features","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"generated":true,"anchor":"Features"}],"op":"replace","path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}