{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"abstract":[{"text":"This guide describes how to manage memory in a keyboard extensions.","type":"text"}],"kind":"article","metadata":{"title":"Memory Management","role":"article","images":[{"type":"card","identifier":"Page.png"}],"roleHeading":"Article","modules":[{"name":"KeyboardKitPro"}]},"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Memory-Management","interfaceLanguage":"swift"},"seeAlsoSections":[{"generated":true,"anchor":"Developer-Guides","title":"Developer Guides","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Custom-Keyboards-Explained","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Data-Syncing","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Debugging"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","text":"Overview","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Native iOS keyboards are severely limited when it comes to how much memory they can allocate. Based on the device and iOS version, a keyboard extension is not allowed to allocate more than "},{"type":"strong","inlineContent":[{"type":"text","text":"~60-70 MB"}]},{"type":"text","text":"."}],"type":"paragraph"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If your keyboard extension allocate more memory than what is allowed by iOS, your keyboard extension will be instantly terminated."}]}],"name":"Important","type":"aside","style":"important"},{"inlineContent":[{"text":"You may avoid some crashes by deferring some allocation until after the keyboard has been loaded, but this is not guaranteed to work.","type":"text"}],"type":"paragraph"},{"anchor":"Why-is-this-problematic","text":"Why is this problematic?","type":"heading","level":2},{"inlineContent":[{"text":"These memory limitations have been in effect for many years, and don’t seem to be extended much, even as our devices become more powerful. Despite several discussions with Apple, these limitations remain more or less unchanged.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This makes it hard for keyboards to provide more powerful features. AI & ML could be used to provide amazing keyboard features, but since such models generally require a lot of memory, keyboard extensions are in general unable to use them directly."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Many keyboards work around these limitations by opening the main app or by requesting external, web-based APIs. This will however result in a bas user experience, since users will have to enable Full Access, cross app navigation works bad, and web requests are slow."}],"type":"paragraph"},{"anchor":"What-can-we-do","text":"What can we do?","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Not much, since Apple are very strict about these limitations. At the very least, make sure to carefully monitor your keyboard extension’s memory consumption, and try to defer memory intense tasks until the keyboard has first been rendered."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"You should reach out to Apple if you struggle with these limitations. If many do, perhaps they will consider increasing the memory limit."}],"type":"paragraph"},{"anchor":"Memory-Leaks","text":"Memory Leaks","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"It’s imperative that you inspect your keyboard extension’s memory consumption, to ensure that it doesn’t have any memory leaks. This can easily happen due to how central the keyboard input view controller is to the keyboard extension. It can however be easily handled."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"First, try to find other ways to rely on the keyboard input controller than passing it around, which will cause a memory leak if an instance isn’t marked as weak or unowned. KeyboardKit makes it easy to avoid having to rely on the controller, and instead use state & services."}],"type":"paragraph"},{"inlineContent":[{"text":"If you have a leak, you will see the memory consumption increase when you switch keyboards back and forth. You will also see multiple instances of the same type in the memory graph (see below). This will nto happen when you don’t have a leak.","type":"text"}],"type":"paragraph"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use KeyboardKit’s state and services to avoid having to rely on the controller. This will drastically reduce the risk of memory leaks."}]}],"name":"Tip","type":"aside","style":"tip"},{"anchor":"How-to","text":"How to…","type":"heading","level":2},{"anchor":"monitor-memory-consumption","text":"…monitor memory consumption","type":"heading","level":3},{"inlineContent":[{"type":"text","text":"It’s "},{"type":"emphasis","inlineContent":[{"type":"text","text":"very"}]},{"type":"text","text":" important that you carefully monitor your keyboard’s memory consumption, if you suspect that it’s close to the "},{"type":"strong","inlineContent":[{"text":"60-70 MB","type":"text"}]},{"type":"text","text":" limit."}],"type":"paragraph"},{"columns":[{"content":[{"inlineContent":[{"identifier":"developer-attach-debugger","type":"image"}],"type":"paragraph"}],"size":1},{"content":[{"type":"paragraph","inlineContent":[{"text":"You can monitor a keyboard’s memory consumption by attaching the Xcode debugger to the keyboard process ","type":"text"},{"type":"emphasis","inlineContent":[{"type":"text","text":"after"}]},{"text":" launching the keyboard, by using “Debug > Attach to Process by PID or Name…” and entering the name of your extension in the modal.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The reason why you should wait with attaching the debugger until the keyboard has launched, is that attaching takes time. This may cause Xcode to terminate the launch, but keep zombie allocations that will show you an inaccurate allocation result.","type":"text"}]}],"size":1}],"type":"row","numberOfColumns":2},{"columns":[{"size":1,"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Once the debugger is attached, you can inspect your keyboard’s memory consumption by tapping the Debug Navigator button (the tiny spray bottle) button in the Xcode Project Navigator."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This will show you how much memory your keyboard extension is currently using, which is great to quickly inspect the consumption at a specific time. The “Memory” value is the number that should stay below 60-70 MB."}]}]},{"size":1,"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"developer-memory-consumption"}]}]}],"type":"row","numberOfColumns":2},{"columns":[{"size":1,"content":[{"inlineContent":[{"type":"image","identifier":"developer-memory-graph"}],"type":"paragraph"}]},{"size":1,"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You can also check the full allocation graph by tapping the Debug Memory Graph button in the Xcode Debug Area. This will pause the runner and show you all allocated instances in the Debug Navigator. It will also show an interactive graph in the main area."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"⚠️ The Debug Area should only show a “KeyboardController (1)”! If you see a “KeyboardController (2)” and haven’t created an extra instance, you either attached the debugger before launching the keyboard, as described above, or have a memory leak!"}]}]}],"type":"row","numberOfColumns":2},{"content":[{"inlineContent":[{"type":"text","text":"Always monitor your keyboard extension’s memory consumption on a physical device! The iOS Simulator doesn’t apply the same memory limitations, and may allocate a very different amount of memory than what will be allocated on-device."}],"type":"paragraph"}],"name":"Important","type":"aside","style":"important"}]}],"variants":[{"paths":["\/documentation\/keyboardkitpro\/developer-memory-management"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/developer-memory-management"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Developer-Data-Syncing":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Data-Syncing","kind":"article","images":[{"type":"card","identifier":"Page.png"}],"abstract":[{"type":"text","text":"This guide describes how to sync data between an app and its keyboard extension."}],"url":"\/documentation\/keyboardkitpro\/developer-data-syncing","role":"article","title":"Data Syncing"},"Page.png":{"identifier":"Page.png","alt":"Page icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png"}],"type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Developer-Custom-Keyboards-Explained":{"title":"Custom Keyboards Explained","images":[{"identifier":"Page.png","type":"card"}],"role":"article","abstract":[{"type":"text","text":"This article describes iOS custom keyboards and how they work."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Custom-Keyboards-Explained","type":"topic","url":"\/documentation\/keyboardkitpro\/developer-custom-keyboards-explained","kind":"article"},"developer-attach-debugger":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/developer-attach-debugger.jpg"}],"type":"image","identifier":"developer-attach-debugger","alt":"A screenshot of how to attach to the debugger"},"developer-memory-consumption":{"identifier":"developer-memory-consumption","alt":"A screenshot of how to monitor the memory consumption","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/developer-memory-consumption.jpg"}],"type":"image"},"developer-memory-graph":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/developer-memory-graph.jpg"}],"type":"image","identifier":"developer-memory-graph","alt":"A screenshot of how to inspect the memory graph"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"title":"KeyboardKitPro","kind":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","abstract":[{"text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI.","type":"text"}],"url":"\/documentation\/keyboardkitpro","role":"collection"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Developer-Debugging":{"title":"Debugging","abstract":[{"type":"text","text":"This guide describes how to debug a keyboard extension."}],"type":"topic","images":[{"identifier":"Page.png","type":"card"}],"url":"\/documentation\/keyboardkitpro\/developer-debugging","kind":"article","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Debugging"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"title":"Developer Guides","generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Custom-Keyboards-Explained","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Data-Syncing","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Debugging"],"anchor":"Developer-Guides"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}