{"schemaVersion":{"major":0,"patch":0,"minor":3},"seeAlsoSections":[{"title":"Developer Guides","anchor":"Developer-Guides","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Custom-Keyboards-Explained","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Data-Syncing","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Memory-Management"],"generated":true}],"primaryContentSections":[{"kind":"content","content":[{"text":"Overview","type":"heading","level":2,"anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Native iOS keyboard extensions are a bit tricky to debug, since launching the app will not trigger any breakpoints that you add to your keyboard extension. Even when the debugger is properly attached, you may also notice that printing doesn’t work as expected."}]},{"inlineContent":[{"text":"To debug the keyboard extension, you must either launch the extension instead of the app, or manually attach the Xcode debugger to the keyboard process. This is fairly straightforward, but may feel awkward the first few times you do it.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"By becoming comfortable with debugging your keyboard extension, you will find it a lot easier to find and handle problems and bugs. Follow the steps below to start getting familiar with how to properly debug your keyboard extension."}],"type":"paragraph"},{"type":"heading","level":2,"text":"Common Warnings","anchor":"Common-Warnings"},{"inlineContent":[{"type":"text","text":"When debugging your keyboard extension, you may see the following warning being logged multiple times as you use the keyboard:"}],"type":"paragraph"},{"inlineContent":[{"code":"-[UIInputViewController needsInputModeSwitchKey] was called before a connection was established to the host application. This will produce an inaccurate result. Please make sure to call this after your primary view controller has been initialized.","type":"codeVoice"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This warning is logged because KeyboardKit checks the "},{"code":"needsInputModeSwitchKey","type":"codeVoice"},{"type":"text","text":" property to determine whether or not to add a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/nextKeyboard"},{"type":"text","text":" key to the keyboard. This warning is logged whenever that property is used, even after the keyboard is presented. It doesn’t have any effect on the keyboard, at least in any way that has been detected or reported."}]},{"level":2,"type":"heading","text":"How to…","anchor":"How-to"},{"type":"heading","anchor":"run-the-keyboard-instead-of-the-app","level":3,"text":"…run the keyboard instead of the app"},{"numberOfColumns":2,"columns":[{"size":1,"content":[{"inlineContent":[{"type":"image","identifier":"developer-launch-extension"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"You can run the keyboard extension instead of the main app, by switching target in the Xcode top Target Switcher. This will make the Xcode debugger wait for the keyboard to start, after which it will automatically attach itself to the keyboard process.","type":"text"}]},{"inlineContent":[{"type":"text","text":"While this alternative is convenient, attaching the debugger before the keyboard extension is loaded may cause the launch to take too long, which may cause Xcode to terminate the initial launch. This can lead to inaccurate behavior and zombie instances."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"A more reliable, but slightly more cumbersome approach, is to attach the Xcode debugger ","type":"text"},{"type":"emphasis","inlineContent":[{"text":"after","type":"text"}]},{"text":" the keyboard has been loaded.","type":"text"}]}],"size":1}],"type":"row"},{"text":"…attach the debugger to a running keyboard","anchor":"attach-the-debugger-to-a-running-keyboard","level":3,"type":"heading"},{"columns":[{"size":1,"content":[{"inlineContent":[{"text":"You can attach the Xcode debugger to the keyboard process ","type":"text"},{"type":"emphasis","inlineContent":[{"text":"after","type":"text"}]},{"type":"text","text":" launching the keyboard, by using “Debug > Attach to Process by PID or Name…” and entering the name of the keyboard extension in the modal that appears."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"Attaching the Xcode debugger to your keyboard will make your keyboard show up in the Xcode Debug Navigator (the top leading spray bottle), and will make breakpoints trigger and printing work.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"image","identifier":"developer-attach-debugger"}],"type":"paragraph"}],"size":1}],"type":"row","numberOfColumns":2},{"text":"…properly print from a keyboard extension","level":3,"type":"heading","anchor":"properly-print-from-a-keyboard-extension"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You may notice that "},{"type":"codeVoice","code":"print(...)"},{"text":" will not always work from a keyboard extension, even after properly attaching the debugger. This is a strange bug in Xcode, which is however easy to fix.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you use "},{"code":"NSLog(...)","type":"codeVoice"},{"text":" instead of ","type":"text"},{"code":"print(...)","type":"codeVoice"},{"type":"text","text":", your keyboard extension should print more reliably. Since "},{"type":"codeVoice","code":"NSLog"},{"text":" is not as versatile as ","type":"text"},{"type":"codeVoice","code":"print"},{"text":", you may however have to convert some types to string to be able to print them.","type":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkitpro\/developer-debugging"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkitpro\/developer-debugging"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Debugging"},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"metadata":{"roleHeading":"Article","role":"article","modules":[{"name":"KeyboardKitPro"}],"images":[{"identifier":"Page.png","type":"card"}],"title":"Debugging"},"kind":"article","abstract":[{"type":"text","text":"This guide describes how to debug a keyboard extension."}],"sections":[],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Developer-Memory-Management":{"kind":"article","title":"Memory Management","role":"article","abstract":[{"type":"text","text":"This guide describes how to manage memory in a keyboard extensions."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Memory-Management","images":[{"type":"card","identifier":"Page.png"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/developer-memory-management"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Developer-Data-Syncing":{"url":"\/documentation\/keyboardkitpro\/developer-data-syncing","kind":"article","title":"Data Syncing","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Data-Syncing","role":"article","type":"topic","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This guide describes how to sync data between an app and its keyboard extension."}]},"developer-launch-extension":{"alt":"A screenshot of how to launch the keyboard extension","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/developer-launch-extension.jpg","traits":["1x","light"]}],"type":"image","identifier":"developer-launch-extension"},"Page.png":{"alt":"Page icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png"}],"type":"image","identifier":"Page.png"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"title":"KeyboardKitPro","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","url":"\/documentation\/keyboardkitpro","type":"topic","role":"collection"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/nextKeyboard":{"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/nextKeyboard","type":"topic","title":"KeyboardAction.nextKeyboard","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardaction\/nextkeyboard","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"nextKeyboard","kind":"identifier"}],"abstract":[{"type":"text","text":"Triggers the system keyboard switcher on release and long press."}]},"developer-attach-debugger":{"alt":"A screenshot of how to attach to the debugger","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/developer-attach-debugger.jpg"}],"type":"image","identifier":"developer-attach-debugger"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Developer-Custom-Keyboards-Explained":{"kind":"article","title":"Custom Keyboards Explained","role":"article","abstract":[{"type":"text","text":"This article describes iOS custom keyboards and how they work."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Custom-Keyboards-Explained","images":[{"type":"card","identifier":"Page.png"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/developer-custom-keyboards-explained"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Custom-Keyboards-Explained","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Data-Syncing","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Memory-Management"],"anchor":"Developer-Guides","generated":true,"title":"Developer Guides"}],"op":"replace","path":"\/seeAlsoSections"}]}]}