{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Custom-Keyboards-Explained"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"article","hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"metadata":{"modules":[{"name":"KeyboardKitPro"}],"role":"article","title":"Custom Keyboards Explained","roleHeading":"Article","images":[{"identifier":"Page.png","type":"card"}]},"abstract":[{"text":"This article describes iOS custom keyboards and how they work.","type":"text"}],"seeAlsoSections":[{"anchor":"Developer-Guides","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Data-Syncing","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Debugging","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Memory-Management"],"title":"Developer Guides","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkitpro\/developer-custom-keyboards-explained"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkitpro\/developer-custom-keyboards-explained"]}],"primaryContentSections":[{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"inlineContent":[{"text":"A custom iOS keyboard (or a keyboard extension) is an app extension that you ship together with your app. It can replace the system keyboard in any app that allows typing, by using the bottom-leading 🌐 key.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Keyboard extensions are the only apps that can be used directly with other apps in iOS, and are as such unique ways to let people use your app and its features within other apps.","type":"text"}],"type":"paragraph"},{"text":"How do I create a custom keyboard?","anchor":"How-do-I-create-a-custom-keyboard","type":"heading","level":2},{"inlineContent":[{"text":"You can add a custom keyboard to any iOS app, from Xcode’s “File > New > Target…” menu option. This will add a keyboard extension to your app and make it possible to switch to that keyboard while typing in any app.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The keyboard will by default show some boilerplate content. You can use KeyboardKit to easily replace this content with a complete keyboard view, as described in the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started-Article","isActive":true},{"type":"text","text":" guide."}],"type":"paragraph"},{"text":"What can a custom keyboard do?","anchor":"What-can-a-custom-keyboard-do","type":"heading","level":2},{"inlineContent":[{"text":"A custom keyboard can render any user interface, and can resize the keyboard area to fit its content. This means that the keyboard can be taller or shorter than the native keyboard and show any content that you want.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Custom keyboards use a "},{"inlineContent":[{"type":"text","text":"document proxy"}],"type":"emphasis"},{"type":"text","text":" to communicate with the currently active app. The proxy can be used to read and modify the document text, move the text input cursor, etc."}],"type":"paragraph"},{"inlineContent":[{"text":"A custom keyboard can use these capabilities to provide custom autocomplete & spell-checking, more sophisticated text analysis, AI-based features, etc. The possibilities are endless, but Apple’s native APIs are unfortunately very limited.","type":"text"}],"type":"paragraph"},{"text":"What can a custom keyboard not do?","anchor":"What-can-a-custom-keyboard-not-do","type":"heading","level":2},{"inlineContent":[{"text":"Apple’s native keyboard APIs are very limited, which is why KeyboardKit extends them with additional capabilities and more features, to make it a lot easier to create amazing keyboard experiences.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"However, some things are just not possible. For instance, a custom keyboard can’t draw outside its bounds and must render within the keyboard frame. Custom keyboards are also memory capped at ~70 MB, which means that you can’t allocate that much memory."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Keyboard extensions must also open their main app to perform certain actions, such as accessing the microphone to perform dictation, and must ask the user to enable Full Access to be able to access certain system tools, make network calls, etc."}],"type":"paragraph"},{"level":2,"text":"Further Reading","anchor":"Further-Reading","type":"heading"},{"inlineContent":[{"text":"See the ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/developer.apple.com\/library\/archive\/documentation\/General\/Conceptual\/ExtensibilityPG\/CustomKeyboard.html"},{"text":" for a thorough explanation of the custom keyboard model, and its capabilities. Note that while Apple’s native APIs are very limited, KeyboardKit extends these APIs with many more features.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"KeyboardKit is open-source and completely free to use. With over 1,5k stars on GitHub, it’s a popular open-source SDK for creating iOS keyboards. It’s used by enterprises, smaller companies, startups, universities and indies, in many ","type":"text"},{"identifier":"https:\/\/keyboardkit.com\/case-studies","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}]}],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Developer-Data-Syncing":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Data-Syncing","type":"topic","kind":"article","title":"Data Syncing","role":"article","abstract":[{"type":"text","text":"This guide describes how to sync data between an app and its keyboard extension."}],"url":"\/documentation\/keyboardkitpro\/developer-data-syncing","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Developer-Memory-Management":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Memory-Management","type":"topic","kind":"article","title":"Memory Management","role":"article","abstract":[{"text":"This guide describes how to manage memory in a keyboard extensions.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/developer-memory-management","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Developer-Debugging":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Debugging","type":"topic","kind":"article","title":"Debugging","role":"article","abstract":[{"text":"This guide describes how to debug a keyboard extension.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/developer-debugging","images":[{"identifier":"Page.png","type":"card"}]},"Page.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png"}],"identifier":"Page.png","alt":"Page icon","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Getting-Started-Article":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started-Article","images":[{"type":"card","identifier":"Page.png"}],"kind":"article","url":"\/documentation\/keyboardkitpro\/getting-started-article","title":"Getting Started","abstract":[{"type":"text","text":"This guide describes how to get started with KeyboardKit."}],"role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"kind":"symbol","url":"\/documentation\/keyboardkitpro","role":"collection","title":"KeyboardKitPro","abstract":[{"text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"},"https://keyboardkit.com/case-studies":{"url":"https:\/\/keyboardkit.com\/case-studies","type":"link","titleInlineContent":[{"text":"innovative projects","type":"text"}],"identifier":"https:\/\/keyboardkit.com\/case-studies","title":"innovative projects"},"https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/CustomKeyboard.html":{"titleInlineContent":[{"text":"Apple App Extension Programming Guide","type":"text"}],"identifier":"https:\/\/developer.apple.com\/library\/archive\/documentation\/General\/Conceptual\/ExtensibilityPG\/CustomKeyboard.html","type":"link","title":"Apple App Extension Programming Guide","url":"https:\/\/developer.apple.com\/library\/archive\/documentation\/General\/Conceptual\/ExtensibilityPG\/CustomKeyboard.html"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Data-Syncing","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Debugging","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Memory-Management"],"generated":true,"anchor":"Developer-Guides","title":"Developer Guides"}]}]}]}