{"kind":"article","identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Data-Syncing","interfaceLanguage":"swift"},"abstract":[{"text":"This guide describes how to sync data between an app and its keyboard extension.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkitpro\/developer-data-syncing"]},{"paths":["\/documentation\/keyboardkitpro\/developer-data-syncing"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"inlineContent":[{"text":"When building a keyboard app, it’s important to be able to sync data between the main app and its keyboard extension, for instance if the app is has screens to manage keyboard settings, which should then be applied to the keyboard.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit makes it easy to set up automatic data sync, by setting up your app and keyboard extension with a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","isActive":true,"type":"reference"},{"text":", as is described in the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started-Article"},{"text":" guide. All you have to do is to create an App Group and apply it to your app and keyboard extension.","type":"text"}]},{"anchor":"How-to","type":"heading","level":2,"text":"How to…"},{"anchor":"set-up-an-App-Group-for-your-app","level":3,"type":"heading","text":"…set up an App Group for your app"},{"type":"row","numberOfColumns":2,"columns":[{"size":1,"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"developer-app-groups"}]}]},{"size":1,"content":[{"type":"paragraph","inlineContent":[{"text":"You must first create an App Group in the Apple Developer Portal, under Certificates, Identifiers & Profiles.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The App Group should start with “group.” followed by your app’s bundle ID. For instance, the KeyboardKit demo application uses “group.com.keyboardkit.demo” as App Group identifier.","type":"text"}]},{"type":"aside","name":"Note","style":"note","content":[{"inlineContent":[{"text":"macOS App Groups must start with the Team ID instead of “group.”. This may be a temporary bug or an unintended change, since having duplicate groups is very cumbersome.","type":"text"}],"type":"paragraph"}]}]}]},{"text":"…link the App Group to the app","type":"heading","level":3,"anchor":"link-the-App-Group-to-the-app"},{"numberOfColumns":2,"columns":[{"size":1,"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"After creating the App Group, you must link it to your app and its keyboard extension. This is done under “Signing & Capabilites”."}]},{"inlineContent":[{"type":"text","text":"It’s "},{"type":"emphasis","inlineContent":[{"text":"imperative","type":"text"}]},{"type":"text","text":" that you enable the App Group for all targets that should share data, otherwise a target without the group will not be able to read from or write to the shared data store."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"image","identifier":"developer-app-group-enable"}],"type":"paragraph"}],"size":1}],"type":"row"},{"text":"…set up KeyboardKit to use the App Group","type":"heading","anchor":"set-up-KeyboardKit-to-use-the-App-Group","level":3},{"inlineContent":[{"text":"You can easily set up KeyboardKit to use the App Group to sync data, by defining an ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/appGroupId","isActive":true,"type":"reference"},{"type":"text","text":" in your "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","type":"reference","isActive":true},{"type":"text","text":" value, then use that value to set up KeyboardKit as described in the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started-Article"},{"type":"text","text":" guide."}],"type":"paragraph"}],"kind":"content"}],"metadata":{"title":"Data Syncing","role":"article","roleHeading":"Article","images":[{"identifier":"Page.png","type":"card"}],"modules":[{"name":"KeyboardKitPro"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"seeAlsoSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Custom-Keyboards-Explained","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Debugging","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Memory-Management"],"anchor":"Developer-Guides","generated":true,"title":"Developer Guides"}],"references":{"Page.png":{"alt":"Page icon","type":"image","identifier":"Page.png","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"KeyboardApp","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This type can be used to define important properties for","type":"text"},{"text":" ","type":"text"},{"text":"your app, and is also a namespace for app-based features.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardApp"}],"url":"\/documentation\/keyboardkitpro\/keyboardapp","title":"KeyboardApp","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Developer-Debugging":{"title":"Debugging","kind":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Debugging","abstract":[{"text":"This guide describes how to debug a keyboard extension.","type":"text"}],"images":[{"type":"card","identifier":"Page.png"}],"url":"\/documentation\/keyboardkitpro\/developer-debugging","role":"article"},"developer-app-group-enable":{"alt":"A screenshot of how to enable App Groups","type":"image","identifier":"developer-app-group-enable","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/developer-app-group-enable.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp/appGroupId":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appGroupId","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The app’s App Group identifier, if any."}],"title":"appGroupId","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardapp\/appgroupid","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/appGroupId","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Getting-Started-Article":{"abstract":[{"text":"This guide describes how to get started with KeyboardKit.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/getting-started-article","images":[{"type":"card","identifier":"Page.png"}],"title":"Getting Started","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started-Article","kind":"article","type":"topic","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"url":"\/documentation\/keyboardkitpro","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","type":"topic","role":"collection","title":"KeyboardKitPro","abstract":[{"text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI.","type":"text"}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Developer-Custom-Keyboards-Explained":{"kind":"article","url":"\/documentation\/keyboardkitpro\/developer-custom-keyboards-explained","title":"Custom Keyboards Explained","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Custom-Keyboards-Explained","abstract":[{"type":"text","text":"This article describes iOS custom keyboards and how they work."}],"role":"article","type":"topic","images":[{"identifier":"Page.png","type":"card"}]},"developer-app-groups":{"alt":"A screenshot of the Developer Portal","type":"image","identifier":"developer-app-groups","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/developer-app-groups.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Developer-Memory-Management":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Memory-Management","images":[{"type":"card","identifier":"Page.png"}],"type":"topic","kind":"article","title":"Memory Management","role":"article","url":"\/documentation\/keyboardkitpro\/developer-memory-management","abstract":[{"text":"This guide describes how to manage memory in a keyboard extensions.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Custom-Keyboards-Explained","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Debugging","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Developer-Memory-Management"],"anchor":"Developer-Guides","generated":true,"title":"Developer Guides"}],"op":"replace"}]}]}