{"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article"},"primaryContentSections":[{"content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has device-related features that can help customize your keyboard for various device types, orientations and screen sizes."}]},{"inlineContent":[{"type":"text","text":"Although you should avoid targeting a specific device, orientation, or screen size, some keyboard features require these considerations."}],"type":"paragraph"},{"anchor":"Device-type","level":2,"text":"Device type","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit has a platform-agnostic ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DeviceType","isActive":true,"type":"reference"},{"type":"text","text":" enum that defines available, supported device types."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can use "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DeviceType\/current","isActive":true},{"type":"text","text":" to get the current device type, then use properties like "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DeviceType\/isPhone","type":"reference"},{"type":"text","text":" to determine what kind of device it is."}]},{"syntax":"swift","code":["let device = DeviceType.current","let isPhone = device.isPhone","let isPad = device.isPad"],"type":"codeListing"},{"text":"Interface orientation","anchor":"Interface-orientation","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has a platform-agnostic "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InterfaceOrientation","type":"reference","isActive":true},{"text":" enum that defines various interface (screen) orientations.","type":"text"}]},{"inlineContent":[{"text":"You can use ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InterfaceOrientation\/current","isActive":true},{"type":"text","text":" to get the current interface orientation, then use properties like "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InterfaceOrientation\/isPortrait","type":"reference","isActive":true},{"text":" to determine its orientation type:","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["let orientation = InterfaceOrientation.current","let isPortrait = orientation.isPortrait","let isLandscape = orientation.isLandscape"]},{"anchor":"Screen-sizes","text":"Screen sizes","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has "},{"type":"codeVoice","code":"CGSize"},{"type":"text","text":" extensions for detecting which hardware you’re on, for instance to define and compare various screen sizes."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can use "},{"type":"codeVoice","code":"isScreenSize(_:withTolerance:)"},{"text":" to check if a certain size matches a screen size in any orientation. It uses a low tolerance by default to support slight variations between model changes of the same device type.","type":"text"}]},{"name":"Warning","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Be careful with using screen size as the foundation for certain features. You never know if your software suddenly runs in another way that makes the screen size irrelevant, e.g. in iPad split screen or floating keyboard mode.","type":"text"}]}],"style":"warning"}],"kind":"content"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"article","abstract":[{"text":"This article describes the KeyboardKit device utilities.","type":"text"}],"variants":[{"paths":["\/documentation\/keyboardkitpro\/device-article"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkitpro\/device-article"]}],"seeAlsoSections":[{"title":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"generated":true,"anchor":"Articles"}],"metadata":{"title":"Device Utilities","modules":[{"name":"KeyboardKitPro"}],"images":[{"identifier":"Page.png","type":"card"}],"role":"article","roleHeading":"Article"},"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/DeviceType/current":{"abstract":[{"text":"Get the current device type.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"current","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14KeyboardKitPro10DeviceTypeO","text":"DeviceType","kind":"typeIdentifier"}],"title":"current","kind":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DeviceType\/current","url":"\/documentation\/keyboardkitpro\/devicetype\/current","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback-Article":{"role":"article","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"kind":"article","title":"Feedback","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","url":"\/documentation\/keyboardkitpro\/feedback-article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/DeviceType":{"kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/devicetype","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DeviceType","abstract":[{"text":"This enum defines various supported device types.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DeviceType","kind":"identifier"}],"role":"symbol","title":"DeviceType","navigatorTitle":[{"kind":"identifier","text":"DeviceType"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete-Article":{"abstract":[{"text":"This article describes the KeyboardKit autocomplete engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","images":[{"type":"card","identifier":"Page.png"}],"title":"Autocomplete","type":"topic","kind":"article","role":"article","url":"\/documentation\/keyboardkitpro\/autocomplete-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Host-Article":{"title":"Host Application","url":"\/documentation\/keyboardkitpro\/host-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","abstract":[{"type":"text","text":"This article describes how KeyboardKit Pro can identify and use the host application."}],"kind":"article","type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","images":[{"type":"card","identifier":"Page.png"}],"title":"Layout","type":"topic","kind":"article","role":"article","url":"\/documentation\/keyboardkitpro\/layout-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Styling-Article":{"images":[{"type":"card","identifier":"Page.png"}],"title":"Styling","role":"article","type":"topic","kind":"article","abstract":[{"text":"This article describes the KeyboardKit styling engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","url":"\/documentation\/keyboardkitpro\/styling-article"},"Page.png":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png"}],"alt":"Page icon","identifier":"Page.png"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis-Article":{"title":"Emojis","url":"\/documentation\/keyboardkitpro\/emojis-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"kind":"article","type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Navigation-Article":{"title":"Navigation","url":"\/documentation\/keyboardkitpro\/navigation-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","abstract":[{"text":"This article describes the KeyboardKit navigation engine.","type":"text"}],"kind":"article","type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards-Article":{"abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","images":[{"type":"card","identifier":"Page.png"}],"title":"External Keyboards","type":"topic","kind":"article","role":"article","url":"\/documentation\/keyboardkitpro\/external-keyboards-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Themes-Article":{"abstract":[{"text":"This article describes the KeyboardKit Pro theme engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article","images":[{"type":"card","identifier":"Page.png"}],"title":"Themes","type":"topic","kind":"article","role":"article","url":"\/documentation\/keyboardkitpro\/themes-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures-Article":{"abstract":[{"text":"This article describes the KeyboardKit gesture engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","images":[{"type":"card","identifier":"Page.png"}],"title":"Gestures","type":"topic","kind":"article","role":"article","url":"\/documentation\/keyboardkitpro\/gestures-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/InterfaceOrientation":{"role":"symbol","navigatorTitle":[{"text":"InterfaceOrientation","kind":"identifier"}],"abstract":[{"text":"This enum defines supported interface orientations.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"InterfaceOrientation","kind":"identifier"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/interfaceorientation","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InterfaceOrientation","title":"InterfaceOrientation"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy-Article":{"abstract":[{"text":"This article describes the KeyboardKit proxy engine and its utilities.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","images":[{"type":"card","identifier":"Page.png"}],"title":"Proxy Utilities","type":"topic","kind":"article","role":"article","url":"\/documentation\/keyboardkitpro\/proxy-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"title":"Callouts","url":"\/documentation\/keyboardkitpro\/callouts-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"kind":"article","type":"topic","role":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit action engine."}],"kind":"article","url":"\/documentation\/keyboardkitpro\/actions-article","title":"Actions","role":"article","type":"topic","images":[{"type":"card","identifier":"Page.png"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"abstract":[{"text":"This article describes the KeyboardKit localization engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","images":[{"identifier":"Page.png","type":"card"}],"title":"Localization","type":"topic","kind":"article","role":"article","url":"\/documentation\/keyboardkitpro\/localization-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/DeviceType/isPhone":{"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isPhone","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isPhone","kind":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DeviceType\/isPhone","url":"\/documentation\/keyboardkitpro\/devicetype\/isphone","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/App-Article":{"title":"App Utilities","url":"\/documentation\/keyboardkitpro\/app-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}],"kind":"article","type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"url":"\/documentation\/keyboardkitpro","abstract":[{"text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","kind":"symbol","title":"KeyboardKitPro","role":"collection"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Text-Input-Article":{"title":"Text Input","url":"\/documentation\/keyboardkitpro\/text-input-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit text input engine."}],"kind":"article","type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AI-Article":{"images":[{"identifier":"Page.png","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","title":"AI Support","abstract":[{"text":"This article describes the KeyboardKit AI support capabilities.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/ai-article","role":"article","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/InterfaceOrientation/isPortrait":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isPortrait"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"isPortrait","url":"\/documentation\/keyboardkitpro\/interfaceorientation\/isportrait","abstract":[{"type":"text","text":"Whether or not the orientation is portrait."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InterfaceOrientation\/isPortrait","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Settings-Article":{"abstract":[{"text":"This article describes the KeyboardKit settings engine and its available settings.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","images":[{"type":"card","identifier":"Page.png"}],"title":"Settings","type":"topic","kind":"article","role":"article","url":"\/documentation\/keyboardkitpro\/settings-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/InterfaceOrientation/current":{"abstract":[{"type":"text","text":"Get the current interface orientation."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"current","kind":"identifier"},{"text":": ","kind":"text"},{"text":"InterfaceOrientation","preciseIdentifier":"s:14KeyboardKitPro20InterfaceOrientationO","kind":"typeIdentifier"}],"title":"current","kind":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InterfaceOrientation\/current","url":"\/documentation\/keyboardkitpro\/interfaceorientation\/current","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation-Article":{"title":"Dictation","url":"\/documentation\/keyboardkitpro\/dictation-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"kind":"article","type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Status-Article":{"title":"Status","url":"\/documentation\/keyboardkitpro\/status-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit status engine."}],"kind":"article","type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Previews-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit preview engine."}],"url":"\/documentation\/keyboardkitpro\/previews-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","kind":"article","type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}],"title":"Previews"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","op":"add","value":null},{"value":[{"title":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"anchor":"Articles","generated":true}],"op":"replace","path":"\/seeAlsoSections"}]}]}