{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkitpro\/dictation-article"]},{"paths":["\/documentation\/keyboardkitpro\/dictation-article"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Article","images":[{"identifier":"Page.png","type":"card"}],"title":"Dictation","role":"article","modules":[{"name":"KeyboardKitPro"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article"},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"seeAlsoSections":[{"generated":true,"anchor":"Features","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"title":"Features"}],"primaryContentSections":[{"content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Dictation can be used to let users enter text by speaking instead of typing on the keyboard. Since keyboard extensions have no access to the microphone, KeyboardKit lets you trigger dictation from a keyboard extension and perform it in the main app."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In KeyboardKit, a "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationService","type":"reference"},{"type":"text","text":" can start autocomplete from a keyboard extension, by opening the main app and let it perform the dictation operation, then return to the keyboard and apply the dictated text once dictation completes."}]},{"inlineContent":[{"type":"text","text":"👑 "},{"type":"reference","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","isActive":true},{"type":"text","text":" unlocks a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/StandardDictationService"},{"type":"text","text":" that can be used to perform dictation from the keyboard. Information about Pro features can be found further down."}],"type":"paragraph"},{"level":2,"anchor":"Namespace","type":"heading","text":"Namespace"},{"inlineContent":[{"text":"KeyboardKit has a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation"},{"type":"text","text":" namespace that contains dictation-related types, like "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/AuthorizationStatus","type":"reference"},{"text":", as well as views that are unlocked by KeyboardKit Pro, like ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/Screen","isActive":true,"type":"reference"},{"type":"text","text":" & "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/BarVisualizer","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"},{"text":"Context","level":2,"anchor":"Context","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has a "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationContext","type":"reference"},{"type":"text","text":" that provides observable dictation state that is kept up to date as dictation is performed. It also has auto-persisted "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationContext\/settings-swift.property","isActive":true,"type":"reference"},{"text":" that can be used to configure the dictation behavior.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit automatically creates an instance of this class, injects it into ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state","type":"reference","isActive":true},{"type":"text","text":" and updates it whenever dictation is performed."}]},{"text":"Services","type":"heading","level":2,"anchor":"Services"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In KeyboardKit, a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationService"},{"text":" can start autocomplete from a keyboard by opening the main app and let it perform dictation, then let the main app try to return to the keyboard and apply the dictated text.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit doesn’t have a standard dictation service, as it has for other services. Instead, it injects a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationService\/disabled","isActive":true},{"type":"text","text":" dictation service into "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","isActive":true},{"text":" until you register ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","overridingTitle":"KeyboardKit Pro","overridingTitleInlineContent":[{"text":"KeyboardKit Pro","type":"text"}]},{"text":" or inject your own service implementation.","type":"text"}]},{"type":"heading","level":2,"anchor":"Settings","text":"Settings"},{"inlineContent":[{"type":"text","text":"KeyboardKit has a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation"},{"type":"text","text":"-specific "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/Settings","type":"reference"},{"text":" type that defines auto-persisted settings. The ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationContext","type":"reference"},{"type":"text","text":" "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationContext\/settings-swift.property","type":"reference"},{"text":" property is used as the main settings instance within KeyboardKit.","type":"text"}],"type":"paragraph"},{"type":"thematicBreak"},{"level":2,"text":"👑 KeyboardKit Pro","anchor":"%F0%9F%91%91-KeyboardKit-Pro","type":"heading"},{"inlineContent":[{"overridingTitleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","isActive":true,"overridingTitle":"KeyboardKit Pro","type":"reference"},{"text":" unlocks services that let you setup and perform dictation in your app and from your keyboard, with very little code.","type":"text"}],"type":"paragraph"},{"text":"Services","level":3,"anchor":"Services","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro unlocks a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/StandardDictationService","isActive":true,"type":"reference"},{"text":" that can be used to start dictation from a keyboard extension, by opening the main app and perform dictation there, then return to the keyboard (if possible).","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The service’s speech recognizer supports: "},{"inlineContent":[{"type":"text","text":"english, english_gb, english_us, arabic, catalan, croatian, czech, danish, dutch, dutch_belgium, finnish, french, french_belgium, french_switzerland, german, german_austria, german_switzerland, greek, hebrew, hungarian, indonesian, italian, malay, norwegian, polish, portuguese, portuguese_brazil, romanian, russian, slovak, spanish, swedish, turkish, ukrainian"}],"type":"strong"},{"type":"text","text":"."}]},{"anchor":"Views","level":3,"type":"heading","text":"Views"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro adds views to the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation","type":"reference"},{"type":"text","text":" namespace, that let you quickly add dictation visualization views to your main app:"}]},{"type":"tabNavigator","tabs":[{"content":[{"columns":[{"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"dictationscreen"}]}],"size":1},{"content":[{"inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks a dictation "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/Screen"},{"type":"text","text":" that lets you overlay your app with a custom dictation view while dictation is active."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The screen will automatically fade in when dictation is started, if you use the Pro keyboard dictation view modifiers."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This view can be styled with a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/ScreenStyle","isActive":true,"type":"reference"},{"text":", which can be applied with a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/dictationScreenStyle(_:)","isActive":true,"type":"reference"},{"type":"text","text":" modifier."}]}],"size":1}],"numberOfColumns":2,"type":"row"}],"title":"Screen"},{"title":"BarVisualizer","content":[{"columns":[{"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"dictationscreen"}]}],"size":1},{"size":1,"content":[{"inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/BarVisualizer","isActive":true},{"type":"text","text":" that can be used to visualize ongoing dictations with a set of animated bars. You can change the number of bars, the colors & thickness of each bar, etc."}],"type":"paragraph"},{"inlineContent":[{"text":"This view can be styled with a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/BarVisualizerStyle","isActive":true},{"text":", which can be applied with a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/dictationScreenStyle(_:)","type":"reference"},{"type":"text","text":" modifier."}],"type":"paragraph"}]}],"type":"row","numberOfColumns":2}]}]},{"type":"thematicBreak"},{"type":"heading","text":"How to…","anchor":"How-to","level":2},{"level":3,"anchor":"Perform-dictation","type":"heading","text":"Perform dictation"},{"inlineContent":[{"type":"text","text":"Dictation works differently in apps, where microphone access is available, and in keyboard extensions, where mic access is unavailable. You can use a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationService","type":"reference","isActive":true},{"text":" to perform dictation from both a keyboard extension, as well as in the main app.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"Before your app can perform dictation, you must configure your app to require the correct permissions. This is described further down.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"To make your keyboard extension start dictation, just trigger ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationService\/startDictationFromKeyboard()"},{"text":" or a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/dictation","isActive":true},{"type":"text","text":" action. This will make the keyboard open the main app to perform dictation, then (try to) return to the keyboard once it’s is done."}]},{"type":"paragraph","inlineContent":[{"text":"To make your main app perform dictation that is started by its keyboard, just apply a ","type":"text"},{"code":".keyboardDictation","type":"codeVoice"},{"type":"text","text":" view modifier to its root view. You dont have to do this when you use a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAppView"},{"text":", since it does this automatically.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To make your main app perform dictation without keyboard integration, just trigger "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationService\/startDictationInApp()"},{"type":"text","text":". Since a dictation operation may stop at any time, a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationService","isActive":true,"type":"reference"},{"text":" should describe how to access the dictated result.","type":"text"}]},{"style":"important","name":"Important","type":"aside","content":[{"inlineContent":[{"type":"text","text":"iOS 17 caused keyboard back navigation to stop working. KeyboardKit Pro uses a list of known host applications to fix this, but this may fail at any time. You can override "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationService\/returnToKeyboardFromApp()"},{"type":"text","text":" to customize the behavior and observe the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationContext\/returnToKeyboardFromAppError","type":"reference","isActive":true},{"type":"text","text":" to show a custom UI that tells the user how to return to the keyboard with the top-leading system back arrow."}],"type":"paragraph"}]},{"anchor":"Configure-your-app-to-handle-dictation","level":3,"type":"heading","text":"Configure your app to handle dictation"},{"inlineContent":[{"text":"This article describes how to set up an app to start dictation from its keyboard extension and perform the dictation in the main app.","type":"text"}],"type":"paragraph"},{"type":"heading","level":4,"text":"Step 1 - Set up the required permissions","anchor":"Step-1-Set-up-the-required-permissions"},{"type":"paragraph","inlineContent":[{"text":"Before you can start dictation, you must add these keys to your app’s ","type":"text"},{"code":"Info.plist","type":"codeVoice"},{"type":"text","text":", otherwise the app will crash at runtime:"}]},{"code":["<key>NSMicrophoneUsageDescription<\/key>","<string>Describe why you need microphone access.<\/string>","<key>NSSpeechRecognitionUsageDescription<\/key>","<string>Describe why you need speech recognition.<\/string>"],"syntax":null,"type":"codeListing"},{"text":"Step 2 - Create an App Group","type":"heading","anchor":"Step-2-Create-an-App-Group","level":4},{"inlineContent":[{"text":"To share data between your app and keyboard extension, you must setup a shared app group for both targets:","type":"text"}],"type":"paragraph"},{"type":"row","numberOfColumns":2,"columns":[{"size":1,"content":[{"inlineContent":[{"identifier":"dictation-appgroup-app","type":"image"}],"type":"paragraph"}]},{"size":1,"content":[{"type":"paragraph","inlineContent":[{"identifier":"dictation-appgroup-keyboard","type":"image"}]}]}]},{"inlineContent":[{"text":"Add this App Group ID to your ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp"},{"type":"text","text":"’s "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/appGroupId"},{"text":" property, to properly set up dictation for the keyboard and its main app.","type":"text"}],"type":"paragraph"},{"level":4,"anchor":"Step-3-Create-a-deep-link","type":"heading","text":"Step 3 - Create a deep link"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To make it possible for the keyboard to open the app, you must set up a deep link URL scheme for the app target:"}]},{"inlineContent":[{"identifier":"dictation-url-scheme","type":"image"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Add this deep link to your "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp"},{"text":"’s ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/deepLinks-swift.property"},{"type":"text","text":" property, to properly set up deep linking for the keyboard and its main app."}]},{"text":"Step 4 - Create a speech recognizer","anchor":"Step-4-Create-a-speech-recognizer","level":4,"type":"heading"},{"inlineContent":[{"type":"text","text":"KeyboardKit uses a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationSpeechRecognizer","isActive":true},{"type":"text","text":" protocol to decouple KeyboardKit from the Speech framework, to avoid having to specify dictation permissions in apps that don’t use speech recognition."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Here’s a standard speech recognizer implementation that you can add to your app and inject into the keyboard dictation view modifier:"}]},{"type":"codeListing","syntax":"swift","code":["import KeyboardKitPro","import Speech","","public extension DictationSpeechRecognizer where Self == StandardSpeechRecognizer {","","    static var standard: Self { .init() }","} ","","public class StandardSpeechRecognizer: DictationSpeechRecognizer {","","    public init() {}","","    private var recognizer: SFSpeechRecognizer?","    private var request: SFSpeechAudioBufferRecognitionRequest?","    private var speechRecognizerTask: SFSpeechRecognitionTask?","","    private typealias Err = Dictation.ServiceError","","    public var authorizationStatus: Dictation.AuthorizationStatus {","        SFSpeechRecognizer.authorizationStatus().keyboardDictationStatus","    }","","    public var supportedLocales: [Locale] {","        Array(SFSpeechRecognizer.supportedLocales())","    }","","    public func requestDictationAuthorization() async throws -> Dictation.AuthorizationStatus {","        await withCheckedContinuation { continuation in","            SFSpeechRecognizer.requestAuthorization { status in","                continuation.resume(returning: status.keyboardDictationStatus)","            }","        }","    }","","    public func resetDictationResult() async throws {}","","    public func startDictation(","        with locale: Locale","    ) async throws {","        try await startDictation(","            with: locale,","            resultHandler: nil","        )","    }","","    public func startDictation(","        with locale: Locale,","        resultHandler: ((Dictation.SpeechRecognizerResult) -> Void)?","    ) async throws {","        recognizer = SFSpeechRecognizer(locale: locale)","        guard let recognizer else { throw Err.missingSpeechRecognizer }","        request = SFSpeechAudioBufferRecognitionRequest()","        request?.shouldReportPartialResults = true","        guard let request else { throw Err.missingSpeechRecognitionRequest }","        speechRecognizerTask = recognizer.recognitionTask(with: request) {","            let result = Dictation.SpeechRecognizerResult(","                dictatedText: $0?.bestTranscription.formattedString,","                error: $1,","                isFinal: $0?.isFinal ?? true)","            resultHandler?(result)","        }","    }","","    public func stopDictation() async throws {","        request?.endAudio()","        request = nil","        speechRecognizerTask?.cancel()","        speechRecognizerTask = nil","    }","","    public func setupAudioEngineBuffer(_ buffer: AVAudioPCMBuffer) {","        request?.append(buffer)","    }","}"]},{"type":"heading","text":"Step 5 - Set up dictation in your keyboard extension","anchor":"Step-5-Set-up-dictation-in-your-keyboard-extension","level":4},{"type":"paragraph","inlineContent":[{"type":"text","text":"To set up dictation for your keyboard extension, just call "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setup(for:)","isActive":true},{"type":"text","text":" with a properly configured "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","isActive":true},{"text":", as described in the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started-Article"},{"type":"text","text":" article. Your "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","type":"reference"},{"type":"text","text":" must define a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/DeepLinks-swift.struct\/dictation","isActive":true,"type":"reference"},{"text":" deep link, or at least an ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/DeepLinks-swift.struct\/app","isActive":true},{"text":" deep link to use the standard link.","type":"text"}]},{"level":4,"type":"heading","text":"Step 6 - Set up dictation in your main application","anchor":"Step-6-Set-up-dictation-in-your-main-application"},{"inlineContent":[{"type":"text","text":"To set up dictation for your main app, just wrap its root view in a  "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAppView","isActive":true},{"text":", as described in the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started-Article","type":"reference","isActive":true},{"type":"text","text":" article, then apply any of the available "},{"type":"codeVoice","code":"keyboardDictation"},{"text":" view modifiers to make the app trigger dictation:","type":"text"}],"type":"paragraph"},{"code":["struct ContentView: View {","","    @Environment(\\.openURL)","    var openURL","    ","    @EnvironmentObject","    private var dictationContext: DictationContext","","    @EnvironmentObject","    private var keyboardContext: KeyboardContext","","    var body: some View {","        KeyboardAppView(for: .keyboardKitDemo) {","            ...","        }","        .keyboardDictation(","            dictationContext: dictationContext,","            keyboardContext: keyboardContext,","            openUrl: openURL,","            speechRecognizer: .standard,         \/\/ As defined earlier","            overlay: dictationOverlay            \/\/ You can use any view","        )","    }","","    func overlay() -> some View {","        Dictation.Screen(","            dictationContext: context,","            titleView: { EmptyView() },","            indicator: { Dictation.BarVisualizer(isAnimating: $0) }","        )","    } ","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"text":"The keyboard dictation view modifier has an overlay parameter that defines the view to show while dictation is active. You can use the Pro dictation ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/Screen","type":"reference","isActive":true},{"type":"text","text":" with any of the built-in dictation visualizers, or a completely custom view."}],"type":"paragraph"},{"type":"heading","level":4,"text":"Step 7 - Perform dictation","anchor":"Step-7-Perform-dictation"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can now start dictation in your keyboard by triggering a "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/dictation","type":"reference"},{"text":" action or by calling ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationService\/startDictationFromKeyboard()","isActive":true},{"type":"text","text":"."}]},{"inlineContent":[{"text":"If everything is correctly configured, the keyboard extension should open its main app to start dictation. Once dictation is done, the app should return to the keyboard to handle the dictated text.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can override "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewWillHandleDictationResult()"},{"type":"text","text":" to customize how the keyboard controller handles the dictation result."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro tries to work around the native back navigation limitations by using the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationContext","isActive":true},{"type":"text","text":"’s "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardHostApplicationProvider\/hostApplication"},{"type":"text","text":" to identify and open the previous app. Since this approach only supports the most popular apps, it may fail in many cases."}]},{"inlineContent":[{"type":"text","text":"If back navigation fails, your dictation screen must inform the user how to return to the keyboard, which can be done by swiping back or tapping the top-trailing back arrow. You can observe "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationContext\/returnToKeyboardFromAppError","isActive":true},{"type":"text","text":" to know when this happens."}],"type":"paragraph"}],"kind":"content"}],"sections":[],"kind":"article","references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit gesture engine."}],"url":"\/documentation\/keyboardkitpro\/gestures-article","images":[{"type":"card","identifier":"Page.png"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","title":"Gestures","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","kind":"symbol","url":"\/documentation\/keyboardkitpro","title":"KeyboardKitPro","role":"collection","type":"topic","abstract":[{"type":"text","text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Settings-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit settings engine."}],"url":"\/documentation\/keyboardkitpro\/settings-article","role":"article","type":"topic","title":"Settings","kind":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAppView":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"KeyboardAppView"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAppView","title":"KeyboardAppView","type":"topic","navigatorTitle":[{"text":"KeyboardAppView","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This view can be used as the root view of a keyboard app,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"to set up KeyboardKit for a certain "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","type":"reference"},{"text":".","type":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardappview"},"dictation-appgroup-keyboard":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/dictation-appgroup-keyboard.jpg","traits":["1x","light"]}],"alt":"Set up an App Group for the keyboard","identifier":"dictation-appgroup-keyboard","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/DictationService/startDictationFromKeyboard()":{"abstract":[{"text":"Start a dictation operation from the keyboard.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationService\/startDictationFromKeyboard()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/keyboardkitpro\/dictationservice\/startdictationfromkeyboard()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startDictationFromKeyboard","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"startDictationFromKeyboard()"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/DictationService/disabled":{"abstract":[{"type":"text","text":"Create a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/DisabledDictationService","type":"reference","isActive":true},{"type":"text","text":" instance."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationService\/disabled","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/dictationservice\/disabled","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"disabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Self","kind":"typeIdentifier"}],"title":"disabled","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" is "},{"type":"codeVoice","code":"Dictation.DisabledDictationService"},{"type":"text","text":"."}]}},"Page.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png"}],"alt":"Page icon","identifier":"Page.png","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/DictationService/returnToKeyboardFromApp()":{"abstract":[{"type":"text","text":"Try to return to the keyboard from the main app."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationService\/returnToKeyboardFromApp()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/keyboardkitpro\/dictationservice\/returntokeyboardfromapp()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"returnToKeyboardFromApp","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"returnToKeyboardFromApp()"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp":{"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"KeyboardApp","kind":"identifier"}],"title":"KeyboardApp","navigatorTitle":[{"text":"KeyboardApp","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardapp","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","kind":"symbol","abstract":[{"text":"This type can be used to define important properties for","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"your app, and is also a namespace for app-based features."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}],"url":"\/documentation\/keyboardkitpro\/autocomplete-article","role":"article","type":"topic","title":"Autocomplete","kind":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/DictationContext/returnToKeyboardFromAppError":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"returnToKeyboardFromAppError"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The last navigate back error."}],"url":"\/documentation\/keyboardkitpro\/dictationcontext\/returntokeyboardfromapperror","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationContext\/returnToKeyboardFromAppError","role":"symbol","title":"returnToKeyboardFromAppError"},"dictation-appgroup-app":{"identifier":"dictation-appgroup-app","alt":"Set up an App Group for the app","type":"image","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/dictation-appgroup-app.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation/AuthorizationStatus":{"abstract":[{"type":"text","text":"This enum defines various dictation statuses."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/AuthorizationStatus","title":"Dictation.AuthorizationStatus","role":"symbol","navigatorTitle":[{"text":"AuthorizationStatus","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/dictation\/authorizationstatus","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthorizationStatus","kind":"identifier"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Host-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","abstract":[{"type":"text","text":"This article describes how KeyboardKit Pro can identify the host application."}],"url":"\/documentation\/keyboardkitpro\/host-article","role":"article","type":"topic","title":"Host Utilities","kind":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/dictation":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"dictation","kind":"identifier"}],"type":"topic","role":"symbol","title":"KeyboardAction.dictation","url":"\/documentation\/keyboardkitpro\/keyboardaction\/dictation","kind":"symbol","abstract":[{"text":"Represents a dictation key.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/dictation"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp/appGroupId":{"type":"topic","title":"appGroupId","url":"\/documentation\/keyboardkitpro\/keyboardapp\/appgroupid","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/appGroupId","kind":"symbol","abstract":[{"type":"text","text":"The app’s App Group identifier, if any."}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"appGroupId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation/BarVisualizer":{"type":"topic","abstract":[{"text":"This visualizer visualizes dictation progress with a","type":"text"},{"type":"text","text":" "},{"text":"horizontal list of animating bars.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"BarVisualizer"}],"url":"\/documentation\/keyboardkitpro\/dictation\/barvisualizer","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/BarVisualizer","title":"Dictation.BarVisualizer","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"BarVisualizer","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Status-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit status engine."}],"url":"\/documentation\/keyboardkitpro\/status-article","role":"article","type":"topic","title":"Status","kind":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Styling-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","abstract":[{"text":"This article describes the KeyboardKit styling engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/styling-article","role":"article","type":"topic","title":"Styling","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","abstract":[{"text":"This article describes the KeyboardKit layout engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/layout-article","role":"article","type":"topic","title":"Layout","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUICore/View/dictationScreenStyle(_:)":{"title":"dictationScreenStyle(_:)","role":"symbol","abstract":[{"type":"text","text":"Apply a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/ScreenStyle"},{"text":".","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/keyboardkitpro\/swiftuicore\/view\/dictationscreenstyle(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dictationScreenStyle"},{"kind":"text","text":"("},{"text":"Dictation","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro9DictationV"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro9DictationV11ScreenStyleV","text":"ScreenStyle","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/dictationScreenStyle(_:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit localization engine."}],"url":"\/documentation\/keyboardkitpro\/localization-article","images":[{"identifier":"Page.png","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","title":"Localization","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp/DeepLinks-swift.struct/dictation":{"abstract":[{"type":"text","text":"A deep link for opening the app and starting dictation."}],"url":"\/documentation\/keyboardkitpro\/keyboardapp\/deeplinks-swift.struct\/dictation","title":"dictation","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/DeepLinks-swift.struct\/dictation","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"dictation","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation/Screen":{"url":"\/documentation\/keyboardkitpro\/dictation\/screen","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Screen"}],"navigatorTitle":[{"kind":"identifier","text":"Screen"}],"role":"symbol","title":"Dictation.Screen","abstract":[{"type":"text","text":"This view can be shown when dictation is in progress."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/Screen"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/viewWillHandleDictationResult()":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewWillHandleDictationResult()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewWillHandleDictationResult","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"text":"This function is called to handle a dictation result","type":"text"},{"text":" ","type":"text"},{"text":"when returning from the main app.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/viewwillhandledictationresult()","type":"topic","kind":"symbol","title":"viewWillHandleDictationResult()","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards-Article":{"abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"images":[{"type":"card","identifier":"Page.png"}],"kind":"article","url":"\/documentation\/keyboardkitpro\/external-keyboards-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","role":"article","title":"External Keyboards","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Essentials-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the essential parts of KeyboardKit."}],"url":"\/documentation\/keyboardkitpro\/essentials-article","images":[{"type":"card","identifier":"Page.png"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","title":"Essentials","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/state":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state","title":"state","role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/state","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V","text":"Keyboard"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A0V5StateC","text":"State","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Keyboard-specific state."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Themes-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit Pro theme engine, which can be used to style the entire keyboard with a single theme."}],"url":"\/documentation\/keyboardkitpro\/themes-article","images":[{"identifier":"Page.png","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article","title":"Themes","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation/StandardDictationService":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StandardDictationService"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/StandardDictationService","abstract":[{"text":"This service can start dictation from a keyboard and","type":"text"},{"type":"text","text":" "},{"text":"perform it in its main app.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"StandardDictationService","kind":"identifier"}],"title":"Dictation.StandardDictationService","url":"\/documentation\/keyboardkitpro\/dictation\/standarddictationservice"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Device-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit device utilities."}],"url":"\/documentation\/keyboardkitpro\/device-article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","title":"Device Utilities","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/services":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"services","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V","text":"Keyboard"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A0V8ServicesC","text":"Services","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"Keyboard-specific services.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/services","title":"services","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/App-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","abstract":[{"text":"This article describes the KeyboardKit app-specific utilities.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/app-article","role":"article","type":"topic","title":"App Utilities","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/DictationService/startDictationInApp()":{"title":"startDictationInApp()","type":"topic","url":"\/documentation\/keyboardkitpro\/dictationservice\/startdictationinapp()","role":"symbol","required":true,"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startDictationInApp"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Start a dictation operation in the main app."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationService\/startDictationInApp()"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","abstract":[{"text":"This article describes the KeyboardKit proxy engine and its utilities.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/proxy-article","role":"article","type":"topic","title":"Proxy Utilities","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp/DeepLinks-swift.struct/app":{"role":"symbol","title":"app","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/DeepLinks-swift.struct\/app","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"app","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardapp\/deeplinks-swift.struct\/app","type":"topic","kind":"symbol","abstract":[{"text":"A deep link for opening the app.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/DictationContext":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DictationContext","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DictationContext"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationContext","url":"\/documentation\/keyboardkitpro\/dictationcontext","title":"DictationContext","abstract":[{"type":"text","text":"This class has observable states and persistent settings"},{"type":"text","text":" "},{"type":"text","text":"for keyboard-based dictation."}],"kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Previews-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit preview engine."}],"url":"\/documentation\/keyboardkitpro\/previews-article","images":[{"identifier":"Page.png","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","title":"Previews","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"url":"\/documentation\/keyboardkitpro\/emojis-article","images":[{"identifier":"Page.png","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","title":"Emojis","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/DictationService":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DictationService","kind":"identifier"}],"abstract":[{"text":"This protocol can be implemented by any classes that can","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"perform dictation from a keyboard extension or in an app."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationService","url":"\/documentation\/keyboardkitpro\/dictationservice","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DictationService","kind":"identifier"}],"title":"DictationService"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp/deepLinks-swift.property":{"abstract":[{"type":"text","text":"App-specific deep links, if any."}],"url":"\/documentation\/keyboardkitpro\/keyboardapp\/deeplinks-swift.property","title":"deepLinks","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"deepLinks"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14KeyboardKitPro0A3AppV9DeepLinksV","text":"DeepLinks","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/deepLinks-swift.property"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","abstract":[{"text":"This article describes the KeyboardKit callout engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/callouts-article","role":"article","type":"topic","title":"Callouts","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"dictationscreen":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/dictationscreen.jpg"}],"alt":"DictationScreen","identifier":"dictationscreen","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/setup(for:)":{"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setup"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A3AppV","text":"KeyboardApp"},{"text":")","kind":"text"}],"title":"setup(for:)","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/setup(for:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setup(for:)","abstract":[{"text":"Set up KeyboardKit for a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","isActive":true},{"type":"text","text":"."}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/feedback-article","role":"article","type":"topic","title":"Feedback","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Text-Input-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit text input engine, which lets you type within the keyboard extension."}],"url":"\/documentation\/keyboardkitpro\/text-input-article","images":[{"type":"card","identifier":"Page.png"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","title":"Text Input","role":"article"},"dictation-url-scheme":{"identifier":"dictation-url-scheme","alt":"Set up a URL Scheme for the app","type":"image","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/dictation-url-scheme.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation":{"url":"\/documentation\/keyboardkitpro\/dictation","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Dictation"}],"navigatorTitle":[{"kind":"identifier","text":"Dictation"}],"role":"symbol","title":"Dictation","abstract":[{"type":"text","text":"This namespace contains dictation-related types."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Navigation-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","abstract":[{"text":"This article describes the KeyboardKit navigation engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/navigation-article","role":"article","type":"topic","title":"Navigation","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation/ScreenStyle":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/ScreenStyle","type":"topic","url":"\/documentation\/keyboardkitpro\/dictation\/screenstyle","abstract":[{"text":"This style can be used to modify the visual style of","type":"text"},{"text":" ","type":"text"},{"text":"the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/Screen","isActive":true,"type":"reference"},{"text":" component.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ScreenStyle"}],"navigatorTitle":[{"text":"ScreenStyle","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"Dictation.ScreenStyle"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation/Settings":{"abstract":[{"type":"text","text":"This type is used for dictation-related settings."}],"navigatorTitle":[{"text":"Settings","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/keyboardkitpro\/dictation\/settings","title":"Dictation.Settings","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Settings","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/Settings"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardHostApplicationProvider/hostApplication":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardHostApplicationProvider\/hostApplication","role":"symbol","abstract":[{"type":"text","text":"The host application, if any."}],"url":"\/documentation\/keyboardkitpro\/keyboardhostapplicationprovider\/hostapplication","kind":"symbol","title":"hostApplication","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hostApplication"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14KeyboardKitPro0A15HostApplicationV","text":"KeyboardHostApplication","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation/DisabledDictationService":{"type":"topic","abstract":[{"type":"text","text":"This class is used as the default service, until you"},{"text":" ","type":"text"},{"type":"text","text":"register a custom implementation or register a valid"},{"text":" ","type":"text"},{"text":"KeyboardKit Pro license key.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DisabledDictationService","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DisabledDictationService"}],"role":"symbol","title":"Dictation.DisabledDictationService","url":"\/documentation\/keyboardkitpro\/dictation\/disableddictationservice","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/DisabledDictationService"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Getting-Started-Article":{"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started-Article","role":"article","type":"topic","images":[{"type":"card","identifier":"Page.png"}],"url":"\/documentation\/keyboardkitpro\/getting-started-article","title":"Getting Started","abstract":[{"type":"text","text":"This article describes how to get started with KeyboardKit."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/DictationContext/settings-swift.property":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"settings","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro16DictationContextC8Settingsa","text":"Settings"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/dictationcontext\/settings-swift.property","role":"symbol","kind":"symbol","title":"settings","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationContext\/settings-swift.property","abstract":[{"type":"text","text":"Dictation-specific, auto-persisted settings."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"type":"topic","abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/actions-article","images":[{"type":"card","identifier":"Page.png"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","title":"Actions","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation/BarVisualizerStyle":{"abstract":[{"text":"This style can be used to modify the visual style of","type":"text"},{"type":"text","text":" "},{"text":"the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/BarVisualizer"},{"type":"text","text":" component."}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/BarVisualizerStyle","url":"\/documentation\/keyboardkitpro\/dictation\/barvisualizerstyle","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"BarVisualizerStyle","kind":"identifier"}],"title":"Dictation.BarVisualizerStyle","navigatorTitle":[{"text":"BarVisualizerStyle","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AI-Article":{"type":"topic","abstract":[{"text":"This article describes the KeyboardKit AI support capabilities.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/ai-article","images":[{"type":"card","identifier":"Page.png"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","title":"AI Support","role":"article"},"https://github.com/KeyboardKit/KeyboardKitPro":{"url":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","title":"KeyboardKit Pro","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","titleInlineContent":[{"text":"KeyboardKit Pro","type":"text"}],"type":"link"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/DictationSpeechRecognizer":{"title":"DictationSpeechRecognizer","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DictationSpeechRecognizer","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationSpeechRecognizer","navigatorTitle":[{"text":"DictationSpeechRecognizer","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"This protocol can be implemented by any classes that can"},{"type":"text","text":" "},{"type":"text","text":"perform speech recognition."}],"url":"\/documentation\/keyboardkitpro\/dictationspeechrecognizer","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"anchor":"Features","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"title":"Features","generated":true}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}