{"primaryContentSections":[{"kind":"content","content":[{"type":"heading","anchor":"overview","level":2,"text":"Overview"},{"inlineContent":[{"type":"text","text":"KeyboardKit has an "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emoji","type":"reference","isActive":true},{"text":" struct that represents an emoji value, and defines available ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiCategory","type":"reference"},{"type":"text","text":" and "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiVersion","isActive":true,"type":"reference"},{"text":" values that let you fetch all available emojis from all available categories and versions.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"👑 "},{"isActive":true,"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","type":"reference"},{"type":"text","text":" unlocks an "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboard","isActive":true},{"type":"text","text":" that’s automatically injected into "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","type":"reference"},{"text":" when a valid license is registered. Information about Pro features can be found at the end of this article.","type":"text"}],"type":"paragraph"},{"anchor":"Emojis","text":"Emojis","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emoji","isActive":true},{"text":" struct represents a structured emoji model that lets you work with emojis and their information in a more structured way:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["let emoji = Emoji(\"😀\")"]},{"inlineContent":[{"type":"text","text":"You can use "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emoji\/all","type":"reference"},{"type":"text","text":" to get a list of all emojis from all categories that are available to the current runtime:"}],"type":"paragraph"},{"code":["let emojis = Emoji.all   \/\/ 😀😃😄😁😆🥹😅😂🤣🥲..."],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"You can trigger emoji character insertion by triggering the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/emoji(_:)-swift.enum.case","isActive":true},{"type":"text","text":" keyboard action, just like you trigger any other keyboard action."}]},{"anchor":"Emoji-Categories","text":"Emoji Categories","level":2,"type":"heading"},{"inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiCategory"},{"type":"text","text":" enum defines all available emoji categories and their emojis:"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["EmojiCategory.smileysAndPeople.emojis  \/\/ 😀😃😄...","EmojiCategory.animalsAndNature.emojis  \/\/ 🐶🐱🐭..."]},{"inlineContent":[{"type":"text","text":"You can use "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiCategory\/all","isActive":true},{"type":"text","text":" to get a list of all available categories, in the native, default sort order:"}],"type":"paragraph"},{"type":"codeListing","code":["EmojiCategory.all      \/\/ [.frequent, .smileyAndPeople, ...]"],"syntax":"swift"},{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiCategory"},{"type":"text","text":" uses "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiVersion","isActive":true,"type":"reference"},{"type":"text","text":" to filter out emojis that are unavailable to the current runtime, to only include available emojis."}],"type":"paragraph"},{"type":"heading","text":"Emoji Versions","anchor":"Emoji-Versions","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiVersion"},{"text":" enum defines all available emoji versions and their emojis and supported platforms:","type":"text"}]},{"code":["let version = EmojiVersion.v15","version.emojis          \/\/ 🫨🫸🫷🪿🫎🪼🫏🪽🪻🫛🫚🪇🪈🪮🪭🩷🩵🩶🪯🛜...","version.version         \/\/ 15.0","version.iOS             \/\/ 16.4","version.macOS           \/\/ 13.3","version.olderVersions   \/\/ [.v14, .v13_1, .v13, .v12_1, ...]"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"text":"All this information is used to resolve ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiVersion\/unavailableEmojis"},{"text":" that are unavailable for a certain emoji version in the current runtime:","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["EmojiVersion.v14.unavailableEmojis \/\/ 🫨🫸🫷🪿🫎🪼🫏🪽..."]},{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiCategory","isActive":true,"type":"reference"},{"type":"text","text":" uses "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiVersion"},{"text":" to filter out emojis that are unavailable to the current runtime, to only include available emojis.","type":"text"}]},{"text":"Unicode Information","anchor":"Unicode-Information","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emoji","isActive":true},{"text":" enum has unicode-specific properties that can be used for identity and naming:","type":"text"}]},{"code":["Emoji(\"👍\").unicodeIdentifier   \/\/ \\\\N{THUMBS UP SIGN}","Emoji(\"👍🏿\").unicodeIdentifier   \/\/ \\\\N{THUMBS UP SIGN}\\\\N{EMOJI MODIFIER FITZPATRICK TYPE-6}","Emoji(\"👍\").unicodeName         \/\/ Thumbs Up Sign","Emoji(\"👍🏿\").unicodeName         \/\/ Thumbs Up Sign"],"syntax":"swift","type":"codeListing"},{"anchor":"Skintone-Information","level":2,"text":"Skintone Information","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emoji"},{"text":" enum has skin tone-specific properties that define skin tone variants for all supported emojis:","type":"text"}]},{"code":["Emoji(\"👍\").hasSkinToneVariants      \/\/ true","Emoji(\"🚀\").hasSkinToneVariants      \/\/ false","Emoji(\"👍🏿\").neutralSkinToneVariant   \/\/ 👍","Emoji(\"👍\").skinToneVariants         \/\/ 👍👍🏻👍🏼👍🏽👍🏾👍🏿"],"syntax":"swift","type":"codeListing"},{"inlineContent":[{"text":"The ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboard"},{"text":" will automatically add skin tones as secondary callout actions to all single-component emojis that have them.","type":"text"}],"type":"paragraph"},{"level":2,"text":"Localization Support","type":"heading","anchor":"Localization-Support"},{"inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emoji","isActive":true,"type":"reference"},{"text":" enum can be localized in any supported locale that has defined translations:","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["Emoji(\"😀\").localizedName                  \/\/ Grinning Face","Emoji(\"😀\").localizedName(for: .swedish)   \/\/ Leende Ansikte"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"text":"Take a look at ","type":"text"},{"code":"Resources\/en.lproj\/Localizable.strings","type":"codeVoice"},{"text":" to see how you can localize emojis for more keyboard locales.","type":"text"}]},{"type":"heading","text":"String & Character Extensions","anchor":"String--Character-Extensions","level":2},{"inlineContent":[{"text":"There are String & Character extensions that can be used to detect and handle emojis, for instance:","type":"text"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["\"Hello!\".containsEmoji           \/\/ false","\"Hello! 👋\".containsEmoji        \/\/ true","\"Hello! 👋\".containsOnlyEmojis   \/\/ false","\"Hello! 👋😀\".emojis             \/\/ [\"👋\", \"😀\"]"]},{"anchor":"%F0%9F%91%91-KeyboardKit-Pro","type":"heading","level":2,"text":"👑 KeyboardKit Pro"},{"type":"paragraph","inlineContent":[{"overridingTitle":"KeyboardKit Pro","overridingTitleInlineContent":[{"text":"KeyboardKit Pro","type":"text"}],"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro"},{"type":"text","text":" unlocks an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboard"},{"type":"text","text":" that is automatically added to the "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","type":"reference"},{"type":"text","text":" when a valid license is registered."}]},{"tabs":[{"content":[{"inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboard","type":"reference","isActive":true},{"text":" component mimics a native emoji keyboard, with support for categories, skin tones, etc. It uses many additional views that are unlocked by KeyboardKit Pro, such as the title, grid, and menu. These views can be used individually as well.","type":"text"}],"type":"paragraph"},{"columns":[{"size":1,"content":[]},{"size":4,"content":[{"type":"paragraph","inlineContent":[{"identifier":"emojikeyboard","type":"image"}]}]},{"size":1,"content":[]}],"type":"row","numberOfColumns":6},{"type":"paragraph","inlineContent":[{"text":"The view can be styled with an ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboardStyle","isActive":true,"type":"reference"},{"text":", which can be applied with the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/emojiKeyboardStyle(_:)","isActive":true},{"type":"text","text":" view modifier."}]}],"title":"EmojiKeyboard"}],"type":"tabNavigator"}]}],"variants":[{"paths":["\/documentation\/keyboardkitpro\/emojis-article"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkitpro\/emojis-article"]}],"kind":"article","metadata":{"title":"Emojis","color":{"standardColorIdentifier":"blue"},"images":[{"type":"card","identifier":"Page.png"}],"modules":[{"name":"KeyboardKitPro"}],"role":"article","roleHeading":"Article"},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"abstract":[{"text":"This article describes the KeyboardKit emoji engine.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"seeAlsoSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"anchor":"Features","title":"Features","generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article"},"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","url":"\/documentation\/keyboardkitpro","abstract":[{"type":"text","text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI."}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","title":"KeyboardKitPro","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","url":"\/documentation\/keyboardkitpro\/callouts-article","title":"Callouts","role":"article","images":[{"type":"card","identifier":"Page.png"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","title":"Localization","role":"article","type":"topic","kind":"article","abstract":[{"text":"This article describes the KeyboardKit localization engine.","type":"text"}],"images":[{"identifier":"Page.png","type":"card"}],"url":"\/documentation\/keyboardkitpro\/localization-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/EmojiCategory/all":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"EmojiCategory","preciseIdentifier":"s:14KeyboardKitPro13EmojiCategoryO"},{"kind":"text","text":"]"}],"role":"symbol","abstract":[],"type":"topic","deprecated":true,"kind":"symbol","url":"\/documentation\/keyboardkitpro\/emojicategory\/all","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiCategory\/all","title":"all"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/EmojiKeyboard":{"abstract":[{"type":"text","text":"This view mimics a native emoji keyboard."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"EmojiKeyboard","kind":"identifier"}],"title":"EmojiKeyboard","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"EmojiKeyboard"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboard","url":"\/documentation\/keyboardkitpro\/emojikeyboard"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emoji/all":{"type":"topic","abstract":[{"type":"text","text":"Get all available emojis from all categories."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"all"},{"text":": [","kind":"text"},{"text":"Emoji","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro5EmojiV"},{"kind":"text","text":"]"}],"url":"\/documentation\/keyboardkitpro\/emoji\/all","title":"all","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emoji\/all"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete-Article":{"images":[{"type":"card","identifier":"Page.png"}],"role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/autocomplete-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}],"title":"Autocomplete"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","title":"Layout","role":"article","abstract":[{"text":"This article describes the KeyboardKit layout engine.","type":"text"}],"images":[{"type":"card","identifier":"Page.png"}],"url":"\/documentation\/keyboardkitpro\/layout-article","kind":"article","type":"topic"},"https://github.com/KeyboardKit/KeyboardKitPro":{"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","url":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","title":"KeyboardKit Pro","type":"link","titleInlineContent":[{"text":"KeyboardKit Pro","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Status-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","url":"\/documentation\/keyboardkitpro\/status-article","title":"Status","role":"article","images":[{"type":"card","identifier":"Page.png"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit status engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Settings-Article":{"url":"\/documentation\/keyboardkitpro\/settings-article","kind":"article","title":"Settings","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit settings engine."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","type":"topic","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Essentials-Article":{"images":[{"identifier":"Page.png","type":"card"}],"kind":"article","url":"\/documentation\/keyboardkitpro\/essentials-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","role":"article","title":"Essentials","abstract":[{"type":"text","text":"This article describes the essential parts of KeyboardKit."}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","url":"\/documentation\/keyboardkitpro\/proxy-article","title":"Proxy Utilities","role":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit proxy engine and its utilities."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/EmojiCategory":{"url":"\/documentation\/keyboardkitpro\/emojicategory","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiCategory","kind":"symbol","title":"EmojiCategory","type":"topic","role":"symbol","navigatorTitle":[{"text":"EmojiCategory","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"EmojiCategory","kind":"identifier"}],"abstract":[{"type":"text","text":"This enum defines the standard emoji categories, as well"},{"type":"text","text":" "},{"text":"as their emojis.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUICore/View/emojiKeyboardStyle(_:)":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/emojiKeyboardStyle(_:)","title":"emojiKeyboardStyle(_:)","role":"symbol","abstract":[{"type":"text","text":"Apply an "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboardStyle","isActive":true},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"emojiKeyboardStyle","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:14KeyboardKitPro05EmojiA5StyleV","text":"EmojiKeyboardStyle","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"url":"\/documentation\/keyboardkitpro\/swiftuicore\/view\/emojikeyboardstyle(_:)","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","title":"External Keyboards","role":"article","type":"topic","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit external keyboard engine."}],"images":[{"identifier":"Page.png","type":"card"}],"url":"\/documentation\/keyboardkitpro\/external-keyboards-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/App-Article":{"title":"App Utilities","abstract":[{"text":"This article describes the KeyboardKit app-specific utilities.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","url":"\/documentation\/keyboardkitpro\/app-article","role":"article","type":"topic","images":[{"identifier":"Page.png","type":"card"}],"kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures-Article":{"images":[{"identifier":"Page.png","type":"card"}],"role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/gestures-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit gesture engine."}],"title":"Gestures"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Previews-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","url":"\/documentation\/keyboardkitpro\/previews-article","title":"Previews","role":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit preview engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/EmojiVersion":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EmojiVersion","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"EmojiVersion"}],"role":"symbol","abstract":[{"type":"text","text":"This enum defines all supported Emoji versions, that are"},{"text":" ","type":"text"},{"type":"text","text":"currently available to macOS."}],"type":"topic","kind":"symbol","url":"\/documentation\/keyboardkitpro\/emojiversion","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiVersion","title":"EmojiVersion"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"images":[{"identifier":"Page.png","type":"card"}],"role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/actions-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit action engine."}],"title":"Actions"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback-Article":{"images":[{"type":"card","identifier":"Page.png"}],"role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/feedback-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit feedback engine."}],"title":"Feedback"},"emojikeyboard":{"identifier":"emojikeyboard","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/emojikeyboard.jpg","traits":["1x","light"]}],"alt":"Emoji Keyboard","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AI-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","url":"\/documentation\/keyboardkitpro\/ai-article","title":"AI Support","role":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit AI support capabilities."}]},"Page.png":{"identifier":"Page.png","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png","traits":["1x","light"]}],"alt":"Page icon","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/EmojiKeyboardStyle":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"This style can be used to modify the visual style of the"},{"text":" ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboard","isActive":true},{"text":" component and its nested views.","type":"text"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EmojiKeyboardStyle","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/emojikeyboardstyle","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboardStyle","navigatorTitle":[{"text":"EmojiKeyboardStyle","kind":"identifier"}],"title":"EmojiKeyboardStyle"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Device-Article":{"kind":"article","url":"\/documentation\/keyboardkitpro\/device-article","type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit device utilities."}],"title":"Device Utilities","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emoji":{"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Emoji","kind":"identifier"}],"title":"Emoji","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Emoji"}],"url":"\/documentation\/keyboardkitpro\/emoji","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emoji","role":"symbol","abstract":[{"text":"This type represents an emoji character and is used as a","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"namespace for emoji-related types and functionality."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Themes-Article":{"images":[{"type":"card","identifier":"Page.png"}],"role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/themes-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit Pro theme engine, which can be used to style the entire keyboard with a single theme."}],"title":"Themes"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/EmojiVersion/unavailableEmojis":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiVersion\/unavailableEmojis","type":"topic","abstract":[{"text":"Get all emojis that are unavailable in this version.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"unavailableEmojis","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro5EmojiV","text":"Emoji","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"url":"\/documentation\/keyboardkitpro\/emojiversion\/unavailableemojis","title":"unavailableEmojis","kind":"symbol","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","url":"\/documentation\/keyboardkitpro\/dictation-article","title":"Dictation","role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Host-Article":{"images":[{"identifier":"Page.png","type":"card"}],"role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/host-article","abstract":[{"type":"text","text":"This article describes how KeyboardKit can identify the host application."}],"title":"Host Utilities"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Styling-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","url":"\/documentation\/keyboardkitpro\/styling-article","title":"Styling","role":"article","images":[{"type":"card","identifier":"Page.png"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit styling engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Navigation-Article":{"title":"Navigation","abstract":[{"type":"text","text":"This article describes the KeyboardKit navigation engine."}],"type":"topic","role":"article","images":[{"type":"card","identifier":"Page.png"}],"url":"\/documentation\/keyboardkitpro\/navigation-article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/emoji(_:)-swift.enum.case":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/emoji(_:)-swift.enum.case","title":"KeyboardAction.emoji(_:)","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"emoji"},{"kind":"text","text":"("},{"text":"Emoji","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro5EmojiV"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/emoji(_:)-swift.enum.case","abstract":[{"text":"Inserts an emoji when released.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Text-Input-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","url":"\/documentation\/keyboardkitpro\/text-input-article","title":"Text Input","role":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit text input engine, which lets you type within the keyboard extension."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardView":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardView","kind":"identifier"}],"title":"KeyboardView","abstract":[{"type":"text","text":"This view can be used to mimic a native iOS keyboard."}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardView"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardview","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"replace","value":[{"generated":true,"anchor":"Features","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"title":"Features"}],"path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}