{"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit provides you with an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emoji"},{"type":"text","text":" struct, an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiCategory"},{"type":"text","text":" enum, an emoji localization engine etc., as well as various emoji keyboard views like "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboard"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiCategoryKeyboard"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro"},{"type":"text","text":" specific features are described at the end of this document."}]},{"anchor":"Emojis","level":2,"type":"heading","text":"Emojis"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emoji"},{"type":"text","text":" struct that lets you handle emojis in a structured way.:"}]},{"type":"codeListing","syntax":"swift","code":["let emoji = Emoji(\"😀\")"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can get all available emojis like this:"}]},{"type":"codeListing","syntax":"swift","code":["let emojis = Emoji.all"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can also get access to additional information, such as the emoji’s unique unicode-based identifier and name, localized name etc.:"}]},{"type":"codeListing","syntax":"swift","code":["let emoji = Emoji(\"😀\")","emoji.unicodeIdentifier \/\/ -> \\\\N{GRINNING FACE}","emoji.unicodeName \/\/ -> Grinning Face","emoji.localizedName(for: .swedish) \/\/ -> Leende Ansikte"]},{"type":"paragraph","inlineContent":[{"overridingTitleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"isActive":true,"type":"reference","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","overridingTitle":"KeyboardKit Pro"},{"type":"text","text":" also adds support for skin tone variants. See more about this further down."}]},{"anchor":"Emoji-categories","level":2,"type":"heading","text":"Emoji categories"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiCategory"},{"type":"text","text":" enum that defines all available emoji categories, such as "},{"type":"codeVoice","code":".smileys"},{"type":"text","text":", "},{"type":"codeVoice","code":".animals"},{"type":"text","text":", "},{"type":"codeVoice","code":".foods"},{"type":"text","text":" etc.:"}]},{"type":"codeListing","syntax":"swift","code":["let category = EmojiCategory.animals","let emojis = category.emojis    \/\/ 🐶🐱🐭🐹🐰🦊🐻🐼🐻‍❄️🐨 ..."]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can get all available categories like this:"}]},{"type":"codeListing","syntax":"swift","code":["let categories = EmojiCategory.all"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"There is also a "},{"type":"codeVoice","code":".frequent"},{"type":"text","text":" category that is handled with a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/FrequentEmojiProvider"},{"type":"text","text":". The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/MostRecentEmojiProvider"},{"type":"text","text":" implements this protocol by keeping track of the most recently tapped emojis. You can also implement a custom provider."}]},{"anchor":"Views","level":2,"type":"heading","text":"Views"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboard"},{"type":"text","text":" that can lists emojis in a grid, as well as an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiCategoryKeyboard"},{"type":"text","text":" that replicates the iOS emoji keyboard by listing the provided categories and their emojis. They can both be styled with an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboardStyle"},{"type":"text","text":"."}]},{"anchor":"How-to-localize-emoji-names","level":2,"type":"heading","text":"How to localize emoji names"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emoji"},{"type":"text","text":" "},{"type":"codeVoice","code":"localizedName(for:)"},{"type":"text","text":" functions use "},{"type":"codeVoice","code":"Localizable.strings"},{"type":"text","text":" files in "},{"type":"codeVoice","code":"Sources\/Resources"},{"type":"text","text":". Emojis that lack a localized name will use the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emoji\/unicodeName"},{"type":"text","text":" property as a fallback."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To localize emojis for a certain locale, simply add localized strings for the various emojis in the correct "},{"type":"codeVoice","code":"Localizable.strings"},{"type":"text","text":" file. This is a major undertaking and therefore a community effort. Feel free to create PRs to help out."}]},{"anchor":"👑-Pro-features","level":2,"type":"heading","text":"👑 Pro features"},{"type":"paragraph","inlineContent":[{"overridingTitleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"isActive":true,"type":"reference","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","overridingTitle":"KeyboardKit Pro"},{"type":"text","text":" unlocks additional emoji capabilities."}]},{"anchor":"Additional-information","level":3,"type":"heading","text":"Additional information"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/ProEmojiInfo"},{"type":"text","text":" protocol that is implemented by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emoji"},{"type":"text","text":" and provides additional emoji information, such as skin tone variant information:"}]},{"type":"codeListing","syntax":"swift","code":["Emoji(\"👍\").hasSkinToneVariants     \/\/ true","Emoji(\"🚀\").hasSkinToneVariants     \/\/ false","","Emoji(\"👍🏿\").neutralSkinToneVariant  \/\/ 👍","","Emoji(\"👍\").skinToneVariants        \/\/ 👍👍🏻👍🏼👍🏽👍🏾👍🏿","Emoji(\"👍\").skinToneVariantActions  \/\/ The above variants as keyboard actions"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"These properties make it possible to resolve all skin tone variants for an emoji that has it."}]},{"anchor":"Additional-emoji-callouts","level":3,"type":"heading","text":"Additional emoji callouts"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Since KeyboardKit Pro unlocks skin tone variants, it will also unlock skin tone variant callout actions for all emojis that has skin tone variants. This means long pressing an emoji that has skin tone variants, will show those variants in a callout."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/keyboardkitpro\/emojis"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/emojis"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji model and how to use it."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Emojis","role":"article","modules":[{"name":"KeyboardKitPro"}]},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"seeAlsoSections":[{"title":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Appearance","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Extensions","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Routing","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/RTL","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings"],"generated":true}],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Appearance":{"role":"article","title":"Appearance","abstract":[{"type":"text","text":"This article describes the KeyboardKit appearance engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Appearance","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/appearance"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts":{"role":"article","title":"Callouts","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/callouts"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLocale/persian":{"role":"symbol","title":"KeyboardLocale.persian","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"persian"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale\/persian","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardlocale\/persian"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization":{"role":"article","title":"Localization","abstract":[{"type":"text","text":"This article describes the KeyboardKit localization model and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/localization"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/RTL":{"role":"article","title":"RTL","abstract":[{"type":"text","text":"KeyboardKit supports RTL (right-to-left) locales, which means that it supports locales like "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale\/arabic"},{"type":"text","text":",  "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale\/persian"},{"type":"text","text":" etc."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/RTL","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/rtl"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard":{"role":"article","title":"Keyboard","abstract":[{"type":"text","text":"This article describes the KeyboardKit keyboard types and how to use them."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboard"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/EmojiCategoryKeyboard":{"role":"symbol","title":"EmojiCategoryKeyboard","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmojiCategoryKeyboard"}],"abstract":[{"type":"text","text":"This keyboard lists all emojis from a selected category, as"},{"type":"text","text":" "},{"type":"text","text":"well as a menu that lets the user select a new category and"},{"type":"text","text":" "},{"type":"text","text":"change back to an alphabetic keyboard."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiCategoryKeyboard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EmojiCategoryKeyboard"}],"url":"\/documentation\/keyboardkitpro\/emojicategorykeyboard"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLocale/arabic":{"role":"symbol","title":"KeyboardLocale.arabic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"arabic"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale\/arabic","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardlocale\/arabic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy-Extensions":{"role":"article","title":"Proxy Extensions","abstract":[{"type":"text","text":"This article describes how KeyboardKit extends "},{"type":"codeVoice","code":"UITextDocumentProxy"},{"type":"text","text":" with a lot of additional functionality."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Extensions","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/proxy-extensions"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout":{"role":"article","title":"Layouts","abstract":[{"type":"text","text":"This article describes the KeyboardKit keyboard layout engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/layout"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/EmojiKeyboardStyle":{"role":"symbol","title":"EmojiKeyboardStyle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmojiKeyboardStyle"}],"abstract":[{"type":"text","text":"This style can be applied to emoji keyboard views, like the"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboard"},{"type":"text","text":" or "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiCategoryKeyboard"},{"type":"text","text":" to customize"},{"type":"text","text":" "},{"type":"text","text":"things like the font, number of rows, item spacing etc."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboardStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EmojiKeyboardStyle"}],"url":"\/documentation\/keyboardkitpro\/emojikeyboardstyle"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/MostRecentEmojiProvider":{"role":"symbol","title":"MostRecentEmojiProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MostRecentEmojiProvider"}],"abstract":[{"type":"text","text":"This emoji provider can be used to return the most recently"},{"type":"text","text":" "},{"type":"text","text":"used emojis."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/MostRecentEmojiProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MostRecentEmojiProvider"}],"url":"\/documentation\/keyboardkitpro\/mostrecentemojiprovider"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Routing":{"role":"article","title":"Routing","abstract":[{"type":"text","text":"This article describes how KeyboardKit adds ways for you to route text from the main app to other text fields within the keyboard."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Routing","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/routing"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/ProEmojiInfo":{"role":"symbol","title":"ProEmojiInfo","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProEmojiInfo"}],"abstract":[{"type":"text","text":"This protocol can be implemented by any types that has more"},{"type":"text","text":" "},{"type":"text","text":"info about emojis than is otherwise available."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/ProEmojiInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProEmojiInfo"}],"url":"\/documentation\/keyboardkitpro\/proemojiinfo"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emoji/unicodeName":{"role":"symbol","title":"unicodeName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"unicodeName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The emoji’s unicode name."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emoji\/unicodeName","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/emoji\/unicodename"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/EmojiCategory":{"role":"symbol","title":"EmojiCategory","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmojiCategory"}],"abstract":[{"type":"text","text":"This enum contains the emoji categories that the native iOS"},{"type":"text","text":" "},{"type":"text","text":"emoji keyboard currently has."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiCategory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EmojiCategory"}],"url":"\/documentation\/keyboardkitpro\/emojicategory"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/EmojiKeyboard":{"role":"symbol","title":"EmojiKeyboard","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmojiKeyboard"}],"abstract":[{"type":"text","text":"This view can be used as an emoji keyboard and will list an"},{"type":"text","text":" "},{"type":"text","text":"emoji collection using the provided configuration."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EmojiKeyboard"}],"url":"\/documentation\/keyboardkitpro\/emojikeyboard"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","title":"KeyboardKitPro","abstract":[{"type":"text","text":"KeyboardKit Pro helps you build custom keyboard extensions for iOS and iPadOS."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions":{"role":"article","title":"Actions","abstract":[{"type":"text","text":"This article describes the KeyboardKit action engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/actions"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Settings":{"role":"article","title":"Settings","abstract":[{"type":"text","text":"This article describes the KeyboardKit settings utilities and how to use them."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/settings"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emoji":{"role":"symbol","title":"Emoji","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Emoji"}],"abstract":[{"type":"text","text":"This struct is just a wrapper around a single character. It"},{"type":"text","text":" "},{"type":"text","text":"can be used to get a little bit of type safety, and to work"},{"type":"text","text":" "},{"type":"text","text":"more structured with emojis."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emoji","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Emoji"}],"url":"\/documentation\/keyboardkitpro\/emoji"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Previews":{"role":"article","title":"Previews","abstract":[{"type":"text","text":"This article describes how KeyboardKit makes it easy to preview keyboard-specific views."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/previews"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback":{"role":"article","title":"Feedback","abstract":[{"type":"text","text":"This article describes the KeyboardKit feedback engine and how to use it to trigger audio and haptic feedback."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/feedback"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures":{"role":"article","title":"Gestures","abstract":[{"type":"text","text":"This article describes the KeyboardKit gesture engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/gestures"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards":{"role":"article","title":"External Keyboards","abstract":[{"type":"text","text":"This article describes the KeyboardKit external keyboard engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/external-keyboards"},"https://github.com/KeyboardKit/KeyboardKitPro":{"title":"KeyboardKit Pro","titleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"type":"link","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","url":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Input":{"role":"article","title":"Input","abstract":[{"type":"text","text":"This article describes the KeyboardKit input set engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/input"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/FrequentEmojiProvider":{"role":"symbol","title":"FrequentEmojiProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FrequentEmojiProvider"}],"abstract":[{"type":"text","text":"This protocol can be implemented by classes that can return"},{"type":"text","text":" "},{"type":"text","text":"a list of frequently used emojis."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/FrequentEmojiProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FrequentEmojiProvider"}],"url":"\/documentation\/keyboardkitpro\/frequentemojiprovider"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete":{"role":"article","title":"Autocomplete","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/autocomplete"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Appearance","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Extensions","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Routing","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/RTL","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}