{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkitpro\/essentials-keyboardview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkitpro\/essentials-keyboardview"]}],"sections":[],"metadata":{"role":"article","title":"Essentials - KeyboardView","images":[{"identifier":"Page.png","type":"card"}],"modules":[{"name":"KeyboardKitPro"}],"roleHeading":"Article"},"seeAlsoSections":[{"title":"Essentials","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article"],"generated":true,"anchor":"Essentials"}],"primaryContentSections":[{"kind":"content","content":[{"type":"heading","anchor":"Keyboard-View","text":"Keyboard View","level":2},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit has a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","type":"reference","isActive":true},{"text":" that mimics the native iOS keyboard. It can be used for alphabetic, numeric & symbolic keyboards, as well as completely custom ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout","type":"reference","isActive":true},{"text":"s, and can be used on all Apple platforms:","type":"text"}]},{"type":"row","numberOfColumns":3,"columns":[{"size":1,"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"keyboardview-english"}]}]},{"size":1,"content":[{"type":"paragraph","inlineContent":[{"identifier":"keyboardview-swedish","type":"image"}]}]},{"size":1,"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"keyboardview-theme"}]}]}]},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","type":"reference"},{"text":" will automatically conform to the current configurations and settings in the various context and settings classes, like ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext","type":"reference"},{"text":" and ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings","type":"reference"},{"text":", apply gestures and callouts to its keys, etc.","type":"text"}]},{"type":"paragraph","inlineContent":[{"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","isActive":true,"type":"reference"},{"type":"text","text":" makes "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","isActive":true,"type":"reference"},{"type":"text","text":" automatically support all the locales in your license, by using localized "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout","isActive":true,"type":"reference"},{"type":"text","text":"s that adapt to the current "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/locale","isActive":true,"type":"reference"},{"type":"text","text":" and "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/keyboardLayoutType","isActive":true,"type":"reference"},{"type":"text","text":"."}]},{"type":"heading","anchor":"Injected-Values-vs-View-Modifiers","text":"Injected Values vs. View Modifiers","level":2},{"type":"paragraph","inlineContent":[{"text":"Since the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView"},{"text":" has all the information it needs, it will set up most things for you. While you can customize each view, it will automatically apply gestures, styles, callouts, etc. based on the provided ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Services"},{"text":" and ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/State"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"You can however apply some view modifiers, like ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/keyboardDockEdge(_:)","type":"reference"},{"text":" to override the default values that  ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","type":"reference"},{"text":" will otherwise apply. This support will be further extended throughout the KeyboardKit 9 lifecycle.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For instance, you will find that you can style many parts of the keyboard with both view modifiers and a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyleService","isActive":true},{"type":"text","text":", while some styles don’t yet have a corresponding view modifier."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In general, use "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Services","isActive":true},{"type":"text","text":", "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/State","isActive":true},{"type":"text","text":", and "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings","isActive":true},{"type":"text","text":" to customize the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","isActive":true},{"type":"text","text":" and use view modifiers for styles and to override context and settings properties that have corresponding view modifiers."}]},{"type":"heading","anchor":"How-to","text":"How to","level":2},{"type":"heading","anchor":"customize-the-keyboard","text":"…customize the keyboard","level":3},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","isActive":true},{"text":" can be customized to great extent. You can pass in custom services & state, and replace any button or sub-view:","type":"text"}]},{"type":"codeListing","code":["KeyboardView(","    controller: controller,             \/\/ You can pass in a controller OR specific states and services","    buttonContent: { $0.view },         \/\/ You can customize the content view of any button","    buttonView: { $0.view },            \/\/ You can customize the entire view of any button","    collapsedView: { $0.view },         \/\/ You can customize the collapsed keyboard view","    emojiKeyboard: { $0.view },         \/\/ You can customize the emoji keyboard, if any","    toolbar: { params in params.view }  \/\/ You can customize the toolbar above the keyboard",")"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Just return "},{"code":"{ $0.view }","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"{ params in params.view }","type":"codeVoice"},{"text":" to use the standard view, or return a custom view for any part of the keyboard, using the contextual parameters that each view builder provides.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The standard emoji keyboard and collapsed view are unlocked by "},{"overridingTitle":"KeyboardKit Pro","isActive":true,"type":"reference","overridingTitleInlineContent":[{"text":"KeyboardKit Pro","type":"text"}],"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro"},{"type":"text","text":". You can however inject any custom views you like."}]},{"type":"heading","anchor":"customize-the-keyboard-behavior","text":"…customize the keyboard behavior","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"The easiest way to customize the behavior of the keyboard is to inherit "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/StandardActionHandler","isActive":true},{"type":"text","text":", then customize the behavior of any "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Gesture","isActive":true},{"type":"text","text":" on any "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","isActive":true},{"type":"text","text":" by overriding the various service functions."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"See the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","type":"reference","isActive":true},{"type":"text","text":" article for more information."}]},{"type":"heading","anchor":"customize-the-keyboard-callouts","text":"…customize the keyboard callouts","level":3},{"type":"paragraph","inlineContent":[{"text":"The easiest way to customize the secondary callout actions that are used for a specific key is to inherit ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardCallout\/StandardCalloutService"},{"text":", then customize which actions to return any keys by overriding the various service functions.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"See the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article"},{"type":"text","text":" article for more information."}]},{"type":"heading","anchor":"customize-the-keyboard-layout","text":"…customize the keyboard layout","level":3},{"type":"paragraph","inlineContent":[{"text":"The easiest way to add, replace and remove keys is to inherit ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout\/StandardLayoutService","type":"reference"},{"text":" and customize the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout","type":"reference"},{"text":" by overriding the various service functions.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"See the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","type":"reference"},{"text":" article for more information.","type":"text"}]},{"type":"heading","anchor":"customize-the-keyboard-design","text":"…customize the keyboard design","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"The easiest way to adjust the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","isActive":true},{"type":"text","text":" design is to inherit "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyle\/StandardStyleService","isActive":true},{"type":"text","text":" and customize the various styles by overriding the various service functions. You can change background and foreground colors, fonts, etc. for any part of the keyboard."}]},{"type":"paragraph","inlineContent":[{"text":"See the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","type":"reference"},{"text":" and ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article","type":"reference"},{"text":" articles for more information.","type":"text"}]},{"type":"heading","anchor":"customize-the-keyboard-size","text":"…customize the keyboard size","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","isActive":true},{"type":"text","text":" will by default take up as much space as it needs, and resize the keyboard extension frame accordingly. It will:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Collapse when "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/isKeyboardCollapsed","isActive":true},{"type":"text","text":" is set, e.g. when connecting an external keyboard."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Collapse when an external keyboard is connected, if "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/isKeyboardAutoCollapseEnabled","type":"reference","isActive":true},{"type":"text","text":" is set."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Dock to any horizontal edge of the screen when "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/keyboardDockEdge"},{"type":"text","text":" is set."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Render as a floating keyboard when ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/isKeyboardFloating","type":"reference"},{"text":" is set (iPad only).","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Render custom sizes for any keys, based on the size information in the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout"},{"type":"text","text":"."}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"See the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","isActive":true},{"type":"text","text":" article and various namespace articles for more information."}]}]}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-KeyboardView","interfaceLanguage":"swift"},"kind":"article","abstract":[{"type":"text","text":"This article describes the essential "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","isActive":true},{"type":"text","text":" and how to use and configure it."}],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardSettings/isKeyboardAutoCollapseEnabled":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isKeyboardAutoCollapseEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isKeyboardAutoCollapseEnabled","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/isKeyboardAutoCollapseEnabled","abstract":[{"text":"Whether to auto-collapse the keyboard when an external keyboard is connected.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardsettings\/iskeyboardautocollapseenabled","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardStyle/StandardStyleService":{"type":"topic","abstract":[{"type":"text","text":"This class provides a standard way to create dynamic"},{"type":"text","text":" "},{"type":"text","text":"keyboard styles."}],"url":"\/documentation\/keyboardkitpro\/keyboardstyle\/standardstyleservice","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyle\/StandardStyleService","kind":"symbol","title":"KeyboardStyle.StandardStyleService","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StandardStyleService"}],"navigatorTitle":[{"kind":"identifier","text":"StandardStyleService"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"title":"KeyboardKitPro","kind":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","abstract":[{"text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI.","type":"text"}],"url":"\/documentation\/keyboardkitpro","role":"collection"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardCallout/StandardCalloutService":{"kind":"symbol","role":"symbol","type":"topic","title":"KeyboardCallout.StandardCalloutService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StandardCalloutService"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardCallout\/StandardCalloutService","url":"\/documentation\/keyboardkitpro\/keyboardcallout\/standardcalloutservice","navigatorTitle":[{"kind":"identifier","text":"StandardCalloutService"}],"abstract":[{"text":"This service class provides a standard way to handle","type":"text"},{"text":" ","type":"text"},{"text":"keyboard callouts.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardSettings/keyboardDockEdge":{"abstract":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/DockEdge","isActive":true},{"text":" to use, if any.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardsettings\/keyboarddockedge","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/keyboardDockEdge","title":"keyboardDockEdge","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardDockEdge","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Keyboard","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V"},{"text":".","kind":"text"},{"text":"DockEdge","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V8DockEdgeO"},{"text":"?","kind":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardContext"}],"type":"topic","title":"KeyboardContext","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext","url":"\/documentation\/keyboardkitpro\/keyboardcontext","abstract":[{"text":"This class has observable states and persistent settings","type":"text"},{"text":" ","type":"text"},{"text":"for the core keyboard functionality.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardContext"}],"role":"symbol"},"Page.png":{"identifier":"Page.png","alt":"Page icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png"}],"type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/locale":{"url":"\/documentation\/keyboardkitpro\/keyboardcontext\/locale","abstract":[{"type":"text","text":"The current locale, by default "},{"code":".current","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/locale","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"locale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale"}],"role":"symbol","title":"locale"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Essentials-Article":{"images":[{"type":"card","identifier":"Page.png"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","url":"\/documentation\/keyboardkitpro\/essentials-article","type":"topic","title":"Essentials","abstract":[{"text":"This article describes the essential parts of KeyboardKit.","type":"text"}],"role":"article","kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardSettings":{"navigatorTitle":[{"kind":"identifier","text":"KeyboardSettings"}],"type":"topic","abstract":[{"type":"text","text":"This type is used for essential keyboard settings."}],"title":"KeyboardSettings","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardsettings","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardSettings","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Themes-Article":{"type":"topic","role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article","url":"\/documentation\/keyboardkitpro\/themes-article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"text":"This article describes the KeyboardKit Pro theme engine.","type":"text"}],"title":"Themes"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"type":"topic","url":"\/documentation\/keyboardkitpro\/actions-article","kind":"article","title":"Actions","role":"article","images":[{"type":"card","identifier":"Page.png"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit action engine."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/DockEdge":{"title":"Keyboard.DockEdge","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/DockEdge","type":"topic","abstract":[{"text":"This enum defines supported keyboard dock edges.","type":"text"}],"kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboard\/dockedge","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DockEdge","kind":"identifier"}],"navigatorTitle":[{"text":"DockEdge","kind":"identifier"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/State":{"abstract":[{"text":"This type specifies global keyboard state.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","title":"Keyboard.State","url":"\/documentation\/keyboardkitpro\/keyboard\/state","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}],"navigatorTitle":[{"kind":"identifier","text":"State"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/State"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardView":{"url":"\/documentation\/keyboardkitpro\/keyboardview","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","role":"symbol","title":"KeyboardView","kind":"symbol","abstract":[{"text":"This view can be used to mimic a native iOS keyboard.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardView","kind":"identifier"}],"navigatorTitle":[{"text":"KeyboardView","kind":"identifier"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/isKeyboardCollapsed":{"title":"isKeyboardCollapsed","url":"\/documentation\/keyboardkitpro\/keyboardcontext\/iskeyboardcollapsed","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isKeyboardCollapsed","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/isKeyboardCollapsed","abstract":[{"type":"text","text":"Whether the keyboard is collapsed."}],"kind":"symbol"},"keyboardview-english":{"identifier":"keyboardview-english","alt":"KeyboardView","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/keyboardview-english.jpg","traits":["1x","light"]}],"type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardStyleService":{"type":"topic","abstract":[{"type":"text","text":"This protocol can be implemented by any classes that can"},{"type":"text","text":" "},{"type":"text","text":"provide dynamic keyboard styles."}],"url":"\/documentation\/keyboardkitpro\/keyboardstyleservice","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardStyleService","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"KeyboardStyleService","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyleService","title":"KeyboardStyleService"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Styling-Article":{"role":"article","images":[{"identifier":"Page.png","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","url":"\/documentation\/keyboardkitpro\/styling-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit styling engine."}],"type":"topic","title":"Styling","kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLayout":{"url":"\/documentation\/keyboardkitpro\/keyboardlayout","navigatorTitle":[{"text":"KeyboardLayout","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout","role":"symbol","type":"topic","abstract":[{"type":"text","text":"This type defines the full set of keys on a keyboard and"},{"type":"text","text":" "},{"type":"text","text":"is also a namespace for layout-related types."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardLayout","kind":"identifier"}],"title":"KeyboardLayout","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/keyboardLayoutType":{"url":"\/documentation\/keyboardkitpro\/keyboardcontext\/keyboardlayouttype","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/keyboardLayoutType","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardLayoutType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Keyboard","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V"},{"text":".","kind":"text"},{"text":"LayoutType","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V10LayoutTypeO"},{"text":"?","kind":"text"}],"title":"keyboardLayoutType","type":"topic","abstract":[{"text":"The current keyboard layout type, if any.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Gesture":{"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Gesture","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Gesture","kind":"identifier"}],"navigatorTitle":[{"text":"Gesture","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboard\/gesture","type":"topic","role":"symbol","abstract":[{"type":"text","text":"This enum defines various keyboard gestures that can"},{"type":"text","text":" "},{"type":"text","text":"be used to interact with a keyboard."}],"title":"Keyboard.Gesture"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","images":[{"type":"card","identifier":"Page.png"}],"role":"article","url":"\/documentation\/keyboardkitpro\/layout-article","title":"Layout","abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}]},"keyboardview-theme":{"identifier":"keyboardview-theme","alt":"KeyboardView","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/keyboardview-theme.jpg"}],"type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction":{"role":"symbol","abstract":[{"type":"text","text":"This enum defines keyboard-specific actions, and is also"},{"type":"text","text":" "},{"type":"text","text":"a namespace for keyboard action-related types."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardAction","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","navigatorTitle":[{"text":"KeyboardAction","kind":"identifier"}],"title":"KeyboardAction","url":"\/documentation\/keyboardkitpro\/keyboardaction"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/StandardActionHandler":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"StandardActionHandler","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardaction\/standardactionhandler","navigatorTitle":[{"text":"StandardActionHandler","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/StandardActionHandler","title":"KeyboardAction.StandardActionHandler","abstract":[{"type":"text","text":"This class provides a standard way to handle actions"},{"type":"text","text":" "},{"type":"text","text":"that are triggered by the keyboard."}],"role":"symbol","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/isKeyboardFloating":{"kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardcontext\/iskeyboardfloating","abstract":[{"text":"Whether the keyboard is in floating mode.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/isKeyboardFloating","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isKeyboardFloating","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isKeyboardFloating","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Services":{"type":"topic","title":"Keyboard.Services","navigatorTitle":[{"kind":"identifier","text":"Services"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Services","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboard\/services","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Services"}],"abstract":[{"text":"This type specifies global keyboard services.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Getting-Started-Article":{"type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This guide describes how to get started with KeyboardKit."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started-Article","url":"\/documentation\/keyboardkitpro\/getting-started-article","title":"Getting Started","kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUICore/View/keyboardDockEdge(_:)":{"abstract":[{"text":"Apply a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/DockEdge","isActive":true},{"text":" value.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/swiftuicore\/view\/keyboarddockedge(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardDockEdge","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Keyboard","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V"},{"text":".","kind":"text"},{"text":"DockEdge","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V8DockEdgeO"},{"text":"?) -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/keyboardDockEdge(_:)","type":"topic","kind":"symbol","title":"keyboardDockEdge(_:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLayout/StandardLayoutService":{"title":"KeyboardLayout.StandardLayoutService","navigatorTitle":[{"kind":"identifier","text":"StandardLayoutService"}],"role":"symbol","abstract":[{"type":"text","text":"This class provides a standard way to create dynamic"},{"type":"text","text":" "},{"type":"text","text":"keyboard layouts."}],"url":"\/documentation\/keyboardkitpro\/keyboardlayout\/standardlayoutservice","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StandardLayoutService"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout\/StandardLayoutService"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","type":"topic","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"title":"Callouts","role":"article","images":[{"type":"card","identifier":"Page.png"}],"url":"\/documentation\/keyboardkitpro\/callouts-article"},"keyboardview-swedish":{"identifier":"keyboardview-swedish","alt":"KeyboardView","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/keyboardview-swedish.jpg"}],"type":"image"},"https://github.com/KeyboardKit/KeyboardKitPro":{"title":"KeyboardKit Pro","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","titleInlineContent":[{"text":"KeyboardKit Pro","type":"text"}],"type":"link","url":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/topicSections"},{"value":[{"generated":true,"title":"Essentials","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article"],"anchor":"Essentials"}],"op":"replace","path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}