{"variants":[{"paths":["\/documentation\/keyboardkitpro\/essentials"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkitpro\/essentials"]}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"This article describes the essential parts of KeyboardKit."}],"primaryContentSections":[{"content":[{"level":2,"anchor":"overview","text":"Overview","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit extends Apple’s native APIs and provides you with a lot more functionality. It lets you mimic the native iOS keyboard and tweak its style and behavior, or create completely custom keyboards."}]},{"inlineContent":[{"text":"KeyboardKit also has a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboard"},{"type":"text","text":" view that mimics the native iOS keyboard and can be customized & styled to great extent. Many of the tools and views in the SDK are used by the system keyboard."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"👑 "},{"isActive":true,"type":"reference","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro"},{"type":"text","text":" unlocks a lot of essential Pro features, such as a toggle toolbar, a system keyboard input toolbar, additional system keyboard views, previews, etc. Information about Pro features can be found at the end of this article."}]},{"text":"Keyboard namespace","level":2,"anchor":"Keyboard-namespace","type":"heading"},{"inlineContent":[{"type":"text","text":"KeyboardKit uses namespaces to make the API surface smaller, by nesting types in logical groups. By typing "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","type":"reference"},{"type":"text","text":" and "},{"type":"codeVoice","code":"."},{"text":", Xcode will provide you with a list of all types in this essential namespace.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"KeyboardKit has other namespaces as well, that extend the library with more specific capabilities, like ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction"},{"type":"text","text":", "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout"},{"text":", ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts","isActive":true},{"type":"text","text":", "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback"},{"text":", etc.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","isActive":true},{"type":"text","text":" namespace has a lot of essential types, like "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/KeyboardType","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Button","isActive":true,"type":"reference"},{"type":"text","text":", "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Diacritic","type":"reference","isActive":true},{"type":"text","text":", etc. that are essential when for creating a custom keyboard. It also contains common views, styles, etc."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Namespaces will not contain protocols, nor important types that are meant to be exposed as top-level types. This includes observable context and settings types, the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","type":"reference","isActive":true},{"text":" and important components like the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboard"},{"text":".","type":"text"}]},{"level":2,"text":"Keyboard input view controller","type":"heading","anchor":"Keyboard-input-view-controller"},{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController"},{"text":" is the most essential type in the library. Just make your ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"KeyboardController"}]},{"type":"text","text":" inherit this class to get access to a bunch of additional capabilities and view lifecycle functions."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","isActive":true,"type":"reference"},{"text":" defines shared ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","isActive":true,"type":"reference"},{"type":"text","text":", "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/settings","isActive":true},{"type":"text","text":" properties, and "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state","isActive":true},{"text":", that can be used to avoid relying on the controller within your code.","type":"text"}]},{"inlineContent":[{"text":"KeyboardKit also has a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardController","isActive":true},{"text":" protocol that aims to make it easier to use KeyboardKit in platforms that don’t support UIKit. This is however not fully implemented yet, although many types use it.","type":"text"}],"type":"paragraph"},{"anchor":"Keyboard-context","level":2,"type":"heading","text":"Keyboard context"},{"inlineContent":[{"text":"KeyboardKit has a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext"},{"type":"text","text":" class that provides observable keyboard state that keeps the keyboard UI up to date with its current state. It has a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/textDocumentProxy"},{"type":"text","text":" reference, lets you get and set "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/locale","type":"reference"},{"text":", ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/keyboardType","isActive":true},{"text":", etc.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"You can use this to update the keyboard. For instance, setting the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/keyboardType","isActive":true},{"text":" will update the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboard","isActive":true},{"text":" accordingly.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Other namespaces have their own context types, like ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteContext","isActive":true,"type":"reference"},{"type":"text","text":", "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutContext","type":"reference"},{"type":"text","text":", "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationContext","isActive":true},{"type":"text","text":", etc. They will all automatically update the keyboard, provided that the keyboard view observes them,"}]},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit automatically creates instances of these classes and injects them into ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state"},{"type":"text","text":", and syncs with the controller when needed."}]},{"anchor":"Keyboard-settings","level":2,"text":"Keyboard settings","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has an "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings","isActive":true},{"text":" class that provides observable keyboard settings that are automatically persisted when they are changed. It has a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/isAutocapitalizationEnabled","isActive":true},{"text":" property and will be extended with more settings over time.","type":"text"}]},{"inlineContent":[{"type":"text","text":"Other namespaces have their own setting types, like "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationSettings","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/FeedbackSettings","type":"reference","isActive":true},{"type":"text","text":", etc. KeyboardKit will observe any changes made to these types and update the keyboard accordingly."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit automatically creates instances of these classes, injects them into ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/settings"},{"type":"text","text":", and syncs with the controller when needed."}]},{"anchor":"Keyboard-behavior","text":"Keyboard behavior","type":"heading","level":2},{"inlineContent":[{"text":"KeyboardKit has a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardBehavior","type":"reference"},{"text":" protocol that can be used to define the keyboard’s behavior. It’s used by some services, like the standard ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler"},{"text":", to make behavior-based decisions.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit automatically creates an instance of "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/StandardBehavior","isActive":true},{"type":"text","text":" and injects it into "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services"},{"text":". You can replace it at any time, by implementing the procotol from scratch or by inheriting and customizing the standard behavior.","type":"text"}]},{"text":"Keyboard styling","type":"heading","level":2,"anchor":"Keyboard-styling"},{"inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","isActive":true,"type":"reference"},{"type":"text","text":" article describes how you can use a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyleProvider"},{"text":" to style your keyboard in a dynamic and flexible way. Various views have their own styles as well, that can be applied with view modifiers.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"The keyboard appearance model can be used to define if a keyboard is light or dark. This is not the same thing as the color scheme. A keyboard can be defined as “dark” even in light mode, and will render slightly darker than the default appearance.","type":"text"}]},{"inlineContent":[{"type":"text","text":"KeyboardKit has an "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/AppearanceViewModifier","isActive":true},{"text":" that can be applied with the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/View\/keyboardAppearance(_:)","isActive":true},{"type":"text","text":" view modifier:"}],"type":"paragraph"},{"type":"codeListing","syntax":null,"code":["TextField(\"Enter text\", text: $text)","    .keyboardAppearance(.dark)"]},{"type":"paragraph","inlineContent":[{"text":"Note that applying a dark appearances will make iOS tell the extension that the ","type":"text"},{"inlineContent":[{"type":"text","text":"color scheme"}],"type":"emphasis"},{"type":"text","text":" is dark, while this may in fact not be true. This will lead to visual bugs, that require workarounds. See the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Colors-Article","isActive":true,"type":"reference"},{"text":" article for more information.","type":"text"}]},{"level":2,"text":"Native Extensions","type":"heading","anchor":"Native-Extensions"},{"inlineContent":[{"text":"KeyboardKit extends native types with a lot more information, to make it easier to implement features like autocomplete, text analysis, etc. Check the extension section in the bottom of the documentation root, or the ","type":"text"},{"type":"codeVoice","code":"Extensions"},{"type":"text","text":" folder for more info."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"For instance, KeyboardKit extends types in "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Foundation","type":"reference","isActive":true},{"type":"text","text":", "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Swift","isActive":true},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI"},{"type":"text","text":", and other platform-specific frameworks."}]},{"anchor":"System-Keyboard","level":2,"type":"heading","text":"System Keyboard"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboard","isActive":true},{"text":" that mimics a native iOS keyboard. It can be used for alphabetic, numeric & symbolic keyboards, supports all supported locales, layouts, callouts, etc., and can be styled to great extent with styles & themes:","type":"text"}]},{"type":"row","columns":[{"size":1,"content":[{"inlineContent":[{"identifier":"systemkeyboard-english","type":"image"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"image","identifier":"systemkeyboard-swedish"}],"type":"paragraph"}],"size":1},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"systemkeyboard-styled","type":"image"}]}],"size":1}],"numberOfColumns":3},{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboard"},{"text":" can be customized to great extent. You can pass in custom services & state, replace any part of the keyboard, and enable additional components:","type":"text"}],"type":"paragraph"},{"code":["SystemKeyboard(","    controller: controller,             \/\/ You can setup the view with a controller instance ","    buttonContent: { $0.view },         \/\/ Can be used to customize the content view of any button","    buttonView: { $0.view },            \/\/ Can be used to customize the entire view of any button","    emojiKeyboard: { $0.view },         \/\/ Can be used to customize the emoji keyboard, if any","    toolbar: { params in params.view }  \/\/ Can be used to customize the toolbar above the keyboard",")"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To use the standard views, just return "},{"type":"codeVoice","code":"{ $0.view }"},{"type":"text","text":", or "},{"type":"codeVoice","code":"{ params in params.view }"},{"type":"text","text":". Otherwise, just return the view you want to use for the provided parameters, which contain contextual information."}]},{"text":"Views","level":2,"anchor":"Views","type":"heading"},{"inlineContent":[{"type":"text","text":"KeyboardKit also provides gerneral, keyboard-specific views in the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","type":"reference","isActive":true},{"text":" namespace, which means that you need to prefix the names below with ","type":"text"},{"type":"codeVoice","code":"Keyboard."},{"type":"text","text":" when using them (this applies to all namespaces in the library):"}],"type":"paragraph"},{"tabs":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has a collection of keyboard "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Button"},{"type":"text","text":" views and styles that can be used to mimic all parts of a native keyboard, as well as their gestures. The "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Button","isActive":true},{"type":"text","text":" renders the full button, while other views like "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ButtonShadow","type":"reference"},{"type":"text","text":" renders parts of it."}]},{"inlineContent":[{"type":"image","identifier":"systemkeyboardbuttonpreview"}],"type":"paragraph"},{"inlineContent":[{"text":"Most of the views can be styled with a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ButtonStyle","isActive":true,"type":"reference"},{"text":", which can be applied with the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/View\/keyboardButtonStyle(_:)"},{"type":"text","text":" view modifier. This is however not yet true for the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Button"},{"text":" itself, which uses a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyleProvider"},{"type":"text","text":" to support more complex styling."}],"type":"paragraph"}],"title":"Button"},{"content":[{"inlineContent":[{"type":"text","text":"KeyboardKit has a "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/NextKeyboardButton","type":"reference"},{"text":" that integrates with the native keyboard switcher, to select the next keyboard on tap and show a menu with all available keyboards on long press.","type":"text"}],"type":"paragraph"},{"columns":[{"content":[],"size":1},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"nextkeyboardbutton","type":"image"}]}],"size":1},{"size":1,"content":[]}],"numberOfColumns":3,"type":"row"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit will by default map the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/nextKeyboard","isActive":true,"type":"reference"},{"text":" action to this view, and automatically register the required ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","isActive":true,"type":"reference"},{"text":" on launch. You just have to add a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/nextKeyboard","type":"reference"},{"type":"text","text":" button, and it will just work."}]}],"title":"NextKeyboardButton"},{"title":"Toolbar","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has a keyboard "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Toolbar"},{"type":"text","text":" that applies a minimum height to its content. It can be used to stop input & action callouts from being cut off, since a custom iOS keyboard can’t render outside of its frame."}]},{"type":"paragraph","inlineContent":[{"identifier":"keyboardtoolbar","type":"image"}]},{"inlineContent":[{"type":"text","text":"This view can be styled with a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ToolbarStyle","type":"reference","isActive":true},{"type":"text","text":", which can be applied with the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/View\/keyboardToolbarStyle(_:)","isActive":true},{"type":"text","text":" view modifier:"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["Keyboard.Toolbar {","    Text(\"Here's a toolbar\")","}",".keyboardToolbarStyle(...)"]}]}],"type":"tabNavigator"},{"level":2,"text":"View Styling","type":"heading","anchor":"View-Styling"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit uses style view modifiers to great extent. This lets you style most KeyboardKit views just like regular SwiftUI views, like how a SwiftUI ","type":"text"},{"type":"codeVoice","code":"Button"},{"type":"text","text":" can be styled with "},{"code":".buttonStyle","type":"codeVoice"},{"type":"text","text":"."}]},{"inlineContent":[{"type":"text","text":"This is however not (yet) true for more complex views, like "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboard","type":"reference","isActive":true},{"text":", where KeyboardKit instead uses the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyleProvider"},{"type":"text","text":" concept to provide dynamic styles to any part of the view hieararchy."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"See the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article"},{"type":"text","text":" article for more information about KeyboardKit view styling."}]},{"anchor":"👑-KeyboardKit-Pro","type":"heading","level":2,"text":"👑 KeyboardKit Pro"},{"type":"paragraph","inlineContent":[{"overridingTitle":"KeyboardKit Pro","isActive":true,"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","overridingTitleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"type":"reference"},{"type":"text","text":" unlocks additional, powerful "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboard","isActive":true,"type":"reference"},{"text":" capabilities, including full support for all ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale","type":"reference"},{"type":"text","text":"s, a full-blown "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboard","type":"reference"},{"text":", input toolbars, powerful ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboardPreview"},{"text":"s, etc.","type":"text"}]},{"type":"heading","text":"System Keyboard","anchor":"System-Keyboard","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks additional "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboard","isActive":true},{"type":"text","text":"-related views and utils, that make it easier to create more powerful keyboards:"}]},{"tabs":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks a "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboardBottomRow","type":"reference"},{"text":" component that can be used to just render a system keyboard bottom row that by default uses the same layout configuration as the full system keyboard.","type":"text"}]},{"inlineContent":[{"identifier":"systemkeyboardbottomrow","type":"image"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This view is convenient if you want to replace the system keyboard with another view, but keep a bottom button row with some actions."}]}],"title":"Bottom Row"},{"content":[{"inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks an "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboard","isActive":true},{"text":", which is automatically added to ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboard","isActive":true,"type":"reference"},{"text":" when a valid license is registered.","type":"text"}],"type":"paragraph"},{"type":"row","numberOfColumns":4,"columns":[{"content":[],"size":1},{"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"emojikeyboard"}]}],"size":2},{"content":[],"size":1}]},{"inlineContent":[{"type":"text","text":"The keyboard has support for categories, runtime version adjustments and skintones. Read more about this in the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article"},{"type":"text","text":" article."}],"type":"paragraph"}],"title":"Emoji Keyboard"},{"title":"Input Toolbar","content":[{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro will automatically add an input toolbar to ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboard","isActive":true},{"text":" if ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/View\/keyboardInputToolbarDisplayMode(_:)","isActive":true,"type":"reference"},{"type":"text","text":" is applied to the view hierarchy, with an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/InputToolbarDisplayMode\/automatic"},{"text":" or ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/InputToolbarDisplayMode\/inputs(_:)","isActive":true},{"type":"text","text":" configuration."}]},{"type":"row","numberOfColumns":2,"columns":[{"size":1,"content":[{"type":"paragraph","inlineContent":[{"identifier":"inputtoolbar-ipad","type":"image"}]}]},{"content":[{"inlineContent":[{"identifier":"inputtoolbar-ipadpro","type":"image"}],"type":"paragraph"}],"size":1}]},{"inlineContent":[{"text":"The toolbar is added between the autocomplete toolbar and the system keyboard, and by default uses a slightly smaller button height.","type":"text"}],"type":"paragraph"}]},{"title":"Localization","content":[{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro unlocks localized services for all supported ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale","isActive":true},{"text":"s, which lets you create fully localized keyboards.","type":"text"}]},{"columns":[{"content":[],"size":1},{"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"systemkeyboard-swedish"}]}],"size":2},{"size":1,"content":[]}],"type":"row","numberOfColumns":4},{"inlineContent":[{"text":"The various license tiers unlock different amount of ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale","type":"reference"},{"text":"s, where Gold unlocks all. Read more in the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article"},{"type":"text","text":" article."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro unlocks a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboardPreview"},{"text":", which can be used to preview various configurations, locales, themes, etc.","type":"text"}]},{"type":"row","numberOfColumns":4,"columns":[{"content":[],"size":1},{"size":2,"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"systemkeyboardpreview-theme"}]}]},{"content":[],"size":1}]},{"inlineContent":[{"type":"text","text":"This view can also be used to show keyboard configurations to your users, e.g. on a settings screen. Read more in the "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","type":"reference"},{"text":" article.","type":"text"}],"type":"paragraph"}],"title":"Previews"}],"type":"tabNavigator"},{"text":"Views","anchor":"Views","level":3,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro also unlocks more general keyboard views in the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard"},{"type":"text","text":" namespace, to let you create more complex keyboards:"}]},{"tabs":[{"title":"ToggleToolbar","content":[{"inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ToggleToolbar","isActive":true,"type":"reference"},{"text":" can be used to toggle between two toolbars, e.g. to place a main menu “behind” the autocomplete toolbar:","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"image","identifier":"keyboardtoggletoolbar"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This view wraps itself in a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Toolbar","isActive":true,"type":"reference"},{"type":"text","text":", which means that it can also be styled with the "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/View\/keyboardToolbarStyle(_:)","type":"reference"},{"type":"text","text":" modifier."}],"type":"paragraph"}]}],"type":"tabNavigator"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials"},"kind":"article","metadata":{"title":"Essentials","modules":[{"name":"KeyboardKitPro"}],"images":[{"type":"card","identifier":"Page.png"}],"roleHeading":"Article","role":"article","color":{"standardColorIdentifier":"blue"}},"seeAlsoSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Colors-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Images-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"generated":true,"title":"Features"}],"sections":[],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Button":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Button","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Button","title":"Keyboard.Button","abstract":[{"text":"This view mimics a native keyboard button.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboard\/button","navigatorTitle":[{"text":"Button","kind":"identifier"}],"type":"topic","kind":"symbol"},"Page.png":{"identifier":"Page.png","alt":"Page icon","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","url":"\/documentation\/keyboardkitpro","type":"topic","title":"KeyboardKitPro","abstract":[{"type":"text","text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI."}],"role":"collection","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUI/View/keyboardButtonStyle(_:)":{"url":"\/documentation\/keyboardkitpro\/swiftui\/view\/keyboardbuttonstyle(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardButtonStyle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Keyboard","preciseIdentifier":"s:14KeyboardKitPro0A0V"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A0V11ButtonStyleV","text":"ButtonStyle","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","title":"keyboardButtonStyle(_:)","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/View\/keyboardButtonStyle(_:)","abstract":[{"text":"Apply a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ButtonStyle","isActive":true},{"text":".","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/state":{"title":"state","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state","abstract":[{"type":"text","text":"The default set of keyboard-specific state."}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/state","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Keyboard","preciseIdentifier":"s:14KeyboardKitPro0A0V"},{"text":".","kind":"text"},{"text":"State","preciseIdentifier":"s:14KeyboardKitPro0A0V5StateC","kind":"typeIdentifier"}],"role":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","kind":"article","type":"topic","abstract":[{"text":"This article describes the KeyboardKit gesture engine.","type":"text"}],"title":"Gestures","url":"\/documentation\/keyboardkitpro\/gestures-article","role":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUI":{"type":"topic","abstract":[],"title":"SwiftUI","role":"collection","kind":"symbol","url":"\/documentation\/keyboardkitpro\/swiftui","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/DictationContext":{"title":"DictationContext","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DictationContext","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DictationContext","kind":"identifier"}],"abstract":[{"type":"text","text":"This class has observable, dictation-related state."}],"type":"topic","url":"\/documentation\/keyboardkitpro\/dictationcontext","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationContext"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/StandardBehavior":{"type":"topic","kind":"symbol","abstract":[{"text":"This class defines the standard keyboard behavior of","type":"text"},{"type":"text","text":" "},{"type":"text","text":"a standard western keyboard, with some locale tweaks."}],"url":"\/documentation\/keyboardkitpro\/keyboard\/standardbehavior","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StandardBehavior"}],"navigatorTitle":[{"kind":"identifier","text":"StandardBehavior"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/StandardBehavior","title":"Keyboard.StandardBehavior"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/ToolbarStyle":{"navigatorTitle":[{"text":"ToolbarStyle","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"This style can be used to modify the visual style of"},{"type":"text","text":" "},{"text":"the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Toolbar","type":"reference","isActive":true},{"type":"text","text":" component."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ToolbarStyle","title":"Keyboard.ToolbarStyle","url":"\/documentation\/keyboardkitpro\/keyboard\/toolbarstyle","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ToolbarStyle"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/InputToolbarDisplayMode/inputs(_:)":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/InputToolbarDisplayMode\/inputs(_:)","abstract":[{"type":"text","text":"This mode can be used to display a set of inputs."}],"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboard\/inputtoolbardisplaymode\/inputs(_:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inputs","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"kind":"symbol","title":"Keyboard.InputToolbarDisplayMode.inputs(_:)","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SystemKeyboardBottomRow":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"SystemKeyboardBottomRow","kind":"identifier"}],"title":"SystemKeyboardBottomRow","kind":"symbol","navigatorTitle":[{"text":"SystemKeyboardBottomRow","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboardBottomRow","abstract":[{"type":"text","text":"This view can be used to create a system keyboard bottom"},{"text":" ","type":"text"},{"type":"text","text":"row, with leading & trailing actions around a space key."}],"url":"\/documentation\/keyboardkitpro\/systemkeyboardbottomrow","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardInputViewController"}],"kind":"symbol","type":"topic","title":"KeyboardInputViewController","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","abstract":[{"type":"text","text":"This is the main input controller in a KeyboardKit-based"},{"text":" ","type":"text"},{"text":"keyboard extension.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardInputViewController"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AI-Article":{"type":"topic","url":"\/documentation\/keyboardkitpro\/ai-article","abstract":[{"text":"This article describes the KeyboardKit AI support capabilities.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","title":"AI Support","images":[{"type":"card","identifier":"Page.png"}],"kind":"article","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Settings-Article":{"kind":"article","images":[{"type":"card","identifier":"Page.png"}],"title":"Settings","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","url":"\/documentation\/keyboardkitpro\/settings-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit settings engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Swift":{"abstract":[],"type":"topic","kind":"symbol","title":"Swift","role":"collection","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Swift","url":"\/documentation\/keyboardkitpro\/swift"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Navigation-Article":{"kind":"article","images":[{"type":"card","identifier":"Page.png"}],"title":"Navigation","role":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/navigation-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit navigation engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AutocompleteSettings":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutocompleteSettings","kind":"identifier"}],"abstract":[{"type":"text","text":"This observable class can be used to manage settings for"},{"type":"text","text":" "},{"type":"text","text":"the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete","isActive":true,"type":"reference"},{"text":" namespace.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings","title":"AutocompleteSettings","url":"\/documentation\/keyboardkitpro\/autocompletesettings","navigatorTitle":[{"text":"AutocompleteSettings","kind":"identifier"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"kind":"article","images":[{"type":"card","identifier":"Page.png"}],"title":"Callouts","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","url":"\/documentation\/keyboardkitpro\/callouts-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete":{"type":"topic","url":"\/documentation\/keyboardkitpro\/autocomplete","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete","abstract":[{"type":"text","text":"This namespace contains autocomplete-related types."}],"title":"Autocomplete","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Autocomplete"}],"navigatorTitle":[{"kind":"identifier","text":"Autocomplete"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Host-Article":{"title":"Host Utilities","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","images":[{"type":"card","identifier":"Page.png"}],"url":"\/documentation\/keyboardkitpro\/host-article","abstract":[{"type":"text","text":"This article describes how KeyboardKit can identify the host application."}],"role":"article","type":"topic","kind":"article"},"keyboardtoolbar":{"alt":"Keyboard Toolbar","variants":[{"url":"\/images\/keyboardtoolbar.jpg","traits":["1x","light"]}],"identifier":"keyboardtoolbar","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Previews-Article":{"kind":"article","images":[{"type":"card","identifier":"Page.png"}],"title":"Previews","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit preview engine."}],"url":"\/documentation\/keyboardkitpro\/previews-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLayout":{"url":"\/documentation\/keyboardkitpro\/keyboardlayout","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout","abstract":[{"type":"text","text":"This type defines the full set of keys on a keyboard and"},{"text":" ","type":"text"},{"type":"text","text":"serves as a namespace for layout-related types."}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"KeyboardLayout"}],"title":"KeyboardLayout","role":"symbol","navigatorTitle":[{"text":"KeyboardLayout","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardTheme":{"url":"\/documentation\/keyboardkitpro\/keyboardtheme","role":"symbol","abstract":[{"type":"text","text":"This struct defines a keyboard-specific theme."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardTheme"}],"navigatorTitle":[{"text":"KeyboardTheme","kind":"identifier"}],"type":"topic","title":"KeyboardTheme"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardActionHandler":{"type":"topic","navigatorTitle":[{"text":"KeyboardActionHandler","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardactionhandler","kind":"symbol","abstract":[{"type":"text","text":"This protocol can be implemented by any classes that can"},{"text":" ","type":"text"},{"text":"handle triggered ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction"},{"text":" events.","type":"text"}],"title":"KeyboardActionHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardActionHandler"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/NextKeyboardButton":{"kind":"symbol","url":"\/documentation\/keyboardkitpro\/nextkeyboardbutton","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"NextKeyboardButton","kind":"identifier"}],"navigatorTitle":[{"text":"NextKeyboardButton","kind":"identifier"}],"abstract":[],"role":"symbol","title":"NextKeyboardButton","deprecated":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/NextKeyboardButton","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardController":{"abstract":[{"type":"text","text":"This protocol can be implemented by any classes that can"},{"type":"text","text":" "},{"type":"text","text":"be used to control a keyboard extension."}],"url":"\/documentation\/keyboardkitpro\/keyboardcontroller","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardController"}],"role":"symbol","title":"KeyboardController","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardController","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardController"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","kind":"article","type":"topic","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"title":"Feedback","url":"\/documentation\/keyboardkitpro\/feedback-article","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLocale":{"url":"\/documentation\/keyboardkitpro\/keyboardlocale","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"KeyboardLocale"}],"abstract":[{"text":"This enum defines KeyboardKit-supported locales and is a","type":"text"},{"type":"text","text":" "},{"text":"namespace for locale-elated types.","type":"text"}],"title":"KeyboardLocale","role":"symbol","navigatorTitle":[{"text":"KeyboardLocale","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/ButtonStyle":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ButtonStyle","kind":"identifier"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboard\/buttonstyle","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ButtonStyle","navigatorTitle":[{"kind":"identifier","text":"ButtonStyle"}],"title":"Keyboard.ButtonStyle","abstract":[{"text":"This style can be used to modify the visual style of","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the various "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Button"},{"text":" components.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SystemKeyboard":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SystemKeyboard"}],"navigatorTitle":[{"text":"SystemKeyboard","kind":"identifier"}],"title":"SystemKeyboard","kind":"symbol","abstract":[{"text":"This keyboard can be used to mimic a native iOS keyboard.","type":"text"}],"role":"symbol","url":"\/documentation\/keyboardkitpro\/systemkeyboard","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboard","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/ButtonShadow":{"role":"symbol","abstract":[{"type":"text","text":"This view mimics a native keyboard button shadow."}],"navigatorTitle":[{"kind":"identifier","text":"ButtonShadow"}],"title":"Keyboard.ButtonShadow","url":"\/documentation\/keyboardkitpro\/keyboard\/buttonshadow","kind":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ButtonShadow","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ButtonShadow"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardSettings":{"title":"KeyboardSettings","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings","abstract":[{"text":"This observable class can be used to manage settings for","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","isActive":true,"type":"reference"},{"type":"text","text":" namespace."}],"url":"\/documentation\/keyboardkitpro\/keyboardsettings","navigatorTitle":[{"text":"KeyboardSettings","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"KeyboardSettings","kind":"identifier"}],"role":"symbol","type":"topic"},"inputtoolbar-ipad":{"alt":"Input Row in iPad","variants":[{"traits":["1x","light"],"url":"\/images\/inputtoolbar-ipad.png"}],"identifier":"inputtoolbar-ipad","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/InputToolbarDisplayMode":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/InputToolbarDisplayMode","kind":"symbol","title":"Keyboard.InputToolbarDisplayMode","type":"topic","navigatorTitle":[{"text":"InputToolbarDisplayMode","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboard\/inputtoolbardisplaymode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"InputToolbarDisplayMode"}],"role":"symbol","abstract":[{"type":"text","text":"This enum defines input toolbar display modes, which"},{"type":"text","text":" "},{"type":"text","text":"can be used to add an input toolbar to e.g. a system"},{"text":" ","type":"text"},{"text":"keyboard component.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/KeyboardType":{"title":"Keyboard.KeyboardType","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardType"}],"url":"\/documentation\/keyboardkitpro\/keyboard\/keyboardtype","role":"symbol","abstract":[{"text":"This enum defines various keyboard types, of which a","type":"text"},{"type":"text","text":" "},{"type":"text","text":"few are already implemented by the library."}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/KeyboardType","navigatorTitle":[{"text":"KeyboardType","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardSettings/isAutocapitalizationEnabled":{"kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardsettings\/isautocapitalizationenabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isAutocapitalizationEnabled"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[],"role":"symbol","title":"isAutocapitalizationEnabled","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/isAutocapitalizationEnabled","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback":{"abstract":[{"text":"This namespace contains feedback-related types.","type":"text"}],"navigatorTitle":[{"text":"Feedback","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback","role":"symbol","title":"Feedback","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Feedback"}],"url":"\/documentation\/keyboardkitpro\/feedback","type":"topic","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/settings":{"title":"settings","abstract":[{"text":"The default set of keyboard-specific settings.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"settings"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A0V","text":"Keyboard","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"s:14KeyboardKitPro0A0V8SettingsC","kind":"typeIdentifier","text":"Settings"}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/settings","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/settings","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardBehavior":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"KeyboardBehavior","kind":"identifier"}],"role":"symbol","title":"KeyboardBehavior","navigatorTitle":[{"text":"KeyboardBehavior","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"This protocol can be implemented by any classes that can","type":"text"},{"type":"text","text":" "},{"text":"define keyboard-specific behaviors.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardbehavior","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardBehavior"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/CalloutContext":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CalloutContext"}],"url":"\/documentation\/keyboardkitpro\/calloutcontext","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"CalloutContext","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutContext","title":"CalloutContext","abstract":[{"text":"This class has observable, callout-related state.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/locale":{"title":"locale","type":"topic","abstract":[{"type":"text","text":"The locale that is currently being used."}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"locale"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Locale","preciseIdentifier":"s:10Foundation6LocaleV"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/locale","url":"\/documentation\/keyboardkitpro\/keyboardcontext\/locale"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Text-Input-Article":{"kind":"article","images":[{"type":"card","identifier":"Page.png"}],"title":"Text Input Support","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit text input engine."}],"url":"\/documentation\/keyboardkitpro\/text-input-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Status-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","kind":"article","type":"topic","title":"Status","abstract":[{"text":"This article describes the KeyboardKit status engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/status-article","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"nextkeyboardbutton":{"alt":"NextKeyboardButton","variants":[{"url":"\/images\/nextkeyboardbutton.jpg","traits":["1x","light"]}],"identifier":"nextkeyboardbutton","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardStyleProvider":{"kind":"symbol","navigatorTitle":[{"text":"KeyboardStyleProvider","kind":"identifier"}],"title":"KeyboardStyleProvider","role":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyleProvider","url":"\/documentation\/keyboardkitpro\/keyboardstyleprovider","abstract":[{"type":"text","text":"This protocol can be implemented by any classes that can"},{"type":"text","text":" "},{"text":"provide dynamic keyboard styles.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"KeyboardStyleProvider","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/AppearanceViewModifier":{"type":"topic","title":"Keyboard.AppearanceViewModifier","url":"\/documentation\/keyboardkitpro\/keyboard\/appearanceviewmodifier","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/AppearanceViewModifier","role":"symbol","abstract":[{"type":"text","text":"This view modifier can be used to apply a light or dark"},{"type":"text","text":" "},{"text":"keyboard appearance to a text input.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AppearanceViewModifier"}],"navigatorTitle":[{"kind":"identifier","text":"AppearanceViewModifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Device-Article":{"kind":"article","title":"Device Utilities","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit device utilities."}],"url":"\/documentation\/keyboardkitpro\/device-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/keyboardType":{"abstract":[{"type":"text","text":"The keyboard type that is currently used."}],"role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardcontext\/keyboardtype","title":"keyboardType","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"keyboardType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Keyboard","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V"},{"kind":"text","text":"."},{"preciseIdentifier":"s:14KeyboardKitPro0A0V0A4TypeO","text":"KeyboardType","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/keyboardType"},"emojikeyboard":{"identifier":"emojikeyboard","alt":"Emoji Keyboard","type":"image","variants":[{"url":"\/images\/emojikeyboard.jpg","traits":["1x","light"]}]},"https://github.com/KeyboardKit/KeyboardKitPro":{"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","title":"KeyboardKit Pro","type":"link","url":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","titleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUI/View/keyboardAppearance(_:)":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/View\/keyboardAppearance(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"keyboardAppearance","kind":"identifier"},{"kind":"text","text":"("},{"text":"ColorScheme","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI11ColorSchemeO"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"}],"kind":"symbol","abstract":[{"type":"text","text":"This view modifier can be used to apply a light or dark"},{"text":" ","type":"text"},{"type":"text","text":"keyboard appearance to a text input."}],"url":"\/documentation\/keyboardkitpro\/swiftui\/view\/keyboardappearance(_:)","title":"keyboardAppearance(_:)","type":"topic","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy-Article":{"kind":"article","images":[{"type":"card","identifier":"Page.png"}],"title":"Proxy Utilities","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","url":"\/documentation\/keyboardkitpro\/proxy-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit proxy engine and its utilities."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction":{"kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardaction","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"KeyboardAction","kind":"identifier"}],"title":"KeyboardAction","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardAction"}],"abstract":[{"text":"This enum defines keyboard-specific actions, and is also","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"serving as a namespace for keyboard action-related types."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Styling-Article":{"kind":"article","images":[{"identifier":"Page.png","type":"card"}],"title":"Styling","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","url":"\/documentation\/keyboardkitpro\/styling-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit styling engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUI/View/keyboardToolbarStyle(_:)":{"title":"keyboardToolbarStyle(_:)","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/View\/keyboardToolbarStyle(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"keyboardToolbarStyle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Keyboard","preciseIdentifier":"s:14KeyboardKitPro0A0V"},{"kind":"text","text":"."},{"text":"ToolbarStyle","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V12ToolbarStyleV"},{"text":") -> ","kind":"text"},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"kind":"symbol","abstract":[{"text":"Apply a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ToolbarStyle"},{"type":"text","text":"."}],"url":"\/documentation\/keyboardkitpro\/swiftui\/view\/keyboardtoolbarstyle(_:)","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/textDocumentProxy":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/textDocumentProxy","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The text document proxy that is currently active."}],"type":"topic","title":"textDocumentProxy","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"textDocumentProxy","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextDocumentProxy","preciseIdentifier":"c:objc(pl)UITextDocumentProxy"}],"url":"\/documentation\/keyboardkitpro\/keyboardcontext\/textdocumentproxy"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/nextKeyboard":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/nextKeyboard","title":"KeyboardAction.nextKeyboard","url":"\/documentation\/keyboardkitpro\/keyboardaction\/nextkeyboard","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A system keyboard switcher that triggers on release and long press."}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextKeyboard","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AutocompleteContext":{"navigatorTitle":[{"text":"AutocompleteContext","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutocompleteContext","kind":"identifier"}],"abstract":[{"type":"text","text":"This class has observable, autocomplete-related state."}],"url":"\/documentation\/keyboardkitpro\/autocompletecontext","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteContext","kind":"symbol","title":"AutocompleteContext"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/InputToolbarDisplayMode/automatic":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"automatic","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Keyboard","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V23InputToolbarDisplayModeO","text":"InputToolbarDisplayMode"}],"title":"automatic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/InputToolbarDisplayMode\/automatic","url":"\/documentation\/keyboardkitpro\/keyboard\/inputtoolbardisplaymode\/automatic","abstract":[{"text":"This mode can be used to apply the default mode.","type":"text"}],"role":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Colors-Article":{"kind":"article","images":[{"identifier":"Page.png","type":"card"}],"title":"Colors","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Colors-Article","abstract":[{"text":"This article describes the KeyboardKit color engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/colors-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/App-Article":{"kind":"article","images":[{"identifier":"Page.png","type":"card"}],"title":"App Utilities","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","url":"\/documentation\/keyboardkitpro\/app-article","abstract":[{"text":"This article describes the KeyboardKit app-specific utilities.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/FeedbackSettings":{"type":"topic","title":"FeedbackSettings","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FeedbackSettings"}],"url":"\/documentation\/keyboardkitpro\/feedbacksettings","role":"symbol","abstract":[{"type":"text","text":"This observable class can be used to manage settings for"},{"type":"text","text":" "},{"text":"the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback","isActive":true,"type":"reference"},{"type":"text","text":" namespace."}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/FeedbackSettings","navigatorTitle":[{"text":"FeedbackSettings","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards-Article":{"kind":"article","images":[{"type":"card","identifier":"Page.png"}],"title":"External Keyboards","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","url":"\/documentation\/keyboardkitpro\/external-keyboards-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit external keyboard engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Images-Article":{"kind":"article","images":[{"type":"card","identifier":"Page.png"}],"title":"Images","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Images-Article","url":"\/documentation\/keyboardkitpro\/images-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit keyboard image engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts":{"abstract":[{"type":"text","text":"This namespace contains callout-related types."}],"kind":"symbol","role":"symbol","title":"Callouts","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Callouts"}],"url":"\/documentation\/keyboardkitpro\/callouts","type":"topic","navigatorTitle":[{"text":"Callouts","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete-Article":{"kind":"article","images":[{"identifier":"Page.png","type":"card"}],"title":"Autocomplete","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","url":"\/documentation\/keyboardkitpro\/autocomplete-article","abstract":[{"text":"This article describes the KeyboardKit autocomplete engine.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation-Article":{"kind":"article","title":"Dictation","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","url":"\/documentation\/keyboardkitpro\/dictation-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","url":"\/documentation\/keyboardkitpro\/keyboard","title":"Keyboard","type":"topic","abstract":[{"type":"text","text":"This namespace contains essential keyboard-related types."}],"role":"symbol","navigatorTitle":[{"text":"Keyboard","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Keyboard"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/ToggleToolbar":{"title":"Keyboard.ToggleToolbar","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ToggleToolbar","abstract":[{"type":"text","text":"This view can be used to toggle between two toolbars."}],"url":"\/documentation\/keyboardkitpro\/keyboard\/toggletoolbar","navigatorTitle":[{"text":"ToggleToolbar","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"ToggleToolbar","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Toolbar":{"title":"Keyboard.Toolbar","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboard\/toolbar","role":"symbol","navigatorTitle":[{"text":"Toolbar","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Toolbar","abstract":[{"text":"This view can be used to render a toolbar with a min","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"height, to ensure that callouts are not cut off."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Toolbar"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/EmojiKeyboard":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboard","url":"\/documentation\/keyboardkitpro\/emojikeyboard","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"EmojiKeyboard"}],"abstract":[{"type":"text","text":"This view mimics a native emoji keyboard."}],"role":"symbol","title":"EmojiKeyboard","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EmojiKeyboard"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation":{"abstract":[{"text":"This namespace contains dictation-related types.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Dictation"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation","url":"\/documentation\/keyboardkitpro\/dictation","navigatorTitle":[{"text":"Dictation","kind":"identifier"}],"title":"Dictation","role":"symbol"},"systemkeyboard-styled":{"identifier":"systemkeyboard-styled","type":"image","alt":"SystemKeyboard","variants":[{"traits":["1x","light"],"url":"\/images\/systemkeyboard-styled.jpg"}]},"systemkeyboardpreview-theme":{"alt":"System Keyboard Preview","variants":[{"traits":["1x","light"],"url":"\/images\/systemkeyboardpreview-theme.jpg"}],"identifier":"systemkeyboardpreview-theme","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","kind":"article","type":"topic","abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"title":"Actions","url":"\/documentation\/keyboardkitpro\/actions-article","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SystemKeyboardPreview":{"title":"SystemKeyboardPreview","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboardPreview","abstract":[{"text":"This view can preview how ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboard","type":"reference","isActive":true},{"text":" will render","type":"text"},{"type":"text","text":" "},{"text":"for some services, configurations and ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme","isActive":true},{"type":"text","text":"s."}],"kind":"symbol","url":"\/documentation\/keyboardkitpro\/systemkeyboardpreview","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"SystemKeyboardPreview","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SystemKeyboardPreview","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardContext"}],"url":"\/documentation\/keyboardkitpro\/keyboardcontext","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"KeyboardContext","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext","title":"KeyboardContext","abstract":[{"text":"This class has observable, keyboard-related state.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUI/View/keyboardInputToolbarDisplayMode(_:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"keyboardInputToolbarDisplayMode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Keyboard","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V23InputToolbarDisplayModeO","text":"InputToolbarDisplayMode"},{"kind":"text","text":") -> "},{"text":"some","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"}],"url":"\/documentation\/keyboardkitpro\/swiftui\/view\/keyboardinputtoolbardisplaymode(_:)","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/View\/keyboardInputToolbarDisplayMode(_:)","title":"keyboardInputToolbarDisplayMode(_:)","role":"symbol","abstract":[{"type":"text","text":"Apply an "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/InputToolbarDisplayMode","isActive":true},{"type":"text","text":" to the"},{"text":" ","type":"text"},{"text":"view hierarchy.","type":"text"}]},"keyboardtoggletoolbar":{"identifier":"keyboardtoggletoolbar","alt":"ToggleToolbar","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/keyboardtoggletoolbar.jpg"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Themes-Article":{"images":[{"identifier":"Page.png","type":"card"}],"title":"Themes","abstract":[{"text":"This article describes the KeyboardKit theme engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/themes-article","kind":"article","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"kind":"article","images":[{"type":"card","identifier":"Page.png"}],"title":"Layout","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}],"url":"\/documentation\/keyboardkitpro\/layout-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","kind":"article","type":"topic","title":"Emojis","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"url":"\/documentation\/keyboardkitpro\/emojis-article","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"systemkeyboard-swedish":{"alt":"System Keyboard in Swedish","variants":[{"traits":["1x","light"],"url":"\/images\/systemkeyboard-swedish.jpg"}],"identifier":"systemkeyboard-swedish","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Foundation":{"abstract":[],"title":"Foundation","type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Foundation","url":"\/documentation\/keyboardkitpro\/foundation","role":"collection"},"inputtoolbar-ipadpro":{"identifier":"inputtoolbar-ipadpro","alt":"Input Row in iPad","type":"image","variants":[{"url":"\/images\/inputtoolbar-ipadpro.png","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/services":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","title":"services","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"services","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V","text":"Keyboard"},{"kind":"text","text":"."},{"text":"Services","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V8ServicesC"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/services","abstract":[{"type":"text","text":"The default set of keyboard-specific services."}],"kind":"symbol"},"systemkeyboardbottomrow":{"alt":"System Keyboard Bottom Row","variants":[{"traits":["1x","light"],"url":"\/images\/systemkeyboardbottomrow.jpg"}],"identifier":"systemkeyboardbottomrow","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Diacritic":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Diacritic","url":"\/documentation\/keyboardkitpro\/keyboard\/diacritic","title":"Keyboard.Diacritic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Diacritic"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Diacritic"}],"abstract":[{"type":"text","text":"This struct can be used to define diacritics for any"},{"type":"text","text":" "},{"text":"keyboard and locale.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"kind":"article","images":[{"identifier":"Page.png","type":"card"}],"title":"Localization","role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","abstract":[{"text":"This article describes the KeyboardKit localization engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/localization-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/DictationSettings":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DictationSettings"}],"url":"\/documentation\/keyboardkitpro\/dictationsettings","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationSettings","abstract":[{"type":"text","text":"This observable class can be used to manage settings for"},{"text":" ","type":"text"},{"type":"text","text":"the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation","type":"reference","isActive":true},{"type":"text","text":" namespace."}],"type":"topic","kind":"symbol","title":"DictationSettings","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DictationSettings","kind":"identifier"}]},"systemkeyboard-english":{"identifier":"systemkeyboard-english","type":"image","alt":"SystemKeyboard","variants":[{"traits":["1x","light"],"url":"\/images\/systemkeyboard-english.jpg"}]},"systemkeyboardbuttonpreview":{"alt":"Keyboard Button","variants":[{"traits":["1x","light"],"url":"\/images\/systemkeyboardbuttonpreview.jpg"}],"identifier":"systemkeyboardbuttonpreview","type":"image"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":[{"title":"Features","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Colors-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Images-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"value":"KeyboardInputViewController","op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title"},{"value":[{"kind":"identifier","text":"KeyboardInputViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}