{"kind":"article","hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","interfaceLanguage":"swift"},"metadata":{"role":"article","images":[{"identifier":"Page.png","type":"card"}],"title":"Essentials","color":{"standardColorIdentifier":"blue"},"roleHeading":"Article","modules":[{"name":"KeyboardKitPro"}]},"seeAlsoSections":[{"title":"Features","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"anchor":"Features","generated":true}],"abstract":[{"type":"text","text":"This article describes the essential parts of KeyboardKit."}],"primaryContentSections":[{"kind":"content","content":[{"level":2,"text":"Overview","type":"heading","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit extends Apple’s native keyboard APIs and provides you with a lot more functionality. It lets you mimic a native iOS keyboard and tweak its style and behavior, or create completely custom keyboards."}]},{"inlineContent":[{"text":"KeyboardKit has a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView"},{"text":" view that mimics the native iOS keyboard. It can be customized and styled to great extent, and lets you replace any key content or key view of any action.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"👑 ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro"},{"text":" unlocks a lot of essential Pro features. Information about Pro features can be found at the end of this article.","type":"text"}]},{"level":2,"anchor":"Namespaces","type":"heading","text":"Namespaces"},{"inlineContent":[{"text":"KeyboardKit uses namespaces to make the API surface smaller, by nesting types in logical groups.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has other namespaces as well, for more specific capabilities, like "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","type":"reference"},{"text":", ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout","isActive":true},{"type":"text","text":", "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts","isActive":true,"type":"reference"},{"type":"text","text":", "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation","type":"reference","isActive":true},{"text":", ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback","type":"reference"},{"type":"text","text":", etc."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Namespaces will not contain protocols, nor important types that are meant to be exposed as top-level types. This includes essential types like "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","isActive":true},{"type":"text","text":", context and settings types like "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext","type":"reference"},{"text":" and ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings","isActive":true,"type":"reference"},{"text":", and important components like ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView"},{"type":"text","text":"."}]},{"level":2,"anchor":"Keyboard-Namespace","text":"Keyboard Namespace","type":"heading"},{"inlineContent":[{"text":"The ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard"},{"text":" namespace contains a lot of essential, keyboard-related types and views. By typing ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","type":"reference"},{"type":"text","text":" and "},{"type":"codeVoice","code":"."},{"type":"text","text":", Xcode will list all essential types within this namespace."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The namespace has a lot of essential types, like "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Accent","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/AutocapitalizationType","type":"reference","isActive":true},{"text":", ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/BackspaceRange","isActive":true},{"type":"text","text":", "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Case","type":"reference","isActive":true},{"type":"text","text":", "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Diacritic","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Gesture","isActive":true},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/InputToolbarDisplayMode"},{"text":", ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/KeyboardType","isActive":true},{"type":"text","text":", "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ReturnKeyType","type":"reference","isActive":true},{"text":", etc.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The namespace also has a lot of view-related types, like "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Background"},{"type":"text","text":", "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Button","isActive":true},{"text":", ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ButtonStyle"},{"type":"text","text":", "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/NextKeyboardButton","type":"reference","isActive":true},{"type":"text","text":", "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/SpaceContent","isActive":true},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Toolbar"},{"type":"text","text":", etc."}]},{"level":2,"anchor":"Keyboard-Controller","type":"heading","text":"Keyboard Controller"},{"inlineContent":[{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","isActive":true,"type":"reference"},{"type":"text","text":" is the most essential type in the library. Just make your "},{"inlineContent":[{"text":"KeyboardController","type":"text"}],"type":"strong"},{"type":"text","text":" inherit this class to get access to a bunch of additional capabilities and view lifecycle functions."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","type":"reference"},{"type":"text","text":" defines shared "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/settings","isActive":true,"type":"reference"},{"type":"text","text":", and "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state"},{"text":" properties, that can be used to avoid relying on the controller within your code.","type":"text"}]},{"inlineContent":[{"type":"text","text":"KeyboardKit also has a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardController","isActive":true,"type":"reference"},{"type":"text","text":" protocol that aims to make it easier to use KeyboardKit in other platforms than UIKit."}],"type":"paragraph"},{"type":"heading","text":"Keyboard Context","level":2,"anchor":"Keyboard-Context"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit has a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext","type":"reference"},{"type":"text","text":" that provides observable keyboard state that keeps the keyboard UI up to date. It has a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/textDocumentProxy","isActive":true},{"type":"text","text":" reference, lets you get and set "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/locale"},{"type":"text","text":", "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/keyboardType"},{"text":", etc.","type":"text"}]},{"inlineContent":[{"text":"Other namespaces define other context types, like ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteContext"},{"type":"text","text":", "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutContext","isActive":true,"type":"reference"},{"type":"text","text":", "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationContext","isActive":true},{"type":"text","text":", etc. They will all automatically update the keyboard, provided that the keyboard view observes them."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit automatically creates instances of these classes and injects them into ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state"},{"text":", and syncs with the controller when needed.","type":"text"}]},{"level":2,"text":"Keyboard Settings","type":"heading","anchor":"Keyboard-Settings"},{"inlineContent":[{"text":"KeyboardKit has a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings"},{"type":"text","text":" class that has a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/store","isActive":true},{"type":"text","text":" that is used to persist all persisted properties in all contexts. When you set up KeyboardKit with a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp"},{"type":"text","text":" that defines an App Group, the store will automatically be set up to sync data between your app and its keyboard extension."}],"type":"paragraph"},{"content":[{"inlineContent":[{"text":"","type":"text"},{"code":"@AppStorage","type":"codeVoice"},{"text":" properties use the store that’s available when they’re first accessed. Make sure to set up a custom store BEFORE accessing any of these settings properties.","type":"text"}],"type":"paragraph"}],"type":"aside","name":"Important","style":"important"},{"anchor":"Keyboard-Behavior","level":2,"type":"heading","text":"Keyboard Behavior"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardBehavior","isActive":true,"type":"reference"},{"text":" protocol that can be used to define the keyboard’s behavior. It’s used by some services, like the standard ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler","type":"reference","isActive":true},{"type":"text","text":", to make behavior-based decisions."}]},{"inlineContent":[{"type":"text","text":"KeyboardKit automatically creates an instance of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/StandardBehavior"},{"type":"text","text":" and injects it into "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services"},{"text":". You can replace it at any time, by implementing the procotol from scratch or by inheriting and customizing the standard behavior.","type":"text"}],"type":"paragraph"},{"text":"Keyboard Styling","anchor":"Keyboard-Styling","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","isActive":true},{"text":" article describes how to use a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyleService","isActive":true},{"text":" to style the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView"},{"text":" in flexible ways.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Various views have separate styles as well, that can be applied with specific view modifiers."}],"type":"paragraph"},{"text":"Keyboard-related Extensions","type":"heading","level":2,"anchor":"Keyboard-related-Extensions"},{"inlineContent":[{"type":"text","text":"KeyboardKit extends native types with keyboard-specific functionality like autocomplete, text analysis, etc. Check the extension section in the bottom of the documentation root for more info."}],"type":"paragraph"},{"level":2,"text":"Keyboard View","type":"heading","anchor":"Keyboard-View"},{"inlineContent":[{"type":"text","text":"KeyboardKit has a "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","type":"reference"},{"type":"text","text":" that mimics a native iOS keyboard. It can be used for alphabetic, numeric & symbolic keyboards, supports all supported locales, layouts, callouts, etc., and can be styled to great extent with styles & themes:"}],"type":"paragraph"},{"numberOfColumns":3,"columns":[{"size":1,"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"keyboardview-english"}]}]},{"size":1,"content":[{"type":"paragraph","inlineContent":[{"identifier":"keyboardview-swedish","type":"image"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"keyboardview-styled"}]}],"size":1}],"type":"row"},{"inlineContent":[{"text":"The view can be customized to great extent. You can pass in custom services & state, and replace any button or entire sub-component:","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["KeyboardView(","    controller: controller,             \/\/ You can pass in a controller, or specific states and services","    buttonContent: { $0.view },         \/\/ You can customize the content view of any button","    buttonView: { $0.view },            \/\/ You can customize the entire view of any button","    emojiKeyboard: { $0.view },         \/\/ You can customize the emoji keyboard, if any","    toolbar: { params in params.view }  \/\/ You can customize the toolbar above the keyboard",")"]},{"inlineContent":[{"type":"text","text":"Just return "},{"type":"codeVoice","code":"{ $0.view }"},{"type":"text","text":" or "},{"code":"{ params in params.view }","type":"codeVoice"},{"type":"text","text":" to use the standard view, or return a custom view for any part of the keyboard. Each view builder provides you with view-related parameters with contextual information."}],"type":"paragraph"},{"type":"heading","anchor":"Views","level":2,"text":"Views"},{"inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","isActive":true,"type":"reference"},{"type":"text","text":" namespace has a lot of views, styles, and view-related types:"}],"type":"paragraph"},{"type":"tabNavigator","tabs":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","isActive":true},{"type":"text","text":" that mimics a native iOS keyboard and that can be customized to great extent. Read more above."}]},{"type":"row","numberOfColumns":5,"columns":[{"content":[],"size":1},{"size":3,"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"keyboardview-english"}]}]},{"size":1,"content":[]}]}],"title":"KeyboardView"},{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","isActive":true},{"text":" namespace has a set of keyboard ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Button"},{"type":"text","text":" views and styles that can be used to mimic all parts of a native keyboard, as well as their gestures. A "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Button","isActive":true},{"text":" renders the full button, while other views like ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ButtonShadow","type":"reference"},{"text":" (not shown here) renders parts of it.","type":"text"}],"type":"paragraph"},{"type":"row","numberOfColumns":5,"columns":[{"size":1,"content":[]},{"content":[{"inlineContent":[{"identifier":"keyboardbuttonpreview","type":"image"}],"type":"paragraph"}],"size":3},{"size":1,"content":[]}]}],"title":"Button"},{"title":"BottomRow","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard"},{"type":"text","text":" namespace has a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/BottomRow","isActive":true},{"text":" that just render a bottom keyboard row, with the same behavior as a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","isActive":true,"type":"reference"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"identifier":"keyboard-bottomrow","type":"image"}]}]},{"title":"Keyboard Switcher","content":[{"inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard"},{"text":" namespace has a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/NextKeyboardButton","isActive":true},{"text":" that works as a native keyboard switcher. It switches to the next system keyboard on tap and shows a popover menu with all available keyboards on long press.","type":"text"}],"type":"paragraph"},{"numberOfColumns":3,"type":"row","columns":[{"content":[],"size":1},{"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"keyboard-nextkeyboardbutton"}]}],"size":1},{"content":[],"size":1}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard"},{"text":" namespace has a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/NumberPad"},{"type":"text","text":" that mimics a native number pad keyboard. The "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","isActive":true},{"type":"text","text":" automatically adds a number pad above itself when the "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/KeyboardType\/numberPad","type":"reference"},{"type":"text","text":" keyboard type is selected."}],"type":"paragraph"},{"type":"row","numberOfColumns":5,"columns":[{"content":[],"size":1},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"keyboard-numberpad","type":"image"}]}],"size":3},{"size":1,"content":[]}]}],"title":"NumberPad"},{"title":"Toolbar","content":[{"inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","type":"reference","isActive":true},{"type":"text","text":" namespace has a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Toolbar","isActive":true,"type":"reference"},{"text":" view that applies a minimum height to its content. KeyboardKit will by default always add a toolbar to the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","type":"reference"},{"text":" to avoid callouts from being cut off, since custom keyboards can’t render outside of the frame.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"identifier":"keyboardtoolbar","type":"image"}],"type":"paragraph"}]}]},{"anchor":"View-Styling","type":"heading","level":2,"text":"View Styling"},{"inlineContent":[{"type":"text","text":"Most views have a corresponding style, which can be used to style it, much like SwiftUI’s "},{"type":"codeVoice","code":"Button"},{"type":"text","text":" has a "},{"code":"ButtonStyle","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":".buttonStyle(...)"},{"type":"text","text":" view modifier, that can be applied to an individual button, or an entire view hierarchy."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"In KeyboardKit, a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","type":"reference","isActive":true},{"type":"text","text":"."},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Button","isActive":true,"type":"reference"},{"type":"text","text":" has a "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ButtonStyle","type":"reference"},{"type":"text","text":" that can be applied with a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/keyboardButtonStyle(_:)","isActive":true},{"text":" view modifier. The ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Toolbar"},{"type":"text","text":" has a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ToolbarStyle","isActive":true,"type":"reference"},{"text":" and a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/keyboardToolbarStyle(_:)","isActive":true},{"type":"text","text":" view modifier, etc."}],"type":"paragraph"},{"inlineContent":[{"text":"When you use a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","isActive":true,"type":"reference"},{"type":"text","text":", you must however use the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyleService","type":"reference","isActive":true},{"text":" concept instead, since the keyboard view is so complex. You can however apply explicit styles within the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","type":"reference","isActive":true},{"text":"’s various view builder parameters.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"See the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article"},{"text":" article for more information.","type":"text"}]},{"text":"👑 KeyboardKit Pro","level":2,"anchor":"%F0%9F%91%91-KeyboardKit-Pro","type":"heading"},{"type":"paragraph","inlineContent":[{"overridingTitleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","overridingTitle":"KeyboardKit Pro"},{"type":"text","text":" unlocks additional, powerful "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","isActive":true,"type":"reference"},{"type":"text","text":" capabilities, including full support for all "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale","isActive":true},{"type":"text","text":"s, a full-blown "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboard","isActive":true,"type":"reference"},{"type":"text","text":", input toolbars, powerful "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardViewPreview","type":"reference","isActive":true},{"type":"text","text":"s, etc."}]},{"type":"heading","text":"Views","anchor":"Views","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks additional "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard"},{"type":"text","text":"-related views and utilities, that make it easier to create even more powerful keyboards:"}]},{"tabs":[{"title":"Localization","content":[{"inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks localized services for all supported "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale"},{"type":"text","text":"s, which lets you create fully localized keyboard views that automatically shows the correct buttons, autocomplete suggestions, and callout actions."}],"type":"paragraph"},{"columns":[{"size":1,"content":[]},{"size":3,"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"keyboardview-swedish"}]}]},{"size":1,"content":[]}],"type":"row","numberOfColumns":5},{"inlineContent":[{"type":"text","text":"The various license tiers unlock different amount of "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale","isActive":true,"type":"reference"},{"text":"s, where Gold unlocks all. Read more in the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","isActive":true},{"type":"text","text":" article."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboard"},{"text":", which is automatically added to ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","isActive":true},{"type":"text","text":" when a valid license is registered."}]},{"columns":[{"content":[],"size":1},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"emojikeyboard","type":"image"}]}],"size":3},{"content":[],"size":1}],"numberOfColumns":5,"type":"row"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The keyboard has support for categories, runtime version adjustments and skintones. Read more about this in the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article"},{"type":"text","text":" article."}]}],"title":"Emoji Keyboard"},{"content":[{"inlineContent":[{"type":"text","text":"KeyboardKit Pro will automatically add an additional input toolbar above "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","type":"reference","isActive":true},{"text":" on large iPad devices, which makes it easy to insert numeric values without switching keyboard type.","type":"text"}],"type":"paragraph"},{"numberOfColumns":5,"columns":[{"size":1,"content":[]},{"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"inputtoolbar-ipad"}]}],"size":3},{"size":1,"content":[]}],"type":"row"},{"inlineContent":[{"type":"text","text":"You can apply a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/keyboardInputToolbarDisplayMode(_:)"},{"type":"text","text":" modifier to the keyboard view to control whether to show or hide the toolbar on all device types, or to customize the buttons on the input keyboard."}],"type":"paragraph"}],"title":"Input Toolbar"},{"title":"Toggle Toolbar","content":[{"inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ToggleToolbar","type":"reference","isActive":true},{"type":"text","text":" can be used to toggle between two toolbars, e.g. to place a main menu “behind” the autocomplete toolbar:"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"keyboardtoggletoolbar"}]},{"inlineContent":[{"type":"text","text":"This view wraps itself in a "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Toolbar","type":"reference"},{"type":"text","text":", which means that it can also be styled with the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/keyboardToolbarStyle(_:)"},{"type":"text","text":" modifier."}],"type":"paragraph"}]}],"type":"tabNavigator"},{"text":"Previews","anchor":"Previews","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro also unlocks "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard"},{"text":"-related previews, that can be used to preview ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","isActive":true,"type":"reference"},{"type":"text","text":" and "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","isActive":true},{"type":"text","text":"."},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Button","type":"reference","isActive":true},{"type":"text","text":" for various configurations, locales, styles, themes, etc."}]},{"tabs":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardViewPreview","isActive":true},{"text":" that can preview the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","isActive":true},{"text":" for various locales, styles, themes, etc.","type":"text"}]},{"type":"row","numberOfColumns":3,"columns":[{"content":[{"inlineContent":[{"identifier":"keyboardview-swedish","type":"image"}],"type":"paragraph"}],"size":1},{"size":1,"content":[{"inlineContent":[{"identifier":"keyboardviewpreview","type":"image"}],"type":"paragraph"}]},{"size":1,"content":[{"inlineContent":[{"type":"image","identifier":"keyboardviewpreview-theme"}],"type":"paragraph"}]}]}],"title":"Keyboard View"},{"content":[{"inlineContent":[{"type":"text","text":"KeyboardKit Pro also unlocks a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard"},{"type":"text","text":"."},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ButtonPreview","type":"reference","isActive":true},{"text":" view that can be used to preview a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","isActive":true},{"type":"text","text":"."},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Button"},{"type":"text","text":", which is a lot more performant than the full "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardViewPreview"},{"type":"text","text":"."}],"type":"paragraph"},{"type":"row","numberOfColumns":5,"columns":[{"size":1,"content":[]},{"size":3,"content":[{"inlineContent":[{"identifier":"keyboardbuttonpreview","type":"image"}],"type":"paragraph"}]},{"size":1,"content":[]}]}],"title":"Keyboard Button"}],"type":"tabNavigator"},{"type":"paragraph","inlineContent":[{"text":"These previews can be used in the main application, to show users how the keyboard will look for different settings, styles, themes, etc.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"You can read more about previews in the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article"},{"type":"text","text":" article."}]}]}],"variants":[{"paths":["\/documentation\/keyboardkitpro\/essentials-article"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkitpro\/essentials-article"]}],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","title":"Localization","role":"article","type":"topic","kind":"article","abstract":[{"text":"This article describes the KeyboardKit localization engine.","type":"text"}],"images":[{"identifier":"Page.png","type":"card"}],"url":"\/documentation\/keyboardkitpro\/localization-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Host-Article":{"images":[{"identifier":"Page.png","type":"card"}],"role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/host-article","abstract":[{"type":"text","text":"This article describes how KeyboardKit can identify the host application."}],"title":"Host Utilities"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","url":"\/documentation\/keyboardkitpro\/keyboardapp","navigatorTitle":[{"kind":"identifier","text":"KeyboardApp"}],"title":"KeyboardApp","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"This type can be used to define important app properties,"},{"text":" ","type":"text"},{"type":"text","text":"and is also a namespace for KeyboardKit Pro app features."}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardApp"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext":{"url":"\/documentation\/keyboardkitpro\/keyboardcontext","title":"KeyboardContext","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext","abstract":[{"text":"This class has observable states and persistent settings.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"KeyboardContext","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"KeyboardContext","kind":"identifier"}],"type":"topic"},"https://github.com/KeyboardKit/KeyboardKitPro":{"titleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"title":"KeyboardKit Pro","url":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","type":"link"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback-Article":{"images":[{"type":"card","identifier":"Page.png"}],"role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/feedback-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit feedback engine."}],"title":"Feedback"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/StandardBehavior":{"kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboard\/standardbehavior","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/StandardBehavior","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StandardBehavior"}],"navigatorTitle":[{"text":"StandardBehavior","kind":"identifier"}],"type":"topic","title":"Keyboard.StandardBehavior","abstract":[{"type":"text","text":"This class defines the standard keyboard behavior of"},{"type":"text","text":" "},{"text":"a standard western keyboard, with some locale tweaks.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","url":"\/documentation\/keyboardkitpro\/dictation-article","title":"Dictation","role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUICore/View/keyboardInputToolbarDisplayMode(_:)":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/keyboardInputToolbarDisplayMode(_:)","title":"keyboardInputToolbarDisplayMode(_:)","role":"symbol","abstract":[{"text":"Apply an ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/InputToolbarDisplayMode","type":"reference","isActive":true},{"text":" to the","type":"text"},{"type":"text","text":" "},{"text":"view hierarchy.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"keyboardInputToolbarDisplayMode","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V","text":"Keyboard"},{"text":".","kind":"text"},{"text":"InputToolbarDisplayMode","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V23InputToolbarDisplayModeO"},{"text":") -> ","kind":"text"},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}],"url":"\/documentation\/keyboardkitpro\/swiftuicore\/view\/keyboardinputtoolbardisplaymode(_:)","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Toolbar":{"kind":"symbol","abstract":[{"type":"text","text":"This view can be used to render a toolbar with a min"},{"type":"text","text":" "},{"type":"text","text":"height, to ensure that callouts are not cut off."}],"title":"Keyboard.Toolbar","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Toolbar"}],"role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboard\/toolbar","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Toolbar","navigatorTitle":[{"kind":"identifier","text":"Toolbar"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","title":"Layout","role":"article","abstract":[{"text":"This article describes the KeyboardKit layout engine.","type":"text"}],"images":[{"type":"card","identifier":"Page.png"}],"url":"\/documentation\/keyboardkitpro\/layout-article","kind":"article","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardActionHandler":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardActionHandler"}],"title":"KeyboardActionHandler","kind":"symbol","navigatorTitle":[{"text":"KeyboardActionHandler","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardactionhandler","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler","role":"symbol","abstract":[{"type":"text","text":"This protocol can be implemented by any classes that can"},{"text":" ","type":"text"},{"text":"handle triggered ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","type":"reference","isActive":true},{"type":"text","text":" events."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUICore/View/keyboardToolbarStyle(_:)":{"abstract":[{"type":"text","text":"Apply a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ToolbarStyle","isActive":true,"type":"reference"},{"text":".","type":"text"}],"title":"keyboardToolbarStyle(_:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/keyboardToolbarStyle(_:)","role":"symbol","kind":"symbol","url":"\/documentation\/keyboardkitpro\/swiftuicore\/view\/keyboardtoolbarstyle(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"keyboardToolbarStyle","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V","text":"Keyboard"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A0V12ToolbarStyleV","text":"ToolbarStyle","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"some","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Case":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Case","abstract":[{"text":"This enum defines various keyboard shift states.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboard\/case","title":"Keyboard.Case","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Case"}],"navigatorTitle":[{"kind":"identifier","text":"Case"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Accent":{"kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboard\/accent","type":"topic","abstract":[{"type":"text","text":"This is a typealias for the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Diacritic"},{"type":"text","text":" type."}],"navigatorTitle":[{"text":"Accent","kind":"identifier"}],"title":"Keyboard.Accent","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Accent","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Accent"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/KeyboardType":{"url":"\/documentation\/keyboardkitpro\/keyboard\/keyboardtype","type":"topic","title":"Keyboard.KeyboardType","role":"symbol","navigatorTitle":[{"text":"KeyboardType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"KeyboardType"}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/KeyboardType","abstract":[{"type":"text","text":"This enum defines various keyboard types, of which a"},{"type":"text","text":" "},{"type":"text","text":"few are implemented by the library."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AI-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","url":"\/documentation\/keyboardkitpro\/ai-article","title":"AI Support","role":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit AI support capabilities."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/settings":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"settings","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V","text":"Keyboard"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A0V8SettingsC","text":"Settings","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/settings","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/settings","title":"settings","role":"symbol","abstract":[{"type":"text","text":"The default set of keyboard-specific settings."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Background":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Background","url":"\/documentation\/keyboardkitpro\/keyboard\/background","abstract":[{"type":"text","text":"This background style can define the background of a"},{"text":" ","type":"text"},{"type":"text","text":"keyboard or any components within."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Background"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Background"}],"title":"Keyboard.Background"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/locale":{"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardcontext\/locale","role":"symbol","abstract":[{"type":"text","text":"The current locale."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"locale"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation6LocaleV","kind":"typeIdentifier","text":"Locale"}],"title":"locale","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/locale","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete-Article":{"images":[{"type":"card","identifier":"Page.png"}],"role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/autocomplete-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}],"title":"Autocomplete"},"keyboardtoggletoolbar":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/keyboardtoggletoolbar.jpg"}],"alt":"ToggleToolbar","identifier":"keyboardtoggletoolbar","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Styling-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","url":"\/documentation\/keyboardkitpro\/styling-article","title":"Styling","role":"article","images":[{"type":"card","identifier":"Page.png"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit styling engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/DictationContext":{"navigatorTitle":[{"kind":"identifier","text":"DictationContext"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DictationContext"}],"abstract":[{"text":"This class has observable states and persistent settings,","type":"text"},{"type":"text","text":" "},{"text":"as well as a couple of persisted properties that are not","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"considered settings, but carry state between the app and"},{"type":"text","text":" "},{"text":"its keyboard extension.","type":"text"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/dictationcontext","title":"DictationContext","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationContext"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/NextKeyboardButton":{"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NextKeyboardButton"}],"role":"symbol","title":"Keyboard.NextKeyboardButton","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/NextKeyboardButton","url":"\/documentation\/keyboardkitpro\/keyboard\/nextkeyboardbutton","kind":"symbol","abstract":[{"text":"This view makes any view behave as a native keyboard","type":"text"},{"type":"text","text":" "},{"text":"switcher button, which switches to the next keyboard","type":"text"},{"type":"text","text":" "},{"text":"when tapped, and opens a switcher menu on long press.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NextKeyboardButton"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/CalloutContext":{"url":"\/documentation\/keyboardkitpro\/calloutcontext","title":"CalloutContext","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutContext","abstract":[{"type":"text","text":"This class has observable, callout-related state."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CalloutContext","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CalloutContext"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Settings-Article":{"url":"\/documentation\/keyboardkitpro\/settings-article","kind":"article","title":"Settings","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit settings engine."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","type":"topic","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"images":[{"identifier":"Page.png","type":"card"}],"role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/actions-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit action engine."}],"title":"Actions"},"keyboard-nextkeyboardbutton":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/keyboard-nextkeyboardbutton.jpg","traits":["1x","light"]}],"alt":"NextKeyboardButton","identifier":"keyboard-nextkeyboardbutton","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback":{"abstract":[{"text":"This namespace contains feedback-related types.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Feedback"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Feedback"}],"kind":"symbol","title":"Feedback","url":"\/documentation\/keyboardkitpro\/feedback"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardView":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardView","kind":"identifier"}],"title":"KeyboardView","abstract":[{"type":"text","text":"This view can be used to mimic a native iOS keyboard."}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardView"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardview","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboard","title":"Keyboard","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Keyboard"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","abstract":[{"type":"text","text":"This namespace contains essential keyboard-related types."}],"navigatorTitle":[{"text":"Keyboard","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLocale":{"url":"\/documentation\/keyboardkitpro\/keyboardlocale","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardLocale","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"This enum defines KeyboardKit-supported locales and is a"},{"type":"text","text":" "},{"text":"namespace for locale-elated types.","type":"text"}],"title":"KeyboardLocale","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardLocale"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Device-Article":{"kind":"article","url":"\/documentation\/keyboardkitpro\/device-article","type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit device utilities."}],"title":"Device Utilities","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/InputToolbarDisplayMode":{"navigatorTitle":[{"kind":"identifier","text":"InputToolbarDisplayMode"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/InputToolbarDisplayMode","abstract":[{"text":"This enum defines input toolbar display modes, which","type":"text"},{"text":" ","type":"text"},{"text":"can be used to set how an input toolbar is displayed.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboard\/inputtoolbardisplaymode","title":"Keyboard.InputToolbarDisplayMode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"InputToolbarDisplayMode","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/textDocumentProxy":{"url":"\/documentation\/keyboardkitpro\/keyboardcontext\/textdocumentproxy","type":"topic","kind":"symbol","title":"textDocumentProxy","abstract":[{"text":"The text document proxy that is currently active.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/textDocumentProxy","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textDocumentProxy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UITextDocumentProxy","text":"UITextDocumentProxy"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","url":"\/documentation\/keyboardkitpro\/callouts-article","title":"Callouts","role":"article","images":[{"type":"card","identifier":"Page.png"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/services":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"services"},{"kind":"text","text":": "},{"text":"Keyboard","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A0V8ServicesC","text":"Services","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/services","title":"services","role":"symbol","abstract":[{"type":"text","text":"The default set of keyboard-specific services."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/ButtonPreview":{"kind":"symbol","title":"Keyboard.ButtonPreview","url":"\/documentation\/keyboardkitpro\/keyboard\/buttonpreview","type":"topic","navigatorTitle":[{"text":"ButtonPreview","kind":"identifier"}],"abstract":[{"type":"text","text":"This view can be used to preview a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Button"},{"text":" ","type":"text"},{"text":"with various actions, themes and services.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ButtonPreview"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ButtonPreview","role":"symbol"},"inputtoolbar-ipad":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/inputtoolbar-ipad.png","traits":["1x","light"]}],"alt":"Input Row in iPad","identifier":"inputtoolbar-ipad","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","url":"\/documentation\/keyboardkitpro","abstract":[{"type":"text","text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI."}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","title":"KeyboardKitPro","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AutocompleteContext":{"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteContext","abstract":[{"text":"This class has observable states and persistent settings","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"for keyboard-related autocomplete."}],"url":"\/documentation\/keyboardkitpro\/autocompletecontext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutocompleteContext"}],"navigatorTitle":[{"text":"AutocompleteContext","kind":"identifier"}],"type":"topic","kind":"symbol","title":"AutocompleteContext"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardViewPreview":{"navigatorTitle":[{"text":"KeyboardViewPreview","kind":"identifier"}],"title":"KeyboardViewPreview","role":"symbol","abstract":[{"type":"text","text":"This view can be used to preview a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","isActive":true,"type":"reference"},{"text":" with","type":"text"},{"type":"text","text":" "},{"type":"text","text":"various actions, themes and services."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardViewPreview","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"KeyboardViewPreview","kind":"identifier"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardviewpreview"},"Page.png":{"type":"image","alt":"Page icon","identifier":"Page.png","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png","traits":["1x","light"]}]},"keyboardviewpreview-theme":{"type":"image","alt":"KeyboardView Preview - Theme","identifier":"keyboardviewpreview-theme","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/keyboardviewpreview-theme.jpg","traits":["1x","light"]}]},"keyboard-bottomrow":{"type":"image","alt":"Keyboard Bottom Row","identifier":"keyboard-bottomrow","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/keyboard-bottomrow.jpg","traits":["1x","light"]}]},"keyboardview-swedish":{"type":"image","alt":"KeyboardView Preview - Swedish","identifier":"keyboardview-swedish","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/keyboardview-swedish.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Themes-Article":{"images":[{"type":"card","identifier":"Page.png"}],"role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/themes-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit Pro theme engine, which can be used to style the entire keyboard with a single theme."}],"title":"Themes"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis-Article":{"images":[{"type":"card","identifier":"Page.png"}],"role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/emojis-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"title":"Emojis"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/BackspaceRange":{"title":"Keyboard.BackspaceRange","url":"\/documentation\/keyboardkitpro\/keyboard\/backspacerange","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/BackspaceRange","abstract":[{"text":"This enum defines how much the backspace key deletes.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"BackspaceRange","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"BackspaceRange"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/NumberPad":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/NumberPad","abstract":[{"type":"text","text":"This view mimics a native number pad keyboard."}],"url":"\/documentation\/keyboardkitpro\/keyboard\/numberpad","type":"topic","title":"Keyboard.NumberPad","navigatorTitle":[{"kind":"identifier","text":"NumberPad"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NumberPad"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/ToggleToolbar":{"navigatorTitle":[{"text":"ToggleToolbar","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ToggleToolbar","abstract":[{"type":"text","text":"This view can be used to toggle between two toolbars."}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"ToggleToolbar","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboard\/toggletoolbar","kind":"symbol","role":"symbol","title":"Keyboard.ToggleToolbar"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Navigation-Article":{"title":"Navigation","abstract":[{"type":"text","text":"This article describes the KeyboardKit navigation engine."}],"type":"topic","role":"article","images":[{"type":"card","identifier":"Page.png"}],"url":"\/documentation\/keyboardkitpro\/navigation-article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Status-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","url":"\/documentation\/keyboardkitpro\/status-article","title":"Status","role":"article","images":[{"type":"card","identifier":"Page.png"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit status engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLayout":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardLayout"}],"abstract":[{"type":"text","text":"This type defines the full set of keys on a keyboard and"},{"type":"text","text":" "},{"text":"is also a namespace for layout-related types.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardlayout","title":"KeyboardLayout","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardLayout","kind":"identifier"}]},"keyboardview-english":{"type":"image","alt":"Keyboard View","identifier":"keyboardview-english","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/keyboardview-english.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardSettings":{"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardsettings","role":"symbol","abstract":[{"type":"text","text":"This class can be used to setup a custom value store for"},{"type":"text","text":" "},{"type":"text","text":"all settings types in the library."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardSettings","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardSettings"}],"title":"KeyboardSettings","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings","kind":"symbol"},"keyboardtoolbar":{"type":"image","alt":"Keyboard Toolbar","identifier":"keyboardtoolbar","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/keyboardtoolbar.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Diacritic":{"navigatorTitle":[{"text":"Diacritic","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Diacritic","title":"Keyboard.Diacritic","url":"\/documentation\/keyboardkitpro\/keyboard\/diacritic","abstract":[{"text":"This struct can be used to define diacritics for any","type":"text"},{"text":" ","type":"text"},{"text":"keyboard and locale.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Diacritic","kind":"identifier"}]},"keyboard-numberpad":{"type":"image","alt":"NextKeyboardButton","identifier":"keyboard-numberpad","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/keyboard-numberpad.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/App-Article":{"title":"App Utilities","abstract":[{"text":"This article describes the KeyboardKit app-specific utilities.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","url":"\/documentation\/keyboardkitpro\/app-article","role":"article","type":"topic","images":[{"identifier":"Page.png","type":"card"}],"kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts":{"kind":"symbol","title":"Callouts","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts","navigatorTitle":[{"kind":"identifier","text":"Callouts"}],"url":"\/documentation\/keyboardkitpro\/callouts","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Callouts"}],"abstract":[{"text":"This namespace contains callout-related types.","type":"text"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","url":"\/documentation\/keyboardkitpro\/proxy-article","title":"Proxy Utilities","role":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit proxy engine and its utilities."}]},"emojikeyboard":{"type":"image","alt":"Emoji Keyboard","identifier":"emojikeyboard","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/emojikeyboard.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/state":{"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/state","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Keyboard","preciseIdentifier":"s:14KeyboardKitPro0A0V","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V5StateC","text":"State"}],"abstract":[{"type":"text","text":"The default set of keyboard-specific state."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state","type":"topic","kind":"symbol","title":"state"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/AutocapitalizationType":{"navigatorTitle":[{"kind":"identifier","text":"AutocapitalizationType"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutocapitalizationType","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/AutocapitalizationType","url":"\/documentation\/keyboardkitpro\/keyboard\/autocapitalizationtype","title":"Keyboard.AutocapitalizationType","role":"symbol","abstract":[{"type":"text","text":"This enum defines keyboard auto-capitalization types."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Text-Input-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","url":"\/documentation\/keyboardkitpro\/text-input-article","title":"Text Input","role":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit text input engine, which lets you type within the keyboard extension."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction":{"type":"topic","title":"KeyboardAction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"KeyboardAction","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardaction","abstract":[{"type":"text","text":"This enum defines keyboard-specific actions, and is also"},{"text":" ","type":"text"},{"text":"a namespace for keyboard action-related types.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardAction"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/EmojiKeyboard":{"abstract":[{"type":"text","text":"This view mimics a native emoji keyboard."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"EmojiKeyboard","kind":"identifier"}],"title":"EmojiKeyboard","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"EmojiKeyboard"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiKeyboard","url":"\/documentation\/keyboardkitpro\/emojikeyboard"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Gesture":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Gesture","title":"Keyboard.Gesture","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboard\/gesture","navigatorTitle":[{"text":"Gesture","kind":"identifier"}],"abstract":[{"text":"This enum defines various keyboard gestures that can","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"be used to interact with a keyboard."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Gesture"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/ReturnKeyType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReturnKeyType","kind":"identifier"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboard\/returnkeytype","kind":"symbol","role":"symbol","title":"Keyboard.ReturnKeyType","abstract":[{"type":"text","text":"This enum defines various keyboard return key types."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ReturnKeyType","navigatorTitle":[{"text":"ReturnKeyType","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Button":{"abstract":[{"type":"text","text":"This view mimics a native keyboard button."}],"type":"topic","title":"Keyboard.Button","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Button","url":"\/documentation\/keyboardkitpro\/keyboard\/button","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Button"}],"navigatorTitle":[{"kind":"identifier","text":"Button"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Dictation","kind":"identifier"}],"abstract":[{"text":"This namespace contains dictation-related types.","type":"text"}],"navigatorTitle":[{"text":"Dictation","kind":"identifier"}],"title":"Dictation","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/dictation"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUICore/View/keyboardButtonStyle(_:)":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/keyboardButtonStyle(_:)","title":"keyboardButtonStyle(_:)","role":"symbol","abstract":[{"type":"text","text":"Apply a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ButtonStyle","isActive":true,"type":"reference"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"keyboardButtonStyle","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V","text":"Keyboard"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A0V11ButtonStyleV","text":"ButtonStyle","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"url":"\/documentation\/keyboardkitpro\/swiftuicore\/view\/keyboardbuttonstyle(_:)","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures-Article":{"images":[{"identifier":"Page.png","type":"card"}],"role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/gestures-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit gesture engine."}],"title":"Gestures"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardBehavior":{"url":"\/documentation\/keyboardkitpro\/keyboardbehavior","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardBehavior","title":"KeyboardBehavior","type":"topic","abstract":[{"type":"text","text":"This protocol can be implemented by any classes that can"},{"text":" ","type":"text"},{"type":"text","text":"define keyboard-specific behaviors."}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardBehavior"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardBehavior","kind":"identifier"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardStyleService":{"url":"\/documentation\/keyboardkitpro\/keyboardstyleservice","title":"KeyboardStyleService","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyleService","abstract":[{"type":"text","text":"This protocol can be implemented by any classes that can"},{"type":"text","text":" "},{"text":"provide dynamic keyboard styles.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardStyleService","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardStyleService"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/ButtonShadow":{"type":"topic","title":"Keyboard.ButtonShadow","kind":"symbol","role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboard\/buttonshadow","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ButtonShadow"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ButtonShadow","navigatorTitle":[{"text":"ButtonShadow","kind":"identifier"}],"abstract":[{"text":"This view mimics a native keyboard button shadow.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/ButtonStyle":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ButtonStyle","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ButtonStyle","title":"Keyboard.ButtonStyle","url":"\/documentation\/keyboardkitpro\/keyboard\/buttonstyle","navigatorTitle":[{"kind":"identifier","text":"ButtonStyle"}],"abstract":[{"type":"text","text":"This style can be used to modify the visual style of"},{"text":" ","type":"text"},{"type":"text","text":"the various "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Button","isActive":true},{"type":"text","text":" components."}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/KeyboardType/numberPad":{"kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboard\/keyboardtype\/numberpad","type":"topic","abstract":[{"type":"text","text":"A number pad keyboard."}],"title":"Keyboard.KeyboardType.numberPad","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"numberPad","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/KeyboardType\/numberPad"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/BottomRow":{"abstract":[{"text":"This view creates a keyboard bottom row with leading","type":"text"},{"text":" ","type":"text"},{"text":"and trailing actions around a space key.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/BottomRow","url":"\/documentation\/keyboardkitpro\/keyboard\/bottomrow","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"BottomRow","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"BottomRow"}],"type":"topic","title":"Keyboard.BottomRow"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/keyboardType":{"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardcontext\/keyboardtype","role":"symbol","abstract":[{"type":"text","text":"The keyboard type that is currently used."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V","text":"Keyboard"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A0V0A4TypeO","text":"KeyboardType","kind":"typeIdentifier"}],"title":"keyboardType","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/keyboardType","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/SpaceContent":{"type":"topic","abstract":[{"type":"text","text":"This view renders standard system space key content."}],"role":"symbol","title":"Keyboard.SpaceContent","navigatorTitle":[{"text":"SpaceContent","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/SpaceContent","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"SpaceContent","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboard\/spacecontent","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardSettings/store":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"store"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSUserDefaults","text":"UserDefaults","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/store","url":"\/documentation\/keyboardkitpro\/keyboardsettings\/store","title":"store","role":"symbol","abstract":[{"type":"text","text":"The store that will be used by library settings."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/ToolbarStyle":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ToolbarStyle","title":"Keyboard.ToolbarStyle","role":"symbol","abstract":[{"type":"text","text":"This style can be used to modify the visual style of"},{"text":" ","type":"text"},{"text":"the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Toolbar","type":"reference"},{"type":"text","text":" component."}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ToolbarStyle"}],"url":"\/documentation\/keyboardkitpro\/keyboard\/toolbarstyle","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ToolbarStyle"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"type":"topic","title":"KeyboardInputViewController","kind":"symbol","role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"KeyboardInputViewController","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","navigatorTitle":[{"kind":"identifier","text":"KeyboardInputViewController"}],"abstract":[{"text":"This is the main input controller in a KeyboardKit-based","type":"text"},{"type":"text","text":" "},{"text":"keyboard extension.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardController":{"type":"topic","role":"symbol","kind":"symbol","title":"KeyboardController","url":"\/documentation\/keyboardkitpro\/keyboardcontroller","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardController","abstract":[{"type":"text","text":"This protocol can be implemented by any classes that can"},{"text":" ","type":"text"},{"text":"be used to control a keyboard extension.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"KeyboardController","kind":"identifier"}],"navigatorTitle":[{"text":"KeyboardController","kind":"identifier"}]},"keyboardviewpreview":{"type":"image","alt":"KeyboardView Preview - Turkish","identifier":"keyboardviewpreview","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/keyboardviewpreview.jpg"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Previews-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","url":"\/documentation\/keyboardkitpro\/previews-article","title":"Previews","role":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit preview engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","title":"External Keyboards","role":"article","type":"topic","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit external keyboard engine."}],"images":[{"identifier":"Page.png","type":"card"}],"url":"\/documentation\/keyboardkitpro\/external-keyboards-article"},"keyboardbuttonpreview":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/keyboardbuttonpreview.jpg","traits":["1x","light"]}],"alt":"Keyboard Button Preview","identifier":"keyboardbuttonpreview","type":"image"},"keyboardview-styled":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/keyboardview-styled.jpg"}],"alt":"KeyboardView","identifier":"keyboardview-styled","type":"image"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/topicSections","op":"add","value":null},{"value":[{"title":"Features","generated":true,"anchor":"Features","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"]}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title","value":"KeyboardInputViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments","value":[{"text":"KeyboardInputViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/navigatorTitle","value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}