{"metadata":{"title":"External Keyboards","modules":[{"name":"KeyboardKitPro"}],"roleHeading":"Article","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","interfaceLanguage":"swift"},"seeAlsoSections":[{"generated":true,"title":"Articles","anchor":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article"]}],"variants":[{"paths":["\/documentation\/keyboardkitpro\/external-keyboards-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/external-keyboards-article"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Keyboard extensions start to behave strangely when you type on an external keyboard. For instance, the keyboard extension will stop receiving information about when text changes, and will only update the context when the text cursor moves."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"👑 "},{"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","isActive":true,"type":"reference"},{"type":"text","text":" unlocks tools that help you easily detect if an external keyboard is connected to the device, for instance if a magic keyboard is connected to an iPad. Information about Pro features can be found further down."}]},{"type":"heading","text":"Workarounds","anchor":"Workarounds","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"One way to force the proxy to update is to move the text cursor with a fixed interval, to make the keyboard read the current text. This may however interfere with the typing, so it’s not encouraged."}]},{"type":"paragraph","inlineContent":[{"text":"Due to this limitation, it may be better to collapse the keyboard to a compact toolbar when an external keyboard is connected. You can always add a button that expands the keyboard again.","type":"text"}]},{"type":"heading","text":"How to auto-collapse the software keyboard","anchor":"How-to-auto-collapse-the-software-keyboard","level":2},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext"},{"text":"’s ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/isKeyboardCollapsed"},{"text":" property can be used to collapse the keyboard, e.g. when an external keyboard is connected. KeyboardKit Pro will automatically update this if ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/isKeyboardAutoCollapseEnabled"},{"text":" is enabled.","type":"text"}]},{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","type":"reference"},{"text":" lets you define which view to show when it’s collapsed. It defaults to a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/CollapsedView","type":"reference"},{"text":". This can be used to display custom content when the keyboard is collapsed. See the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","type":"reference"},{"text":" article for more information.","type":"text"}]},{"type":"heading","text":"How to manage external keyboard state","anchor":"How-to-manage-external-keyboard-state","level":2},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit has an ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/ExternalKeyboardContext","type":"reference","isActive":true},{"text":" that has state for if an external keyboard is connected, such as a Smart Keyboard Folio, a Magic Keyboard, any Bluetooth keyboards, etc.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro will automatically keep this context up to date when an external keyboard is connected and disconnected. Without it, you must listen for connection changes yourself and update this context accordingly.","type":"text"}]},{"type":"thematicBreak"},{"type":"heading","text":"👑 KeyboardKit Pro","anchor":"%F0%9F%91%91-KeyboardKit-Pro","level":2},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro will automatically keep the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/ExternalKeyboardContext"},{"text":" up to date when an external keyboard is connected and disconnected. Without it, you must listen for connection changes yourself and update this context accordingly.","type":"text"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro will consider an Apple Smart Keyboard Folio to be connected even when it’s just snapped on to the device and not being actively used. This should be improved.","type":"text"}]}],"type":"aside","style":"warning","name":"Warning"}]}],"kind":"article","sections":[],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Device-Article":{"role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","url":"\/documentation\/keyboardkitpro\/device-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit device utilities."}],"title":"Device Utilities"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"role":"article","url":"\/documentation\/keyboardkitpro\/localization-article","abstract":[{"text":"This article describes the KeyboardKit localization engine.","type":"text"}],"type":"topic","title":"Localization","images":[{"identifier":"Page.png","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback-Article":{"images":[{"identifier":"Page.png","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","url":"\/documentation\/keyboardkitpro\/feedback-article","type":"topic","role":"article","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"kind":"article","title":"Feedback"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"images":[{"identifier":"Page.png","type":"card"}],"title":"Actions","url":"\/documentation\/keyboardkitpro\/actions-article","kind":"article","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Input-Article":{"title":"Input","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","url":"\/documentation\/keyboardkitpro\/input-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}],"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit input engine."}],"role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/App-Article":{"url":"\/documentation\/keyboardkitpro\/app-article","type":"topic","kind":"article","role":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","title":"App Utilities"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AI-Article":{"abstract":[{"text":"This article describes the KeyboardKit AI support capabilities.","type":"text"}],"role":"article","type":"topic","kind":"article","images":[{"identifier":"Page.png","type":"card"}],"url":"\/documentation\/keyboardkitpro\/ai-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","title":"AI Support"},"https://github.com/KeyboardKit/KeyboardKitPro":{"type":"link","titleInlineContent":[{"text":"KeyboardKit Pro","type":"text"}],"title":"KeyboardKit Pro","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","url":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"url":"\/documentation\/keyboardkitpro","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"type":"topic","title":"KeyboardKitPro","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"},"Page.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png"}],"identifier":"Page.png","type":"image","alt":"Page icon"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/ExternalKeyboardContext":{"navigatorTitle":[{"kind":"identifier","text":"ExternalKeyboardContext"}],"kind":"symbol","url":"\/documentation\/keyboardkitpro\/externalkeyboardcontext","abstract":[{"type":"text","text":"This context can be used to keep track of if an external"},{"type":"text","text":" "},{"type":"text","text":"keyboard is connected to the device."}],"title":"ExternalKeyboardContext","role":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/ExternalKeyboardContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExternalKeyboardContext"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/CollapsedView":{"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/CollapsedView","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CollapsedView","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboard\/collapsedview","navigatorTitle":[{"text":"CollapsedView","kind":"identifier"}],"role":"symbol","title":"Keyboard.CollapsedView","abstract":[{"type":"text","text":"This view can be used to render a collapsed keyboard,"},{"type":"text","text":" "},{"type":"text","text":"e.g. when an external keyboard is connected."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"title":"Callouts","kind":"article","url":"\/documentation\/keyboardkitpro\/callouts-article","role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures-Article":{"type":"topic","images":[{"identifier":"Page.png","type":"card"}],"kind":"article","url":"\/documentation\/keyboardkitpro\/gestures-article","role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit gesture engine."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","title":"Gestures"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext":{"url":"\/documentation\/keyboardkitpro\/keyboardcontext","title":"KeyboardContext","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardContext"}],"abstract":[{"type":"text","text":"This class has observable states and persistent settings"},{"type":"text","text":" "},{"type":"text","text":"for the core keyboard functionality."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardContext"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardSettings/isKeyboardAutoCollapseEnabled":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isKeyboardAutoCollapseEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/isKeyboardAutoCollapseEnabled","abstract":[{"text":"Whether to auto-collapse the keyboard when an external keyboard is connected.","type":"text"}],"title":"isKeyboardAutoCollapseEnabled","url":"\/documentation\/keyboardkitpro\/keyboardsettings\/iskeyboardautocollapseenabled"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}],"url":"\/documentation\/keyboardkitpro\/autocomplete-article","type":"topic","title":"Autocomplete","role":"article","images":[{"identifier":"Page.png","type":"card"}],"kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Host-Article":{"kind":"article","role":"article","images":[{"identifier":"Page.png","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","url":"\/documentation\/keyboardkitpro\/host-article","type":"topic","title":"Host Application","abstract":[{"type":"text","text":"This article describes how KeyboardKit Pro can identify and use the host application."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardView":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardView"}],"type":"topic","title":"KeyboardView","navigatorTitle":[{"kind":"identifier","text":"KeyboardView"}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","url":"\/documentation\/keyboardkitpro\/keyboardview","role":"symbol","abstract":[{"text":"This view can be used to mimic a native iOS keyboard.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis-Article":{"url":"\/documentation\/keyboardkitpro\/emojis-article","type":"topic","title":"Emojis","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"text":"This article describes the KeyboardKit emoji engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","kind":"article","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation-Article":{"abstract":[{"text":"This article describes the KeyboardKit dictation engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/dictation-article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","type":"topic","images":[{"identifier":"Page.png","type":"card"}],"role":"article","title":"Dictation"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/isKeyboardCollapsed":{"type":"topic","title":"isKeyboardCollapsed","abstract":[{"type":"text","text":"Whether the keyboard is collapsed."}],"role":"symbol","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardcontext\/iskeyboardcollapsed","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isKeyboardCollapsed","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/isKeyboardCollapsed"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Navigation-Article":{"abstract":[{"text":"This article describes the KeyboardKit navigation engine.","type":"text"}],"title":"Navigation","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","images":[{"identifier":"Page.png","type":"card"}],"role":"article","url":"\/documentation\/keyboardkitpro\/navigation-article","kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Essentials-Article":{"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","url":"\/documentation\/keyboardkitpro\/essentials-article","kind":"article","title":"Essentials","abstract":[{"text":"This article describes the essential parts of KeyboardKit.","type":"text"}],"images":[{"type":"card","identifier":"Page.png"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"abstract":[{"text":"This article describes the KeyboardKit layout engine.","type":"text"}],"title":"Layout","kind":"article","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","url":"\/documentation\/keyboardkitpro\/layout-article","type":"topic","images":[{"identifier":"Page.png","type":"card"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"replace","path":"\/seeAlsoSections","value":[{"anchor":"Articles","title":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}