{"kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit feedback engine."}],"metadata":{"images":[{"identifier":"Page.png","type":"card"}],"roleHeading":"Article","modules":[{"name":"KeyboardKitPro"}],"role":"article","title":"Feedback"},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article"},"sections":[],"primaryContentSections":[{"content":[{"level":2,"type":"heading","anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Feedback is an important part of the typing experience, where a keyboard can trigger audio and haptic feedback when a user taps on a key or performs certain actions."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In KeyboardKit, keyboard feedback can be triggered with a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedbackService"},{"type":"text","text":", a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler"},{"type":"text","text":", or using the underlying "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/AudioEngine"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/HapticEngine"},{"type":"text","text":" engines directly."}]},{"level":2,"type":"heading","anchor":"Namespace","text":"Namespace"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback"},{"type":"text","text":" namespace that contains feedback-related types, like "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/Audio"},{"type":"text","text":" & "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/Haptic"},{"type":"text","text":" enums that define available feedback types, "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/AudioEngine"},{"type":"text","text":" & "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/HapticEngine"},{"type":"text","text":", etc."}]},{"level":2,"type":"heading","anchor":"Audio--Haptic-Feedback","text":"Audio & Haptic Feedback"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/Audio"},{"type":"text","text":" enum defines audio feedback types, like "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/Audio\/input"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/Audio\/system"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/Audio\/delete"},{"type":"text","text":", etc. The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback"},{"type":"text","text":" namespace also has other audio-related types like "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/AudioConfiguration","type":"reference"},{"type":"text","text":", which can be used to define complex audio feedback behavior."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/Haptic","type":"reference"},{"type":"text","text":" enum defines haptic feedback types, like "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/Haptic\/success","type":"reference"},{"type":"text","text":", "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/Haptic\/warning","type":"reference"},{"type":"text","text":", "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/Haptic\/error","type":"reference"},{"type":"text","text":" etc. The "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback","type":"reference"},{"type":"text","text":" namespace also has other haptic-related types like "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/HapticConfiguration","type":"reference"},{"type":"text","text":", which can be used to define complex haptic feedback behavior."}]},{"level":2,"type":"heading","anchor":"Context","text":"Context"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit has an observable ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedbackContext","type":"reference","isActive":true},{"text":" class that can be used to configure feedback for various gestures and actions. It also has auto-persisted ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedbackContext\/settings-swift.property","type":"reference","isActive":true},{"text":" that can be used to customize the feedback behavior and toggle it on and off.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit automatically creates an instance of this class and injects it into "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state","isActive":true},{"type":"text","text":". You can use this instance to configure feedback."}]},{"level":2,"type":"heading","anchor":"Services","text":"Services"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In KeyboardKit, a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedbackService","isActive":true,"type":"reference"},{"type":"text","text":" can be used to trigger audio & haptic feedback as users interacts with the keyboard. The "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler","isActive":true,"type":"reference"},{"type":"text","text":" protocol also implements this protocol."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit injects a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/StandardFeedbackService","isActive":true},{"type":"text","text":"  instance into "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","isActive":true},{"type":"text","text":". You can replace it at any time, to customize it to affect how the keyboard triggers feedback."}]},{"level":2,"type":"heading","anchor":"Settings","text":"Settings"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit has a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedbackSettings"},{"text":" type with feedback-related settings. The context ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedbackContext\/settings-swift.property"},{"text":" is used by default.","type":"text"}]},{"type":"thematicBreak"},{"level":2,"type":"heading","anchor":"How-to","text":"How to…"},{"level":3,"type":"heading","anchor":"trigger-keyboard-feedback","text":"…trigger keyboard feedback"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can trigger "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/Audio"},{"type":"text","text":" & "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/Haptic"},{"type":"text","text":" feedback with a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedbackService"},{"type":"text","text":" or a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler"},{"type":"text","text":". The standard action handler uses a nested feedback service by default."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To trigger feedback, just use "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedbackService\/triggerAudioFeedback(_:)","isActive":true},{"type":"text","text":" and "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedbackService\/triggerHapticFeedback(_:)","isActive":true},{"type":"text","text":". The standard action handler has more ways to customize which feedback to trigger for specific "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","isActive":true},{"type":"text","text":" gestures."}]},{"level":3,"type":"heading","anchor":"customize-keyboard-feedback","text":"…customize keyboard feedback"},{"type":"paragraph","inlineContent":[{"text":"You can configure the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/State\/feedbackContext","isActive":true,"type":"reference"},{"text":"  in the main ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state","isActive":true,"type":"reference"},{"text":" to configure the feedback behavior. For instance, this would customize the audio feedback for input keys, then disable haptic feedback:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["class KeyboardViewController: KeyboardInputViewController {","","    override func viewDidLoad() {","        super.viewDidLoad()","        let context = state.feedbackContext","        context.audioConfiguration.input = .custom(id: 1329)","        context.settings.isHapticFeedbackEnabled = false","    }","}"]},{"type":"paragraph","inlineContent":[{"text":"You can also use use the context to register custom feedback for any gesture on any action.","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["class KeyboardViewController: KeyboardInputViewController {","","    override func viewDidLoad() {","        super.viewDidLoad()","        let context = state.feedbackContext","        context.registerCustomFeedback(.audio(.rocketFuse, for: .press, on: .rocket))","        context.registerCustomFeedback(.audio(.rocketLaunch, for: .release, on: .rocket))","        context.registerCustomFeedback(.haptic(.selection, for: .repeat, on: .rocket))","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Since the configuration is observable, any changes will automatically cause the keyboard to update, e.g. if you have feedback toggles."}]},{"level":3,"type":"heading","anchor":"define-custom-audio-feedback","text":"…define custom audio feedback"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/Audio","type":"reference","isActive":true},{"text":" feedback type uses ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"AudioServices"}]},{"text":", which means that you can use any system audio (see ","type":"text"},{"identifier":"https:\/\/iphonedev.wiki\/index.php\/AudioServices","type":"reference","isActive":true},{"text":" for info) as feedback:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["extension Feedback.Audio {","","    static let sentMessage = .custom(id: 1004)","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can also use the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/Audio\/customUrl(_:)"},{"type":"text","text":" feedback type to define a custom audio feedback that loads a sound effect from an audio file:"}]},{"type":"codeListing","syntax":"swift","code":["extension Feedback.Audio {","","    static let sentMessage = .customUrl(","        Bundle.main.url(forResource: \"sent\", withExtension: \"mp3\")","    )","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can also implement a custom action handler to trigger feedback in a different ways. See the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article"},{"type":"text","text":" article for more information."}]}],"kind":"content"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"seeAlsoSections":[{"title":"Articles","generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article"],"anchor":"Articles"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkitpro\/feedback-article"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkitpro\/feedback-article"]}],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardFeedback/HapticEngine":{"url":"\/documentation\/keyboardkitpro\/keyboardfeedback\/hapticengine","abstract":[{"text":"This engine can be used to trigger haptic feedback.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HapticEngine","kind":"identifier"}],"kind":"symbol","type":"topic","title":"KeyboardFeedback.HapticEngine","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/HapticEngine","navigatorTitle":[{"text":"HapticEngine","kind":"identifier"}],"role":"symbol"},"Page.png":{"type":"image","identifier":"Page.png","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png","traits":["1x","light"]}],"alt":"Page icon"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"type":"topic","url":"\/documentation\/keyboardkitpro\/actions-article","kind":"article","title":"Actions","role":"article","images":[{"type":"card","identifier":"Page.png"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit action engine."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardFeedback/Audio/system":{"abstract":[{"type":"text","text":"Represents the sound of a system key."}],"url":"\/documentation\/keyboardkitpro\/keyboardfeedback\/audio\/system","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/Audio\/system","kind":"symbol","role":"symbol","title":"KeyboardFeedback.Audio.system","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"system","kind":"identifier"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"url":"\/documentation\/keyboardkitpro\/localization-article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","title":"Localization","abstract":[{"text":"This article describes the KeyboardKit localization engine.","type":"text"}],"images":[{"identifier":"Page.png","type":"card"}],"role":"article","kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardFeedbackService/triggerHapticFeedback(_:)":{"abstract":[{"type":"text","text":"Trigger the provided haptic feedback."}],"kind":"symbol","title":"triggerHapticFeedback(_:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedbackService\/triggerHapticFeedback(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"triggerHapticFeedback","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A8FeedbackV","text":"KeyboardFeedback","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A8FeedbackV6HapticO","text":"Haptic","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"url":"\/documentation\/keyboardkitpro\/keyboardfeedbackservice\/triggerhapticfeedback(_:)","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","type":"topic","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"title":"Callouts","role":"article","images":[{"type":"card","identifier":"Page.png"}],"url":"\/documentation\/keyboardkitpro\/callouts-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardFeedback/StandardFeedbackService":{"navigatorTitle":[{"text":"StandardFeedbackService","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StandardFeedbackService","kind":"identifier"}],"title":"KeyboardFeedback.StandardFeedbackService","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/StandardFeedbackService","abstract":[{"type":"text","text":"This standard service can be used to trigger various"},{"type":"text","text":" "},{"type":"text","text":"audio and haptic feedback, using system capabilities."}],"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardfeedback\/standardfeedbackservice","kind":"symbol","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardFeedbackSettings":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"This type is used for feedback-related settings."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardFeedbackSettings","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"KeyboardFeedbackSettings","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedbackSettings","url":"\/documentation\/keyboardkitpro\/keyboardfeedbacksettings","title":"KeyboardFeedbackSettings"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"title":"KeyboardKitPro","kind":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","abstract":[{"text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI.","type":"text"}],"url":"\/documentation\/keyboardkitpro","role":"collection"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardFeedbackService/triggerAudioFeedback(_:)":{"required":true,"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedbackService\/triggerAudioFeedback(_:)","title":"triggerAudioFeedback(_:)","url":"\/documentation\/keyboardkitpro\/keyboardfeedbackservice\/triggeraudiofeedback(_:)","abstract":[{"text":"Trigger the provided audio feedback.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"triggerAudioFeedback"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A8FeedbackV","text":"KeyboardFeedback"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A8FeedbackV5AudioO","text":"Audio"},{"kind":"text","text":")"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete-Article":{"url":"\/documentation\/keyboardkitpro\/autocomplete-article","abstract":[{"text":"This article describes the KeyboardKit autocomplete engine.","type":"text"}],"images":[{"type":"card","identifier":"Page.png"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","kind":"article","role":"article","type":"topic","title":"Autocomplete"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AI-Article":{"type":"topic","kind":"article","abstract":[{"text":"This article describes the KeyboardKit AI support capabilities.","type":"text"}],"images":[{"type":"card","identifier":"Page.png"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","title":"AI Support","url":"\/documentation\/keyboardkitpro\/ai-article","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardFeedback/Audio/delete":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delete","kind":"identifier"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardfeedback\/audio\/delete","abstract":[{"type":"text","text":"Represents the sound of a delete key."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/Audio\/delete","role":"symbol","title":"KeyboardFeedback.Audio.delete"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"kind":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","title":"Emojis","role":"article","url":"\/documentation\/keyboardkitpro\/emojis-article","images":[{"identifier":"Page.png","type":"card"}]},"https://iphonedev.wiki/index.php/AudioServices":{"type":"link","identifier":"https:\/\/iphonedev.wiki\/index.php\/AudioServices","title":"this site","titleInlineContent":[{"type":"text","text":"this site"}],"url":"https:\/\/iphonedev.wiki\/index.php\/AudioServices"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardFeedbackContext/settings-swift.property":{"title":"settings","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"settings","kind":"identifier"},{"text":": ","kind":"text"},{"text":"KeyboardFeedbackSettings","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A16FeedbackSettingsV"}],"url":"\/documentation\/keyboardkitpro\/keyboardfeedbackcontext\/settings-swift.property","abstract":[{"text":"Feedback-specific, auto-persisted settings.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedbackContext\/settings-swift.property"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardActionHandler":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardActionHandler","kind":"identifier"}],"navigatorTitle":[{"text":"KeyboardActionHandler","kind":"identifier"}],"title":"KeyboardActionHandler","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"This protocol can be implemented by any classes that can"},{"type":"text","text":" "},{"type":"text","text":"handle triggered "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction"},{"type":"text","text":" events."}],"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardactionhandler"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardFeedback/AudioConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"AudioConfiguration"}],"kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardfeedback\/audioconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioConfiguration"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/AudioConfiguration","title":"KeyboardFeedback.AudioConfiguration","type":"topic","abstract":[{"type":"text","text":"This struct can be used to configure audio feedback."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Input-Article":{"url":"\/documentation\/keyboardkitpro\/input-article","role":"article","title":"Input","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","kind":"article","images":[{"type":"card","identifier":"Page.png"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit input engine."}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation-Article":{"kind":"article","url":"\/documentation\/keyboardkitpro\/dictation-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"title":"Dictation","type":"topic","images":[{"type":"card","identifier":"Page.png"}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction":{"role":"symbol","abstract":[{"type":"text","text":"This enum defines keyboard-specific actions, and is also"},{"type":"text","text":" "},{"type":"text","text":"a namespace for keyboard action-related types."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardAction","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","navigatorTitle":[{"text":"KeyboardAction","kind":"identifier"}],"title":"KeyboardAction","url":"\/documentation\/keyboardkitpro\/keyboardaction"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/State/feedbackContext":{"abstract":[{"text":"The feedback context to use.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"feedbackContext","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A15FeedbackContextC","text":"KeyboardFeedbackContext","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboard\/state\/feedbackcontext","title":"feedbackContext","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/State\/feedbackContext"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardFeedback/Audio/customUrl(_:)":{"role":"symbol","abstract":[{"type":"text","text":"Represents a custom sound at a certain URL."}],"url":"\/documentation\/keyboardkitpro\/keyboardfeedback\/audio\/customurl(_:)","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customUrl","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"KeyboardFeedback.Audio.customUrl(_:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/Audio\/customUrl(_:)","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardFeedback/Audio":{"abstract":[{"text":"This enum defines standard audio feedback types.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"Audio","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardfeedback\/audio","title":"KeyboardFeedback.Audio","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Audio","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/Audio","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Device-Article":{"kind":"article","url":"\/documentation\/keyboardkitpro\/device-article","title":"Device Utilities","abstract":[{"type":"text","text":"This article describes the KeyboardKit device utilities."}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","images":[{"type":"card","identifier":"Page.png"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardFeedbackContext":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"This class has observable states and persistent settings"},{"type":"text","text":" "},{"type":"text","text":"for keyboard feedback."}],"kind":"symbol","title":"KeyboardFeedbackContext","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardFeedbackContext","kind":"identifier"}],"navigatorTitle":[{"text":"KeyboardFeedbackContext","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardfeedbackcontext","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedbackContext"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Host-Article":{"role":"article","kind":"article","url":"\/documentation\/keyboardkitpro\/host-article","type":"topic","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes how KeyboardKit Pro can identify and use the host application."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","title":"Host Application"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardFeedback/Haptic/warning":{"title":"KeyboardFeedback.Haptic.warning","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/Haptic\/warning","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Represents feedback for a warning event."}],"url":"\/documentation\/keyboardkitpro\/keyboardfeedback\/haptic\/warning","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"warning","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardFeedback/HapticConfiguration":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HapticConfiguration"}],"title":"KeyboardFeedback.HapticConfiguration","abstract":[{"text":"This struct can be used to configure haptic feedback.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardfeedback\/hapticconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HapticConfiguration"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/HapticConfiguration"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardFeedbackService":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedbackService","type":"topic","title":"KeyboardFeedbackService","abstract":[{"type":"text","text":"This protocol can be implemented by any type that can be"},{"type":"text","text":" "},{"type":"text","text":"used to trigger audio and haptic feedback."}],"role":"symbol","navigatorTitle":[{"text":"KeyboardFeedbackService","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardfeedbackservice","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardFeedbackService","kind":"identifier"}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardFeedback/AudioEngine":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioEngine","kind":"identifier"}],"abstract":[{"text":"This engine can be used to trigger audio feedback.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/AudioEngine","type":"topic","title":"KeyboardFeedback.AudioEngine","navigatorTitle":[{"text":"AudioEngine","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardfeedback\/audioengine","kind":"symbol","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardFeedback/Haptic/success":{"url":"\/documentation\/keyboardkitpro\/keyboardfeedback\/haptic\/success","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/Haptic\/success","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"success","kind":"identifier"}],"type":"topic","abstract":[{"text":"Represents feedback for a successful event.","type":"text"}],"role":"symbol","title":"KeyboardFeedback.Haptic.success"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardFeedback/Audio/input":{"url":"\/documentation\/keyboardkitpro\/keyboardfeedback\/audio\/input","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/Audio\/input","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"input"}],"abstract":[{"type":"text","text":"Represents the sound of an input key."}],"title":"KeyboardFeedback.Audio.input","kind":"symbol","type":"topic","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/state":{"kind":"symbol","abstract":[{"type":"text","text":"Keyboard-specific state."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Keyboard","preciseIdentifier":"s:14KeyboardKitPro0A0V"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"s:14KeyboardKitPro0A0V5StateC"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/state","type":"topic","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state","title":"state"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardFeedback/Haptic/error":{"title":"KeyboardFeedback.Haptic.error","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/Haptic\/error","url":"\/documentation\/keyboardkitpro\/keyboardfeedback\/haptic\/error","type":"topic","abstract":[{"type":"text","text":"Represents feedback for an error event."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Navigation-Article":{"images":[{"type":"card","identifier":"Page.png"}],"type":"topic","title":"Navigation","abstract":[{"type":"text","text":"This article describes the KeyboardKit navigation engine."}],"kind":"article","role":"article","url":"\/documentation\/keyboardkitpro\/navigation-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardFeedback":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardFeedback","kind":"identifier"}],"title":"KeyboardFeedback","abstract":[{"type":"text","text":"This namespace contains keyboard feedback-related types."}],"navigatorTitle":[{"text":"KeyboardFeedback","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback","url":"\/documentation\/keyboardkitpro\/keyboardfeedback","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","images":[{"type":"card","identifier":"Page.png"}],"role":"article","url":"\/documentation\/keyboardkitpro\/layout-article","title":"Layout","abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards-Article":{"images":[{"type":"card","identifier":"Page.png"}],"url":"\/documentation\/keyboardkitpro\/external-keyboards-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"type":"topic","role":"article","title":"External Keyboards","kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/services":{"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/services","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"services","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A0V","text":"Keyboard","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A0V8ServicesC","text":"Services","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Keyboard-specific services."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","role":"symbol","title":"services","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures-Article":{"type":"topic","kind":"article","abstract":[{"text":"This article describes the KeyboardKit gesture engine.","type":"text"}],"title":"Gestures","role":"article","url":"\/documentation\/keyboardkitpro\/gestures-article","images":[{"type":"card","identifier":"Page.png"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/App-Article":{"title":"App Utilities","url":"\/documentation\/keyboardkitpro\/app-article","role":"article","abstract":[{"text":"This article describes the KeyboardKit app-specific utilities.","type":"text"}],"kind":"article","images":[{"identifier":"Page.png","type":"card"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardFeedback/Haptic":{"title":"KeyboardFeedback.Haptic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Haptic"}],"navigatorTitle":[{"kind":"identifier","text":"Haptic"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedback\/Haptic","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"This enum defines standard haptic feedback types."}],"role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardfeedback\/haptic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article"],"generated":true,"anchor":"Articles","title":"Articles"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}