{"primaryContentSections":[{"kind":"content","content":[{"level":2,"type":"heading","anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"Native iOS keyboards use more gestures than you may think. For instance, keys can be pressed, released, long pressed, etc. Space can be dragged to move the cursor, shift can be double tapped to toggle caps-lock, etc.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"These gestures can be complicated to set up, but KeyboardKit provides you with a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Gesture"},{"type":"text","text":" enum that defines all supported gestures, as well as views and extensions that trigger rich gesture actions that can be handled by a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler","isActive":true},{"type":"text","text":"."}]},{"anchor":"Namespace","level":2,"text":"Namespace","type":"heading"},{"inlineContent":[{"text":"KeyboardKit has a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures","type":"reference"},{"text":" namespace with gesture-related types, like ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/GestureButton","isActive":true},{"text":". It however doesn’t contain the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Gesture"},{"text":" enum, which is an essential type that is defined in the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","isActive":true,"type":"reference"},{"text":" namespace.","type":"text"}],"type":"paragraph"},{"type":"heading","anchor":"View-Modifiers","text":"View Modifiers","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can use the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/keyboardButtonGestures(for:actionHandler:repeatTimer:calloutContext:isPressed:isGestureAutoCancellable:scrollState:releaseOutsideTolerance:)","isActive":true},{"type":"text","text":" "},{"type":"text","text":"modifier to apply keyboard gesture to any view:"}]},{"type":"codeListing","syntax":"swift","code":["Text(\"😀\")","    .keyboardButtonGestures(","        for: .emoji(\"😀\"),","        ...","    )"]},{"type":"paragraph","inlineContent":[{"text":"This will apply all standard gestures for the provided action. You can also set up completely custom gesture actions with this modifier.","type":"text"}]},{"anchor":"Drag-gesture-handlers","text":"Drag gesture handlers","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit has a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DragGestureHandler","type":"reference"},{"text":" protocol that handles drag gestures. For instance, a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures\/SpaceDragGestureHandler","isActive":true},{"text":" handles drag gestures on the space key.","type":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article"},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"variants":[{"paths":["\/documentation\/keyboardkitpro\/gestures-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/gestures-article"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"seeAlsoSections":[{"title":"Features","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"generated":true,"anchor":"Features"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit gesture engine."}],"metadata":{"color":{"standardColorIdentifier":"blue"},"role":"article","images":[{"identifier":"Page.png","type":"card"}],"modules":[{"name":"KeyboardKitPro"}],"title":"Gestures","roleHeading":"Article"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"article","references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","kind":"symbol","url":"\/documentation\/keyboardkitpro","title":"KeyboardKitPro","role":"collection","type":"topic","abstract":[{"type":"text","text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardActionHandler":{"navigatorTitle":[{"kind":"identifier","text":"KeyboardActionHandler"}],"kind":"symbol","title":"KeyboardActionHandler","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler","role":"symbol","abstract":[{"text":"This protocol can be implemented by any classes that can","type":"text"},{"text":" ","type":"text"},{"text":"handle triggered ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","isActive":true},{"text":" events.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"KeyboardActionHandler","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardactionhandler"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Previews-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit preview engine."}],"url":"\/documentation\/keyboardkitpro\/previews-article","images":[{"identifier":"Page.png","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","title":"Previews","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","abstract":[{"text":"This article describes the KeyboardKit layout engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/layout-article","role":"article","type":"topic","title":"Layout","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Device-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit device utilities."}],"url":"\/documentation\/keyboardkitpro\/device-article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","title":"Device Utilities","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures":{"url":"\/documentation\/keyboardkitpro\/gestures","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Gestures","kind":"identifier"}],"role":"symbol","type":"topic","title":"Gestures","navigatorTitle":[{"kind":"identifier","text":"Gestures"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures","abstract":[{"type":"text","text":"This namespace contains gesture-related types."}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Essentials-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the essential parts of KeyboardKit."}],"url":"\/documentation\/keyboardkitpro\/essentials-article","images":[{"type":"card","identifier":"Page.png"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","title":"Essentials","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Settings-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit settings engine."}],"url":"\/documentation\/keyboardkitpro\/settings-article","role":"article","type":"topic","title":"Settings","kind":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures/SpaceDragGestureHandler":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures\/SpaceDragGestureHandler","navigatorTitle":[{"text":"SpaceDragGestureHandler","kind":"identifier"}],"title":"Gestures.SpaceDragGestureHandler","kind":"symbol","role":"symbol","url":"\/documentation\/keyboardkitpro\/gestures\/spacedraggesturehandler","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SpaceDragGestureHandler"}],"abstract":[{"type":"text","text":"This custom gesture handler can handle the space key"},{"type":"text","text":" "},{"type":"text","text":"gesture that moves the input cursor."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}],"url":"\/documentation\/keyboardkitpro\/autocomplete-article","role":"article","type":"topic","title":"Autocomplete","kind":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","url":"\/documentation\/keyboardkitpro\/keyboard","abstract":[{"text":"This namespace contains essential keyboard-related types.","type":"text"}],"kind":"symbol","title":"Keyboard","navigatorTitle":[{"kind":"identifier","text":"Keyboard"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Keyboard"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/feedback-article","role":"article","type":"topic","title":"Feedback","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"type":"topic","abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/actions-article","images":[{"type":"card","identifier":"Page.png"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","title":"Actions","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","abstract":[{"text":"This article describes the KeyboardKit callout engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/callouts-article","role":"article","type":"topic","title":"Callouts","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUICore/View/keyboardButtonGestures(for:actionHandler:repeatTimer:calloutContext:isPressed:isGestureAutoCancellable:scrollState:releaseOutsideTolerance:)":{"title":"keyboardButtonGestures(for:actionHandler:repeatTimer:calloutContext:isPressed:isGestureAutoCancellable:scrollState:releaseOutsideTolerance:)","role":"symbol","abstract":[{"type":"text","text":"Apply keyboard button gestures that use the provided"},{"type":"text","text":" "},{"code":"actionHandler","type":"codeVoice"},{"text":" to trigger gesture actions.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/keyboardkitpro\/swiftuicore\/view\/keyboardbuttongestures(for:actionhandler:repeattimer:calloutcontext:ispressed:isgestureautocancellable:scrollstate:releaseoutsidetolerance:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardButtonGestures"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"text":"KeyboardAction","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A6ActionO"},{"text":", ","kind":"text"},{"text":"actionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A13ActionHandlerP","kind":"typeIdentifier","text":"KeyboardActionHandler"},{"kind":"text","text":", "},{"text":"repeatTimer","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro18GestureButtonTimerC","text":"GestureButtonTimer"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"calloutContext"},{"text":": ","kind":"text"},{"text":"KeyboardCalloutContext","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A14CalloutContextC"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"isPressed"},{"text":": ","kind":"text"},{"text":"Binding","preciseIdentifier":"s:7SwiftUI7BindingV","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":">, "},{"text":"isGestureAutoCancellable","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"scrollState"},{"kind":"text","text":": "},{"text":"GestureButtonScrollState","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro24GestureButtonScrollStateC"},{"kind":"text","text":"?, "},{"text":"releaseOutsideTolerance","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":") -> "},{"text":"some","kind":"keyword"},{"kind":"text","text":" "},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/keyboardButtonGestures(for:actionHandler:repeatTimer:calloutContext:isPressed:isGestureAutoCancellable:scrollState:releaseOutsideTolerance:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/DragGestureHandler":{"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DragGestureHandler","url":"\/documentation\/keyboardkitpro\/draggesturehandler","title":"DragGestureHandler","abstract":[{"type":"text","text":"This protocol can be implemented by any type that can be"},{"type":"text","text":" "},{"type":"text","text":"used to handle drag gestures from one point to another."}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DragGestureHandler","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"DragGestureHandler","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards-Article":{"abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"images":[{"type":"card","identifier":"Page.png"}],"kind":"article","url":"\/documentation\/keyboardkitpro\/external-keyboards-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","role":"article","title":"External Keyboards","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Status-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit status engine."}],"url":"\/documentation\/keyboardkitpro\/status-article","role":"article","type":"topic","title":"Status","kind":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction":{"navigatorTitle":[{"kind":"identifier","text":"KeyboardAction"}],"title":"KeyboardAction","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction","abstract":[{"type":"text","text":"This enum defines keyboard-specific actions, and is also"},{"text":" ","type":"text"},{"text":"a namespace for keyboard action-related types.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"KeyboardAction"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Navigation-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","abstract":[{"text":"This article describes the KeyboardKit navigation engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/navigation-article","role":"article","type":"topic","title":"Navigation","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"Page.png":{"type":"image","alt":"Page icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png","traits":["1x","light"]}],"identifier":"Page.png"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Gesture":{"url":"\/documentation\/keyboardkitpro\/keyboard\/gesture","title":"Keyboard.Gesture","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Gesture"}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Gesture","type":"topic","abstract":[{"text":"This enum defines various keyboard gestures that can","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"be used to interact with a keyboard."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Gesture","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/GestureButton":{"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"GestureButton","kind":"identifier"}],"title":"GestureButton","url":"\/documentation\/keyboardkitpro\/gesturebutton","abstract":[{"text":"This button can be used to trigger gesture-based actions.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"GestureButton","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/GestureButton","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Styling-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","abstract":[{"text":"This article describes the KeyboardKit styling engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/styling-article","role":"article","type":"topic","title":"Styling","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/App-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","abstract":[{"text":"This article describes the KeyboardKit app-specific utilities.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/app-article","role":"article","type":"topic","title":"App Utilities","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit localization engine."}],"url":"\/documentation\/keyboardkitpro\/localization-article","images":[{"identifier":"Page.png","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","title":"Localization","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"url":"\/documentation\/keyboardkitpro\/emojis-article","images":[{"identifier":"Page.png","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","title":"Emojis","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Host-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","abstract":[{"type":"text","text":"This article describes how KeyboardKit Pro can identify the host application."}],"url":"\/documentation\/keyboardkitpro\/host-article","role":"article","type":"topic","title":"Host Utilities","kind":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AI-Article":{"type":"topic","abstract":[{"text":"This article describes the KeyboardKit AI support capabilities.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/ai-article","images":[{"type":"card","identifier":"Page.png"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","title":"AI Support","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Themes-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit Pro theme engine, which can be used to style the entire keyboard with a single theme."}],"url":"\/documentation\/keyboardkitpro\/themes-article","images":[{"identifier":"Page.png","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article","title":"Themes","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","abstract":[{"text":"This article describes the KeyboardKit proxy engine and its utilities.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/proxy-article","role":"article","type":"topic","title":"Proxy Utilities","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Text-Input-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit text input engine, which lets you type within the keyboard extension."}],"url":"\/documentation\/keyboardkitpro\/text-input-article","images":[{"type":"card","identifier":"Page.png"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","title":"Text Input","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"url":"\/documentation\/keyboardkitpro\/dictation-article","images":[{"type":"card","identifier":"Page.png"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","title":"Dictation","role":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","value":null,"op":"add"},{"value":[{"generated":true,"title":"Features","anchor":"Features","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"]}],"op":"replace","path":"\/seeAlsoSections"}]}]}