{"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This guide completes the standard KeyboardKit "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started"},{"type":"text","text":" guide with KeyboardKit Pro-specific information."}]},{"anchor":"How-to-install-KeyboardKit-Pro","level":2,"type":"heading","text":"How to install KeyboardKit Pro"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro can be installed with the Swift Package Manager:"}]},{"type":"codeListing","syntax":null,"code":["https:\/\/github.com\/KeyboardKit\/KeyboardKitPro.git"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Since KeyboardKit Pro installs as a binary, it only has to be added to the main app target."}]},{"anchor":"How-to-setup-KeyboardKit-Pro","level":2,"type":"heading","text":"How to setup KeyboardKit Pro"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro is setup just like KeyboardKit (see "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started"},{"type":"text","text":"), but requires that you use "},{"type":"codeVoice","code":"setupPro(withLicenseKey:view:licenseConfiguration:)"},{"type":"text","text":" instead of "},{"type":"codeVoice","code":"setup(with:)"},{"type":"text","text":":"}]},{"type":"codeListing","syntax":"swift","code":["func viewWillSetupKeyboard() {","    super.viewWillSetupKeyboard()","    do {","        try setupPro(","            withLicenseKey: \"your-license-key\", ","            view: AnyKeyboardView()","        ) { license in","            \/\/ Perform any license-based configurations","        }","    } catch {","        let licenseError = error as? LicenseError","        \/\/ Here, you can check what went wrong","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This will first validate and register the license key. If the license key is valid, the setup will proceed just like in KeyboardKit. If the license is invalid, you will get an error view that describes the error instead of the provided keyboard view."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you want to setup KeyboardKit Pro without a view, you can use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setupPro(withLicenseKey:)"},{"type":"text","text":":"}]},{"type":"codeListing","syntax":"swift","code":["func viewDidLoad() {","    super.viewDidLoad()","    try? setupPro(withLicenseKey: \"your-key\")","    \/\/ You can then setup your view whenever you want","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"As you can see above, you can use "},{"type":"codeVoice","code":"try?"},{"type":"text","text":" if you don’t care about the error."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Since KeyboardKit will by default setup a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboard"},{"type":"text","text":", you can just set up your license key like this without having to setup a view."}]},{"anchor":"How-to-setup-KeyboardKit-Pro-without-a-controller","level":2,"type":"heading","text":"How to setup KeyboardKit Pro without a controller"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you want to setup KeyboardKit Pro where you don’t have an input controller, you can use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/License\/register(licenseKey:)"},{"type":"text","text":":"}]},{"type":"codeListing","syntax":"swift","code":["var ContentView: View {","","    var body: some View {","        Text(\"This is my amazing SwiftUI app\")","            .onAppear { License\/register(licenseKey: \"your-key\") }","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Registering a license key will unlock all the Pro features that the license gives access to, which is described in more detail in the next section."}]},{"anchor":"How-to-handle-licenses","level":2,"type":"heading","text":"How to handle licenses"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Registering a KeyboardKit Pro license key will unlock all the Pro features that the license gives access to and configure KeyboardKit according to the license configuration."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For instance, "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/autocompleteProvider"},{"type":"text","text":" will be configured to use a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardAutocompleteProvider"},{"type":"text","text":", the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/locales"},{"type":"text","text":" collection will be set to the locales that your license supports and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/locale"},{"type":"text","text":" will be set to the first locale in your license’s locale list."}]},{"anchor":"How-to-access-your-license","level":3,"type":"heading","text":"How to access your license"},{"type":"paragraph","inlineContent":[{"type":"text","text":"After registering a valid license as described above, you can use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/License\/current"},{"type":"text","text":" to inspect your license information:"}]},{"type":"codeListing","syntax":"swift","code":["let license = License.current","let expirationDate = license?.expires"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The license contains license and customer information, such as "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/License\/tier"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/License\/expirationDate"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/License\/locales"},{"type":"text","text":" , "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/License\/featureIds"},{"type":"text","text":" etc."}]},{"anchor":"How-to-reconfigure-your-license","level":3,"type":"heading","text":"How to reconfigure your license"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Registering a valid license will cause KeyboardKit to configure your application and extension according to the license configuration, as described above."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you want to change the license’s standard configuration, you must do so after registering your license key, otherwise your changes will be overwritten."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For instance, here we replace the standard autocomplete provider with another one:"}]},{"type":"codeListing","syntax":"swift","code":["func viewWillSetupKeyboard() {","    super.viewWillSetupKeyboard()","    setupPro(withLicenseKey: \"your-key\") { license in","        \/\/ Here, you can setup anything that needs the license","    }","    \/\/ Here you can setup anything that should override the Pro configuration","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Have a look at the demo app for more examples."}]},{"anchor":"How-to-handle-license-errors","level":3,"type":"heading","text":"How to handle license errors"},{"type":"paragraph","inlineContent":[{"type":"text","text":"All Pro features are throwing, since they require a valid license. They will all throw a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/LicenseError"},{"type":"text","text":" whenever anything goes wrong."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Trying to register an invalid license key will throw a license error that describes what went wrong. For instance, you may have used an invalid or expired license key, used the license in a bundle that it doesn’t include etc."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Trying to access Pro features without first registering a license key, or trying access a feature that isn’t included in the license, will also throw a license error. For instance, you may be tyring to access a feature that requires a higher tier."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You don’t have to handle any errors that are thrown when registering a license key while setting up a keyboard view, since any thrown license error will be displayed instead of the keyboard view."}]},{"anchor":"Going-Further","level":2,"type":"heading","text":"Going Further"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The things above are basically what differs using KeyboardKit Pro from using KeyboardKit."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Have a look at the general "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started"},{"type":"text","text":" guide for more information about how to use KeyboardKit, and the other KeyboardKit Pro articles for more information about KeyboardKit Pro-specific features."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/keyboardkitpro\/getting-started-with-keyboardkit-pro"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/getting-started-with-keyboardkit-pro"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started-With-KeyboardKit-Pro","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This article discusses how get started with KeyboardKit Pro."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Getting Started With KeyboardKit Pro","role":"article","modules":[{"name":"KeyboardKitPro"}]},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"seeAlsoSections":[{"title":"Getting Started","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started"],"generated":true}],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","title":"KeyboardKitPro","abstract":[{"type":"text","text":"KeyboardKit Pro helps you build custom keyboard extensions for iOS and iPadOS."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/locale":{"role":"symbol","title":"locale","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"locale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Locale","preciseIdentifier":"s:10Foundation6LocaleV"}],"abstract":[{"type":"text","text":"The locale that is currently being used."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/locale","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardcontext\/locale"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SystemKeyboard":{"role":"symbol","title":"SystemKeyboard","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SystemKeyboard"}],"abstract":[{"type":"text","text":"This keyboard can be used to create alphabetic, numeric and"},{"type":"text","text":" "},{"type":"text","text":"symbolic keyboards that mimic the native iOS keyboard."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SystemKeyboard"}],"url":"\/documentation\/keyboardkitpro\/systemkeyboard"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/License/featureIds":{"role":"symbol","title":"featureIds","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"featureIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The feature IDs the license gives access to."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/License\/featureIds","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/license\/featureids"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardAutocompleteProvider":{"role":"symbol","title":"StandardAutocompleteProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StandardAutocompleteProvider"}],"abstract":[{"type":"text","text":"This autocomplete provider can be used to make autocomplete"},{"type":"text","text":" "},{"type":"text","text":"requests locally on the device."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardAutocompleteProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StandardAutocompleteProvider"}],"url":"\/documentation\/keyboardkitpro\/standardautocompleteprovider"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/License/expirationDate":{"role":"symbol","title":"expirationDate","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"expirationDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The license expiration date, if any."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/License\/expirationDate","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/license\/expirationdate"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/setupPro(withLicenseKey:)":{"role":"symbol","title":"setupPro(withLicenseKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupPro"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withLicenseKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Setup KeyboardKit Pro with a license key."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setupPro(withLicenseKey:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/setuppro(withlicensekey:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/License/current":{"role":"symbol","title":"current","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"current"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"License","preciseIdentifier":"s:14KeyboardKitPro7LicenseV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get the currently registered license, if any."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/License\/current","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/license\/current"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/locales":{"role":"symbol","title":"locales","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"locales"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Locale","preciseIdentifier":"s:10Foundation6LocaleV"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The locales that are currently enabled for the keyboard."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/locales","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardcontext\/locales"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Getting-Started":{"role":"article","title":"Getting Started","abstract":[{"type":"text","text":"This article discusses how get started with KeyboardKit."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/getting-started"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/autocompleteProvider":{"role":"symbol","title":"autocompleteProvider","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autocompleteProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutocompleteProvider","preciseIdentifier":"s:14KeyboardKitPro20AutocompleteProviderP"}],"abstract":[{"type":"text","text":"This provider is used to provide the keyboard extension"},{"type":"text","text":" "},{"type":"text","text":"with autocomplete suggestions."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/autocompleteProvider","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/autocompleteprovider"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/License/locales":{"role":"symbol","title":"locales","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"locales"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"KeyboardLocale","preciseIdentifier":"s:14KeyboardKitPro0A6LocaleO"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Get all locales that are included in the license."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/License\/locales","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/license\/locales"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/LicenseError":{"role":"symbol","title":"LicenseError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LicenseError"}],"abstract":[{"type":"text","text":"This enum defines various license errors that can be thrown"},{"type":"text","text":" "},{"type":"text","text":"when registering a license key or trying to access features"},{"type":"text","text":" "},{"type":"text","text":"that require a specific license type."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/LicenseError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LicenseError"}],"url":"\/documentation\/keyboardkitpro\/licenseerror"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/License/register(licenseKey:)":{"role":"symbol","title":"register(licenseKey:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"register"},{"kind":"text","text":"("},{"kind":"externalParam","text":"licenseKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"License","preciseIdentifier":"s:14KeyboardKitPro7LicenseV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Register a license with the provided license key."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/License\/register(licenseKey:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/license\/register(licensekey:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/License/tier":{"role":"symbol","title":"tier","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"tier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LicenseTier","preciseIdentifier":"s:14KeyboardKitPro11LicenseTierV"}],"abstract":[{"type":"text","text":"The license tier."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/License\/tier","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/license\/tier"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Getting Started","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}