{"variants":[{"paths":["\/documentation\/keyboardkitpro\/getting-started-guide"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkitpro\/getting-started-guide"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started-Guide","interfaceLanguage":"swift"},"metadata":{"title":"Getting Started","modules":[{"name":"KeyboardKitPro"}],"roleHeading":"Article","images":[{"type":"card","identifier":"Page.png"}],"role":"article"},"sections":[],"abstract":[{"type":"text","text":"This guide describes how to get started with KeyboardKit."}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Memory-Management-Guide"],"anchor":"Guides","title":"Guides","generated":true}],"primaryContentSections":[{"kind":"content","content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"This guide goes through the steps of adding ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKit"},{"text":" or ","type":"text"},{"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","isActive":true,"type":"reference"},{"text":" to your project and setting up the main app and keyboard.","type":"text"}]},{"type":"heading","text":"Step 1. Add KeyboardKit to your project","level":2,"anchor":"Step-1-Add-KeyboardKit-to-your-project"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The easiest way to add KeyboardKit to your app or package is with the Swift Package Manager. You can either use "},{"type":"reference","overridingTitle":"KeyboardKit","isActive":true,"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKit","overridingTitleInlineContent":[{"type":"text","text":"KeyboardKit"}]},{"type":"text","text":" or the more capable, commercially licensed "},{"overridingTitle":"KeyboardKit Pro","type":"reference","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","overridingTitleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"isActive":true},{"text":":","type":"text"}]},{"code":["https:\/\/github.com\/KeyboardKit\/KeyboardKit.git      \/\/ or...","https:\/\/github.com\/KeyboardKit\/KeyboardKitPro.git"],"type":"codeListing","syntax":null},{"inlineContent":[{"text":"KeyboardKit must be linked to the main app target ","type":"text"},{"type":"emphasis","inlineContent":[{"type":"text","text":"and"}]},{"type":"text","text":" its keyboard extension, while KeyboardKit Pro must only be added to the app."}],"type":"paragraph"},{"type":"heading","level":2,"text":"Step 2. Define app-specific information","anchor":"Step-2-Define-app-specific-information"},{"inlineContent":[{"text":"The easiest way to set up KeyboardKit is with a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp"},{"text":", which can define ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/bundleId","isActive":true},{"type":"text","text":", "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/appGroupId","isActive":true},{"text":", a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/licenseKey"},{"type":"text","text":", etc."}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["import KeyboardKit (or KeyboardKitPro)","","extension KeyboardApp {","","    static var keyboardKitDemo: KeyboardApp {","        .init(","            name: \"KeyboardKit\",","            licenseKey: \"your-key-here\",                \/\/ Sets up KeyboardKit Pro!","            appGroupId: \"group.com.keyboardkit.demo\",   \/\/ Sets up App Group data sync","            locales: .keyboardKitSupported,             \/\/ Sets up the enabled locales","            autocomplete: .init(                        \/\/ Sets up custom autocomplete  ","                nextWordPredictionRequest: .claude(...) \/\/ Sets up AI-based prediction","            ),","            deepLinks: .init(app: \"kkdemo:\/\/\", ...)     \/\/ Defines how to open the app","        )","    }","}"]},{"type":"paragraph","inlineContent":[{"text":"Define this in a file that you add to both the app and its keyboard extension, to easily refer to it from both. See ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","isActive":true,"type":"reference"},{"type":"text","text":" for more info."}]},{"text":"Step 3. Set up the keyboard extension","type":"heading","level":2,"anchor":"Step-3-Set-up-the-keyboard-extension"},{"inlineContent":[{"text":"To set up a keyboard to use KeyboardKit, first inherit ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController"},{"text":" instead of ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/UIKit\/UIInputViewController"},{"type":"text","text":":"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["import KeyboardKit (or KeyboardKitPro)","","class KeyboardController: KeyboardInputViewController {}"]},{"inlineContent":[{"type":"text","text":"This gives you access to lifecycle functions like "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewWillSetupKeyboardView()","type":"reference"},{"type":"text","text":", observable "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state","type":"reference","isActive":true},{"type":"text","text":", keyboard "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services"},{"text":", etc.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"Override ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewDidLoad()","type":"reference"},{"type":"text","text":" and call "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setup(for:)","isActive":true,"type":"reference"},{"text":" (or ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setupPro(for:errorDisplay:completion:)"},{"text":" if you use ","type":"text"},{"isActive":true,"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","overridingTitle":"KeyboardKit Pro","overridingTitleInlineContent":[{"text":"KeyboardKit Pro","type":"text"}],"type":"reference"},{"text":") to set up the keyboard extension for your app:","type":"text"}]},{"type":"tabNavigator","tabs":[{"title":"KeyboardKit","content":[{"syntax":"swift","code":["class KeyboardViewController: KeyboardInputViewController {","","    override func viewDidLoad() {","        super.viewDidLoad()","        setup(for: .keyboardKitDemo)","    }","}"],"type":"codeListing"}]},{"title":"KeyboardKit Pro 👑","content":[{"code":["class KeyboardViewController: KeyboardInputViewController {","","    override func viewDidLoad() {","        super.viewDidLoad()","        setupPro(for: .keyboardKitDemo) { result in","            \/\/ This is called when the license registration completes","        }","    }","}"],"type":"codeListing","syntax":"swift"}]}]},{"type":"paragraph","inlineContent":[{"text":"This will make the keyboard ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Settings"},{"type":"text","text":" sync data between the keyboard extension and its main app if you define a valid "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/appGroupId","isActive":true},{"text":", set up your KeyboardKit Pro license if you define a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/licenseKey","isActive":true},{"text":", set up dictation, deep links, etc.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"This also makes the keyboard use a standard ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","isActive":true,"type":"reference"},{"text":" that is configured for your app. Override ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewWillSetupKeyboardView()","type":"reference"},{"type":"text","text":" and call "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setupKeyboardView(_:)"},{"text":" to replace or customize the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","isActive":true},{"type":"text","text":":"}]},{"type":"codeListing","code":["class KeyboardViewController: KeyboardInputViewController {","","    override func viewWillSetupKeyboardView() {","        setupKeyboardView { [weak self] controller in \/\/ <-- Use weak or unknowned if you must use self!","            CustomKeyboardView( ","                state: controller.state","                services: controller.services","            )","        }","    }","}","","\/\/ Defining a custom view in a separate file keeps your controller clean.","struct CustomKeyboardView: View {","","    var state: Keyboard.State","    var services: Keyboard.Services","","    \/\/ State can also be accessed from the enviroment.","    @EnvironmentObject var keyboardContext: KeyboardContext","","    var body: some View {","        if keyboardContext.keyboardType == .email {","            \/\/ Insert your GPT-powered email client here :)","        } else {","            KeyboardView(","                state: state,","                services: services,","                buttonContent: { $0.view },        \/\/ Use $0.view to use the standard view","                buttonView: { $0.view },           \/\/ The $0 has additional parameter data             ","                collapsedView: { params in params.view },   \/\/ This is the same as $0.view","                emojiKeyboard: { $0.view },        ","                toolbar: { _ in CustomToolbar() }  \/\/ Ignores the params and returns a view","            )","        }","    }","}"],"syntax":"swift"},{"name":"Warning","type":"aside","style":"warning","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setupKeyboardView(_:)"},{"type":"text","text":" provides you with an unowned controller, to help you avoid memory leaks. If you must refer to your specific controller type, you MUST use "},{"type":"codeVoice","code":"[weak self]"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"[unowned self]"},{"text":", or the self reference will cause a memory leak!","type":"text"}]}]},{"text":"Step 4. Set up the main app (optional)","type":"heading","level":2,"anchor":"Step-4-Set-up-the-main-app-optional"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can use KeyboardKit in your main app, to display the enabled and Full Access status of your keyboard, link to System Settings, etc. It’s a great place for app and keyboard settings, since it has more space than in the keyboard extension."}]},{"inlineContent":[{"type":"text","text":"The easiest way to set up an app is to use a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAppView"},{"text":" root view, which uses a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","isActive":true,"type":"reference"},{"type":"text","text":" to set up everything it needs:"}],"type":"paragraph"},{"syntax":"swift","code":["@main","struct MyApp: App {","","    var body: some Scene {","        WindowGroup {","            KeyboardAppView(for: .keyboardKitDemo) {","                ContentView()","            }","        }","    }","}"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"text":"You can use the KeyboardKit Pro ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/HomeScreen","isActive":true,"type":"reference"},{"text":" to easily set up a start screen for the app, or link to the individual ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/SettingsScreen","isActive":true},{"text":", ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/LocaleScreen","isActive":true},{"text":", and ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/ThemeScreen","type":"reference"},{"type":"text","text":" screens from any screen. You can also use a status "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStatus\/Section","isActive":true,"type":"reference"},{"type":"text","text":" to show keyboard status."}]},{"type":"heading","anchor":"Step-5-Customize-state--services-optional","text":"Step 5. Customize state & services (optional)","level":2},{"type":"paragraph","inlineContent":[{"text":"The main ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","type":"reference"},{"type":"text","text":" provides you with keyboard "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state","isActive":true,"type":"reference"},{"text":" and ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","isActive":true},{"type":"text","text":", to let you build great keyboards."}]},{"inlineContent":[{"text":"KeyboardKit injects observable state into the view hierarchy as environment objects, which lets you access various state types like this:","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["struct CustomView: View {","","    @EnvironmentObject","    var keyboardContext: KeyboardContext","","    var body: some View {","        ...","    }","}"]},{"inlineContent":[{"type":"text","text":"Services are not injected into the view hierarchy, and must be passed around. KeyboardKit uses init injection for both state and services."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"You can replace any services with custom implementations. For instance, here we replace the standard ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler","type":"reference"},{"text":":","type":"text"}]},{"type":"tabNavigator","tabs":[{"title":"KeyboardKit","content":[{"code":["class KeyboardViewController: KeyboardInputViewController {","","    override func viewDidLoad() {","        super.viewDidLoad()","        setup(for: .keyboardKitDemo)","        services.actionHandler = CustomActionHandler(controller: self)","    }","}"],"type":"codeListing","syntax":"swift"}]},{"title":"KeyboardKit Pro 👑","content":[{"syntax":"swift","code":["class KeyboardViewController: KeyboardInputViewController {","","    override func viewDidLoad() {","        super.viewDidLoad()","        setupPro(for: .keyboardKitDemo) { _ in ","            services.actionHandler = CustomActionHandler(controller: self)","        }","    }","}"],"type":"codeListing"}]}]},{"syntax":"swift","code":["class CustomActionHandler: StandardActionHandler {","","    open override func handle(_ action: KeyboardAction) {","        if action == .space {","            print(\"Pressed space!\")","        }","        super.handle(gesture, on: action) ","    }","}"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"Since services are lazy and resolved when they’re used for the first time, you should set up any custom services as early as possible."}],"type":"paragraph"},{"text":"Bonus - Set up KeyboardKit as a package dependency","level":2,"type":"heading","anchor":"Bonus-Set-up-KeyboardKit-as-a-package-dependency"},{"type":"tabNavigator","tabs":[{"title":"KeyboardKit","content":[{"inlineContent":[{"type":"text","text":"To set up KeyboardKit as a transient package dependency, just add it to package dependencies and link it to any target that needs it."}],"type":"paragraph"},{"syntax":"swift","code":["...","dependencies: [","    .package(","        url: \"https:\/\/github.com\/KeyboardKit\/KeyboardKit.git\",","        .upToNextMajor(from: \"9.0.0\")","    )","],","targets: [","    .target(","        name: \"MyPackage\",","        dependencies: [\"KeyboardKit\"]","    )","]"],"type":"codeListing"}]},{"title":"KeyboardKit Pro 👑","content":[{"inlineContent":[{"type":"text","text":"To set up KeyboardKit Pro as a package dependency, just add it to package dependencies and link it to any target that needs it."}],"type":"paragraph"},{"code":["...","dependencies: [","    .package(","        url: \"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro.git\",","        .upToNextMajor(from: \"9.0.0\")","    )","],","targets: [","    .target(","        name: \"MyPackage\",","        dependencies: [\"KeyboardKit\"]","    )","]"],"type":"codeListing","syntax":"swift"},{"name":"Important","content":[{"type":"paragraph","inlineContent":[{"text":"You don’t have to link to KeyboardKit Pro from any target that adds ","type":"text"},{"type":"emphasis","inlineContent":[{"text":"your","type":"text"}]},{"type":"text","text":" package, but the target "},{"inlineContent":[{"text":"must","type":"text"}],"type":"emphasis"},{"type":"text","text":" update its "},{"type":"strong","inlineContent":[{"type":"text","text":"runpath search paths"}]},{"type":"text","text":" under "},{"type":"strong","inlineContent":[{"type":"text","text":"Build Settings"}]},{"text":". Use ","type":"text"},{"type":"strong","inlineContent":[{"text":"@executable_path\/Frameworks","type":"text"}]},{"type":"text","text":" for the main app and "},{"inlineContent":[{"text":"@executable_path\/..\/..\/Frameworks","type":"text"}],"type":"strong"},{"text":" for the keyboard. Failing to set the search paths will cause a runtime crash when you try to use KeyboardKit Pro.","type":"text"}]}],"style":"important","type":"aside"}]}]},{"type":"heading","text":"That’s it!","anchor":"Thats-it","level":2},{"inlineContent":[{"type":"text","text":"You should now have a fully functional keyboard extension and companion app, which you can customize even further to fit your needs. For more information, see the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","isActive":true},{"type":"text","text":" article, as well as the other articles in this documentation."}],"type":"paragraph"},{"type":"thematicBreak"}]}],"kind":"article","references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp/ThemeScreen":{"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/ThemeScreen","navigatorTitle":[{"text":"ThemeScreen","kind":"identifier"}],"abstract":[{"type":"text","text":"This view can be used as a keyboard theme picker, in"},{"text":" ","type":"text"},{"type":"text","text":"a keyboard app or its keyboard extension."}],"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ThemeScreen","kind":"identifier"}],"title":"KeyboardApp.ThemeScreen","url":"\/documentation\/keyboardkitpro\/keyboardapp\/themescreen"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp/bundleId":{"kind":"symbol","role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardapp\/bundleid","title":"bundleId","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/bundleId","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bundleId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"deprecated":true},"https://github.com/KeyboardKit/KeyboardKitPro":{"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","title":"KeyboardKit Pro","titleInlineContent":[{"text":"KeyboardKit Pro","type":"text"}],"type":"link","url":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/state":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V","text":"Keyboard"},{"kind":"text","text":"."},{"text":"State","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V5StateC"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/state","title":"state","abstract":[{"type":"text","text":"Keyboard-specific state."}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/setupPro(for:errorDisplay:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupPro","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A3AppV","text":"KeyboardApp","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"errorDisplay"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A19InputViewControllerC29LicenseValidationErrorDisplayO","text":"LicenseValidationErrorDisplay"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A19InputViewControllerC25LicenseRegistrationResulta","text":"LicenseRegistrationResult"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setupPro(for:errorDisplay:completion:)","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/setuppro(for:errordisplay:completion:)","type":"topic","title":"setupPro(for:errorDisplay:completion:)","abstract":[{"text":"Set up KeyboardKit Pro for the provided ","type":"text"},{"code":"app","type":"codeVoice"},{"type":"text","text":"."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp/licenseKey":{"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardapp\/licensekey","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/licenseKey","title":"licenseKey","abstract":[{"text":"Your license key, if any.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"licenseKey","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"role":"symbol","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardView":{"role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"KeyboardView","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardview","type":"topic","abstract":[{"type":"text","text":"This view can be used to mimic a native iOS keyboard."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","title":"KeyboardView","navigatorTitle":[{"kind":"identifier","text":"KeyboardView"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/setupKeyboardView(_:)":{"abstract":[{"type":"text","text":"Set up KeyboardKit with a custom view and an unowned"},{"text":" ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController"},{"type":"text","text":" reference."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setupKeyboardView(_:)","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/setupkeyboardview(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupKeyboardView"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Content"},{"text":">((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"text":": ","kind":"text"},{"text":"KeyboardInputViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A19InputViewControllerC05setupaE0yyxACc7SwiftUI0E0RzlF7ContentL_xmfp","kind":"typeIdentifier","text":"Content"},{"text":")","kind":"text"}],"title":"setupKeyboardView(_:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp/LocaleScreen":{"navigatorTitle":[{"text":"LocaleScreen","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"This view can be used as a locale settings screen in"},{"type":"text","text":" "},{"type":"text","text":"a keyboard app or its keyboard extension."}],"type":"topic","title":"KeyboardApp.LocaleScreen","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"LocaleScreen","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardapp\/localescreen","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/LocaleScreen"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/UIKit/UIInputViewController":{"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","preciseIdentifier":"c:objc(cs)UIInputViewController","text":"UIInputViewController"}],"navigatorTitle":[{"kind":"identifier","text":"UIInputViewController"}],"type":"topic","kind":"symbol","url":"\/documentation\/keyboardkitpro\/uikit\/uiinputviewcontroller","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/UIKit\/UIInputViewController","title":"UIInputViewController","abstract":[],"role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp/SettingsScreen":{"type":"topic","navigatorTitle":[{"text":"SettingsScreen","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/SettingsScreen","url":"\/documentation\/keyboardkitpro\/keyboardapp\/settingsscreen","abstract":[{"type":"text","text":"This view can be used as the main settings screen in"},{"text":" ","type":"text"},{"type":"text","text":"a keyboard app or its keyboard extension."}],"role":"symbol","title":"KeyboardApp.SettingsScreen","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SettingsScreen"}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp/appGroupId":{"abstract":[{"type":"text","text":"The app’s App Group identifier, if any."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/appGroupId","role":"symbol","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardapp\/appgroupid","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"appGroupId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"appGroupId"},"Page.png":{"identifier":"Page.png","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png","traits":["1x","light"]}],"type":"image","alt":"Page icon"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Memory-Management-Guide":{"images":[{"type":"card","identifier":"Page.png"}],"type":"topic","kind":"article","url":"\/documentation\/keyboardkitpro\/memory-management-guide","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Memory-Management-Guide","title":"Memory Management","abstract":[{"type":"text","text":"This guide describes how to manage memory in a keyboard extensions."}],"role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Essentials-Article":{"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","type":"topic","title":"Essentials","role":"article","url":"\/documentation\/keyboardkitpro\/essentials-article","abstract":[{"type":"text","text":"This article describes the essential parts of KeyboardKit."}],"images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAppView":{"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAppView","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardAppView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardAppView"}],"abstract":[{"type":"text","text":"This view can be used as the root view of a keyboard app,"},{"text":" ","type":"text"},{"text":"to set up KeyboardKit for a certain ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","type":"reference","isActive":true},{"text":".","type":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardappview","type":"topic","title":"KeyboardAppView"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/services":{"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"services","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Keyboard","preciseIdentifier":"s:14KeyboardKitPro0A0V","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A0V8ServicesC","kind":"typeIdentifier","text":"Services"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","abstract":[{"text":"Keyboard-specific services.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/services","type":"topic","title":"services"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","kind":"symbol","abstract":[{"type":"text","text":"This enum defines keyboard-specific actions, and is also"},{"text":" ","type":"text"},{"type":"text","text":"a namespace for keyboard action-related types."}],"url":"\/documentation\/keyboardkitpro\/keyboardaction","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardAction","kind":"identifier"}],"title":"KeyboardAction","navigatorTitle":[{"kind":"identifier","text":"KeyboardAction"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/setup(for:)":{"abstract":[{"text":"Set up KeyboardKit for a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","isActive":true},{"text":".","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setup(for:)","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/setup(for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"KeyboardApp","preciseIdentifier":"s:14KeyboardKitPro0A3AppV"},{"kind":"text","text":")"}],"title":"setup(for:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/App-Article":{"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","type":"topic","title":"App Utilities","role":"article","url":"\/documentation\/keyboardkitpro\/app-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}],"images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"role":"symbol","title":"KeyboardInputViewController","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller","abstract":[{"type":"text","text":"This is the main input controller in a KeyboardKit-based"},{"type":"text","text":" "},{"text":"keyboard extension.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardInputViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardInputViewController"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardActionHandler":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"KeyboardActionHandler"}],"url":"\/documentation\/keyboardkitpro\/keyboardactionhandler","title":"KeyboardActionHandler","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler","role":"symbol","kind":"symbol","abstract":[{"text":"This protocol can be implemented by any classes that can","type":"text"},{"text":" ","type":"text"},{"text":"handle triggered ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","isActive":true},{"text":" events.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"KeyboardActionHandler","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp":{"role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardapp","abstract":[{"type":"text","text":"This type can be used to define important properties for"},{"text":" ","type":"text"},{"text":"your app, and is also a namespace for app-based features.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","title":"KeyboardApp","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"KeyboardApp"}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardApp"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"type":"topic","url":"\/documentation\/keyboardkitpro","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI."}],"title":"KeyboardKitPro","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp/HomeScreen":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/HomeScreen","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"HomeScreen","kind":"identifier"}],"title":"KeyboardApp.HomeScreen","navigatorTitle":[{"text":"HomeScreen","kind":"identifier"}],"abstract":[{"type":"text","text":"This screen can be used as the main home screen in a"},{"text":" ","type":"text"},{"text":"keyboard app, and resembles the iOS Settings app.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardapp\/homescreen","type":"topic"},"https://github.com/KeyboardKit/KeyboardKit":{"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKit","title":"KeyboardKit","titleInlineContent":[{"type":"text","text":"KeyboardKit"}],"type":"link","url":"https:\/\/github.com\/KeyboardKit\/KeyboardKit"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Settings":{"title":"Keyboard.Settings","url":"\/documentation\/keyboardkitpro\/keyboard\/settings","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Settings","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Settings","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"Settings","kind":"identifier"}],"abstract":[{"text":"This type is used for essential keyboard settings.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/viewWillSetupKeyboardView()":{"abstract":[{"type":"text","text":"This function is called when the controller is about"},{"type":"text","text":" "},{"type":"text","text":"to create or update the keyboard view."}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/viewwillsetupkeyboardview()","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewWillSetupKeyboardView()","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillSetupKeyboardView"},{"kind":"text","text":"()"}],"title":"viewWillSetupKeyboardView()","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/viewDidLoad()":{"abstract":[],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/viewdidload()","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewDidLoad()","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"kind":"text","text":"()"}],"title":"viewDidLoad()","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardStatus/Section":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStatus\/Section","abstract":[{"type":"text","text":"This section can be used to show keyboard status for"},{"type":"text","text":" "},{"type":"text","text":"a certain keyboard bundle ID."}],"url":"\/documentation\/keyboardkitpro\/keyboardstatus\/section","navigatorTitle":[{"kind":"identifier","text":"Section"}],"kind":"symbol","title":"KeyboardStatus.Section","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Section"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/seeAlsoSections","value":[{"title":"Guides","generated":true,"anchor":"Guides","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Memory-Management-Guide"]}],"op":"replace"},{"value":"KeyboardInputViewController","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"KeyboardInputViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"KeyboardInputViewController"}]},{"value":"viewDidLoad","op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1viewDidLoad()\/title"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1viewDidLoad()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}