{"primaryContentSections":[{"content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This guide goes through the steps of adding "},{"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKit"},{"type":"text","text":" or "},{"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro"},{"type":"text","text":" to your project and setting up the main app and keyboard."}]},{"type":"heading","level":2,"text":"Step 1. Add KeyboardKit to your project","anchor":"Step-1-Add-KeyboardKit-to-your-project"},{"type":"paragraph","inlineContent":[{"text":"The easiest way to add KeyboardKit to your app or package is with the Swift Package Manager. You can either use ","type":"text"},{"isActive":true,"overridingTitle":"KeyboardKit","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKit","type":"reference","overridingTitleInlineContent":[{"type":"text","text":"KeyboardKit"}]},{"text":" or the more capable, commercially licensed ","type":"text"},{"isActive":true,"overridingTitle":"KeyboardKit Pro","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","type":"reference","overridingTitleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}]},{"text":":","type":"text"}]},{"code":["https:\/\/github.com\/KeyboardKit\/KeyboardKit.git      \/\/ or...","https:\/\/github.com\/KeyboardKit\/KeyboardKitPro.git"],"type":"codeListing","syntax":null},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit must be linked to the main app target "},{"inlineContent":[{"type":"text","text":"and"}],"type":"emphasis"},{"type":"text","text":" its keyboard extension, while KeyboardKit Pro must "},{"inlineContent":[{"text":"only","type":"text"}],"type":"emphasis"},{"type":"text","text":" be added to the app."}]},{"type":"heading","level":2,"text":"Step 2. Define app-specific information","anchor":"Step-2-Define-app-specific-information"},{"type":"paragraph","inlineContent":[{"text":"The easiest way to set up KeyboardKit is with a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","type":"reference","isActive":true},{"text":" that can define a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/bundleId","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/appGroupId","type":"reference","isActive":true},{"text":", a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/licenseKey","type":"reference","isActive":true},{"text":", etc.","type":"text"}]},{"code":["import KeyboardKit (or KeyboardKitPro)","","extension KeyboardApp {","","    static var keyboardKitDemo: KeyboardApp {","        .init(","            name: \"KeyboardKit\",","            licenseKey: \"your-key-here\",                \/\/ Required by KeyboardKit Pro!","            appGroupId: \"group.com.keyboardkit.demo\",   \/\/ Sets up App Group data sync","            locales: .keyboardKitSupported,             \/\/ Sets up the enabled locales","            autocomplete: .init(                        \/\/ Sets up custom autocomplete  ","                nextWordPredictionRequest: .claude(...) \/\/ Sets up AI-based prediction","            ),","            deepLinks: .init(app: \"kkdemo:\/\/\", ...)     \/\/ Defines how to open the app","        )","    }","}"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"Define this in a file that you add to the app ","type":"text"},{"type":"emphasis","inlineContent":[{"type":"text","text":"and"}]},{"text":" its keyboard extension, to be able to use it in both targets. See ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","type":"reference"},{"text":" for more info.","type":"text"}]},{"type":"heading","level":2,"text":"Step 3. Set up the keyboard extension","anchor":"Step-3-Set-up-the-keyboard-extension"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To use KeyboardKit, first make your controller inherit "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","type":"reference","isActive":true},{"type":"text","text":" instead of "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/UIKit\/UIInputViewController","type":"reference","isActive":true},{"type":"text","text":":"}]},{"code":["import KeyboardKit (or KeyboardKitPro)","","class KeyboardController: KeyboardInputViewController {}"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"This adds tons of capabilities to the controller, new lifecycle functions, as well as keyboard-specific ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","type":"reference"},{"text":" and observable ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state","type":"reference"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can now set up KeyboardKit for the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","type":"reference","isActive":true},{"type":"text","text":" we created, by calling "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setup(for:completion:)","type":"reference","isActive":true},{"type":"text","text":" in "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewDidLoad()","type":"reference","isActive":true},{"type":"text","text":":"}]},{"code":["class KeyboardViewController: KeyboardInputViewController {","","    override func viewDidLoad() {","        super.viewDidLoad()","        ","        \/\/ Set up the keyboard with the app we created above","        setup(for: .keyboardKitDemo) { result in","            \/\/ If the result is `.success`, the setup succeeded.","            \/\/ This is where you can setup custom services, etc.","        }","    }","}"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"This will set up ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings","type":"reference","isActive":true},{"text":" to automatically sync data between the app and the keyboard if the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","type":"reference","isActive":true},{"text":" defines an ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/appGroupId","type":"reference","isActive":true},{"text":", set up KeyboardKit Pro if it defines a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/licenseKey","type":"reference","isActive":true},{"text":", register deep links, set up dictation, etc.","type":"text"}]},{"type":"heading","level":2,"text":"Step 4. Customize the keyboard view (optional)","anchor":"Step-4-Customize-the-keyboard-view-optional"},{"type":"paragraph","inlineContent":[{"text":"To replace or customize the default ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView"},{"text":", just override ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewWillSetupKeyboardView()"},{"text":" and call ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setupKeyboardView(_:)"},{"text":" with the view that you want to use:","type":"text"}]},{"code":["class KeyboardViewController: KeyboardInputViewController {","","    override func viewWillSetupKeyboardView() {","        setupKeyboardView { [weak self] controller in \/\/ <-- Use weak or unknowned if you must use self!","            CustomKeyboardView( ","                state: controller.state","                services: controller.services","            )","        }","    }","}","","\/\/ Defining a custom view in a separate file keeps your controller clean.","struct CustomKeyboardView: View {","","    \/\/ These properties are provided when creating the custom keyboard view.","    var state: Keyboard.State","    var services: Keyboard.Services","","    \/\/ All observable keyboard state can be accessed from the enviroment.","    @EnvironmentObject var keyboardContext: KeyboardContext","","    var body: some View {","        if keyboardContext.keyboardType == .email {","            \/\/ You can customize your keyboard view for any observable state","        } else {","            KeyboardView(","                state: state,","                services: services,","                buttonContent: { $0.view },        \/\/ Use $0.view to use the standard view","                buttonView: { $0.view },           \/\/ The $0 arg has additional properties             ","                collapsedView: { params in params.view },   \/\/ This is the same as $0.view","                emojiKeyboard: { $0.view },        ","                toolbar: { _ in CustomToolbar() }  \/\/ This code ignores the input parameters","            )","        }","    }","}"],"type":"codeListing","syntax":"swift"},{"style":"important","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Passing in the controller into a keyboard view can easily result in a memory leak, if you forget to make the controller reference weak or unowned. The ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setupKeyboardView(_:)","type":"reference"},{"text":" view builder therefore provides you with an unowned controller reference, to avoid memory leaks. If you must refer to your specific controller type, you MUST use ","type":"text"},{"code":"[weak self]","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"[unowned self]","type":"codeVoice"},{"text":" as you can see above! Also make sure to define your custom view in a separate struct, since this helps avoiding controller misuse.","type":"text"}]}],"name":"Important"},{"type":"heading","level":2,"text":"Step 5. Set up the main app (optional)","anchor":"Step-5-Set-up-the-main-app-optional"},{"type":"paragraph","inlineContent":[{"text":"The main app target can be used to display the enabled and Full Access status of your keyboard, link to Settings, etc. It’s a great place for keyboard settings, since it has more space than the keyboard extension.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The easiest way to set up an app target is to use "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAppView"},{"type":"text","text":" as the root view, with the same "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp"},{"type":"text","text":" as the keyboard:"}]},{"code":["@main","struct MyApp: App {","","    var body: some Scene {","        WindowGroup {","            KeyboardAppView(for: .keyboardKitDemo) {","                ContentView() \/\/ <-- The \"real\" app root","            }","        }","    }","}"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"This will set up the app in the same way as the keyboard, register your Pro license before rendering the content view, etc. You can use any view as content view, and use any Pro features you want, since the app view will redraw the content view after registering a license.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"See "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article"},{"type":"text","text":" for more information about how to easily set up a full-blown keyboard app with KeyboardKit Pro’s various app utilities."}]},{"type":"heading","level":2,"text":"Step 6. Customize state & services (optional)","anchor":"Step-6-Customize-state--services-optional"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The main "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","isActive":true},{"type":"text","text":" provides you with keyboard "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state","isActive":true},{"type":"text","text":" and "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","isActive":true},{"type":"text","text":", to let you build great keyboards."}]},{"type":"paragraph","inlineContent":[{"text":"You can change any observable state at any time, to affect the keyboard. For instance, changing the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/State\/keyboardContext","isActive":true,"type":"reference"},{"text":" ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/keyboardType","isActive":true,"type":"reference"},{"text":" will automatically change which keyboard that is rendered. Each observable context also has its own auto-persisted ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/settings-swift.property","isActive":true,"type":"reference"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit will inject all observable context types into the environment. This means that you can access them from anywhere, like this:","type":"text"}]},{"code":["struct CustomView: View {","","    @EnvironmentObject var keyboardContext: KeyboardContext","    ","    ...","}"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Services are not injected into the view hierarchy, and must be passed around. KeyboardKit uses init injection for both state and services."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can replace any services with custom implementations. For instance, here we replace the standard "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler"},{"type":"text","text":":"}]},{"code":["class KeyboardViewController: KeyboardInputViewController {","","    override func viewDidLoad() {","        super.viewDidLoad()","        setup(for: .keyboardKitDemo) { [weak self] _ in","            guard let self else { return }","            self.services.actionHandler = CustomActionHandler(controller: self)    ","        }","    }","}","","class CustomActionHandler: KeyboardAction.StandardActionHandler {","","    open override func handle(_ action: KeyboardAction) {","        if action == .space {","            print(\"Pressed space!\")","        }","        super.handle(action) ","    }","}"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"Since services are lazy and resolved when they’re used for the first time, you should set up any custom services as early as possible.","type":"text"}]},{"style":"important","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Any keyboard customizations that rely on Pro features must be made within the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setup(for:completion:)"},{"type":"text","text":" completion block."}]}],"name":"Important"},{"type":"heading","level":2,"text":"Bonus - Set up KeyboardKit as a package dependency","anchor":"Bonus-Set-up-KeyboardKit-as-a-package-dependency"},{"type":"tabNavigator","tabs":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"To set up KeyboardKit as a transient package dependency, just add it to package dependencies and link it to any target that needs it."}]},{"type":"codeListing","code":["...","dependencies: [","    .package(","        url: \"https:\/\/github.com\/KeyboardKit\/KeyboardKit.git\",","        .upToNextMajor(from: \"9.0.0\")","    )","],","targets: [","    .target(","        name: \"MyPackage\",","        dependencies: [\"KeyboardKit\"]","    )","]"],"syntax":"swift"}],"title":"KeyboardKit"},{"content":[{"inlineContent":[{"text":"To set up KeyboardKit Pro as a package dependency, just add it to package dependencies and link it to any target that needs it.","type":"text"}],"type":"paragraph"},{"code":["...","dependencies: [","    .package(","        url: \"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro.git\",","        .upToNextMajor(from: \"9.0.0\")","    )","],","targets: [","    .target(","        name: \"MyPackage\",","        dependencies: [\"KeyboardKitPro\"]","    )","]"],"syntax":"swift","type":"codeListing"},{"content":[{"inlineContent":[{"type":"text","text":"You don’t have to link KeyboardKit Pro to any target that adds "},{"inlineContent":[{"type":"text","text":"your"}],"type":"emphasis"},{"type":"text","text":" package, but the target "},{"inlineContent":[{"type":"text","text":"must"}],"type":"emphasis"},{"type":"text","text":" update its "},{"inlineContent":[{"type":"text","text":"runpath search paths"}],"type":"strong"},{"type":"text","text":" under "},{"inlineContent":[{"text":"Build Settings","type":"text"}],"type":"strong"},{"type":"text","text":". Use "},{"inlineContent":[{"type":"text","text":"@executable_path\/Frameworks"}],"type":"strong"},{"type":"text","text":" for an app and "},{"inlineContent":[{"type":"text","text":"@executable_path\/..\/..\/Frameworks"}],"type":"strong"},{"type":"text","text":" for its keyboard. Failing to set the search paths will cause a runtime crash when you try to use KeyboardKit Pro."}],"type":"paragraph"}],"style":"important","type":"aside","name":"Important"}],"title":"KeyboardKit Pro 👑"}]},{"type":"heading","level":2,"text":"That’s it!","anchor":"Thats-it"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You should now have a fully functional keyboard extension and companion app, which you can customize even further to fit your needs. For more information, see the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","isActive":true},{"type":"text","text":" article, as well as the other articles in this documentation."}]},{"type":"thematicBreak"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started-Article"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkitpro\/getting-started-article"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkitpro\/getting-started-article"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"This guide describes how to get started with KeyboardKit.","type":"text"}],"seeAlsoSections":[{"title":"Essentials","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-KeyboardView"],"generated":true,"anchor":"Essentials"}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"metadata":{"roleHeading":"Article","title":"Getting Started","role":"article","images":[{"identifier":"Page.png","type":"card"}],"modules":[{"name":"KeyboardKitPro"}]},"sections":[],"kind":"article","references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller","title":"KeyboardInputViewController","kind":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","abstract":[{"type":"text","text":"This is the main input controller in a KeyboardKit-based"},{"type":"text","text":" "},{"type":"text","text":"keyboard extension."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardInputViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardInputViewController"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardView":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardView"}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","abstract":[{"type":"text","text":"This view can be used to mimic a native iOS keyboard."}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardView"}],"title":"KeyboardView","url":"\/documentation\/keyboardkitpro\/keyboardview"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/state":{"role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/state","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state","abstract":[{"text":"Keyboard-specific state.","type":"text"}],"type":"topic","kind":"symbol","title":"state","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Keyboard","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V"},{"text":".","kind":"text"},{"text":"State","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V5StateC"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/App-Article":{"title":"App Utilities","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","role":"article","url":"\/documentation\/keyboardkitpro\/app-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}],"images":[{"type":"card","identifier":"Page.png"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAppView":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAppView","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardAppView"}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardAppView"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardappview","kind":"symbol","abstract":[{"text":"This view can be used as the root view of a keyboard app,","type":"text"},{"text":" ","type":"text"},{"text":"to set up KeyboardKit for a certain ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","type":"reference"},{"text":".","type":"text"}],"title":"KeyboardAppView"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Essentials-Article":{"abstract":[{"type":"text","text":"This article describes the essential parts of KeyboardKit."}],"type":"topic","kind":"article","role":"article","title":"Essentials","url":"\/documentation\/keyboardkitpro\/essentials-article","images":[{"identifier":"Page.png","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article"},"Page.png":{"identifier":"Page.png","alt":"Page icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png","traits":["1x","light"]}],"type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/viewWillSetupKeyboardView()":{"type":"topic","title":"viewWillSetupKeyboardView()","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewWillSetupKeyboardView()","role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/viewwillsetupkeyboardview()","abstract":[{"type":"text","text":"This function is called when the controller is about"},{"type":"text","text":" "},{"type":"text","text":"to create or update the keyboard view."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillSetupKeyboardView","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/viewDidLoad()":{"navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewDidLoad()","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/viewdidload()","role":"symbol","title":"viewDidLoad()","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction":{"navigatorTitle":[{"text":"KeyboardAction","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardAction","kind":"identifier"}],"abstract":[{"text":"This enum defines keyboard-specific actions, and is also","type":"text"},{"text":" ","type":"text"},{"text":"a namespace for keyboard action-related types.","type":"text"}],"title":"KeyboardAction","url":"\/documentation\/keyboardkitpro\/keyboardaction"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"abstract":[{"text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI.","type":"text"}],"title":"KeyboardKitPro","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","role":"collection","url":"\/documentation\/keyboardkitpro","kind":"symbol","type":"topic"},"https://github.com/KeyboardKit/KeyboardKitPro":{"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","title":"KeyboardKit Pro","url":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","titleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"type":"link"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp/bundleId":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/bundleId","url":"\/documentation\/keyboardkitpro\/keyboardapp\/bundleid","title":"bundleId","deprecated":true,"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bundleId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardActionHandler":{"navigatorTitle":[{"text":"KeyboardActionHandler","kind":"identifier"}],"title":"KeyboardActionHandler","abstract":[{"type":"text","text":"This protocol can be implemented by any classes that can"},{"type":"text","text":" "},{"type":"text","text":"handle triggered "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","type":"reference"},{"type":"text","text":" events."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardActionHandler","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardactionhandler","type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/State/keyboardContext":{"abstract":[{"type":"text","text":"The keyboard context to use."}],"kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboard\/state\/keyboardcontext","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/State\/keyboardContext","role":"symbol","title":"keyboardContext","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardContext","kind":"identifier"},{"text":": ","kind":"text"},{"text":"KeyboardContext","preciseIdentifier":"s:14KeyboardKitPro0A7ContextC","kind":"typeIdentifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/setup(for:completion:)":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Set up KeyboardKit Pro for the provided app."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setup(for:completion:)","title":"setup(for:completion:)","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/setup(for:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setup","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"KeyboardApp","preciseIdentifier":"s:14KeyboardKitPro0A3AppV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"License","preciseIdentifier":"s:14KeyboardKitPro7LicenseV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp/licenseKey":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Your license key, if any."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/licenseKey","title":"licenseKey","url":"\/documentation\/keyboardkitpro\/keyboardapp\/licensekey","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"licenseKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardSettings":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardSettings","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardsettings","navigatorTitle":[{"text":"KeyboardSettings","kind":"identifier"}],"type":"topic","abstract":[{"text":"This type is used for essential keyboard settings.","type":"text"}],"title":"KeyboardSettings"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/setupKeyboardView(_:)":{"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/setupkeyboardview(_:)","title":"setupKeyboardView(_:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setupKeyboardView(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupKeyboardView","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Content","kind":"genericParameter"},{"text":">((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"KeyboardInputViewController","preciseIdentifier":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Content","preciseIdentifier":"s:14KeyboardKitPro0A19InputViewControllerC05setupaE0yyxACc7SwiftUI0E0RzlF7ContentL_xmfp","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Set up KeyboardKit with a custom view and an unowned"},{"type":"text","text":" "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","isActive":true,"type":"reference"},{"type":"text","text":" reference."}],"type":"topic","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Essentials-KeyboardView":{"kind":"article","type":"topic","abstract":[{"type":"text","text":"This article describes the essential "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","isActive":true},{"type":"text","text":" and how to use and configure it."}],"title":"Essentials - KeyboardView","url":"\/documentation\/keyboardkitpro\/essentials-keyboardview","role":"article","images":[{"type":"card","identifier":"Page.png"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-KeyboardView"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardApp","kind":"identifier"}],"title":"KeyboardApp","role":"symbol","type":"topic","navigatorTitle":[{"text":"KeyboardApp","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","abstract":[{"type":"text","text":"This type can be used to define important properties for"},{"type":"text","text":" "},{"type":"text","text":"your app, and is also a namespace for app-based features."}],"url":"\/documentation\/keyboardkitpro\/keyboardapp"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/UIKit/UIInputViewController":{"kind":"symbol","role":"symbol","abstract":[],"title":"UIInputViewController","url":"\/documentation\/keyboardkitpro\/uikit\/uiinputviewcontroller","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/UIKit\/UIInputViewController","navigatorTitle":[{"text":"UIInputViewController","kind":"identifier"}],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIInputViewController","text":"UIInputViewController","kind":"identifier"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/services":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"services","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A0V","text":"Keyboard","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A0V8ServicesC","text":"Services","kind":"typeIdentifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/services","abstract":[{"text":"Keyboard-specific services.","type":"text"}],"role":"symbol","type":"topic","title":"services","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services"},"https://github.com/KeyboardKit/KeyboardKit":{"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKit","title":"KeyboardKit","url":"https:\/\/github.com\/KeyboardKit\/KeyboardKit","titleInlineContent":[{"type":"text","text":"KeyboardKit"}],"type":"link"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp/appGroupId":{"url":"\/documentation\/keyboardkitpro\/keyboardapp\/appgroupid","abstract":[{"type":"text","text":"The app’s App Group identifier, if any."}],"title":"appGroupId","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/appGroupId","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appGroupId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/settings-swift.property":{"title":"settings","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"settings","kind":"identifier"},{"text":": ","kind":"text"},{"text":"KeyboardSettings","preciseIdentifier":"s:14KeyboardKitPro0A8SettingsV","kind":"typeIdentifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardcontext\/settings-swift.property","type":"topic","abstract":[{"text":"Auto-persisted keyboard settings.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/settings-swift.property","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/keyboardType":{"url":"\/documentation\/keyboardkitpro\/keyboardcontext\/keyboardtype","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Keyboard","preciseIdentifier":"s:14KeyboardKitPro0A0V","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"KeyboardType","preciseIdentifier":"s:14KeyboardKitPro0A0V0A4TypeO","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/keyboardType","title":"keyboardType","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The keyboard type that is currently used."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/topicSections"},{"value":[{"anchor":"Essentials","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-KeyboardView"],"title":"Essentials","generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"value":"KeyboardInputViewController","op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title"},{"value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments"},{"value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/navigatorTitle"},{"value":"viewDidLoad","op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1viewDidLoad()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1viewDidLoad()\/fragments"}]}]}