{"abstract":[{"type":"text","text":"This article describes how KeyboardKit can identify the host application."}],"seeAlsoSections":[{"generated":true,"title":"Features","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"anchor":"Features"}],"sections":[],"kind":"article","hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"inlineContent":[{"type":"text","text":"KeyboardKit provides ways to easily identify the host application, which may be of interest for many reasons, e.g. to vary the style or functionality of a keyboard based on the currently active app."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"👑 "},{"type":"reference","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","isActive":true},{"type":"text","text":" unlocks an additional keyboard host application enum, that defines many common apps, and makes it easier to identify and navigate to specific apps."}],"type":"paragraph"},{"text":"Host Application Bundle Identifier","level":2,"type":"heading","anchor":"Host-Application-Bundle-Identifier"},{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController"},{"text":" has a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/hostApplicationBundleId","isActive":true,"type":"reference"},{"type":"text","text":" property that tries to resolve the bundle identifier for the application that is currently using the keyboard."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext","isActive":true},{"type":"text","text":" also has a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/hostApplicationBundleId","isActive":true,"type":"reference"},{"text":" property that is kept in sync with the controller. Since you should not pass around the controller, this property may be more convenient to use within your code.","type":"text"}]},{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationContext","isActive":true,"type":"reference"},{"type":"text","text":" also has a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationContext\/hostApplicationBundleId"},{"type":"text","text":", but unlike the others, this is used to tell the main app which app to navigate back to after the main app has finished a dictation operation."}]},{"anchor":"%F0%9F%91%91-KeyboardKit-Pro","text":"👑 KeyboardKit Pro","type":"heading","level":2},{"inlineContent":[{"overridingTitleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"overridingTitle":"KeyboardKit Pro","isActive":true,"type":"reference","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro"},{"type":"text","text":" unlocks more ways to identify the current host application."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro Gold unlocks a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardHostApplication","isActive":true},{"type":"text","text":" enum that defines many popular applications, and also tells you how to navigate to some of them, using app-specific URL schemes."}]},{"inlineContent":[{"type":"text","text":"Since it’s impossible to define all apps that exist in the App Store, this enum just aims to cover the most popular ones. Reach out if you miss any app, or if an existing one stops working."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro also extends ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext","type":"reference"},{"type":"text","text":", and "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationContext","isActive":true},{"type":"text","text":" with a "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardHostApplicationProvider\/hostApplication","type":"reference"},{"type":"text","text":" property, that tries to map the raw bundle identifier to a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardHostApplication"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"All in all, This means that KeyboardKit Pro makes it easier to identify and navigate to many of the most popular apps in the App Store."}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/keyboardkitpro\/host-article"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkitpro\/host-article"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article"},"metadata":{"role":"article","roleHeading":"Article","images":[{"type":"card","identifier":"Page.png"}],"color":{"standardColorIdentifier":"blue"},"modules":[{"name":"KeyboardKitPro"}],"title":"Host Utilities"},"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","title":"Layout","role":"article","abstract":[{"text":"This article describes the KeyboardKit layout engine.","type":"text"}],"images":[{"type":"card","identifier":"Page.png"}],"url":"\/documentation\/keyboardkitpro\/layout-article","kind":"article","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","title":"Localization","role":"article","type":"topic","kind":"article","abstract":[{"text":"This article describes the KeyboardKit localization engine.","type":"text"}],"images":[{"identifier":"Page.png","type":"card"}],"url":"\/documentation\/keyboardkitpro\/localization-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"images":[{"identifier":"Page.png","type":"card"}],"role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/actions-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit action engine."}],"title":"Actions"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/DictationContext/hostApplicationBundleId":{"title":"hostApplicationBundleId","kind":"symbol","abstract":[{"text":"The bundle ID of the app that is using the keyboard.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hostApplicationBundleId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationContext\/hostApplicationBundleId","url":"\/documentation\/keyboardkitpro\/dictationcontext\/hostapplicationbundleid","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete-Article":{"images":[{"type":"card","identifier":"Page.png"}],"role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/autocomplete-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}],"title":"Autocomplete"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Previews-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","url":"\/documentation\/keyboardkitpro\/previews-article","title":"Previews","role":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit preview engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures-Article":{"images":[{"identifier":"Page.png","type":"card"}],"role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/gestures-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit gesture engine."}],"title":"Gestures"},"Page.png":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png","traits":["1x","light"]}],"alt":"Page icon","identifier":"Page.png","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Device-Article":{"kind":"article","url":"\/documentation\/keyboardkitpro\/device-article","type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit device utilities."}],"title":"Device Utilities","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Styling-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","url":"\/documentation\/keyboardkitpro\/styling-article","title":"Styling","role":"article","images":[{"type":"card","identifier":"Page.png"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit styling engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/App-Article":{"title":"App Utilities","abstract":[{"text":"This article describes the KeyboardKit app-specific utilities.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","url":"\/documentation\/keyboardkitpro\/app-article","role":"article","type":"topic","images":[{"identifier":"Page.png","type":"card"}],"kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","url":"\/documentation\/keyboardkitpro\/proxy-article","title":"Proxy Utilities","role":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit proxy engine and its utilities."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardHostApplication":{"role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardhostapplication","abstract":[{"text":"This enum defines a list of known applications, that can","type":"text"},{"text":" ","type":"text"},{"text":"be used to identify the keyboard host application.","type":"text"}],"title":"KeyboardHostApplication","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"KeyboardHostApplication"}],"type":"topic","navigatorTitle":[{"text":"KeyboardHostApplication","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardHostApplication"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","url":"\/documentation\/keyboardkitpro","abstract":[{"type":"text","text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI."}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","title":"KeyboardKitPro","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/hostApplicationBundleId":{"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/hostApplicationBundleId","abstract":[{"text":"The bundle ID of the keyboard host application.","type":"text"}],"type":"topic","title":"hostApplicationBundleId","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hostApplicationBundleId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardcontext\/hostapplicationbundleid"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Essentials-Article":{"images":[{"identifier":"Page.png","type":"card"}],"kind":"article","url":"\/documentation\/keyboardkitpro\/essentials-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","role":"article","title":"Essentials","abstract":[{"type":"text","text":"This article describes the essential parts of KeyboardKit."}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","title":"External Keyboards","role":"article","type":"topic","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit external keyboard engine."}],"images":[{"identifier":"Page.png","type":"card"}],"url":"\/documentation\/keyboardkitpro\/external-keyboards-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/DictationContext":{"navigatorTitle":[{"kind":"identifier","text":"DictationContext"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DictationContext"}],"abstract":[{"text":"This class has observable states and persistent settings,","type":"text"},{"type":"text","text":" "},{"text":"as well as a couple of persisted properties that are not","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"considered settings, but carry state between the app and"},{"type":"text","text":" "},{"text":"its keyboard extension.","type":"text"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/dictationcontext","title":"DictationContext","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationContext"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Text-Input-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","url":"\/documentation\/keyboardkitpro\/text-input-article","title":"Text Input","role":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit text input engine, which lets you type within the keyboard extension."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Navigation-Article":{"title":"Navigation","abstract":[{"type":"text","text":"This article describes the KeyboardKit navigation engine."}],"type":"topic","role":"article","images":[{"type":"card","identifier":"Page.png"}],"url":"\/documentation\/keyboardkitpro\/navigation-article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Settings-Article":{"url":"\/documentation\/keyboardkitpro\/settings-article","kind":"article","title":"Settings","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit settings engine."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","type":"topic","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","url":"\/documentation\/keyboardkitpro\/callouts-article","title":"Callouts","role":"article","images":[{"type":"card","identifier":"Page.png"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/hostApplicationBundleId":{"abstract":[{"type":"text","text":"The bundle ID of the host application, if any, or if the view"},{"type":"text","text":" "},{"type":"text","text":"is instantiated directly within a host app, the bundle id"},{"text":" ","type":"text"},{"text":"of the main bundle.","type":"text"}],"kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/hostapplicationbundleid","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hostApplicationBundleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/hostApplicationBundleId","role":"symbol","title":"hostApplicationBundleId"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","url":"\/documentation\/keyboardkitpro\/dictation-article","title":"Dictation","role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}]},"https://github.com/KeyboardKit/KeyboardKitPro":{"title":"KeyboardKit Pro","url":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","titleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"type":"link","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AI-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","url":"\/documentation\/keyboardkitpro\/ai-article","title":"AI Support","role":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit AI support capabilities."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback-Article":{"images":[{"type":"card","identifier":"Page.png"}],"role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/feedback-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit feedback engine."}],"title":"Feedback"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext":{"url":"\/documentation\/keyboardkitpro\/keyboardcontext","title":"KeyboardContext","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext","abstract":[{"text":"This class has observable states and persistent settings.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"KeyboardContext","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"KeyboardContext","kind":"identifier"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"type":"topic","title":"KeyboardInputViewController","kind":"symbol","role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"KeyboardInputViewController","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","navigatorTitle":[{"kind":"identifier","text":"KeyboardInputViewController"}],"abstract":[{"text":"This is the main input controller in a KeyboardKit-based","type":"text"},{"type":"text","text":" "},{"text":"keyboard extension.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Themes-Article":{"images":[{"type":"card","identifier":"Page.png"}],"role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/themes-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit Pro theme engine, which can be used to style the entire keyboard with a single theme."}],"title":"Themes"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Status-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","url":"\/documentation\/keyboardkitpro\/status-article","title":"Status","role":"article","images":[{"type":"card","identifier":"Page.png"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit status engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardHostApplicationProvider/hostApplication":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hostApplication","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A15HostApplicationO","text":"KeyboardHostApplication"},{"text":"?","kind":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardHostApplicationProvider\/hostApplication","kind":"symbol","abstract":[{"type":"text","text":"The host application, if any."}],"title":"hostApplication","url":"\/documentation\/keyboardkitpro\/keyboardhostapplicationprovider\/hostapplication"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis-Article":{"images":[{"type":"card","identifier":"Page.png"}],"role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/emojis-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"title":"Emojis"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/seeAlsoSections","value":[{"anchor":"Features","generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"title":"Features"}],"op":"replace"},{"value":"KeyboardInputViewController","op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments","value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"op":"replace"},{"value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/navigatorTitle"}]}]}