{"kind":"article","hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article"},"metadata":{"roleHeading":"Article","role":"article","title":"Input","images":[{"identifier":"Page.png","type":"card"}],"modules":[{"name":"KeyboardKitPro"}]},"abstract":[{"type":"text","text":"This article describes the KeyboardKit input engine."}],"seeAlsoSections":[{"title":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article"],"generated":true,"anchor":"Articles"}],"primaryContentSections":[{"content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Custom iOS keyboards use a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/UIKit\/UITextDocumentProxy","isActive":true,"type":"reference"},{"text":" to modify text, move the input cursor, provide input-related information, etc.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This proxy points to the currently selected text field in the currently active app, and will "},{"type":"emphasis","inlineContent":[{"type":"text","text":"not"}]},{"type":"text","text":" detect if you focus on a text field inside the keyboard extension. Text that you type will still be sent to the currently active app."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks text input views that let you type directly within a keyboard extension, as well as "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Vietnamese"},{"type":"text","text":" input support."}]},{"text":"Text routing","anchor":"Text-routing","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext"},{"text":" has a custom ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/textInputProxy"},{"text":" that can be set to route text to any other text field or custom proxy. You can always access the original text document proxy with the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/originalTextDocumentProxy"},{"text":" property.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","isActive":true,"type":"reference"},{"text":" has similar properties, but you should avoid referring to it and passing it within your code.","type":"text"}]},{"text":"👑 KeyboardKit Pro","anchor":"%F0%9F%91%91-KeyboardKit-Pro","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","isActive":true,"type":"reference"},{"type":"text","text":" unlocks a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextField","isActive":true,"type":"reference"},{"type":"text","text":" and "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextView","isActive":true,"type":"reference"},{"type":"text","text":" that let you type directly within a keyboard extension by automatically registering themselves as "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/textInputProxy","isActive":true,"type":"reference"},{"type":"text","text":" when they get focus"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro also unlocks additional "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextInput"},{"type":"text","text":" support, like "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Vietnamese"},{"type":"text","text":", to let you to type in locale-specific ways."}]},{"text":"🇻🇳 Vietnamese Input (BETA)","anchor":"%F0%9F%87%BB%F0%9F%87%B3-Vietnamese-Input-BETA","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Vietnamese","isActive":true},{"type":"text","text":" namespace, with Vietnamese-related types, as well as a  "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/VietnameseInputEngine","isActive":true},{"type":"text","text":" that supports typing with TELEX, VIQR, and VNI."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro will automatically use the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/VietnameseInputEngine","isActive":true},{"type":"text","text":" when applicable. You can also use these types as standalone features to implement Vietnamese input support elsewhere."}]},{"style":"important","name":"Important","type":"aside","content":[{"inlineContent":[{"type":"text","text":"Vietnamese typing requires a "},{"type":"codeVoice","code":"Gold"},{"type":"text","text":" license."}],"type":"paragraph"}]},{"text":"Input Views","anchor":"Input-Views","type":"heading","level":3},{"type":"tabNavigator","tabs":[{"title":"KeyboardTextField","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextField","type":"reference","isActive":true},{"text":" component wraps a native text field and can be used for single-line text input inside a keyboard extension.","type":"text"}]}]},{"title":"KeyboardTextView","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextView"},{"text":" component wraps a native text view and can be used for multi-line text input inside a keyboard extension.","type":"text"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Both views support "},{"type":"codeVoice","code":"@FocusState"},{"type":"text","text":", and have a custom "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/focused(_:doneButton:)"},{"type":"text","text":" view modifier that lets you provide a custom done button that slides in when the view is focused, and can be tapped to end editing:"}]},{"code":["struct CustomKeyboardToolbar: View {","","    unowned var controller: KeyboardInputViewController","","    @State ","    private var text = \"\"","","    @FocusState ","    private var isTextFieldFocused","","    var body: some View {","        if hasFullAccess {","            KeyboardTextField(","                \"Type here...\", ","                text: $text, ","                controller: controller,","                config: configureTextField,","                onSubmit: handleReturnKeyPressed    ","                \/\/ Use onSubmit: to detect the return key.","                \/\/ The onSubmit(...) view modifier doesn't work.","            )","            .focused($isTextFieldFocused) {","                Image(systemName: \"xmark.circle.fill\")","            }","        }","    }","    ","    func configureTextField(_ view: UITextField) {","        \/\/ Configure the underlying view in any way you want.","    }","    ","    func handleReturnKeyPressed() {","        print(\"Return key pressed!\")","    }","}"],"type":"codeListing","syntax":"swift"},{"style":"note","name":"Note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextField","type":"reference","isActive":true},{"type":"text","text":" and "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextView","type":"reference","isActive":true},{"type":"text","text":" require at least a "},{"type":"codeVoice","code":"Silver"},{"type":"text","text":" license."}],"type":"paragraph"}]},{"style":"important","name":"Important","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"These views require Full Access, due to an iOS bug that causes a crash when using them while Full Access is disabled. They will automatically disable themselves when Full Access is disabled."}]}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/keyboardkitpro\/input-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/input-article"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"title":"Callouts","kind":"article","url":"\/documentation\/keyboardkitpro\/callouts-article","role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardTextView":{"abstract":[{"text":"This view can be used to type within keyboard extensions.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardTextView"}],"title":"KeyboardTextView","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardTextView"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextView","url":"\/documentation\/keyboardkitpro\/keyboardtextview"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"url":"\/documentation\/keyboardkitpro","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"type":"topic","title":"KeyboardKitPro","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Host-Article":{"kind":"article","role":"article","images":[{"identifier":"Page.png","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","url":"\/documentation\/keyboardkitpro\/host-article","type":"topic","title":"Host Application","abstract":[{"type":"text","text":"This article describes how KeyboardKit Pro can identify and use the host application."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}],"url":"\/documentation\/keyboardkitpro\/autocomplete-article","type":"topic","title":"Autocomplete","role":"article","images":[{"identifier":"Page.png","type":"card"}],"kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"role":"article","url":"\/documentation\/keyboardkitpro\/localization-article","abstract":[{"text":"This article describes the KeyboardKit localization engine.","type":"text"}],"type":"topic","title":"Localization","images":[{"identifier":"Page.png","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards-Article":{"role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","url":"\/documentation\/keyboardkitpro\/external-keyboards-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"title":"External Keyboards"},"Page.png":{"type":"image","alt":"Page icon","identifier":"Page.png","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation-Article":{"abstract":[{"text":"This article describes the KeyboardKit dictation engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/dictation-article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","type":"topic","images":[{"identifier":"Page.png","type":"card"}],"role":"article","title":"Dictation"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/VietnameseInputEngine":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VietnameseInputEngine"}],"navigatorTitle":[{"kind":"identifier","text":"VietnameseInputEngine"}],"url":"\/documentation\/keyboardkitpro\/vietnameseinputengine","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/VietnameseInputEngine","abstract":[{"text":"This Vietnamese typing engine can be used to resolve any","type":"text"},{"text":" ","type":"text"},{"text":"diacritic replacements when typing in Vietnamese.","type":"text"}],"type":"topic","title":"VietnameseInputEngine","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/textInputProxy":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/textInputProxy","url":"\/documentation\/keyboardkitpro\/keyboardcontext\/textinputproxy","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textInputProxy","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UITextDocumentProxy","preciseIdentifier":"c:objc(pl)UITextDocumentProxy","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"A custom text proxy to which text can be routed."}],"type":"topic","title":"textInputProxy","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback-Article":{"images":[{"identifier":"Page.png","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","url":"\/documentation\/keyboardkitpro\/feedback-article","type":"topic","role":"article","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"kind":"article","title":"Feedback"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardTextInput":{"type":"topic","title":"KeyboardTextInput","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardTextInput"}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardTextInput"}],"url":"\/documentation\/keyboardkitpro\/keyboardtextinput","deprecated":true,"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextInput"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AI-Article":{"abstract":[{"text":"This article describes the KeyboardKit AI support capabilities.","type":"text"}],"role":"article","type":"topic","kind":"article","images":[{"identifier":"Page.png","type":"card"}],"url":"\/documentation\/keyboardkitpro\/ai-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","title":"AI Support"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/App-Article":{"url":"\/documentation\/keyboardkitpro\/app-article","type":"topic","kind":"article","role":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","title":"App Utilities"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Device-Article":{"role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","url":"\/documentation\/keyboardkitpro\/device-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit device utilities."}],"title":"Device Utilities"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"images":[{"identifier":"Page.png","type":"card"}],"title":"Actions","url":"\/documentation\/keyboardkitpro\/actions-article","kind":"article","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller","navigatorTitle":[{"text":"KeyboardInputViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"This is the main input controller in a KeyboardKit-based"},{"type":"text","text":" "},{"type":"text","text":"keyboard extension."}],"role":"symbol","title":"KeyboardInputViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardInputViewController","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","type":"topic","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardTextField":{"title":"KeyboardTextField","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextField","navigatorTitle":[{"text":"KeyboardTextField","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardtextfield","abstract":[{"type":"text","text":"This view can be used to type within keyboard extensions."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardTextField","kind":"identifier"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext":{"url":"\/documentation\/keyboardkitpro\/keyboardcontext","title":"KeyboardContext","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardContext"}],"abstract":[{"type":"text","text":"This class has observable states and persistent settings"},{"type":"text","text":" "},{"type":"text","text":"for the core keyboard functionality."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardContext"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures-Article":{"type":"topic","images":[{"identifier":"Page.png","type":"card"}],"kind":"article","url":"\/documentation\/keyboardkitpro\/gestures-article","role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit gesture engine."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","title":"Gestures"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/UIKit/UITextDocumentProxy":{"kind":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITextDocumentProxy","preciseIdentifier":"c:objc(pl)UITextDocumentProxy","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/UIKit\/UITextDocumentProxy","abstract":[],"navigatorTitle":[{"text":"UITextDocumentProxy","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/uikit\/uitextdocumentproxy","title":"UITextDocumentProxy"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"abstract":[{"text":"This article describes the KeyboardKit layout engine.","type":"text"}],"title":"Layout","kind":"article","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","url":"\/documentation\/keyboardkitpro\/layout-article","type":"topic","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUICore/View/focused(_:doneButton:)":{"title":"focused(_:doneButton:)","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/focused(_:doneButton:)","url":"\/documentation\/keyboardkitpro\/swiftuicore\/view\/focused(_:donebutton:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"focused","kind":"identifier"},{"text":"<","kind":"text"},{"text":"DoneButton","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"FocusState","preciseIdentifier":"s:7SwiftUI10FocusStateV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":">.","kind":"text"},{"text":"Binding","preciseIdentifier":"s:7SwiftUI10FocusStateV7BindingV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"doneButton","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"text":"DoneButton","preciseIdentifier":"s:7SwiftUI4ViewP14KeyboardKitProE7focused_10doneButtonQrAA10FocusStateV7BindingVySb_G_qd__yctAaBRd__lFQO04DoneI0qd__mfp","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Apply a "},{"type":"codeVoice","code":"FocusState"},{"type":"text","text":" with a "},{"type":"codeVoice","code":"doneButton"},{"type":"text","text":" that slides"},{"type":"text","text":" "},{"type":"text","text":"in and out as the view gets and loses focus."}],"type":"topic","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis-Article":{"url":"\/documentation\/keyboardkitpro\/emojis-article","type":"topic","title":"Emojis","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"text":"This article describes the KeyboardKit emoji engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","kind":"article","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Navigation-Article":{"abstract":[{"text":"This article describes the KeyboardKit navigation engine.","type":"text"}],"title":"Navigation","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","images":[{"identifier":"Page.png","type":"card"}],"role":"article","url":"\/documentation\/keyboardkitpro\/navigation-article","kind":"article"},"https://github.com/KeyboardKit/KeyboardKitPro":{"type":"link","title":"KeyboardKit Pro","titleInlineContent":[{"text":"KeyboardKit Pro","type":"text"}],"url":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Vietnamese":{"abstract":[{"type":"text","text":"This is a namespace for Vietnamese types."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Vietnamese"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Vietnamese","type":"topic","url":"\/documentation\/keyboardkitpro\/vietnamese","title":"Vietnamese","navigatorTitle":[{"kind":"identifier","text":"Vietnamese"}],"kind":"symbol","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/originalTextDocumentProxy":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/originalTextDocumentProxy","url":"\/documentation\/keyboardkitpro\/keyboardcontext\/originaltextdocumentproxy","title":"originalTextDocumentProxy","type":"topic","role":"symbol","abstract":[{"text":"The original text document proxy.","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"originalTextDocumentProxy","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UITextDocumentProxy","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UITextDocumentProxy"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"title":"Articles","generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article"],"anchor":"Articles"}],"path":"\/seeAlsoSections"},{"op":"replace","value":"KeyboardInputViewController","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"KeyboardInputViewController"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments"},{"op":"replace","value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/navigatorTitle"}]}]}