{"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Overall, KeyboardKit tries to separate its parts into descriptive namespaces, but in the "},{"type":"codeVoice","code":"Keyboard"},{"type":"text","text":" case, the types in this namespace are tightly coupled with the keyboard in particular, which means that "},{"type":"codeVoice","code":"Keyboard"},{"type":"text","text":" is its own namespace."}]},{"anchor":"Keyboard-context","level":2,"type":"heading","text":"Keyboard context"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has an observable "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext"},{"type":"text","text":" class that provides information about the keyboard extension, such as a reference to the current "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/textDocumentProxy"},{"type":"text","text":", the current "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/keyboardType"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/locale"},{"type":"text","text":" etc."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit will by default create a context instance and apply it to the input controller’s "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/keyboardContext"},{"type":"text","text":". You can configure this instance to change the keyboard behavior. It will also sync with the input controller whenever needed."}]},{"anchor":"Keyboard-enabled-state","level":2,"type":"heading","text":"Keyboard enabled state"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has a few types that can be used to inspect the enabled and active state of a keyboard:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardEnabledStateInspector"},{"type":"text","text":" is a protocol that can be implemented by any type that should be able to inspect the state of a keyboard extension, such as if it’s enabled in System Settings, if it is being used, if Full Access is enabled etc."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardEnabledState"},{"type":"text","text":" is an observable class that keeps itself in sync when the keyboard state changes. It has published properties that you can use to keep your UI in sync."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardEnabledLabel"},{"type":"text","text":" is a basic view that can display all these states in the same way."}]}]}]},{"anchor":"Keyboard-types","level":2,"type":"heading","text":"Keyboard types"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardType"},{"type":"text","text":" enum that defines many different keyboard types, such as:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardType\/alphabetic(_:)"},{"type":"text","text":" - represents an alphabetic keyboard."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardType\/numeric"},{"type":"text","text":" - represents a numeric keyboard."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardType\/symbolic"},{"type":"text","text":" - represents a symbolic keyboard."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardType\/email"},{"type":"text","text":" - represents an e-mail keyboard."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardType\/emojis"},{"type":"text","text":" - represents an emoji keyboard."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardType\/images"},{"type":"text","text":" - represents an image keyboard."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardType\/custom(named:)"},{"type":"text","text":" - a custom type if no other types fit your needs"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note that some keyboard types require custom handling."}]},{"anchor":"How-to-change-keyboard-type","level":2,"type":"heading","text":"How to change keyboard type"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To change the current keyboard type, just set "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext"},{"type":"text","text":"’s "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/keyboardType"},{"type":"text","text":". However, this will not have any effect unless you actually use the type to create a keyboard view that you present to the user."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you do use the context’s keyboard type, changing it will automatically update the UI."}]},{"anchor":"Views","level":2,"type":"heading","text":"Views"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Besides the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardEnabledLabel"},{"type":"text","text":", there is also a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/NextKeyboardButton"},{"type":"text","text":" that can be used to switch to the next keyboard, which corresponds to tapping the 🌐 button."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/keyboardkitpro\/keyboard"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/keyboard"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This article describes the KeyboardKit keyboard types and how to use them."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Keyboard","role":"article","modules":[{"name":"KeyboardKitPro"}]},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"seeAlsoSections":[{"title":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Appearance","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Extensions","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Routing","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/RTL","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings"],"generated":true}],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardType/alphabetic(_:)":{"role":"symbol","title":"KeyboardType.alphabetic(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"alphabetic"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"KeyboardCase","preciseIdentifier":"s:14KeyboardKitPro0A4CaseO"},{"kind":"text","text":")"}],"abstract":[{"type":"codeVoice","code":".alphabetic"},{"type":"text","text":" represents keyboards that have alphabetic"},{"type":"text","text":" "},{"type":"text","text":"input keys for the current locale."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardType\/alphabetic(_:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardtype\/alphabetic(_:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardType/symbolic":{"role":"symbol","title":"KeyboardType.symbolic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"symbolic"}],"abstract":[{"type":"codeVoice","code":".symbolic"},{"type":"text","text":" represents keyboards that have symbol input"},{"type":"text","text":" "},{"type":"text","text":"keys for the current locale."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardType\/symbolic","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardtype\/symbolic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization":{"role":"article","title":"Localization","abstract":[{"type":"text","text":"This article describes the KeyboardKit localization model and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/localization"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","title":"KeyboardKitPro","abstract":[{"type":"text","text":"KeyboardKit Pro helps you build custom keyboard extensions for iOS and iPadOS."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardType/emojis":{"role":"symbol","title":"KeyboardType.emojis","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"emojis"}],"abstract":[{"type":"codeVoice","code":".emoji"},{"type":"text","text":" represents keyboards that either present emoji"},{"type":"text","text":" "},{"type":"text","text":"characters or emoji categories."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardType\/emojis","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardtype\/emojis"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardType/numeric":{"role":"symbol","title":"KeyboardType.numeric","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"numeric"}],"abstract":[{"type":"codeVoice","code":".numeric"},{"type":"text","text":" represents keyboards that have numeric input"},{"type":"text","text":" "},{"type":"text","text":"keys for the current locale."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardType\/numeric","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardtype\/numeric"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLocale/persian":{"role":"symbol","title":"KeyboardLocale.persian","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"persian"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale\/persian","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardlocale\/persian"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Input":{"role":"article","title":"Input","abstract":[{"type":"text","text":"This article describes the KeyboardKit input set engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/input"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete":{"role":"article","title":"Autocomplete","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/autocomplete"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Appearance":{"role":"article","title":"Appearance","abstract":[{"type":"text","text":"This article describes the KeyboardKit appearance engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Appearance","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/appearance"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions":{"role":"article","title":"Actions","abstract":[{"type":"text","text":"This article describes the KeyboardKit action engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/actions"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardEnabledState":{"role":"symbol","title":"KeyboardEnabledState","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardEnabledState"}],"abstract":[{"type":"text","text":"This observable class can be used to observe the state of a"},{"type":"text","text":" "},{"type":"text","text":"keyboard extension."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardEnabledState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardEnabledState"}],"url":"\/documentation\/keyboardkitpro\/keyboardenabledstate"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext":{"role":"symbol","title":"KeyboardContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardContext"}],"abstract":[{"type":"text","text":"This class provides keyboard extensions with contextual and"},{"type":"text","text":" "},{"type":"text","text":"observable information about the keyboard extension itself."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardContext"}],"url":"\/documentation\/keyboardkitpro\/keyboardcontext"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardEnabledStateInspector":{"role":"symbol","title":"KeyboardEnabledStateInspector","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardEnabledStateInspector"}],"abstract":[{"type":"text","text":"This protocol can be implemented by any type that can check"},{"type":"text","text":" "},{"type":"text","text":"state state of keyboard extensions."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardEnabledStateInspector","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardEnabledStateInspector"}],"url":"\/documentation\/keyboardkitpro\/keyboardenabledstateinspector"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback":{"role":"article","title":"Feedback","abstract":[{"type":"text","text":"This article describes the KeyboardKit feedback engine and how to use it to trigger audio and haptic feedback."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/feedback"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards":{"role":"article","title":"External Keyboards","abstract":[{"type":"text","text":"This article describes the KeyboardKit external keyboard engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/external-keyboards"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/keyboardType":{"role":"symbol","title":"keyboardType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardType","preciseIdentifier":"s:14KeyboardKitPro0A4TypeO"}],"abstract":[{"type":"text","text":"The keyboard type that is currently used."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/keyboardType","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardcontext\/keyboardtype"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Previews":{"role":"article","title":"Previews","abstract":[{"type":"text","text":"This article describes how KeyboardKit makes it easy to preview keyboard-specific views."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/previews"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts":{"role":"article","title":"Callouts","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/callouts"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout":{"role":"article","title":"Layouts","abstract":[{"type":"text","text":"This article describes the KeyboardKit keyboard layout engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/layout"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/NextKeyboardButton":{"role":"symbol","title":"NextKeyboardButton","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NextKeyboardButton"}],"abstract":[{"type":"text","text":"This button makes any view behave as a next keyboard button,"},{"type":"text","text":" "},{"type":"text","text":"which switches to the next keyboard when tapped and opens a"},{"type":"text","text":" "},{"type":"text","text":"keyboard switcher menu when pressed."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/NextKeyboardButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NextKeyboardButton"}],"url":"\/documentation\/keyboardkitpro\/nextkeyboardbutton"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/textDocumentProxy":{"role":"symbol","title":"textDocumentProxy","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textDocumentProxy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextDocumentProxy","preciseIdentifier":"c:objc(pl)UITextDocumentProxy"}],"abstract":[{"type":"text","text":"The text document proxy that is currently active."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/textDocumentProxy","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardcontext\/textdocumentproxy"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy-Extensions":{"role":"article","title":"Proxy Extensions","abstract":[{"type":"text","text":"This article describes how KeyboardKit extends "},{"type":"codeVoice","code":"UITextDocumentProxy"},{"type":"text","text":" with a lot of additional functionality."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Extensions","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/proxy-extensions"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardType/custom(named:)":{"role":"symbol","title":"KeyboardType.custom(named:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"custom"},{"kind":"text","text":"("},{"kind":"externalParam","text":"named"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"codeVoice","code":".custom"},{"type":"text","text":" can be used to indicate that keyboards should"},{"type":"text","text":" "},{"type":"text","text":"use an entirely custom type."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardType\/custom(named:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardtype\/custom(named:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLocale/arabic":{"role":"symbol","title":"KeyboardLocale.arabic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"arabic"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale\/arabic","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardlocale\/arabic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Routing":{"role":"article","title":"Routing","abstract":[{"type":"text","text":"This article describes how KeyboardKit adds ways for you to route text from the main app to other text fields within the keyboard."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Routing","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/routing"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures":{"role":"article","title":"Gestures","abstract":[{"type":"text","text":"This article describes the KeyboardKit gesture engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/gestures"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis":{"role":"article","title":"Emojis","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji model and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/emojis"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardType/images":{"role":"symbol","title":"KeyboardType.images","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"images"}],"abstract":[{"type":"codeVoice","code":".image"},{"type":"text","text":" represents keyboards that present custom image"},{"type":"text","text":" "},{"type":"text","text":"buttons with custom handing."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardType\/images","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardtype\/images"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Settings":{"role":"article","title":"Settings","abstract":[{"type":"text","text":"This article describes the KeyboardKit settings utilities and how to use them."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/settings"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardType/email":{"role":"symbol","title":"KeyboardType.email","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"email"}],"abstract":[{"type":"codeVoice","code":".email"},{"type":"text","text":" represents keyboards that have e-mail specific"},{"type":"text","text":" "},{"type":"text","text":"input keys for the current locale."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardType\/email","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardtype\/email"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/keyboardContext":{"role":"symbol","title":"keyboardContext","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardContext","preciseIdentifier":"s:14KeyboardKitPro0A7ContextC"}],"abstract":[{"type":"text","text":"The default, observable keyboard context."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/keyboardContext","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/keyboardcontext"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/locale":{"role":"symbol","title":"locale","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"locale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Locale","preciseIdentifier":"s:10Foundation6LocaleV"}],"abstract":[{"type":"text","text":"The locale that is currently being used."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/locale","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardcontext\/locale"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardEnabledLabel":{"role":"symbol","title":"KeyboardEnabledLabel","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardEnabledLabel"}],"abstract":[{"type":"text","text":"This label can be used to show different views depending on"},{"type":"text","text":" "},{"type":"text","text":"a provided enabled state."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardEnabledLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardEnabledLabel"}],"url":"\/documentation\/keyboardkitpro\/keyboardenabledlabel"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardType":{"role":"symbol","title":"KeyboardType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardType"}],"abstract":[{"type":"text","text":"This enum contains all keyboard types that can currently be"},{"type":"text","text":" "},{"type":"text","text":"bound to the "},{"type":"codeVoice","code":"KeyboardAction"},{"type":"text","text":" switch keyboard action."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardType"}],"url":"\/documentation\/keyboardkitpro\/keyboardtype"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/RTL":{"role":"article","title":"RTL","abstract":[{"type":"text","text":"KeyboardKit supports RTL (right-to-left) locales, which means that it supports locales like "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale\/arabic"},{"type":"text","text":",  "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale\/persian"},{"type":"text","text":" etc."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/RTL","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/rtl"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Appearance","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Extensions","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Routing","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/RTL","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}