{"seeAlsoSections":[{"title":"Articles","anchor":"Articles","generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkitpro\/layout-article"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkitpro\/layout-article"]}],"metadata":{"role":"article","title":"Layout","images":[{"identifier":"Page.png","type":"card"}],"modules":[{"name":"KeyboardKitPro"}],"roleHeading":"Article"},"abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}],"primaryContentSections":[{"kind":"content","content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"While most keyboards have 3 input rows surrounded by action keys, and a bottom row with space bar and action keys, this is not true for all locales. The layout can vary greatly, which means that the layout engine must be flexible."}]},{"type":"paragraph","inlineContent":[{"text":"In KeyboardKit, an ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet"},{"text":" defines the input keys of a keyboard, after which a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayoutService"},{"text":" can create a dynamic ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout"},{"text":" at runtime that defines the full set of keys to render for the keyboard.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"👑 ","type":"text"},{"type":"reference","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","isActive":true},{"text":" unlocks extensions that make it easier to modify layouts, adds more input sets like ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet\/qwertz","isActive":true},{"text":", ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet\/azerty","isActive":true},{"text":", ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet\/colemak","isActive":true},{"text":" and ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet\/dvorak","isActive":true},{"text":", and unlocks iPad Pro support and localized input sets & layouts for all locales in your license.","type":"text"}]},{"text":"Namespace","anchor":"Namespace","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout"},{"type":"text","text":" type that is also a namespace for other layout-related types like "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout\/DeviceConfiguration"},{"type":"text","text":"."}]},{"text":"Input Sets & Layouts","anchor":"Input-Sets--Layouts","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"In KeyboardKit an ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet","isActive":true,"type":"reference"},{"text":" specifies the input keys of a keyboard, while a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout","isActive":true,"type":"reference"},{"text":" specifies the full set of keys. Layouts can vary greatly for different devices, screens, locales, etc.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit comes with pre-defined input sets, like "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet\/qwerty"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet\/numeric(currency:)"},{"type":"text","text":" & "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet\/symbolic(currencies:)"},{"type":"text","text":". KeyboardKit Pro unlocks more input sets, like "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet\/qwertz"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet\/azerty"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet\/colemak"},{"type":"text","text":" & "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet\/dvorak"},{"type":"text","text":", as well as locale-specific input sets for all supported locales."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro makes certain layouts support multiple "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/LayoutType"},{"type":"text","text":"s, which means that you can use various layouts for e.g. English."}]},{"text":"Services","anchor":"Services","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"In KeyboardKit, a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayoutService"},{"type":"text","text":" can generate dynamic layouts at runtime, It provides us with the flexibility we need, to accomodate to the varying needs for different locales, devices, etc."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit injects "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout\/StandardLayoutService","type":"reference","isActive":true},{"type":"text","text":" into "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","type":"reference","isActive":true},{"type":"text","text":". You can replace it at any time, as described further down, or add custom services to it with "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayoutService\/tryRegisterLocalizedService(_:)","type":"reference","isActive":true},{"type":"text","text":"."}]},{"type":"thematicBreak"},{"text":"👑 KeyboardKit Pro","anchor":"%F0%9F%91%91-KeyboardKit-Pro","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"overridingTitle":"KeyboardKit Pro","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","overridingTitleInlineContent":[{"text":"KeyboardKit Pro","type":"text"}],"isActive":true,"type":"reference"},{"text":" unlocks more input sets, like ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet\/qwertz","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet\/azerty","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet\/colemak","isActive":true,"type":"reference"},{"text":" and ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet\/dvorak","isActive":true,"type":"reference"},{"text":", plus alphabetic, numeric & symbolic sets and locale-specific layout services for all ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Foundation\/Locale\/keyboardKitSupported","isActive":true,"type":"reference"},{"text":" locales that are included in your license.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro will automatically set up all input sets and layout services in your license, and use them when you change ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/locale","isActive":true},{"text":" and ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/keyboardLayoutType","isActive":true},{"text":", but you can also use them individually, as standalone features:","type":"text"}]},{"code":["let swedishInputSet = try InputSet.swedish","let swedishService = try KeyboardLayout.ProLayoutService.Swedish()"],"syntax":"swift","type":"codeListing"},{"type":"paragraph","inlineContent":[{"text":"These input sets and services will throw a license error if you try to access them without first registering a valid KeyboardKit Pro license. If you are on the Basic or Silver plan, you must specify which locales to use in your ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp"},{"text":". See ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started-Article"},{"text":" for instructions.","type":"text"}]},{"text":"iPad Pro Support","anchor":"iPad-Pro-Support","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks an "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout\/iPadProLayoutService","isActive":true,"type":"reference"},{"type":"text","text":" that can generate iPad Pro-specific layouts for most supported locales."}]},{"type":"paragraph","inlineContent":[{"identifier":"keyboardview-ipadpro","type":"image"}]},{"text":"Keyboard Layout Extensions","anchor":"Keyboard-Layout-Extensions","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro extends "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout","type":"reference"},{"type":"text","text":" and its related types and collections to make it easier to add, remove, and replace items."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"See "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout"},{"type":"text","text":" and the nested layout "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout\/Item"},{"type":"text","text":" type in the KeyboardKit Pro documentation for a full list of additional capabilities."}]},{"text":"Locales With Multiple Layouts","anchor":"Locales-With-Multiple-Layouts","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro extends "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Foundation\/Locale","isActive":true},{"type":"text","text":" with a list of "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Foundation\/Locale\/supportedLayoutTypes","isActive":true},{"type":"text","text":" and makes the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/LocaleScreen","isActive":true},{"type":"text","text":" add a layout picker to all added locales that support multiple layouts."}]},{"items":[{"content":[{"inlineContent":[{"inlineContent":[{"text":"Catalan","type":"text"}],"type":"strong"},{"text":": QWERY - Catalan, QWERTY, AZERTY, QWERTZ, Colemak, Dvorak","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Croatian","type":"text"}],"type":"strong"},{"text":": QWERTZ, QWERTY, AZERTY, Colemak, Dvorak","type":"text"}]}]},{"content":[{"inlineContent":[{"inlineContent":[{"type":"text","text":"Dutch"}],"type":"strong"},{"text":": QWERTY, AZERTY, QWERTZ, Colemak, Dvorak","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Dutch_belgium"}]},{"type":"text","text":": AZERTY, QWERTY, QWERTZ, Colemak, Dvorak"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"text":"English","type":"text"}]},{"type":"text","text":": QWERTY, AZERTY, QWERTZ, Colemak, Dvorak"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"English_australia"}]},{"type":"text","text":": QWERTY, AZERTY, QWERTZ, Colemak, Dvorak"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"English_canada","type":"text"}],"type":"strong"},{"text":": QWERTY, AZERTY, QWERTZ, Colemak, Dvorak","type":"text"}]}]},{"content":[{"inlineContent":[{"inlineContent":[{"type":"text","text":"English_gb"}],"type":"strong"},{"type":"text","text":": QWERTY, AZERTY, QWERTZ, Colemak, Dvorak"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"English_us","type":"text"}],"type":"strong"},{"text":": QWERTY, AZERTY, QWERTZ, Colemak, Dvorak","type":"text"}]}]},{"content":[{"inlineContent":[{"inlineContent":[{"text":"Estonian","type":"text"}],"type":"strong"},{"type":"text","text":": QWERTY, QWERTZ, AZERTY, .colemak"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Hungarian"}]},{"type":"text","text":": QWERTZ, QWERTY, AZERTY, Colemak, Dvorak"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"inlineContent":[{"type":"text","text":"Indonesian"}],"type":"strong"},{"type":"text","text":": QWERTY, QWERTZ, AZERTY, Colemak, Dvorak"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Irish","type":"text"}],"type":"strong"},{"text":": QWERTY, QWERTZ, AZERTY, Colemak, Dvorak","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Italian","type":"text"}],"type":"strong"},{"text":": QWERTY, AZERTY, QWERTZ, Colemak, Dvorak","type":"text"}]}]},{"content":[{"inlineContent":[{"inlineContent":[{"type":"text","text":"Latvian"}],"type":"strong"},{"type":"text","text":": QWERTY, QWERTZ, AZERTY, Colemak, Dvorak"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"text":"Malay","type":"text"}]},{"text":": QWERTY, QWERTZ, AZERTY, Colemak, Dvorak","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"inlineContent":[{"text":"Polish","type":"text"}],"type":"strong"},{"text":": QWERTY, QWERTZ, AZERTY, Colemak, Dvorak","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"inlineContent":[{"text":"Portuguese","type":"text"}],"type":"strong"},{"text":": QWERTY, AZERTY, QWERTZ, Colemak, Dvorak","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Portuguese_brazil"}]},{"type":"text","text":": QWERTY, AZERTY, QWERTZ, Colemak, Dvorak"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Romanian","type":"text"}],"type":"strong"},{"text":": QWERTY, QWERTZ, AZERTY, Colemak, Dvorak","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Serbian_latin"}]},{"type":"text","text":": QWERTY, QWERTZ, AZERTY, Colemak, Dvorak"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Slovenian"}]},{"type":"text","text":": QWERTZ, QWERTY, AZERTY, Colemak, Dvorak"}]}]},{"content":[{"inlineContent":[{"inlineContent":[{"type":"text","text":"Swahili"}],"type":"strong"},{"type":"text","text":": QWERTY, AZERTY, QWERTZ, Colemak, Dvorak"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Uzbek","type":"text"}],"type":"strong"},{"text":": QWERTY, AZERTY, QWERTZ, Colemak, Dvorak","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"text":"Vietnamese","type":"text"}]},{"text":" TELEX, VIQR, VNI (QWERTY, AZERTY, QWERTZ for all)","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"Welsh","type":"text"}]},{"text":": QWERTY, AZERTY, QWERTZ, Colemak, Dvorak","type":"text"}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"text":"All ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout\/ProLayoutService","isActive":true},{"text":" implementations use the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/keyboardLayoutType","isActive":true},{"text":" to adjust their alphabetic input set for the current type.","type":"text"}]},{"type":"thematicBreak"},{"text":"How to…","anchor":"How-to","type":"heading","level":2},{"text":"…create a custom layout service","anchor":"create-a-custom-layout-service","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"text":"You can create a custom ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayoutService"},{"text":" to customize the layout for a certain locale, device type, or complete layout.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"You can implement the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayoutService"},{"text":" protocol from scratch, or inherit and customize ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout\/StandardLayoutService"},{"text":" or any of the available ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout\/iPadLayoutService"},{"text":", ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout\/iPadProLayoutService"},{"text":", or ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout\/iPhoneLayoutService"},{"text":" base classes:","type":"text"}]},{"code":["class CustomKeyboardLayoutService: KeyboardLayout.StandardLayoutService {","    ","    override func keyboardLayout(for context: KeyboardContext) -> KeyboardLayout {","        var layout = super.keyboardLayout(for: context)","        \/\/ Perform any modifications here","        \/\/ 💡 KeyboardKit Pro unlocks many layout extensions","        return layout","    }","}"],"syntax":"swift","type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To use your custom service instead of the standard one, just inject it into "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services"},{"type":"text","text":" by replacing its "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Services\/layoutService"},{"type":"text","text":" property:"}]},{"code":["class KeyboardViewController: KeyboardInputViewController {","","    override func viewDidLoad() {","        super.viewDidLoad()","        services.layoutService = CustomKeyboardLayoutService()","    }","}"],"syntax":"swift","type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This will make KeyboardKit use your custom implementation instead of the standard one."}]},{"text":"…customize a localized layout service","anchor":"customize-a-localized-layout-service","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"Service that inherit "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout\/StandardLayoutService","isActive":true},{"type":"text","text":" can use "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayoutService\/tryRegisterLocalizedService(_:)","isActive":true},{"type":"text","text":" or the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Services","isActive":true},{"type":"text","text":" convenient "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Services\/tryRegisterLocalizedLayoutService(_:)","isActive":true},{"type":"text","text":" function to register a custom service for a certain locale, for instance:"}]},{"code":["class MyCustomGermanService: KeyboardLayout.ProLayoutService.German { ... } ","","class KeyboardViewController: KeyboardInputViewController {","","    override func viewDidLoad() {","        super.viewDidLoad()","        setup(for: ...) { result in","            \/\/ Check result to see that setup was successful","            self.services.tryRegisterLocalizedLayoutService(","                try! MyCustomGermanService() ","            )","        }","    }","}"],"syntax":"swift","type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This makes it easy to replace the service for a certain locale, since you can inherit and customize the related "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout\/ProLayoutService","isActive":true},{"type":"text","text":"."}]},{"text":"…customize the layout for a certain locale","anchor":"customize-the-layout-for-a-certain-locale","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"Most "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout\/ProLayoutService"},{"type":"text","text":" implementations in KeyboardKit Pro lets you specify custom input sets when you initialize them. This can for instance be used to use another alphabetic layout for locales that support it:"}]},{"code":["class KeyboardViewController: KeyboardInputViewController {","","    override func viewDidLoad() {","        super.viewDidLoad()","        setup(for: ...) { _ in","            \/\/ Check result to see that setup was successful","            try? self?.services.tryRegisterLocalizedLayoutService(","                KeyboardLayout.ProLayoutService.English(","                    alphabeticInputSet: try? .qwertz","                )","            )","        }","    }","}"],"syntax":"swift","type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can use the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Foundation\/Locale\/supportedLayoutTypes"},{"type":"text","text":" information that KeyboardKit Pro unlocks to check if a locale supports a certain layout. A layout service that is provided with an unsupported layout type may render it incorrectly."}]},{"text":"…override the layout type for a certain locale","anchor":"override-the-layout-type-for-a-certain-locale","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit has a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/selectLocale(_:layoutType:)","type":"reference"},{"text":" that can be used to set both the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/locale","type":"reference"},{"text":" and ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/keyboardLayoutType","type":"reference"},{"text":". The layout type will be used to override the default layout type of certain layout services.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This function is automatically used when you use the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/addedLocales"},{"type":"text","text":" collection to manually set a keyboard layout type for a certain locale. Both the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/selectNextLocale()"},{"type":"text","text":" and the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Foundation\/Locale\/ContextMenu"},{"type":"text","text":" will use this function to set both properties properly."}]}]}],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","interfaceLanguage":"swift"},"kind":"article","hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Foundation/Locale":{"url":"\/documentation\/keyboardkitpro\/foundation\/locale","role":"symbol","type":"topic","navigatorTitle":[{"text":"Locale","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Foundation\/Locale","title":"Locale","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Locale","kind":"identifier","preciseIdentifier":"s:10Foundation6LocaleV"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/InputSet/numeric(currency:)":{"kind":"symbol","role":"symbol","url":"\/documentation\/keyboardkitpro\/inputset\/numeric(currency:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet\/numeric(currency:)","type":"topic","title":"numeric(currency:)","abstract":[{"type":"text","text":"A standard numeric input set."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numeric"},{"kind":"text","text":"("},{"kind":"externalParam","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"InputSet","preciseIdentifier":"s:14KeyboardKitPro8InputSetV"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}],"url":"\/documentation\/keyboardkitpro\/autocomplete-article","type":"topic","title":"Autocomplete","role":"article","images":[{"identifier":"Page.png","type":"card"}],"kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Services":{"role":"symbol","abstract":[{"text":"This type specifies global keyboard services.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"Services","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Services","kind":"identifier"}],"title":"Keyboard.Services","url":"\/documentation\/keyboardkitpro\/keyboard\/services","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Services"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback-Article":{"images":[{"identifier":"Page.png","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","url":"\/documentation\/keyboardkitpro\/feedback-article","type":"topic","role":"article","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"kind":"article","title":"Feedback"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/selectLocale(_:layoutType:)":{"abstract":[{"type":"text","text":"Select a locale with an optional layout type."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/selectLocale(_:layoutType:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectLocale","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Locale","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV"},{"text":", ","kind":"text"},{"text":"layoutType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Keyboard","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V"},{"text":".","kind":"text"},{"text":"LayoutType","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V10LayoutTypeO"},{"text":"?)","kind":"text"}],"title":"selectLocale(_:layoutType:)","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardcontext\/selectlocale(_:layouttype:)","role":"symbol","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLayoutService/tryRegisterLocalizedService(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tryRegisterLocalizedService","kind":"identifier"},{"text":"(","kind":"text"},{"text":"KeyboardLayoutService","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A13LayoutServiceP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayoutService\/tryRegisterLocalizedService(_:)","url":"\/documentation\/keyboardkitpro\/keyboardlayoutservice\/tryregisterlocalizedservice(_:)","role":"symbol","title":"tryRegisterLocalizedService(_:)","kind":"symbol","type":"topic","abstract":[{"text":"Try to register a localized layout service.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/enabledLocales":{"title":"enabledLocales","url":"\/documentation\/keyboardkitpro\/keyboardcontext\/enabledlocales","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enabledLocales","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Locale","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV"},{"text":"]","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/addedLocales","isActive":true},{"type":"text","text":", or the static"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/locales","isActive":true},{"type":"text","text":" if there are no added ones."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/enabledLocales","type":"topic","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardSettings/addedLocales":{"url":"\/documentation\/keyboardkitpro\/keyboardsettings\/addedlocales","abstract":[{"text":"A list of explicitly added locale identifiers.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/addedLocales","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addedLocales","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Keyboard","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V"},{"text":".","kind":"text"},{"text":"AddedLocale","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V11AddedLocaleV"},{"text":"]","kind":"text"}],"type":"topic","title":"addedLocales"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLayout/iPhoneLayoutService":{"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout\/iPhoneLayoutService","type":"topic","navigatorTitle":[{"text":"iPhoneLayoutService","kind":"identifier"}],"abstract":[{"type":"text","text":"This base class provides a foundation for generating"},{"type":"text","text":" "},{"type":"text","text":"iPhone-specific layouts."}],"url":"\/documentation\/keyboardkitpro\/keyboardlayout\/iphonelayoutservice","kind":"symbol","title":"KeyboardLayout.iPhoneLayoutService","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iPhoneLayoutService","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Foundation/Locale/ContextMenu":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Foundation\/Locale\/ContextMenu","title":"Locale.ContextMenu","abstract":[{"text":"This modifier can apply a locale context menu to any","type":"text"},{"text":" ","type":"text"},{"text":"view or keyboard button.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/foundation\/locale\/contextmenu","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContextMenu"}],"navigatorTitle":[{"kind":"identifier","text":"ContextMenu"}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/services":{"kind":"symbol","title":"services","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/services","abstract":[{"type":"text","text":"Keyboard-specific services."}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"services","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Keyboard","preciseIdentifier":"s:14KeyboardKitPro0A0V","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Services","preciseIdentifier":"s:14KeyboardKitPro0A0V8ServicesC","kind":"typeIdentifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Navigation-Article":{"abstract":[{"text":"This article describes the KeyboardKit navigation engine.","type":"text"}],"title":"Navigation","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","images":[{"identifier":"Page.png","type":"card"}],"role":"article","url":"\/documentation\/keyboardkitpro\/navigation-article","kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Input-Article":{"title":"Input","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","url":"\/documentation\/keyboardkitpro\/input-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}],"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit input engine."}],"role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures-Article":{"type":"topic","images":[{"identifier":"Page.png","type":"card"}],"kind":"article","url":"\/documentation\/keyboardkitpro\/gestures-article","role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit gesture engine."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","title":"Gestures"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLayout/iPadLayoutService":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout\/iPadLayoutService","title":"KeyboardLayout.iPadLayoutService","abstract":[{"text":"This base class provides a foundation for generating","type":"text"},{"text":" ","type":"text"},{"text":"iPad-specific layouts.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardlayout\/ipadlayoutservice","role":"symbol","navigatorTitle":[{"text":"iPadLayoutService","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iPadLayoutService","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Services/tryRegisterLocalizedLayoutService(_:)":{"role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboard\/services\/tryregisterlocalizedlayoutservice(_:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Services\/tryRegisterLocalizedLayoutService(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tryRegisterLocalizedLayoutService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A13LayoutServiceP","text":"KeyboardLayoutService"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"title":"tryRegisterLocalizedLayoutService(_:)","abstract":[{"text":"Try to register a localized service, which will then","type":"text"},{"text":" ","type":"text"},{"text":"be used for the locale it specifies.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Services/layoutService":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A13LayoutServiceP","text":"KeyboardLayoutService"}],"role":"symbol","title":"layoutService","abstract":[{"type":"text","text":"The keyboard layout service to use."}],"kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboard\/services\/layoutservice","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Services\/layoutService"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/InputSet/symbolic(currencies:)":{"title":"symbolic(currencies:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"symbolic","kind":"identifier"},{"text":"(","kind":"text"},{"text":"currencies","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]) -> ","kind":"text"},{"text":"InputSet","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro8InputSetV"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet\/symbolic(currencies:)","kind":"symbol","url":"\/documentation\/keyboardkitpro\/inputset\/symbolic(currencies:)","type":"topic","abstract":[{"type":"text","text":"A standard symbolic input set."}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation-Article":{"abstract":[{"text":"This article describes the KeyboardKit dictation engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/dictation-article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","type":"topic","images":[{"identifier":"Page.png","type":"card"}],"role":"article","title":"Dictation"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AI-Article":{"abstract":[{"text":"This article describes the KeyboardKit AI support capabilities.","type":"text"}],"role":"article","type":"topic","kind":"article","images":[{"identifier":"Page.png","type":"card"}],"url":"\/documentation\/keyboardkitpro\/ai-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","title":"AI Support"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLayout/ProLayoutService":{"type":"topic","role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardlayout\/prolayoutservice","kind":"symbol","navigatorTitle":[{"text":"ProLayoutService","kind":"identifier"}],"title":"KeyboardLayout.ProLayoutService","abstract":[{"text":"This class is inherited by all Pro services and also","type":"text"},{"text":" ","type":"text"},{"text":"serves as a namespace for Pro service types.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout\/ProLayoutService","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProLayoutService","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp/LocaleScreen":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/LocaleScreen","abstract":[{"text":"This screen can be used as the main locale screen in","type":"text"},{"text":" ","type":"text"},{"text":"a keyboard app or its keyboard extension.","type":"text"}],"navigatorTitle":[{"text":"LocaleScreen","kind":"identifier"}],"title":"KeyboardApp.LocaleScreen","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocaleScreen","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardapp\/localescreen"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/InputSet/azerty":{"url":"\/documentation\/keyboardkitpro\/inputset\/azerty","title":"azerty","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"This is an AZERTY alphabetic input set."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet\/azerty","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"azerty","kind":"identifier"},{"text":": ","kind":"text"},{"text":"InputSet","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro8InputSetV"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards-Article":{"role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","url":"\/documentation\/keyboardkitpro\/external-keyboards-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"title":"External Keyboards"},"https://github.com/KeyboardKit/KeyboardKitPro":{"title":"KeyboardKit Pro","titleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"url":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","type":"link","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Foundation/Locale/supportedLayoutTypes":{"abstract":[{"text":"A list of layout types that the locale supports.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/foundation\/locale\/supportedlayouttypes","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Foundation\/Locale\/supportedLayoutTypes","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportedLayoutTypes"},{"kind":"text","text":": ["},{"text":"Keyboard","preciseIdentifier":"s:14KeyboardKitPro0A0V","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"LayoutType","preciseIdentifier":"s:14KeyboardKitPro0A0V10LayoutTypeO","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"kind":"symbol","title":"supportedLayoutTypes","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"title":"Callouts","kind":"article","url":"\/documentation\/keyboardkitpro\/callouts-article","role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/InputSet/dvorak":{"type":"topic","title":"dvorak","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dvorak"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro8InputSetV","text":"InputSet"}],"abstract":[{"text":"This is an Dvorak alphabetic input set.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/inputset\/dvorak","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet\/dvorak","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/selectNextLocale()":{"title":"selectNextLocale()","role":"symbol","abstract":[{"type":"text","text":"Select the next locale from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/enabledLocales"},{"type":"text","text":"."}],"url":"\/documentation\/keyboardkitpro\/keyboardcontext\/selectnextlocale()","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/selectNextLocale()","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectNextLocale","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/App-Article":{"url":"\/documentation\/keyboardkitpro\/app-article","type":"topic","kind":"article","role":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","title":"App Utilities"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"role":"article","url":"\/documentation\/keyboardkitpro\/localization-article","abstract":[{"text":"This article describes the KeyboardKit localization engine.","type":"text"}],"type":"topic","title":"Localization","images":[{"identifier":"Page.png","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp":{"url":"\/documentation\/keyboardkitpro\/keyboardapp","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardApp"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardApp"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","role":"symbol","type":"topic","abstract":[{"type":"text","text":"This type can be used to define important properties for"},{"type":"text","text":" "},{"type":"text","text":"your app, and is also a namespace for app-based features."}],"title":"KeyboardApp"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLayout/Item":{"url":"\/documentation\/keyboardkitpro\/keyboardlayout\/item","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout\/Item","abstract":[{"text":"A keyboard layout items defines an action, size, and","type":"text"},{"text":" ","type":"text"},{"text":"optional insets for a key on a layout-based keyboard.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Item"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Item"}],"type":"topic","title":"KeyboardLayout.Item","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/InputSet/qwerty":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/keyboardkitpro\/inputset\/qwerty","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"qwerty"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14KeyboardKitPro8InputSetV","kind":"typeIdentifier","text":"InputSet"}],"title":"qwerty","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet\/qwerty","abstract":[{"type":"text","text":"A standard QWERTY input set."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/keyboardLayoutType":{"kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardcontext\/keyboardlayouttype","title":"keyboardLayoutType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardLayoutType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V","text":"Keyboard"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V10LayoutTypeO","text":"LayoutType"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/keyboardLayoutType","role":"symbol","type":"topic","abstract":[{"text":"The current keyboard layout type, if any.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLayout/DeviceConfiguration":{"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardlayout\/deviceconfiguration","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout\/DeviceConfiguration","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"This type defines layout configs for various devices"},{"type":"text","text":" "},{"type":"text","text":"and screen orientations."}],"title":"KeyboardLayout.DeviceConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"DeviceConfiguration"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/InputSet":{"navigatorTitle":[{"text":"InputSet","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet","abstract":[{"type":"text","text":"An input set defines the input keys on a keyboard."}],"type":"topic","kind":"symbol","title":"InputSet","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InputSet","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/inputset"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/locale":{"abstract":[{"type":"text","text":"The current locale, by default "},{"type":"codeVoice","code":".current"},{"type":"text","text":"."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/locale","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"locale","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Locale","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV"}],"url":"\/documentation\/keyboardkitpro\/keyboardcontext\/locale","role":"symbol","title":"locale"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLayout/StandardLayoutService":{"abstract":[{"text":"This class provides a standard way to create dynamic","type":"text"},{"text":" ","type":"text"},{"text":"keyboard layouts.","type":"text"}],"title":"KeyboardLayout.StandardLayoutService","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout\/StandardLayoutService","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StandardLayoutService","kind":"identifier"}],"navigatorTitle":[{"text":"StandardLayoutService","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardlayout\/standardlayoutservice","role":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLayout":{"type":"topic","abstract":[{"text":"This type defines the full set of keys on a keyboard and","type":"text"},{"text":" ","type":"text"},{"text":"is also a namespace for layout-related types.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"KeyboardLayout","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardlayout","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardLayout","kind":"identifier"}],"kind":"symbol","title":"KeyboardLayout"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLayout/iPadProLayoutService":{"url":"\/documentation\/keyboardkitpro\/keyboardlayout\/ipadprolayoutservice","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"This base class provides a foundation for generating"},{"type":"text","text":" "},{"type":"text","text":"iPad Pro-specific layouts."}],"title":"KeyboardLayout.iPadProLayoutService","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iPadProLayoutService","kind":"identifier"}],"navigatorTitle":[{"text":"iPadProLayoutService","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout\/iPadProLayoutService"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Foundation/Locale/keyboardKitSupported":{"type":"topic","abstract":[{"text":"A list of KeyboardKit supported locales.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Foundation\/Locale\/keyboardKitSupported","url":"\/documentation\/keyboardkitpro\/foundation\/locale\/keyboardkitsupported","title":"keyboardKitSupported","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardKitSupported","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Locale","preciseIdentifier":"s:10Foundation6LocaleV","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Getting-Started-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started-Article","type":"topic","abstract":[{"type":"text","text":"This guide describes how to get started with KeyboardKit."}],"kind":"article","images":[{"identifier":"Page.png","type":"card"}],"url":"\/documentation\/keyboardkitpro\/getting-started-article","role":"article","title":"Getting Started"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/InputSet/colemak":{"url":"\/documentation\/keyboardkitpro\/inputset\/colemak","abstract":[{"type":"text","text":"This is a Colemak alphabetic input set."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"colemak"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14KeyboardKitPro8InputSetV","kind":"typeIdentifier","text":"InputSet"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet\/colemak","title":"colemak"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"images":[{"identifier":"Page.png","type":"card"}],"title":"Actions","url":"\/documentation\/keyboardkitpro\/actions-article","kind":"article","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/InputSet/qwertz":{"abstract":[{"type":"text","text":"This is a QWERTZ alphabetic input set."}],"url":"\/documentation\/keyboardkitpro\/inputset\/qwertz","type":"topic","title":"qwertz","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qwertz","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro8InputSetV","text":"InputSet","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet\/qwertz"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"url":"\/documentation\/keyboardkitpro","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"type":"topic","title":"KeyboardKitPro","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"},"Page.png":{"alt":"Page icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png"}],"type":"image","identifier":"Page.png"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Host-Article":{"kind":"article","role":"article","images":[{"identifier":"Page.png","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","url":"\/documentation\/keyboardkitpro\/host-article","type":"topic","title":"Host Application","abstract":[{"type":"text","text":"This article describes how KeyboardKit Pro can identify and use the host application."}]},"keyboardview-ipadpro":{"alt":"iPad Pro Layout","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/keyboardview-ipadpro.jpg","traits":["1x","light"]}],"type":"image","identifier":"keyboardview-ipadpro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis-Article":{"url":"\/documentation\/keyboardkitpro\/emojis-article","type":"topic","title":"Emojis","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"text":"This article describes the KeyboardKit emoji engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","kind":"article","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/LayoutType":{"type":"topic","abstract":[{"text":"This enum defines supported keyboard layout types.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LayoutType","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"LayoutType","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboard\/layouttype","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/LayoutType","title":"Keyboard.LayoutType"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLayoutService":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardLayoutService","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardlayoutservice","title":"KeyboardLayoutService","navigatorTitle":[{"text":"KeyboardLayoutService","kind":"identifier"}],"type":"topic","abstract":[{"text":"This protocol can be implemented by any classes that can","type":"text"},{"text":" ","type":"text"},{"text":"generate keyboard layouts in various ways.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayoutService","kind":"symbol","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Device-Article":{"role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","url":"\/documentation\/keyboardkitpro\/device-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit device utilities."}],"title":"Device Utilities"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"title":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article"],"anchor":"Articles","generated":true}],"op":"replace"}]}]}