{"sections":[],"seeAlsoSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started-Guide"],"title":"Guides","generated":true,"anchor":"Guides"}],"primaryContentSections":[{"content":[{"anchor":"overview","level":2,"text":"Overview","type":"heading"},{"inlineContent":[{"type":"text","text":"Native iOS keyboards are severely limited when it comes to how much memory they can allocate. Based on the device and iOS version, a keyboard extension is not allowed to allocate more than "},{"type":"strong","inlineContent":[{"type":"text","text":"~60-70 MB"}]},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Keyboard extensions that allocate more than this will be instantly terminated by the operating system. You may avoid some crashes by deferring some allocation until after the keyboard has been loaded, but this is not guaranteed to work."}],"type":"paragraph"},{"text":"Why is this problematic?","anchor":"Why-is-this-problematic","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"These strict memory limitations have been in effect for many years, and don’t seem to be expanded even though our devices become more powerful each year. Despite several discussions with Apple, the memory allowance remain more or less unchanged.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The reason for these limitations is to protect the device from memory intense keyboards affecting the main app’s performance. Still, a ","type":"text"},{"inlineContent":[{"type":"text","text":"~60-70 MB"}],"type":"strong"},{"text":" limitation is ","type":"text"},{"inlineContent":[{"type":"text","text":"very"}],"type":"emphasis"},{"type":"text","text":" strict, and makes it hard to provide functionality that may require just a little more memory."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"With the rise of AI and ML models, 3rd party keyboards could provide a lot of amazing AI\/ML-based functionality. However, such models often require a lot of memory, which means that these limitations make it hard to use such features in keyboard extensions."}]},{"text":"What can we do?","level":2,"type":"heading","anchor":"What-can-we-do"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Not much. Make sure to carefully monitor your keyboard extension’s memory consumption, and try to defer memory intense tasks until the keyboard has first been rendered, to avoid allocating a lot of memory on launch."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If possible, try to extract features that requires a lot of memory to external services, such as remote APIs. You could also try to open the main app to perform some operations, then return to the keyboard using KeyboardKit Pro’s "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","type":"reference","isActive":true},{"type":"text","text":"."}]},{"inlineContent":[{"type":"text","text":"You can also reach out to Apple if you struggle with these limitations. If many do, perhaps they will consider increasing the memory limit."}],"type":"paragraph"},{"type":"heading","text":"How to monitor memory consumption","anchor":"How-to-monitor-memory-consumption","level":2},{"inlineContent":[{"text":"It’s very important that you carefully monitor your keyboard’s memory consumption, if you suspect that it has memory-intense features.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can easily see how much memory your keyboard extension has allocated, by attaching the debugger to the keyboard process "},{"inlineContent":[{"type":"text","text":"after"}],"type":"emphasis"},{"text":" launching the keyboard, using the “Debug > Attach to Process by PID or Name…” menu alternative.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The reason why it’s best to wait until the keyboard has launched, is that the attachment may take time, which may cause the keyboard launch to be aborted."}]},{"inlineContent":[{"type":"text","text":"Once attached, you can check the memory consumption by tapping the top-leading spray bottle in the Xcode Project Navigator. You can also inspect the memory graph by tapping the graph button in Xcode’s process runner toolbar."}],"type":"paragraph"},{"type":"aside","name":"Important","content":[{"type":"paragraph","inlineContent":[{"text":"Make sure to always monitor your keyboard extension’s memory consumption on a physical device. The iOS simulator doesn’t apply the same memory limit, which means that it lets keyboard extensions allocate huge amounts of memory without crashing.","type":"text"}]}],"style":"important"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkitpro\/memory-management-guide"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkitpro\/memory-management-guide"]}],"kind":"article","hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Memory-Management-Guide","interfaceLanguage":"swift"},"abstract":[{"text":"This guide describes how to manage memory in a keyboard extensions.","type":"text"}],"metadata":{"title":"Memory Management","modules":[{"name":"KeyboardKitPro"}],"role":"article","images":[{"identifier":"Page.png","type":"card"}],"roleHeading":"Article"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Host-Article":{"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","type":"topic","title":"Host Utilities","role":"article","url":"\/documentation\/keyboardkitpro\/host-article","abstract":[{"type":"text","text":"This article describes how KeyboardKit Pro can identify the host application."}],"images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"type":"topic","url":"\/documentation\/keyboardkitpro","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI."}],"title":"KeyboardKitPro","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"},"Page.png":{"identifier":"Page.png","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png"}],"alt":"Page icon","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Getting-Started-Guide":{"abstract":[{"text":"This guide describes how to get started with KeyboardKit.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started-Guide","role":"article","kind":"article","url":"\/documentation\/keyboardkitpro\/getting-started-guide","type":"topic","images":[{"type":"card","identifier":"Page.png"}],"title":"Getting Started"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","value":null,"op":"add"},{"value":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started-Guide"],"title":"Guides","generated":true,"anchor":"Guides"}],"op":"replace","path":"\/seeAlsoSections"}]}]}