{"primaryContentSections":[{"kind":"content","content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A custom keyboard extension may sometimes have to open URLs or trigger deep links, for instance to open the app or System Settings."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Keyboard extensions can however not access "},{"type":"strong","inlineContent":[{"text":"UIApplication.shared","type":"text"}]},{"type":"text","text":", which means that you have to jump through hoops to open URLs."}]},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit therefore provides ways to open URLs from a keyboard extension, without using ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"UIApplication.shared"}]},{"text":".","type":"text"}]},{"type":"thematicBreak"},{"type":"heading","level":2,"anchor":"How-to","text":"How to…"},{"type":"heading","level":3,"anchor":"open-a-URL-from-a-keyboard-extension","text":"…open a URL from a keyboard extension"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The best way to open a URL from a keyboard extension, where you can’t access "},{"code":"UIApplication.shared","type":"codeVoice"},{"type":"text","text":" is to use a SwiftUI "},{"code":"Link","type":"codeVoice"},{"type":"text","text":". You can also trigger a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/url(_:id:)","type":"reference","isActive":true},{"type":"text","text":" action and let the main "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Services\/actionHandler","type":"reference","isActive":true},{"type":"text","text":" in "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","type":"reference","isActive":true},{"type":"text","text":" handle it."}]},{"type":"heading","level":3,"anchor":"open-System-Settings","text":"…open System Settings"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit defines a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Foundation\/URL\/systemSettings","isActive":true},{"type":"text","text":" URL, which can be used to open your app in System Settings. If your keyboard navigates to the System Settings root instead of your app, try to add an empty settings bundle to your app."}]},{"type":"heading","level":3,"anchor":"navigate-back-to-the-keyboard-from-the-app","text":"…navigate back to the keyboard from the app"},{"type":"paragraph","inlineContent":[{"text":"If a keyboard opens the main app to perform a quick operation, it may want to automatically return to the keyboard once the operation is done. One such example is when performing dictation.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This is however not easy, since Apple continues to restrict the ways in which apps can open other apps. Previous ways to implement this have either stopped working, or will be rejected by Apple when you push them to the App Store."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Since being able to return to the keyboard from the main app is an important part of some operations, KeyboardKit Pro has therefore added a "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardHostApplication","type":"reference"},{"type":"text","text":" that lets you navigate back to the most common apps."}]},{"type":"paragraph","inlineContent":[{"text":"You can read more in the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","type":"reference"},{"text":" article.","type":"text"}]}]}],"metadata":{"images":[{"type":"card","identifier":"Page.png"}],"modules":[{"name":"KeyboardKitPro"}],"roleHeading":"Article","title":"Navigation","role":"article"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article"},"kind":"article","seeAlsoSections":[{"generated":true,"anchor":"Articles","title":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/keyboardkitpro\/navigation-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/navigation-article"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit navigation engine."}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"sections":[],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"role":"article","url":"\/documentation\/keyboardkitpro\/localization-article","abstract":[{"text":"This article describes the KeyboardKit localization engine.","type":"text"}],"type":"topic","title":"Localization","images":[{"identifier":"Page.png","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"url":"\/documentation\/keyboardkitpro","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"type":"topic","title":"KeyboardKitPro","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardHostApplication":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardHostApplication","type":"topic","abstract":[{"text":"This enum defines a list of known host applications that","type":"text"},{"text":" ","type":"text"},{"text":"can be used to identify various application.","type":"text"}],"role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardhostapplication","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardHostApplication","kind":"identifier"}],"navigatorTitle":[{"text":"KeyboardHostApplication","kind":"identifier"}],"kind":"symbol","title":"KeyboardHostApplication"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis-Article":{"url":"\/documentation\/keyboardkitpro\/emojis-article","type":"topic","title":"Emojis","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"text":"This article describes the KeyboardKit emoji engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","kind":"article","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/App-Article":{"url":"\/documentation\/keyboardkitpro\/app-article","type":"topic","kind":"article","role":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","title":"App Utilities"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"title":"Callouts","kind":"article","url":"\/documentation\/keyboardkitpro\/callouts-article","role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Device-Article":{"role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","url":"\/documentation\/keyboardkitpro\/device-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit device utilities."}],"title":"Device Utilities"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback-Article":{"images":[{"identifier":"Page.png","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","url":"\/documentation\/keyboardkitpro\/feedback-article","type":"topic","role":"article","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"kind":"article","title":"Feedback"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards-Article":{"role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","url":"\/documentation\/keyboardkitpro\/external-keyboards-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"title":"External Keyboards"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation-Article":{"abstract":[{"text":"This article describes the KeyboardKit dictation engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/dictation-article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","type":"topic","images":[{"identifier":"Page.png","type":"card"}],"role":"article","title":"Dictation"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures-Article":{"type":"topic","images":[{"identifier":"Page.png","type":"card"}],"kind":"article","url":"\/documentation\/keyboardkitpro\/gestures-article","role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit gesture engine."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","title":"Gestures"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AI-Article":{"abstract":[{"text":"This article describes the KeyboardKit AI support capabilities.","type":"text"}],"role":"article","type":"topic","kind":"article","images":[{"identifier":"Page.png","type":"card"}],"url":"\/documentation\/keyboardkitpro\/ai-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","title":"AI Support"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"abstract":[{"text":"This article describes the KeyboardKit layout engine.","type":"text"}],"title":"Layout","kind":"article","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","url":"\/documentation\/keyboardkitpro\/layout-article","type":"topic","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/services":{"kind":"symbol","title":"services","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/services","abstract":[{"type":"text","text":"Keyboard-specific services."}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"services","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Keyboard","preciseIdentifier":"s:14KeyboardKitPro0A0V","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Services","preciseIdentifier":"s:14KeyboardKitPro0A0V8ServicesC","kind":"typeIdentifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Services/actionHandler":{"abstract":[{"type":"text","text":"The keyboard action handler to use."}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Services\/actionHandler","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionHandler","kind":"identifier"},{"text":": ","kind":"text"},{"text":"KeyboardActionHandler","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A13ActionHandlerP"}],"url":"\/documentation\/keyboardkitpro\/keyboard\/services\/actionhandler","role":"symbol","kind":"symbol","title":"actionHandler"},"Page.png":{"identifier":"Page.png","alt":"Page icon","type":"image","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/url(_:id:)":{"type":"topic","title":"KeyboardAction.url(_:id:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"url","kind":"identifier"},{"text":"(","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[{"text":"Open an url when released, using a custom id for identification.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardaction\/url(_:id:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/url(_:id:)","kind":"symbol","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}],"url":"\/documentation\/keyboardkitpro\/autocomplete-article","type":"topic","title":"Autocomplete","role":"article","images":[{"identifier":"Page.png","type":"card"}],"kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Input-Article":{"title":"Input","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","url":"\/documentation\/keyboardkitpro\/input-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}],"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit input engine."}],"role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Host-Article":{"kind":"article","role":"article","images":[{"identifier":"Page.png","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","url":"\/documentation\/keyboardkitpro\/host-article","type":"topic","title":"Host Application","abstract":[{"type":"text","text":"This article describes how KeyboardKit Pro can identify and use the host application."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Foundation/URL/systemSettings":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Foundation\/URL\/systemSettings","kind":"symbol","url":"\/documentation\/keyboardkitpro\/foundation\/url\/systemsettings","abstract":[{"text":"This URL will deep link to the app’s custom settings","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"in System Settings."}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemSettings","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"systemSettings"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"images":[{"identifier":"Page.png","type":"card"}],"title":"Actions","url":"\/documentation\/keyboardkitpro\/actions-article","kind":"article","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"generated":true,"anchor":"Articles","title":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article"]}],"op":"replace"}]}]}