{"seeAlsoSections":[{"title":"Previews","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewCalloutActionProvider","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewInputSetProvider","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewKeyboardActionHandler","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewKeyboardAppearance","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewKeyboardLayoutProvider"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviewTextDocumentProxy"}],"title":"PreviewTextDocumentProxy","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@KeyboardKitPro@objc(cs)PreviewTextDocumentProxy","modules":[{"name":"KeyboardKitPro"}],"navigatorTitle":[{"kind":"identifier","text":"PreviewTextDocumentProxy"}]},"abstract":[{"type":"text","text":"This document proxy can be used in SwiftUI previews."}],"sections":[],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)NSObject","doc:\/\/com.keyboardkit.KeyboardKitPro\/s7CVarArgP","doc:\/\/com.keyboardkit.KeyboardKitPro\/s28CustomDebugStringConvertibleP","doc:\/\/com.keyboardkit.KeyboardKitPro\/s23CustomStringConvertibleP","doc:\/\/com.keyboardkit.KeyboardKitPro\/SQ","doc:\/\/com.keyboardkit.KeyboardKitPro\/SH","doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UIKeyInput","doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UITextDocumentProxy","doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UITextInputTraits"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/init()"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/autocapitalizationType","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/documentContextAfterInput","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/documentContextBeforeInput","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/documentIdentifier","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/documentInputMode","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/hasText","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/returnKeyType","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/selectedText"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/adjustTextPosition(byCharacterOffset:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/deleteBackward()","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/insertText(_:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/setMarkedText(_:selectedRange:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/unmarkText()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/UITextDocumentProxy-Implementations"],"generated":true}],"variants":[{"paths":["\/documentation\/keyboardkitpro\/previewtextdocumentproxy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/previewtextdocumentproxy"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviewTextDocumentProxy"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/PreviewTextDocumentProxy/UITextDocumentProxy-Implementations":{"role":"collectionGroup","title":"UITextDocumentProxy Implementations","abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/UITextDocumentProxy-Implementations","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/previewtextdocumentproxy\/uitextdocumentproxy-implementations"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/PreviewCalloutActionProvider":{"role":"symbol","title":"PreviewCalloutActionProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviewCalloutActionProvider"}],"abstract":[{"type":"text","text":"This action provider can be used in SwiftUI previews."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewCalloutActionProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PreviewCalloutActionProvider"}],"url":"\/documentation\/keyboardkitpro\/previewcalloutactionprovider"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/PreviewTextDocumentProxy/insertText(_:)":{"role":"symbol","title":"insertText(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insertText"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/insertText(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"insertText:"}],"url":"\/documentation\/keyboardkitpro\/previewtextdocumentproxy\/inserttext(_:)"},"doc://com.keyboardkit.KeyboardKitPro/objc(pl)UITextDocumentProxy":{"type":"unresolvable","title":"UITextDocumentProxy","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UITextDocumentProxy"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/PreviewTextDocumentProxy/returnKeyType":{"role":"symbol","title":"returnKeyType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnKeyType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIReturnKeyType","preciseIdentifier":"c:@E@UIReturnKeyType"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/returnKeyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"returnKeyType"}],"url":"\/documentation\/keyboardkitpro\/previewtextdocumentproxy\/returnkeytype"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/PreviewTextDocumentProxy/selectedText":{"role":"symbol","title":"selectedText","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/selectedText","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectedText"}],"url":"\/documentation\/keyboardkitpro\/previewtextdocumentproxy\/selectedtext"},"doc://com.keyboardkit.KeyboardKitPro/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/SH"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/PreviewInputSetProvider":{"role":"symbol","title":"PreviewInputSetProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviewInputSetProvider"}],"abstract":[{"type":"text","text":"This input set provider can be used in SwiftUI previews."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewInputSetProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PreviewInputSetProvider"}],"url":"\/documentation\/keyboardkitpro\/previewinputsetprovider"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/PreviewTextDocumentProxy/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/keyboardkitpro\/previewtextdocumentproxy\/init()"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/PreviewKeyboardAppearance":{"role":"symbol","title":"PreviewKeyboardAppearance","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviewKeyboardAppearance"}],"abstract":[{"type":"text","text":"This appearance can be used in SwiftUI previews."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewKeyboardAppearance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PreviewKeyboardAppearance"}],"url":"\/documentation\/keyboardkitpro\/previewkeyboardappearance"},"doc://com.keyboardkit.KeyboardKitPro/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(cs)NSObject"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/PreviewTextDocumentProxy/deleteBackward()":{"role":"symbol","title":"deleteBackward()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteBackward"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/deleteBackward()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteBackward"}],"url":"\/documentation\/keyboardkitpro\/previewtextdocumentproxy\/deletebackward()"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/PreviewTextDocumentProxy/documentInputMode":{"role":"symbol","title":"documentInputMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentInputMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextInputMode","preciseIdentifier":"c:objc(cs)UITextInputMode"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/documentInputMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"documentInputMode"}],"url":"\/documentation\/keyboardkitpro\/previewtextdocumentproxy\/documentinputmode"},"doc://com.keyboardkit.KeyboardKitPro/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/s23CustomStringConvertibleP"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","title":"KeyboardKitPro","abstract":[{"type":"text","text":"KeyboardKit Pro helps you build custom keyboard extensions for iOS and iPadOS."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro"},"doc://com.keyboardkit.KeyboardKitPro/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/s28CustomDebugStringConvertibleP"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/PreviewTextDocumentProxy/documentIdentifier":{"role":"symbol","title":"documentIdentifier","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/documentIdentifier","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"documentIdentifier"}],"url":"\/documentation\/keyboardkitpro\/previewtextdocumentproxy\/documentidentifier"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/PreviewTextDocumentProxy/hasText":{"role":"symbol","title":"hasText","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/hasText","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hasText"}],"url":"\/documentation\/keyboardkitpro\/previewtextdocumentproxy\/hastext"},"doc://com.keyboardkit.KeyboardKitPro/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)NSObject"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/PreviewTextDocumentProxy":{"role":"symbol","title":"PreviewTextDocumentProxy","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviewTextDocumentProxy"}],"abstract":[{"type":"text","text":"This document proxy can be used in SwiftUI previews."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PreviewTextDocumentProxy"}],"url":"\/documentation\/keyboardkitpro\/previewtextdocumentproxy"},"doc://com.keyboardkit.KeyboardKitPro/objc(pl)UIKeyInput":{"type":"unresolvable","title":"UIKit.UIKeyInput","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UIKeyInput"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/PreviewTextDocumentProxy/setMarkedText(_:selectedRange:)":{"role":"symbol","title":"setMarkedText(_:selectedRange:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMarkedText"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"selectedRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@T@NSRange"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/setMarkedText(_:selectedRange:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setMarkedText:selectedRange:"}],"url":"\/documentation\/keyboardkitpro\/previewtextdocumentproxy\/setmarkedtext(_:selectedrange:)"},"doc://com.keyboardkit.KeyboardKitPro/objc(pl)UITextInputTraits":{"type":"unresolvable","title":"UIKit.UITextInputTraits","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UITextInputTraits"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/PreviewKeyboardLayoutProvider":{"role":"symbol","title":"PreviewKeyboardLayoutProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviewKeyboardLayoutProvider"}],"abstract":[{"type":"text","text":"This layout provider can be used in SwiftUI previews."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewKeyboardLayoutProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PreviewKeyboardLayoutProvider"}],"url":"\/documentation\/keyboardkitpro\/previewkeyboardlayoutprovider"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/PreviewTextDocumentProxy/autocapitalizationType":{"role":"symbol","title":"autocapitalizationType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autocapitalizationType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextAutocapitalizationType","preciseIdentifier":"c:@E@UITextAutocapitalizationType"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/autocapitalizationType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"autocapitalizationType"}],"url":"\/documentation\/keyboardkitpro\/previewtextdocumentproxy\/autocapitalizationtype"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/PreviewTextDocumentProxy/documentContextAfterInput":{"role":"symbol","title":"documentContextAfterInput","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentContextAfterInput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/documentContextAfterInput","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"documentContextAfterInput"}],"url":"\/documentation\/keyboardkitpro\/previewtextdocumentproxy\/documentcontextafterinput"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/PreviewKeyboardActionHandler":{"role":"symbol","title":"PreviewKeyboardActionHandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviewKeyboardActionHandler"}],"abstract":[{"type":"text","text":"This action handler can be used in SwiftUI previews."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewKeyboardActionHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PreviewKeyboardActionHandler"}],"url":"\/documentation\/keyboardkitpro\/previewkeyboardactionhandler"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/PreviewTextDocumentProxy/adjustTextPosition(byCharacterOffset:)":{"role":"symbol","title":"adjustTextPosition(byCharacterOffset:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adjustTextPosition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byCharacterOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/adjustTextPosition(byCharacterOffset:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adjustTextPositionByCharacterOffset:"}],"url":"\/documentation\/keyboardkitpro\/previewtextdocumentproxy\/adjusttextposition(bycharacteroffset:)"},"doc://com.keyboardkit.KeyboardKitPro/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/s7CVarArgP"},"doc://com.keyboardkit.KeyboardKitPro/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/SQ"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/PreviewTextDocumentProxy/unmarkText()":{"role":"symbol","title":"unmarkText()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unmarkText"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/unmarkText()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unmarkText"}],"url":"\/documentation\/keyboardkitpro\/previewtextdocumentproxy\/unmarktext()"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/PreviewTextDocumentProxy/documentContextBeforeInput":{"role":"symbol","title":"documentContextBeforeInput","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentContextBeforeInput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/documentContextBeforeInput","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"documentContextBeforeInput"}],"url":"\/documentation\/keyboardkitpro\/previewtextdocumentproxy\/documentcontextbeforeinput"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PreviewTextDocumentProxy"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PreviewTextDocumentProxy"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PreviewTextDocumentProxy"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/autocapitalizationType","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/documentContextAfterInput","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/documentContextBeforeInput","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/documentIdentifier","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/documentInputMode","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/hasText","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/returnKeyType","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/selectedText"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/adjustTextPosition(byCharacterOffset:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/deleteBackward()","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/init()","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/insertText(_:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/setMarkedText(_:selectedRange:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/PreviewTextDocumentProxy\/unmarkText()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UITextDocumentProxy"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"replace","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviewTextDocumentProxy"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1insertText(_:)\/title","value":"insertText:"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1insertText(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"insertText:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1returnKeyType\/title","value":"returnKeyType"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1returnKeyType\/fragments","value":[{"kind":"identifier","text":"returnKeyType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1selectedText\/title","value":"selectedText"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1selectedText\/fragments","value":[{"kind":"identifier","text":"selectedText"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1deleteBackward()\/title","value":"deleteBackward"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1deleteBackward()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteBackward"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1documentInputMode\/title","value":"documentInputMode"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1documentInputMode\/fragments","value":[{"kind":"identifier","text":"documentInputMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1documentIdentifier\/title","value":"documentIdentifier"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1documentIdentifier\/fragments","value":[{"kind":"identifier","text":"documentIdentifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1hasText\/title","value":"hasText"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1hasText\/fragments","value":[{"kind":"identifier","text":"hasText"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy\/title","value":"PreviewTextDocumentProxy"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy\/fragments","value":[{"kind":"identifier","text":"PreviewTextDocumentProxy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1setMarkedText(_:selectedRange:)\/title","value":"setMarkedText:selectedRange:"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1setMarkedText(_:selectedRange:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMarkedText:selectedRange:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1autocapitalizationType\/title","value":"autocapitalizationType"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1autocapitalizationType\/fragments","value":[{"kind":"identifier","text":"autocapitalizationType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1documentContextAfterInput\/title","value":"documentContextAfterInput"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1documentContextAfterInput\/fragments","value":[{"kind":"identifier","text":"documentContextAfterInput"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1adjustTextPosition(byCharacterOffset:)\/title","value":"adjustTextPositionByCharacterOffset:"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1adjustTextPosition(byCharacterOffset:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adjustTextPositionByCharacterOffset:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1unmarkText()\/title","value":"unmarkText"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1unmarkText()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unmarkText"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1documentContextBeforeInput\/title","value":"documentContextBeforeInput"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1PreviewTextDocumentProxy~1documentContextBeforeInput\/fragments","value":[{"kind":"identifier","text":"documentContextBeforeInput"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}