{"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has a collection of preview-specific state and services that you can use in your previews:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/ActionCalloutContext"},{"type":"text","text":"."},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/ActionCalloutContext\/preview"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutActionProvider"},{"type":"text","text":"."},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutActionProvider\/preview"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputCalloutContext"},{"type":"text","text":"."},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputCalloutContext\/preview"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSetProvider"},{"type":"text","text":"."},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSetProvider\/preview"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler"},{"type":"text","text":"."},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler\/preview"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAppearance"},{"type":"text","text":"."},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAppearance\/preview"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext"},{"type":"text","text":"."},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/preview"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController"},{"type":"text","text":"."},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/preview"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout"},{"type":"text","text":"."},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout\/preview"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayoutProvider"},{"type":"text","text":"."},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayoutProvider\/preview"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"UITextDocumentContext"},{"type":"text","text":"."},{"type":"codeVoice","code":"preview"},{"type":"text","text":"."}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If the view you want to preview uses any of these types, you can just use "},{"type":"codeVoice","code":".preview"},{"type":"text","text":"."}]},{"anchor":"How-to-use-preview-specific-state-and-services","level":2,"type":"heading","text":"How to use preview-specific state and services"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Consider this view that takes an action handler as init parameter and looks for the keyboard context in the environment:"}]},{"type":"codeListing","syntax":"swift","code":["struct MyView {","","    init(actionHandler: KeyboardActionHandler) {","        self.actionHandler = actionHandler","    }","","    actionHandler: KeyboardActionHandler","","    @EnvironmentObject","    private var context: KeyboardContext","","    var body: some View {","        VStack {","            Button(\"Trigger backspace\") {","                actionHandler.handle(.release, on: .backspace)","            }","            Button(\"Delete text in the proxu\") {","                context.textDocumentProxy.deleteBackwards()","            }","        }","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In your preview, you can just inject "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler\/preview"},{"type":"text","text":" in the initializer and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/preview"},{"type":"text","text":" as an environment object:"}]},{"type":"codeListing","syntax":"swift","code":["struct MyView_Previews: PreviewProvider {","","    static var previews: some View {","        MyView(actionHandler: .preview)","            .environmentObject(KeyboardContext.preview)","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Although using environment objects is convenient, KeyboardKit doesn’t use environment objects since they make for hard to discover dependencies. As such, you will never have to inject environment objects to preview views in KeyboardKit."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/keyboardkitpro\/previews"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/previews"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This article describes how KeyboardKit makes it easy to preview keyboard-specific views."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Previews","role":"article","modules":[{"name":"KeyboardKitPro"}]},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"seeAlsoSections":[{"title":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Appearance","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Extensions","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Routing","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/RTL","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings"],"generated":true}],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAppearance":{"role":"symbol","title":"KeyboardAppearance","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardAppearance"}],"abstract":[{"type":"text","text":"This protocol can be implemented by classes that can define"},{"type":"text","text":" "},{"type":"text","text":"styles and appearances for different parts of a keyboard."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAppearance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardAppearance"}],"url":"\/documentation\/keyboardkitpro\/keyboardappearance"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/InputSet":{"role":"symbol","title":"InputSet","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InputSet"}],"abstract":[{"type":"text","text":"An input set defines the input keys on a keyboard. The keys"},{"type":"text","text":" "},{"type":"text","text":"can then be used to create a keyboard layout, which defines"},{"type":"text","text":" "},{"type":"text","text":"the full set of keys, including the surrounding system keys."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InputSet"}],"url":"\/documentation\/keyboardkitpro\/inputset"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/preview":{"role":"symbol","title":"preview","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardContext","preciseIdentifier":"s:14KeyboardKitPro0A7ContextC"}],"abstract":[{"type":"text","text":"This preview context can be used in SwiftUI previews."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/preview","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardcontext\/preview"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Settings":{"role":"article","title":"Settings","abstract":[{"type":"text","text":"This article describes the KeyboardKit settings utilities and how to use them."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/settings"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Routing":{"role":"article","title":"Routing","abstract":[{"type":"text","text":"This article describes how KeyboardKit adds ways for you to route text from the main app to other text fields within the keyboard."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Routing","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/routing"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLocale/persian":{"role":"symbol","title":"KeyboardLocale.persian","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"persian"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale\/persian","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardlocale\/persian"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/ActionCalloutContext":{"role":"symbol","title":"ActionCalloutContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActionCalloutContext"}],"abstract":[{"type":"text","text":"This context can be used to handle callouts that show a set"},{"type":"text","text":" "},{"type":"text","text":"of secondary actions for various keyboard actions."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/ActionCalloutContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ActionCalloutContext"}],"url":"\/documentation\/keyboardkitpro\/actioncalloutcontext"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis":{"role":"article","title":"Emojis","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji model and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/emojis"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard":{"role":"article","title":"Keyboard","abstract":[{"type":"text","text":"This article describes the KeyboardKit keyboard types and how to use them."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboard"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAppearance/preview":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" is "},{"type":"codeVoice","code":"PreviewKeyboardAppearance"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"preview","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardAppearance","preciseIdentifier":"s:14KeyboardKitPro0A10AppearanceP"}],"abstract":[{"type":"text","text":"This preview appearance can be used in SwiftUI previews."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAppearance\/preview","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardappearance\/preview"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Input":{"role":"article","title":"Input","abstract":[{"type":"text","text":"This article describes the KeyboardKit input set engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/input"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"role":"symbol","title":"KeyboardInputViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardInputViewController"}],"abstract":[{"type":"text","text":"This class extends "},{"type":"codeVoice","code":"UIInputViewController"},{"type":"text","text":" with KeyboardKit"},{"type":"text","text":" "},{"type":"text","text":"specific functionality."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardInputViewController"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction":{"role":"symbol","title":"KeyboardAction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardAction"}],"abstract":[{"type":"text","text":"This enum defines keyboard-specific actions that correspond"},{"type":"text","text":" "},{"type":"text","text":"to actions that can be found on various keyboards."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardAction"}],"url":"\/documentation\/keyboardkitpro\/keyboardaction"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization":{"role":"article","title":"Localization","abstract":[{"type":"text","text":"This article describes the KeyboardKit localization model and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/localization"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards":{"role":"article","title":"External Keyboards","abstract":[{"type":"text","text":"This article describes the KeyboardKit external keyboard engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/external-keyboards"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback":{"role":"article","title":"Feedback","abstract":[{"type":"text","text":"This article describes the KeyboardKit feedback engine and how to use it to trigger audio and haptic feedback."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/feedback"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLocale/arabic":{"role":"symbol","title":"KeyboardLocale.arabic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"arabic"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale\/arabic","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardlocale\/arabic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/InputSetProvider/preview":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" is "},{"type":"codeVoice","code":"PreviewInputSetProvider"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"preview","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InputSetProvider","preciseIdentifier":"s:14KeyboardKitPro16InputSetProviderP"}],"abstract":[{"type":"text","text":"This preview provider can be used in SwiftUI previews."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSetProvider\/preview","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/inputsetprovider\/preview"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLayoutProvider":{"role":"symbol","title":"KeyboardLayoutProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardLayoutProvider"}],"abstract":[{"type":"text","text":"This protocol can be implemented by any classes that can be"},{"type":"text","text":" "},{"type":"text","text":"used to generate a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout"},{"type":"text","text":" for a certain context."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayoutProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardLayoutProvider"}],"url":"\/documentation\/keyboardkitpro\/keyboardlayoutprovider"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLayout/preview":{"role":"symbol","title":"preview","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardLayout","preciseIdentifier":"s:14KeyboardKitPro0A6LayoutC"}],"abstract":[{"type":"text","text":"This preview layout can be used in SwiftUI previews."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout\/preview","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardlayout\/preview"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/ActionCalloutContext/preview":{"role":"symbol","title":"preview","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActionCalloutContext","preciseIdentifier":"s:14KeyboardKitPro20ActionCalloutContextC"}],"abstract":[{"type":"text","text":"This preview context can be used in SwiftUI previews."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/ActionCalloutContext\/preview","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/actioncalloutcontext\/preview"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete":{"role":"article","title":"Autocomplete","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/autocomplete"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts":{"role":"article","title":"Callouts","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/callouts"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext":{"role":"symbol","title":"KeyboardContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardContext"}],"abstract":[{"type":"text","text":"This class provides keyboard extensions with contextual and"},{"type":"text","text":" "},{"type":"text","text":"observable information about the keyboard extension itself."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardContext"}],"url":"\/documentation\/keyboardkitpro\/keyboardcontext"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardActionHandler/preview":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" is "},{"type":"codeVoice","code":"PreviewKeyboardActionHandler"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"preview","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardActionHandler","preciseIdentifier":"s:14KeyboardKitPro0A13ActionHandlerP"}],"abstract":[{"type":"text","text":"This preview handler can be used in SwiftUI previews."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler\/preview","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardactionhandler\/preview"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLayout":{"role":"symbol","title":"KeyboardLayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardLayout"}],"abstract":[{"type":"text","text":"A keyboard layout defines all available keyboard actions on"},{"type":"text","text":" "},{"type":"text","text":"a keyboard, as well as their size."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardLayout"}],"url":"\/documentation\/keyboardkitpro\/keyboardlayout"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/InputSetProvider":{"role":"symbol","title":"InputSetProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InputSetProvider"}],"abstract":[{"type":"text","text":"This protocol can be implemented by any classes that can be"},{"type":"text","text":" "},{"type":"text","text":"used to provide various "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSet"},{"type":"text","text":" values."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputSetProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InputSetProvider"}],"url":"\/documentation\/keyboardkitpro\/inputsetprovider"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Appearance":{"role":"article","title":"Appearance","abstract":[{"type":"text","text":"This article describes the KeyboardKit appearance engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Appearance","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/appearance"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLayoutProvider/preview":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" is "},{"type":"codeVoice","code":"PreviewKeyboardLayoutProvider"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"preview","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardLayoutProvider","preciseIdentifier":"s:14KeyboardKitPro0A14LayoutProviderP"}],"abstract":[{"type":"text","text":"This preview provider can be used in SwiftUI previews."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLayoutProvider\/preview","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardlayoutprovider\/preview"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions":{"role":"article","title":"Actions","abstract":[{"type":"text","text":"This article describes the KeyboardKit action engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/actions"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures":{"role":"article","title":"Gestures","abstract":[{"type":"text","text":"This article describes the KeyboardKit gesture engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/gestures"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout":{"role":"article","title":"Layouts","abstract":[{"type":"text","text":"This article describes the KeyboardKit keyboard layout engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/layout"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","title":"KeyboardKitPro","abstract":[{"type":"text","text":"KeyboardKit Pro helps you build custom keyboard extensions for iOS and iPadOS."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy-Extensions":{"role":"article","title":"Proxy Extensions","abstract":[{"type":"text","text":"This article describes how KeyboardKit extends "},{"type":"codeVoice","code":"UITextDocumentProxy"},{"type":"text","text":" with a lot of additional functionality."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Extensions","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/proxy-extensions"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/InputCalloutContext/preview":{"role":"symbol","title":"preview","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InputCalloutContext","preciseIdentifier":"s:14KeyboardKitPro19InputCalloutContextC"}],"abstract":[{"type":"text","text":"This preview context can be used in SwiftUI previews."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputCalloutContext\/preview","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/inputcalloutcontext\/preview"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/CalloutActionProvider":{"role":"symbol","title":"CalloutActionProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CalloutActionProvider"}],"abstract":[{"type":"text","text":"This protocol can be implemented by any classes that can be"},{"type":"text","text":" "},{"type":"text","text":"used to get callout actions for a keyboard action."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutActionProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CalloutActionProvider"}],"url":"\/documentation\/keyboardkitpro\/calloutactionprovider"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardActionHandler":{"role":"symbol","title":"KeyboardActionHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardActionHandler"}],"abstract":[{"type":"text","text":"This protocol can be implemented by classes that can handle"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction"},{"type":"text","text":" events."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardActionHandler"}],"url":"\/documentation\/keyboardkitpro\/keyboardactionhandler"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/preview":{"role":"symbol","title":"preview","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardInputViewController","preciseIdentifier":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController"}],"abstract":[{"type":"text","text":"This preview controller can be used in SwiftUI previews."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/preview","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/preview"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/RTL":{"role":"article","title":"RTL","abstract":[{"type":"text","text":"KeyboardKit supports RTL (right-to-left) locales, which means that it supports locales like "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale\/arabic"},{"type":"text","text":",  "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale\/persian"},{"type":"text","text":" etc."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/RTL","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/rtl"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/CalloutActionProvider/preview":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" is "},{"type":"codeVoice","code":"PreviewCalloutActionProvider"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"preview","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CalloutActionProvider","preciseIdentifier":"s:14KeyboardKitPro21CalloutActionProviderP"}],"abstract":[{"type":"text","text":"This preview provider can be used in SwiftUI previews."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/CalloutActionProvider\/preview","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/calloutactionprovider\/preview"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/InputCalloutContext":{"role":"symbol","title":"InputCalloutContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InputCalloutContext"}],"abstract":[{"type":"text","text":"This context can be used to handle callouts that show a big"},{"type":"text","text":" "},{"type":"text","text":"version of the currently typed character."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/InputCalloutContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InputCalloutContext"}],"url":"\/documentation\/keyboardkitpro\/inputcalloutcontext"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Appearance","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Extensions","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Routing","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/RTL","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title","value":"KeyboardInputViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments","value":[{"kind":"identifier","text":"KeyboardInputViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}