{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Getting-the-URL-to-your-apps-System-Settings-screen","level":2,"type":"heading","text":"Getting the URL to your app’s System Settings screen"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettingsUrlProvider"},{"type":"text","text":" protocol that provides any type that implements it with a static "},{"type":"codeVoice","code":".keyboardSettings"},{"type":"text","text":" URL that leads to your app’s System Settings screen."}]},{"type":"codeListing","syntax":"swift","code":["let url: URL = .keyboardSettings"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This protocol is implemented by "},{"type":"codeVoice","code":"URL"},{"type":"text","text":", which means that you can use "},{"type":"codeVoice","code":"URL.keyboardSettings"},{"type":"text","text":" to get the URL."}]},{"anchor":"Keyboard-settings-link","level":2,"type":"heading","text":"Keyboard settings link"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit also has a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettingsLink"},{"type":"text","text":" that will navigate the user to the settings url when tapped."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The link supports using a custom title, image and even url, although it will by default use values that make sense."}]},{"anchor":"Random-behavior","level":2,"type":"heading","text":"Random behavior"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you have used the url above, you may have noticed that it sometimes leads to your app’s System Settings screen, as expected, while at other times it just takes you to the System Settings root."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This random behavior makes for a bad user experience, since it may be hard for users to find your app in System Settings, if they have to navigate to it from the root screen…if they even know that it exists. This can lead to users not being able to enable or configure your keyboard."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Although this random behavior is bad, fixing it is actually very easy. All you have to do is just to add an empty Settings Bundle to your app, after which the app will consistently take you to the correct place in System Settings, instead of randomly taking you to the settings root."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/keyboardkitpro\/settings"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/settings"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This article describes the KeyboardKit settings utilities and how to use them."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Settings","role":"article","modules":[{"name":"KeyboardKitPro"}]},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"seeAlsoSections":[{"title":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Appearance","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Extensions","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Routing","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/RTL"],"generated":true}],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Previews":{"role":"article","title":"Previews","abstract":[{"type":"text","text":"This article describes how KeyboardKit makes it easy to preview keyboard-specific views."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/previews"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardSettingsLink":{"role":"symbol","title":"KeyboardSettingsLink","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardSettingsLink"}],"abstract":[{"type":"text","text":"This link can be used to navigate a user to System Settings."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettingsLink","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardSettingsLink"}],"url":"\/documentation\/keyboardkitpro\/keyboardsettingslink"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout":{"role":"article","title":"Layouts","abstract":[{"type":"text","text":"This article describes the KeyboardKit keyboard layout engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/layout"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions":{"role":"article","title":"Actions","abstract":[{"type":"text","text":"This article describes the KeyboardKit action engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/actions"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardSettingsUrlProvider":{"role":"symbol","title":"KeyboardSettingsUrlProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardSettingsUrlProvider"}],"abstract":[{"type":"text","text":"This protocol can be implemented by any type that should be"},{"type":"text","text":" "},{"type":"text","text":"able to resolve a URL to an app’s keyboard settings page in"},{"type":"text","text":" "},{"type":"text","text":"System Settings."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettingsUrlProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardSettingsUrlProvider"}],"url":"\/documentation\/keyboardkitpro\/keyboardsettingsurlprovider"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLocale/arabic":{"role":"symbol","title":"KeyboardLocale.arabic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"arabic"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale\/arabic","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardlocale\/arabic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback":{"role":"article","title":"Feedback","abstract":[{"type":"text","text":"This article describes the KeyboardKit feedback engine and how to use it to trigger audio and haptic feedback."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/feedback"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Routing":{"role":"article","title":"Routing","abstract":[{"type":"text","text":"This article describes how KeyboardKit adds ways for you to route text from the main app to other text fields within the keyboard."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Routing","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/routing"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/RTL":{"role":"article","title":"RTL","abstract":[{"type":"text","text":"KeyboardKit supports RTL (right-to-left) locales, which means that it supports locales like "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale\/arabic"},{"type":"text","text":",  "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale\/persian"},{"type":"text","text":" etc."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/RTL","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/rtl"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis":{"role":"article","title":"Emojis","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji model and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/emojis"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy-Extensions":{"role":"article","title":"Proxy Extensions","abstract":[{"type":"text","text":"This article describes how KeyboardKit extends "},{"type":"codeVoice","code":"UITextDocumentProxy"},{"type":"text","text":" with a lot of additional functionality."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Extensions","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/proxy-extensions"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization":{"role":"article","title":"Localization","abstract":[{"type":"text","text":"This article describes the KeyboardKit localization model and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/localization"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures":{"role":"article","title":"Gestures","abstract":[{"type":"text","text":"This article describes the KeyboardKit gesture engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/gestures"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts":{"role":"article","title":"Callouts","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/callouts"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Input":{"role":"article","title":"Input","abstract":[{"type":"text","text":"This article describes the KeyboardKit input set engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/input"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete":{"role":"article","title":"Autocomplete","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/autocomplete"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard":{"role":"article","title":"Keyboard","abstract":[{"type":"text","text":"This article describes the KeyboardKit keyboard types and how to use them."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboard"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardLocale/persian":{"role":"symbol","title":"KeyboardLocale.persian","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"persian"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardLocale\/persian","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardlocale\/persian"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Appearance":{"role":"article","title":"Appearance","abstract":[{"type":"text","text":"This article describes the KeyboardKit appearance engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Appearance","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/appearance"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards":{"role":"article","title":"External Keyboards","abstract":[{"type":"text","text":"This article describes the KeyboardKit external keyboard engine and how to use it."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/external-keyboards"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","title":"KeyboardKitPro","abstract":[{"type":"text","text":"KeyboardKit Pro helps you build custom keyboard extensions for iOS and iPadOS."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Appearance","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Extensions","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Routing","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/RTL"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}