{"seeAlsoSections":[{"anchor":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article"],"title":"Articles","generated":true}],"sections":[],"metadata":{"modules":[{"name":"KeyboardKitPro"}],"roleHeading":"Article","role":"article","title":"Settings","images":[{"identifier":"Page.png","type":"card"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article"},"kind":"article","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/keyboardkitpro\/settings-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/settings-article"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"primaryContentSections":[{"content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit provides you with auto-persisted keyboard-related settings, as well as ways to integrate with System Settings. You can use this to provide users with ways to open System Settings from the app and keyboard, and to configure the keyboard extension.","type":"text"}]},{"level":2,"type":"heading","text":"Settings Types","anchor":"Settings-Types"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit has ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings","isActive":true,"type":"reference"},{"text":" and other namespace-specific settings types that provide the following auto-persisted settings:","type":"text"}]},{"type":"tabNavigator","tabs":[{"title":"Keyboard","content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/addedLocales"}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/inputToolbarType-swift.property"}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/isAutocapitalizationEnabled"}]},{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/isKeyboardAutoCollapseEnabled"}]},{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/keyboardDockEdge","type":"reference"}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/keyboardLayoutTypeIdentifier"}]},{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/localeIdentifier","isActive":true}]},{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/spaceContextMenuLeading","isActive":true,"type":"reference"}]},{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/spaceContextMenuTrailing"}]},{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/spaceLongPressBehavior","type":"reference"}]}]},{"title":"Autocomplete","content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/isAutocompleteEnabled","isActive":true}],"type":"paragraph"},{"inlineContent":[{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/isAutocorrectEnabled","isActive":true,"type":"reference"}],"type":"paragraph"},{"inlineContent":[{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/isAutolearnEnabled","type":"reference","isActive":true}],"type":"paragraph"},{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/isAutoIgnoreEnabled"}],"type":"paragraph"},{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/isEmojiAutocompleteEnabled"}],"type":"paragraph"},{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/isNextCharacterPredictionEnabled"}],"type":"paragraph"},{"inlineContent":[{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/isNextWordPredictionEnabled","isActive":true,"type":"reference"}],"type":"paragraph"},{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/nextWordPredictionRequestApiKey"}],"type":"paragraph"},{"inlineContent":[{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/nextWordPredictionRequestType","isActive":true,"type":"reference"}],"type":"paragraph"},{"inlineContent":[{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/suggestionsDisplayCount","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"title":"Dictation","content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationSettings\/silenceLimit","type":"reference","isActive":true}]}]},{"title":"Feedback","content":[{"inlineContent":[{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedbackSettings\/isAudioFeedbackEnabled","isActive":true,"type":"reference"}],"type":"paragraph"},{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedbackSettings\/isHapticFeedbackEnabled","isActive":true}],"type":"paragraph"}]},{"title":"Themes","content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardThemeSettings\/theme"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"These settings can be set with code or presented to the user, for instance using the various KeyboardKit Pro settings screens. See the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","type":"reference","isActive":true},{"type":"text","text":" article for more information."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The various context classes have settings properties, like "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext","type":"reference","isActive":true},{"type":"text","text":" "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/settings-swift.property","type":"reference","isActive":true},{"type":"text","text":", that are used as the main settings values. The distinction between contexts and settings, is that a context provides contextual information, while settings provide persisted ones."}]},{"level":2,"type":"heading","text":"Settings Observation","anchor":"Settings-Observation"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note that while a context’s settings property, like "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/settings-swift.property","type":"reference"},{"type":"text","text":" is marked as "},{"code":"@Published","type":"codeVoice"},{"type":"text","text":", it will not publish any changes made to values within the type, e.g. when using a form. This means that views will by default not update if another view makes a change to a property."}]},{"type":"paragraph","inlineContent":[{"text":"You can solve this by using local state properties, bind those properties to the view or form, initialize the properties with the settings you want to affect, and sync any state changes back to those settings.","type":"text"}]},{"level":2,"type":"heading","text":"Settings Persistency & Sync","anchor":"Settings-Persistency--Sync"},{"inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings","isActive":true,"type":"reference"},{"type":"text","text":" class has a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/store","isActive":true,"type":"reference"},{"type":"text","text":" that is used by all settings types to persist data. This store will automatically sync data between the main app and its keyboard if you use a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","isActive":true,"type":"reference"},{"type":"text","text":" that defines an "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/appGroupId","isActive":true,"type":"reference"},{"type":"text","text":" to set up the app and keyboard."}],"type":"paragraph"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The auto-peristed settings properties will use the store that is available when they’re first used, so make sure to set up your app and keyboard as shown in ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started-Article","type":"reference","isActive":true},{"text":", ","type":"text"},{"type":"emphasis","inlineContent":[{"text":"before","type":"text"}]},{"text":" accessing any of these properties.","type":"text"}]}],"type":"aside","style":"important","name":"Important"},{"text":"System Settings","level":2,"type":"heading","anchor":"System-Settings"},{"inlineContent":[{"type":"text","text":"Since keyboard extensions can only access a limited set of all System Settings, your app must provide its own settings to great extent. This is made easy with KeyboardKit’s settings types and KeyboardKit Pro’s settings screens (see "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","type":"reference","isActive":true},{"type":"text","text":")."}],"type":"paragraph"},{"inlineContent":[{"text":"For settings that ","type":"text"},{"inlineContent":[{"text":"must","type":"text"}],"type":"emphasis"},{"text":" be done on a system level, your app or keyboard can open System Settings by triggering the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Foundation\/URL\/systemSettings","isActive":true,"type":"reference"},{"text":" URL. This can be used to let your users enable your keyboard, enable Full Access, etc.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"You can use a SwiftUI Link to open the URL, or trigger "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler\/handle(action:)","type":"reference","isActive":true},{"type":"text","text":" with a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/url(_:id:)","type":"reference","isActive":true},{"type":"text","text":" in any "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"},{"type":"codeListing","code":["if let url = URL.systemSettings {","    Link(\"Open System Settings\", destination: url)","}"],"syntax":"swift"},{"inlineContent":[{"type":"text","text":"If your app or keyboard randomly navigates to the Settings root instead of your app, try adding an empty Settings Bundle to your app."}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"text":"This article describes the KeyboardKit settings engine and its available settings.","type":"text"}],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AutocompleteSettings/isNextCharacterPredictionEnabled":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Whether next character prediction is enabled, by default "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/isNextCharacterPredictionEnabled","url":"\/documentation\/keyboardkitpro\/autocompletesettings\/isnextcharacterpredictionenabled","role":"symbol","title":"isNextCharacterPredictionEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isNextCharacterPredictionEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardSettings/store":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/store","title":"store","abstract":[{"type":"text","text":"The store that will be used by library settings."}],"url":"\/documentation\/keyboardkitpro\/keyboardsettings\/store","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"store"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSUserDefaults","kind":"typeIdentifier","text":"UserDefaults"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AutocompleteSettings/isAutoIgnoreEnabled":{"type":"topic","role":"symbol","title":"isAutoIgnoreEnabled","url":"\/documentation\/keyboardkitpro\/autocompletesettings\/isautoignoreenabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isAutoIgnoreEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/isAutoIgnoreEnabled","kind":"symbol","abstract":[{"type":"text","text":"Whether to automatically ignore adjusted suggestions, by default "},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","images":[{"type":"card","identifier":"Page.png"}],"role":"article","url":"\/documentation\/keyboardkitpro\/layout-article","title":"Layout","abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards-Article":{"images":[{"type":"card","identifier":"Page.png"}],"url":"\/documentation\/keyboardkitpro\/external-keyboards-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"type":"topic","role":"article","title":"External Keyboards","kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/url(_:id:)":{"url":"\/documentation\/keyboardkitpro\/keyboardaction\/url(_:id:)","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/url(_:id:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Open an url when released, using a custom id for identification."}],"title":"KeyboardAction.url(_:id:)","kind":"symbol","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AutocompleteSettings/nextWordPredictionRequestType":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextWordPredictionRequestType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Autocomplete","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro12AutocompleteV"},{"text":".","kind":"text"},{"text":"NextWordPredictionRequestType","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro12AutocompleteV29NextWordPredictionRequestTypeO"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/nextWordPredictionRequestType","abstract":[{"type":"text","text":"A custom, user-specified next word predicton request type."}],"title":"nextWordPredictionRequestType","role":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/autocompletesettings\/nextwordpredictionrequesttype"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardFeedbackSettings/isHapticFeedbackEnabled":{"role":"symbol","title":"isHapticFeedbackEnabled","type":"topic","abstract":[{"type":"text","text":"Whether haptic feedback is enabled, by default "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedbackSettings\/isHapticFeedbackEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isHapticFeedbackEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/keyboardkitpro\/keyboardfeedbacksettings\/ishapticfeedbackenabled"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardActionHandler":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardActionHandler","kind":"identifier"}],"navigatorTitle":[{"text":"KeyboardActionHandler","kind":"identifier"}],"title":"KeyboardActionHandler","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"This protocol can be implemented by any classes that can"},{"type":"text","text":" "},{"type":"text","text":"handle triggered "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction"},{"type":"text","text":" events."}],"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardactionhandler"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction":{"role":"symbol","abstract":[{"type":"text","text":"This enum defines keyboard-specific actions, and is also"},{"type":"text","text":" "},{"type":"text","text":"a namespace for keyboard action-related types."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardAction","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","navigatorTitle":[{"text":"KeyboardAction","kind":"identifier"}],"title":"KeyboardAction","url":"\/documentation\/keyboardkitpro\/keyboardaction"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Foundation/URL/systemSettings":{"url":"\/documentation\/keyboardkitpro\/foundation\/url\/systemsettings","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemSettings","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"systemSettings","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Foundation\/URL\/systemSettings","kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"This URL will deep link to the app’s custom settings","type":"text"},{"text":" ","type":"text"},{"text":"in System Settings.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AI-Article":{"type":"topic","kind":"article","abstract":[{"text":"This article describes the KeyboardKit AI support capabilities.","type":"text"}],"images":[{"type":"card","identifier":"Page.png"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","title":"AI Support","url":"\/documentation\/keyboardkitpro\/ai-article","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardSettings/keyboardDockEdge":{"abstract":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/DockEdge","isActive":true},{"text":" to use, if any.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardsettings\/keyboarddockedge","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/keyboardDockEdge","title":"keyboardDockEdge","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardDockEdge","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Keyboard","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V"},{"text":".","kind":"text"},{"text":"DockEdge","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V8DockEdgeO"},{"text":"?","kind":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"type":"topic","url":"\/documentation\/keyboardkitpro\/actions-article","kind":"article","title":"Actions","role":"article","images":[{"type":"card","identifier":"Page.png"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit action engine."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardSettings/spaceLongPressBehavior":{"title":"spaceLongPressBehavior","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardsettings\/spacelongpressbehavior","abstract":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/SpaceLongPressBehavior","isActive":true},{"type":"text","text":" to use for the space key."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/spaceLongPressBehavior","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"spaceLongPressBehavior","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A0V","text":"Keyboard","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A0V22SpaceLongPressBehaviorO","text":"SpaceLongPressBehavior","kind":"typeIdentifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardSettings/localeIdentifier":{"url":"\/documentation\/keyboardkitpro\/keyboardsettings\/localeidentifier","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localeIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"text":"The identifier of the current locale, set by ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/locale"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/localeIdentifier","title":"localeIdentifier","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/DictationSettings/silenceLimit":{"type":"topic","abstract":[{"type":"text","text":"The max number of seconds of silence, after which dictation automatically ends."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"silenceLimit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"title":"silenceLimit","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DictationSettings\/silenceLimit","url":"\/documentation\/keyboardkitpro\/dictationsettings\/silencelimit","kind":"symbol","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/DockEdge":{"title":"Keyboard.DockEdge","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/DockEdge","type":"topic","abstract":[{"text":"This enum defines supported keyboard dock edges.","type":"text"}],"kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboard\/dockedge","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DockEdge","kind":"identifier"}],"navigatorTitle":[{"text":"DockEdge","kind":"identifier"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Host-Article":{"role":"article","kind":"article","url":"\/documentation\/keyboardkitpro\/host-article","type":"topic","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes how KeyboardKit Pro can identify and use the host application."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","title":"Host Application"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/App-Article":{"title":"App Utilities","url":"\/documentation\/keyboardkitpro\/app-article","role":"article","abstract":[{"text":"This article describes the KeyboardKit app-specific utilities.","type":"text"}],"kind":"article","images":[{"identifier":"Page.png","type":"card"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AutocompleteSettings/isEmojiAutocompleteEnabled":{"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/isEmojiAutocompleteEnabled","abstract":[{"type":"text","text":"Whether emoji autocomplete is enabled, by default "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"title":"isEmojiAutocompleteEnabled","kind":"symbol","url":"\/documentation\/keyboardkitpro\/autocompletesettings\/isemojiautocompleteenabled","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEmojiAutocompleteEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation-Article":{"kind":"article","url":"\/documentation\/keyboardkitpro\/dictation-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"title":"Dictation","type":"topic","images":[{"type":"card","identifier":"Page.png"}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete-Article":{"url":"\/documentation\/keyboardkitpro\/autocomplete-article","abstract":[{"text":"This article describes the KeyboardKit autocomplete engine.","type":"text"}],"images":[{"type":"card","identifier":"Page.png"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","kind":"article","role":"article","type":"topic","title":"Autocomplete"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardSettings/isAutocapitalizationEnabled":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAutocapitalizationEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/isAutocapitalizationEnabled","title":"isAutocapitalizationEnabled","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Whether auto-capitalization is enabled."}],"url":"\/documentation\/keyboardkitpro\/keyboardsettings\/isautocapitalizationenabled"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardSettings/inputToolbarType-swift.property":{"title":"inputToolbarType","role":"symbol","abstract":[{"text":"The input toolbar type to use, if any.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/inputToolbarType-swift.property","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardsettings\/inputtoolbartype-swift.property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inputToolbarType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"InputToolbarType","preciseIdentifier":"s:14KeyboardKitPro0A8SettingsV16InputToolbarTypeO","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"url":"\/documentation\/keyboardkitpro\/localization-article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","title":"Localization","abstract":[{"text":"This article describes the KeyboardKit localization engine.","type":"text"}],"images":[{"identifier":"Page.png","type":"card"}],"role":"article","kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardSettings/keyboardLayoutTypeIdentifier":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/keyboardLayoutTypeIdentifier","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardLayoutTypeIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V","text":"Keyboard"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V10LayoutTypeO","text":"LayoutType"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V10LayoutTypeO2IDa","text":"ID"},{"kind":"text","text":"?"}],"url":"\/documentation\/keyboardkitpro\/keyboardsettings\/keyboardlayouttypeidentifier","title":"keyboardLayoutTypeIdentifier","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The identifier of the current layout type, set by "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/keyboardLayoutType"},{"type":"text","text":"."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AutocompleteSettings/suggestionsDisplayCount":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/suggestionsDisplayCount","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"suggestionsDisplayCount","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"role":"symbol","title":"suggestionsDisplayCount","url":"\/documentation\/keyboardkitpro\/autocompletesettings\/suggestionsdisplaycount","abstract":[{"type":"text","text":"The number of autocomplete suggestions to display, by default "},{"type":"codeVoice","code":"3"},{"type":"text","text":"."}],"type":"topic","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AutocompleteSettings/isAutolearnEnabled":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/isAutolearnEnabled","url":"\/documentation\/keyboardkitpro\/autocompletesettings\/isautolearnenabled","type":"topic","role":"symbol","abstract":[{"text":"Whether to autolearn unknown suggestions, by default ","type":"text"},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}],"title":"isAutolearnEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isAutolearnEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AutocompleteSettings/isAutocorrectEnabled":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isAutocorrectEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/isAutocorrectEnabled","abstract":[{"text":"Whether autocorrect is enabled, by default ","type":"text"},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/autocompletesettings\/isautocorrectenabled","title":"isAutocorrectEnabled","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"title":"KeyboardKitPro","kind":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","abstract":[{"text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI.","type":"text"}],"url":"\/documentation\/keyboardkitpro","role":"collection"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardSettings/spaceContextMenuLeading":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/spaceContextMenuLeading","title":"spaceContextMenuLeading","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"spaceContextMenuLeading","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A0V","text":"Keyboard","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A0V13SpaceMenuTypeO","text":"SpaceMenuType","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"A leading "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/SpaceMenuType"},{"type":"text","text":" to add to the space key, if any."}],"role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardsettings\/spacecontextmenuleading"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures-Article":{"type":"topic","kind":"article","abstract":[{"text":"This article describes the KeyboardKit gesture engine.","type":"text"}],"title":"Gestures","role":"article","url":"\/documentation\/keyboardkitpro\/gestures-article","images":[{"type":"card","identifier":"Page.png"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp/appGroupId":{"type":"topic","role":"symbol","kind":"symbol","title":"appGroupId","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/appGroupId","abstract":[{"type":"text","text":"The app’s App Group identifier, if any."}],"url":"\/documentation\/keyboardkitpro\/keyboardapp\/appgroupid","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"appGroupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/settings-swift.property":{"abstract":[{"text":"Auto-persisted keyboard settings.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardcontext\/settings-swift.property","title":"settings","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"settings","kind":"identifier"},{"text":": ","kind":"text"},{"text":"KeyboardSettings","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A8SettingsV"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/settings-swift.property"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardThemeSettings/theme":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"theme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardTheme","preciseIdentifier":"s:14KeyboardKitPro0A5ThemeV"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardthemesettings\/theme","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardThemeSettings\/theme","abstract":[{"text":"The current theme, if any.","type":"text"}],"kind":"symbol","role":"symbol","title":"theme"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Getting-Started-Article":{"type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This guide describes how to get started with KeyboardKit."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started-Article","url":"\/documentation\/keyboardkitpro\/getting-started-article","title":"Getting Started","kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Device-Article":{"kind":"article","url":"\/documentation\/keyboardkitpro\/device-article","title":"Device Utilities","abstract":[{"type":"text","text":"This article describes the KeyboardKit device utilities."}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","images":[{"type":"card","identifier":"Page.png"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Input-Article":{"url":"\/documentation\/keyboardkitpro\/input-article","role":"article","title":"Input","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","kind":"article","images":[{"type":"card","identifier":"Page.png"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit input engine."}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/SpaceLongPressBehavior":{"url":"\/documentation\/keyboardkitpro\/keyboard\/spacelongpressbehavior","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SpaceLongPressBehavior"}],"type":"topic","kind":"symbol","title":"Keyboard.SpaceLongPressBehavior","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/SpaceLongPressBehavior","navigatorTitle":[{"kind":"identifier","text":"SpaceLongPressBehavior"}],"role":"symbol","abstract":[{"type":"text","text":"This enum defines various space long press behaviors."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/keyboardLayoutType":{"url":"\/documentation\/keyboardkitpro\/keyboardcontext\/keyboardlayouttype","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/keyboardLayoutType","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardLayoutType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Keyboard","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V"},{"text":".","kind":"text"},{"text":"LayoutType","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V10LayoutTypeO"},{"text":"?","kind":"text"}],"title":"keyboardLayoutType","type":"topic","abstract":[{"text":"The current keyboard layout type, if any.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp":{"title":"KeyboardApp","navigatorTitle":[{"text":"KeyboardApp","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","kind":"symbol","role":"symbol","abstract":[{"text":"This type can be used to define important properties for","type":"text"},{"text":" ","type":"text"},{"text":"your app, and is also a namespace for app-based features.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardApp","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardapp"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardSettings":{"navigatorTitle":[{"kind":"identifier","text":"KeyboardSettings"}],"type":"topic","abstract":[{"type":"text","text":"This type is used for essential keyboard settings."}],"title":"KeyboardSettings","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardsettings","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardSettings","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardContext"}],"type":"topic","title":"KeyboardContext","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext","url":"\/documentation\/keyboardkitpro\/keyboardcontext","abstract":[{"text":"This class has observable states and persistent settings","type":"text"},{"text":" ","type":"text"},{"text":"for the core keyboard functionality.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardContext"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/locale":{"url":"\/documentation\/keyboardkitpro\/keyboardcontext\/locale","abstract":[{"type":"text","text":"The current locale, by default "},{"code":".current","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/locale","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"locale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale"}],"role":"symbol","title":"locale"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"kind":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","title":"Emojis","role":"article","url":"\/documentation\/keyboardkitpro\/emojis-article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback-Article":{"images":[{"type":"card","identifier":"Page.png"}],"role":"article","type":"topic","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/feedback-article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","title":"Feedback"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AutocompleteSettings/nextWordPredictionRequestApiKey":{"kind":"symbol","type":"topic","role":"symbol","title":"nextWordPredictionRequestApiKey","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/nextWordPredictionRequestApiKey","url":"\/documentation\/keyboardkitpro\/autocompletesettings\/nextwordpredictionrequestapikey","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextWordPredictionRequestApiKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[{"type":"text","text":"A custom, user-specified next word predicton request API key."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AutocompleteSettings/isAutocompleteEnabled":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isAutocompleteEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/keyboardkitpro\/autocompletesettings\/isautocompleteenabled","role":"symbol","title":"isAutocompleteEnabled","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/isAutocompleteEnabled","abstract":[{"type":"text","text":"Whether autocomplete is enabled, by default "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}]},"Page.png":{"identifier":"Page.png","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png","traits":["1x","light"]}],"alt":"Page icon","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardActionHandler/handle(action:)":{"role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Handle a certain keyboard action.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler\/handle(action:)","url":"\/documentation\/keyboardkitpro\/keyboardactionhandler\/handle(action:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A6ActionO","text":"KeyboardAction"},{"kind":"text","text":")"}],"title":"handle(action:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardSettings/addedLocales":{"abstract":[{"text":"A list of explicitly added locale identifiers.","type":"text"}],"kind":"symbol","type":"topic","title":"addedLocales","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addedLocales"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V","text":"Keyboard"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V11AddedLocaleV","text":"AddedLocale"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/addedLocales","role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardsettings\/addedlocales"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardSettings/isKeyboardAutoCollapseEnabled":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isKeyboardAutoCollapseEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isKeyboardAutoCollapseEnabled","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/isKeyboardAutoCollapseEnabled","abstract":[{"text":"Whether to auto-collapse the keyboard when an external keyboard is connected.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardsettings\/iskeyboardautocollapseenabled","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","type":"topic","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"title":"Callouts","role":"article","images":[{"type":"card","identifier":"Page.png"}],"url":"\/documentation\/keyboardkitpro\/callouts-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/SpaceMenuType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SpaceMenuType"}],"type":"topic","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboard\/spacemenutype","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SpaceMenuType"}],"title":"Keyboard.SpaceMenuType","abstract":[{"type":"text","text":"This enum defines spacebar context menus that can be"},{"type":"text","text":" "},{"type":"text","text":"added as leading and trailing items to the spacebar."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/SpaceMenuType"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AutocompleteSettings/isNextWordPredictionEnabled":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isNextWordPredictionEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AutocompleteSettings\/isNextWordPredictionEnabled","kind":"symbol","abstract":[{"text":"Whether next word prediction is enabled, by default ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/keyboardkitpro\/autocompletesettings\/isnextwordpredictionenabled","title":"isNextWordPredictionEnabled"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardSettings/spaceContextMenuTrailing":{"kind":"symbol","title":"spaceContextMenuTrailing","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"spaceContextMenuTrailing"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14KeyboardKitPro0A0V","kind":"typeIdentifier","text":"Keyboard"},{"kind":"text","text":"."},{"preciseIdentifier":"s:14KeyboardKitPro0A0V13SpaceMenuTypeO","kind":"typeIdentifier","text":"SpaceMenuType"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettings\/spaceContextMenuTrailing","url":"\/documentation\/keyboardkitpro\/keyboardsettings\/spacecontextmenutrailing","abstract":[{"text":"A trailing ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/SpaceMenuType","isActive":true,"type":"reference"},{"text":" to add to the space key, if any.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardFeedbackSettings/isAudioFeedbackEnabled":{"url":"\/documentation\/keyboardkitpro\/keyboardfeedbacksettings\/isaudiofeedbackenabled","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isAudioFeedbackEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether audio feedback is enabled, by default "},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"title":"isAudioFeedbackEnabled","kind":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardFeedbackSettings\/isAudioFeedbackEnabled"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":[{"generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article"],"anchor":"Articles","title":"Articles"}],"path":"\/seeAlsoSections","op":"replace"}]}]}