{"seeAlsoSections":[{"title":"Actions","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DeleteBackwardRange","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActions","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionRows","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionMappable"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StandardKeyboardActionHandler"}],"title":"StandardKeyboardActionHandler","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@KeyboardKitPro@objc(cs)StandardKeyboardActionHandler","modules":[{"name":"KeyboardKitPro"}],"navigatorTitle":[{"kind":"identifier","text":"StandardKeyboardActionHandler"}]},"abstract":[{"type":"text","text":"This standard keyboard action handler is used by default by"},{"type":"text","text":" "},{"type":"text","text":"KeyboardKit and provides a standard way of handling actions."}],"sections":[],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler","doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)NSObject","doc:\/\/com.keyboardkit.KeyboardKitPro\/s7CVarArgP","doc:\/\/com.keyboardkit.KeyboardKitPro\/s28CustomDebugStringConvertibleP","doc:\/\/com.keyboardkit.KeyboardKitPro\/s23CustomStringConvertibleP","doc:\/\/com.keyboardkit.KeyboardKitPro\/SQ","doc:\/\/com.keyboardkit.KeyboardKitPro\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/init(inputViewController:spaceDragGestureHandler:spaceDragSensitivity:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/init(keyboardController:keyboardContext:keyboardBehavior:keyboardFeedbackHandler:autocompleteContext:spaceDragGestureHandler:spaceDragSensitivity:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/autocompleteContext","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/keyboardBehavior","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/keyboardContext","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/keyboardController","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/keyboardFeedbackHandler","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/spaceDragGestureHandler","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/textDocumentProxy"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/action(for:on:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/canHandle(_:on:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/handle(_:on:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/handle(_:on:replaced:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/handleDrag(on:from:to:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/replacementAction(for:on:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/shouldTriggerFeedback(for:on:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/triggerFeedback(for:on:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/tryApplyAutocompleteSuggestion(before:on:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/tryChangeKeyboardType(after:on:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/tryEndSentence(after:on:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/tryHandleReplacementAction(before:on:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/tryRegisterEmoji(after:on:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/tryReinsertAutocompleteRemovedSpace(after:on:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/tryRemoveAutocompleteInsertedSpace(before:on:)"]}],"variants":[{"paths":["\/documentation\/keyboardkitpro\/standardkeyboardactionhandler"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/standardkeyboardactionhandler"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StandardKeyboardActionHandler"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can inherit this class and override any open properties"},{"type":"text","text":" "},{"type":"text","text":"and functions to customize the standard action behavior."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note that the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/keyboardController"},{"type":"text","text":" reference is "},{"type":"codeVoice","code":"weak"},{"type":"text","text":" to"},{"type":"text","text":" "},{"type":"text","text":"avoid a retain cycle when the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController"},{"type":"text","text":" "},{"type":"text","text":"uses itself to setup its action handler."}]}]}],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler/autocompleteContext":{"role":"symbol","title":"autocompleteContext","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"autocompleteContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutocompleteContext","preciseIdentifier":"s:14KeyboardKitPro19AutocompleteContextC"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/autocompleteContext","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/autocompletecontext"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler":{"role":"symbol","title":"StandardKeyboardActionHandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StandardKeyboardActionHandler"}],"abstract":[{"type":"text","text":"This standard keyboard action handler is used by default by"},{"type":"text","text":" "},{"type":"text","text":"KeyboardKit and provides a standard way of handling actions."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StandardKeyboardActionHandler"}],"url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler/tryChangeKeyboardType(after:on:)":{"role":"symbol","title":"tryChangeKeyboardType(after:on:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tryChangeKeyboardType"},{"kind":"text","text":"("},{"kind":"externalParam","text":"after"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardGesture","preciseIdentifier":"s:14KeyboardKitPro0A7GestureO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardAction","preciseIdentifier":"s:14KeyboardKitPro0A6ActionO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Try to change "},{"type":"codeVoice","code":"keyboardType"},{"type":"text","text":" after a "},{"type":"codeVoice","code":"gesture"},{"type":"text","text":" has been"},{"type":"text","text":" "},{"type":"text","text":"performed on the provided "},{"type":"codeVoice","code":"action"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/tryChangeKeyboardType(after:on:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/trychangekeyboardtype(after:on:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler/action(for:on:)":{"role":"symbol","title":"action(for:on:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"action"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardGesture","preciseIdentifier":"s:14KeyboardKitPro0A7GestureO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardAction","preciseIdentifier":"s:14KeyboardKitPro0A6ActionO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"KeyboardAction","preciseIdentifier":"s:14KeyboardKitPro0A6ActionO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"GestureAction","preciseIdentifier":"s:14KeyboardKitPro0A6ActionO07GestureD0a"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"This is the standard action that is used by the handler"},{"type":"text","text":" "},{"type":"text","text":"when a gesture is performed on a certain action."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/action(for:on:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/action(for:on:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler/tryEndSentence(after:on:)":{"role":"symbol","title":"tryEndSentence(after:on:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tryEndSentence"},{"kind":"text","text":"("},{"kind":"externalParam","text":"after"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardGesture","preciseIdentifier":"s:14KeyboardKitPro0A7GestureO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardAction","preciseIdentifier":"s:14KeyboardKitPro0A6ActionO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Try to end the current sentence after the "},{"type":"codeVoice","code":"gesture"},{"type":"text","text":" has"},{"type":"text","text":" "},{"type":"text","text":"been performed on the provided "},{"type":"codeVoice","code":"action"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/tryEndSentence(after:on:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/tryendsentence(after:on:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler/canHandle(_:on:)":{"role":"symbol","title":"canHandle(_:on:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canHandle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"KeyboardGesture","preciseIdentifier":"s:14KeyboardKitPro0A7GestureO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardAction","preciseIdentifier":"s:14KeyboardKitPro0A6ActionO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether or not the action handler can be used to handle"},{"type":"text","text":" "},{"type":"text","text":"a certain "},{"type":"codeVoice","code":"gesture"},{"type":"text","text":" on a certain "},{"type":"codeVoice","code":"action"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/canHandle(_:on:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/canhandle(_:on:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler/handle(_:on:)":{"role":"symbol","title":"handle(_:on:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"KeyboardGesture","preciseIdentifier":"s:14KeyboardKitPro0A7GestureO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardAction","preciseIdentifier":"s:14KeyboardKitPro0A6ActionO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Try to handling a certain "},{"type":"codeVoice","code":"gesture"},{"type":"text","text":" n a certain "},{"type":"codeVoice","code":"action"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/handle(_:on:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/handle(_:on:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler/shouldTriggerFeedback(for:on:)":{"role":"symbol","title":"shouldTriggerFeedback(for:on:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldTriggerFeedback"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardGesture","preciseIdentifier":"s:14KeyboardKitPro0A7GestureO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardAction","preciseIdentifier":"s:14KeyboardKitPro0A6ActionO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether or not a feedback should be given for a certain"},{"type":"text","text":" "},{"type":"text","text":"gesture on a certain action."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/shouldTriggerFeedback(for:on:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/shouldtriggerfeedback(for:on:)"},"doc://com.keyboardkit.KeyboardKitPro/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/s23CustomStringConvertibleP"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler/handleDrag(on:from:to:)":{"role":"symbol","title":"handleDrag(on:from:to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleDrag"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardAction","preciseIdentifier":"s:14KeyboardKitPro0A6ActionO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Handle a drag gesture on a certain action, from a start"},{"type":"text","text":" "},{"type":"text","text":"location to the drag gesture’s current location."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/handleDrag(on:from:to:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/handledrag(on:from:to:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler/init(inputViewController:spaceDragGestureHandler:spaceDragSensitivity:)":{"role":"symbol","title":"init(inputViewController:spaceDragGestureHandler:spaceDragSensitivity:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inputViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardInputViewController","preciseIdentifier":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"spaceDragGestureHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DragGestureHandler","preciseIdentifier":"s:14KeyboardKitPro18DragGestureHandlerP"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"spaceDragSensitivity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SpaceDragSensitivity","preciseIdentifier":"s:14KeyboardKitPro20SpaceDragSensitivityO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Create a standard keyboard action handler, using a view"},{"type":"text","text":" "},{"type":"text","text":"controller to setup all dependencies."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/init(inputViewController:spaceDragGestureHandler:spaceDragSensitivity:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/init(inputviewcontroller:spacedraggesturehandler:spacedragsensitivity:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler/keyboardFeedbackHandler":{"role":"symbol","title":"keyboardFeedbackHandler","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardFeedbackHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardFeedbackHandler","preciseIdentifier":"s:14KeyboardKitPro0A15FeedbackHandlerP"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/keyboardFeedbackHandler","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/keyboardfeedbackhandler"},"doc://com.keyboardkit.KeyboardKitPro/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/SQ"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler/tryApplyAutocompleteSuggestion(before:on:)":{"role":"symbol","title":"tryApplyAutocompleteSuggestion(before:on:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tryApplyAutocompleteSuggestion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"before"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardGesture","preciseIdentifier":"s:14KeyboardKitPro0A7GestureO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardAction","preciseIdentifier":"s:14KeyboardKitPro0A6ActionO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Try to apply an "},{"type":"codeVoice","code":"isAutocomplete"},{"type":"text","text":" autocomplete suggesion"},{"type":"text","text":" "},{"type":"text","text":"before the "},{"type":"codeVoice","code":"gesture"},{"type":"text","text":" has been performed on the "},{"type":"codeVoice","code":"action"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/tryApplyAutocompleteSuggestion(before:on:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/tryapplyautocompletesuggestion(before:on:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler/init(keyboardController:keyboardContext:keyboardBehavior:keyboardFeedbackHandler:autocompleteContext:spaceDragGestureHandler:spaceDragSensitivity:)":{"role":"symbol","title":"init(keyboardController:keyboardContext:keyboardBehavior:keyboardFeedbackHandler:autocompleteContext:spaceDragGestureHandler:spaceDragSensitivity:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keyboardController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardController","preciseIdentifier":"s:14KeyboardKitPro0A10ControllerP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"keyboardContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardContext","preciseIdentifier":"s:14KeyboardKitPro0A7ContextC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"keyboardBehavior"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardBehavior","preciseIdentifier":"s:14KeyboardKitPro0A8BehaviorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"keyboardFeedbackHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardFeedbackHandler","preciseIdentifier":"s:14KeyboardKitPro0A15FeedbackHandlerP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autocompleteContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutocompleteContext","preciseIdentifier":"s:14KeyboardKitPro19AutocompleteContextC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"spaceDragGestureHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DragGestureHandler","preciseIdentifier":"s:14KeyboardKitPro18DragGestureHandlerP"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"spaceDragSensitivity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SpaceDragSensitivity","preciseIdentifier":"s:14KeyboardKitPro20SpaceDragSensitivityO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Create a standard keyboard action handler."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/init(keyboardController:keyboardContext:keyboardBehavior:keyboardFeedbackHandler:autocompleteContext:spaceDragGestureHandler:spaceDragSensitivity:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/init(keyboardcontroller:keyboardcontext:keyboardbehavior:keyboardfeedbackhandler:autocompletecontext:spacedraggesturehandler:spacedragsensitivity:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction":{"role":"symbol","title":"KeyboardAction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardAction"}],"abstract":[{"type":"text","text":"This enum defines keyboard-specific actions that correspond"},{"type":"text","text":" "},{"type":"text","text":"to actions that can be found on various keyboards."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardAction"}],"url":"\/documentation\/keyboardkitpro\/keyboardaction"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler/tryRemoveAutocompleteInsertedSpace(before:on:)":{"role":"symbol","title":"tryRemoveAutocompleteInsertedSpace(before:on:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tryRemoveAutocompleteInsertedSpace"},{"kind":"text","text":"("},{"kind":"externalParam","text":"before"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardGesture","preciseIdentifier":"s:14KeyboardKitPro0A7GestureO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardAction","preciseIdentifier":"s:14KeyboardKitPro0A6ActionO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Try to removed an autocomplete inserted space after the"},{"type":"text","text":" "},{"type":"codeVoice","code":"gesture"},{"type":"text","text":" has been performed on the provided "},{"type":"codeVoice","code":"action"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/tryRemoveAutocompleteInsertedSpace(before:on:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/tryremoveautocompleteinsertedspace(before:on:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"role":"symbol","title":"KeyboardInputViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardInputViewController"}],"abstract":[{"type":"text","text":"This class extends "},{"type":"codeVoice","code":"UIInputViewController"},{"type":"text","text":" with KeyboardKit"},{"type":"text","text":" "},{"type":"text","text":"specific functionality."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardInputViewController"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler/spaceDragGestureHandler":{"role":"symbol","title":"spaceDragGestureHandler","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"spaceDragGestureHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DragGestureHandler","preciseIdentifier":"s:14KeyboardKitPro18DragGestureHandlerP"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/spaceDragGestureHandler","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/spacedraggesturehandler"},"doc://com.keyboardkit.KeyboardKitPro/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/SH"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler/keyboardBehavior":{"role":"symbol","title":"keyboardBehavior","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardBehavior"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardBehavior","preciseIdentifier":"s:14KeyboardKitPro0A8BehaviorP"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/keyboardBehavior","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/keyboardbehavior"},"doc://com.keyboardkit.KeyboardKitPro/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/s28CustomDebugStringConvertibleP"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler/tryHandleReplacementAction(before:on:)":{"role":"symbol","title":"tryHandleReplacementAction(before:on:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tryHandleReplacementAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"before"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardGesture","preciseIdentifier":"s:14KeyboardKitPro0A7GestureO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardAction","preciseIdentifier":"s:14KeyboardKitPro0A6ActionO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Try to resolve and handle a replacement keyboard action"},{"type":"text","text":" "},{"type":"text","text":"before the "},{"type":"codeVoice","code":"gesture"},{"type":"text","text":" is performed on the "},{"type":"codeVoice","code":"action"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/tryHandleReplacementAction(before:on:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/tryhandlereplacementaction(before:on:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler/handle(_:on:replaced:)":{"role":"symbol","title":"handle(_:on:replaced:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"KeyboardGesture","preciseIdentifier":"s:14KeyboardKitPro0A7GestureO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardAction","preciseIdentifier":"s:14KeyboardKitPro0A6ActionO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replaced"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Try handling a certain "},{"type":"codeVoice","code":"gesture"},{"type":"text","text":" on a certain "},{"type":"codeVoice","code":"action"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/handle(_:on:replaced:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/handle(_:on:replaced:)"},"doc://com.keyboardkit.KeyboardKitPro/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/s7CVarArgP"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler/replacementAction(for:on:)":{"role":"symbol","title":"replacementAction(for:on:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"replacementAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardGesture","preciseIdentifier":"s:14KeyboardKitPro0A7GestureO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardAction","preciseIdentifier":"s:14KeyboardKitPro0A6ActionO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"KeyboardAction","preciseIdentifier":"s:14KeyboardKitPro0A6ActionO"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Try to resolve a replacement keyboard action before the"},{"type":"text","text":" "},{"type":"codeVoice","code":"gesture"},{"type":"text","text":" is performed on the provided "},{"type":"codeVoice","code":"action"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/replacementAction(for:on:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/replacementaction(for:on:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardActionRows":{"role":"symbol","title":"KeyboardActionRows","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardActionRows"}],"abstract":[{"type":"text","text":"This typealias represents a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActions"},{"type":"text","text":" array."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionRows","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardActionRows"}],"url":"\/documentation\/keyboardkitpro\/keyboardactionrows"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/DeleteBackwardRange":{"role":"symbol","title":"DeleteBackwardRange","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeleteBackwardRange"}],"abstract":[{"type":"text","text":"This enum can be used to vary how the backspace action will"},{"type":"text","text":" "},{"type":"text","text":"behave when pressing and holding the backspace key."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/DeleteBackwardRange","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeleteBackwardRange"}],"url":"\/documentation\/keyboardkitpro\/deletebackwardrange"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler/triggerFeedback(for:on:)":{"role":"symbol","title":"triggerFeedback(for:on:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"triggerFeedback"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardGesture","preciseIdentifier":"s:14KeyboardKitPro0A7GestureO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardAction","preciseIdentifier":"s:14KeyboardKitPro0A6ActionO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Trigger feedback for a certain "},{"type":"codeVoice","code":"gesture"},{"type":"text","text":" on an "},{"type":"codeVoice","code":"action"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"if "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/shouldTriggerFeedback(for:on:)"},{"type":"text","text":" returns "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/triggerFeedback(for:on:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/triggerfeedback(for:on:)"},"doc://com.keyboardkit.KeyboardKitPro/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(cs)NSObject"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardActionHandler":{"role":"symbol","title":"KeyboardActionHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardActionHandler"}],"abstract":[{"type":"text","text":"This protocol can be implemented by classes that can handle"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction"},{"type":"text","text":" events."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardActionHandler"}],"url":"\/documentation\/keyboardkitpro\/keyboardactionhandler"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler/keyboardContext":{"role":"symbol","title":"keyboardContext","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardContext","preciseIdentifier":"s:14KeyboardKitPro0A7ContextC"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/keyboardContext","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/keyboardcontext"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler/tryRegisterEmoji(after:on:)":{"role":"symbol","title":"tryRegisterEmoji(after:on:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tryRegisterEmoji"},{"kind":"text","text":"("},{"kind":"externalParam","text":"after"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardGesture","preciseIdentifier":"s:14KeyboardKitPro0A7GestureO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardAction","preciseIdentifier":"s:14KeyboardKitPro0A6ActionO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Try to register a certain emoji after the "},{"type":"codeVoice","code":"gesture"},{"type":"text","text":" has"},{"type":"text","text":" "},{"type":"text","text":"been performed on the provided "},{"type":"codeVoice","code":"action"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/tryRegisterEmoji(after:on:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/tryregisteremoji(after:on:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler/keyboardController":{"role":"symbol","title":"keyboardController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardController","preciseIdentifier":"s:14KeyboardKitPro0A10ControllerP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/keyboardController","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/keyboardcontroller"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/ReturnType":{"role":"symbol","title":"KeyboardAction.ReturnType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReturnType"}],"abstract":[{"type":"text","text":"This enum can be used together with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/primary(_:)"},{"type":"text","text":" and"},{"type":"text","text":" "},{"type":"text","text":"represents a primary button on the keyboard."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/ReturnType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReturnType"}],"url":"\/documentation\/keyboardkitpro\/keyboardaction\/returntype"},"doc://com.keyboardkit.KeyboardKitPro/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)NSObject"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardActionMappable/keyboardAction":{"role":"symbol","title":"keyboardAction","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardAction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardAction","preciseIdentifier":"s:14KeyboardKitPro0A6ActionO"}],"abstract":[{"type":"text","text":"The keyboard action that this type maps to."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionMappable\/keyboardAction","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardactionmappable\/keyboardaction"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler/tryReinsertAutocompleteRemovedSpace(after:on:)":{"role":"symbol","title":"tryReinsertAutocompleteRemovedSpace(after:on:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tryReinsertAutocompleteRemovedSpace"},{"kind":"text","text":"("},{"kind":"externalParam","text":"after"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardGesture","preciseIdentifier":"s:14KeyboardKitPro0A7GestureO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardAction","preciseIdentifier":"s:14KeyboardKitPro0A6ActionO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Try to reinsert an automatically removed space that was"},{"type":"text","text":" "},{"type":"text","text":"removed due to autocomplete after the provided "},{"type":"codeVoice","code":"gesture"},{"type":"text","text":" "},{"type":"text","text":"has been performed on the provided "},{"type":"codeVoice","code":"action"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/tryReinsertAutocompleteRemovedSpace(after:on:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/tryreinsertautocompleteremovedspace(after:on:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler/textDocumentProxy":{"role":"symbol","title":"textDocumentProxy","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textDocumentProxy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextDocumentProxy","preciseIdentifier":"c:objc(pl)UITextDocumentProxy"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/textDocumentProxy","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/textdocumentproxy"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","title":"KeyboardKitPro","abstract":[{"type":"text","text":"KeyboardKit Pro helps you build custom keyboard extensions for iOS and iPadOS."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardActionMappable":{"role":"symbol","title":"KeyboardActionMappable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardActionMappable"}],"abstract":[{"type":"text","text":"This protocol can be implemented by types that can return a"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/ReturnType"},{"type":"text","text":", which is then be mapped to a"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/primary(_:)"},{"type":"text","text":" action by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionMappable\/keyboardAction"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionMappable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardActionMappable"}],"url":"\/documentation\/keyboardkitpro\/keyboardactionmappable"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/primary(_:)":{"role":"symbol","title":"KeyboardAction.primary(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"primary"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ReturnType","preciseIdentifier":"s:14KeyboardKitPro0A6ActionO10ReturnTypeO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Represents a primary return button, e.g. "},{"type":"codeVoice","code":"return"},{"type":"text","text":", "},{"type":"codeVoice","code":"go"},{"type":"text","text":", "},{"type":"codeVoice","code":"search"},{"type":"text","text":" etc."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/primary(_:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/primary(_:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardActions":{"role":"symbol","title":"KeyboardActions","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardActions"}],"abstract":[{"type":"text","text":"This typealias represents a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction"},{"type":"text","text":" array."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardActions"}],"url":"\/documentation\/keyboardkitpro\/keyboardactions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"StandardKeyboardActionHandler"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"StandardKeyboardActionHandler"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"StandardKeyboardActionHandler"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"StandardKeyboardActionHandler"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1StandardKeyboardActionHandler\/title","value":"StandardKeyboardActionHandler"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1StandardKeyboardActionHandler\/fragments","value":[{"kind":"identifier","text":"StandardKeyboardActionHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title","value":"KeyboardInputViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments","value":[{"kind":"identifier","text":"KeyboardInputViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}