{"sections":[],"abstract":[{"text":"This article describes the KeyboardKit status engine.","type":"text"}],"seeAlsoSections":[{"title":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article"],"generated":true,"anchor":"Articles"}],"primaryContentSections":[{"content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"inlineContent":[{"text":"KeyboardKit has ways to check various keyboard statuses, e.g. if a keyboard is enabled in System Settings, if Full Access is enabled, if a keyboard is actively being used, etc. This can be used to help users set up their keyboard.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"👑 ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro"},{"text":" unlocks more keyboard status-related views & utilities. Information about Pro features can be found further down.","type":"text"}],"type":"paragraph"},{"text":"Namespace","anchor":"Namespace","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"KeyboardKit has a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStatus","isActive":true},{"type":"text","text":" namespace that contains status-related types and views, like the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStatus\/Label","isActive":true},{"type":"text","text":" that can be used to visualize a certain status value, as well as the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStatus\/Section","isActive":true},{"type":"text","text":" which is unlocked by KeyboardKit Pro."}],"type":"paragraph"},{"text":"Context","anchor":"Context","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"The observable "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStatusContext"},{"type":"text","text":" can be used to observe the state of any keyboard:"}],"type":"paragraph"},{"code":["struct MyView: View {","","    @StateObject","    var status = KeyboardStatusContext(bundleId: \"com.myapp.keyboard\")","","    var body: some View {","        VStack {","            Text(\"Enabled: \\(status.isKeyboardEnabled.description)\")","            Text(\"Active: \\(status.isKeyboardActive.description)\")","            Text(\"Full Access: \\(status.isFullAccessEnabled.description)\")","        }","    }","} "],"syntax":"swift","type":"codeListing"},{"inlineContent":[{"type":"text","text":"The context is observable, so any status changes will immediately cause the view to refresh. It supports bundle ID wildcards, which lets you inspect multiple keyboards with a single instance:"}],"type":"paragraph"},{"code":["@StateObject","var status = KeyboardStatusContext(bundleId: \"com.myapp.*\")"],"syntax":null,"type":"codeListing"},{"text":"Views","anchor":"Views","type":"heading","level":2},{"inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStatus","type":"reference"},{"text":" namespace has status-specific views, that can be used to display various keyboard status-related values:","type":"text"}],"type":"paragraph"},{"tabs":[{"title":"Label","content":[{"numberOfColumns":2,"type":"row","columns":[{"size":1,"content":[{"inlineContent":[{"type":"image","identifier":"keyboardstatuslabel"}],"type":"paragraph"}]},{"size":1,"content":[{"type":"paragraph","inlineContent":[{"text":"A keyboard status ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStatus\/Label","type":"reference","isActive":true},{"text":" can display various keyboard statuses, e.g. if a keyboard has been enabled, if Full Access is enabled, etc.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The view supports custom texts, icons, etc. and can be styled with the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/keyboardStatusLabelStyle(_:)","isActive":true},{"type":"text","text":" view modifier."}]}]}]}]}],"type":"tabNavigator"},{"type":"thematicBreak"},{"text":"👑 KeyboardKit Pro","anchor":"%F0%9F%91%91-KeyboardKit-Pro","type":"heading","level":2},{"inlineContent":[{"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","overridingTitle":"KeyboardKit Pro","type":"reference","overridingTitleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"isActive":true},{"text":" unlocks additional keyboard status views and utilities, like a keyboard status section that can be added to the home or settings screen in an app that has a custom keyboard.","type":"text"}],"type":"paragraph"},{"tabs":[{"title":"Section","content":[{"type":"row","numberOfColumns":2,"columns":[{"content":[{"inlineContent":[{"identifier":"keyboardstatussection","type":"image"}],"type":"paragraph"}],"size":1},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A keyboard status "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStatus\/Section","type":"reference","isActive":true},{"type":"text","text":" can display all relevant status labels for a keyboard extension, with a link to System Settings if needed."}]},{"type":"paragraph","inlineContent":[{"text":"The view is used by the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/HomeScreen","isActive":true,"type":"reference"},{"text":" component, and can be added as a standalone section, in e.g. an app’s settings screen.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The view can be styled with the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/keyboardStatusSectionStyle(_:)","type":"reference","isActive":true},{"type":"text","text":" view modifier."}]}],"size":1}]}]}],"type":"tabNavigator"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/keyboardkitpro\/status-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/status-article"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"kind":"article","metadata":{"title":"Status","images":[{"type":"card","identifier":"Page.png"}],"roleHeading":"Article","role":"article","modules":[{"name":"KeyboardKitPro"}]},"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"url":"\/documentation\/keyboardkitpro","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"type":"topic","title":"KeyboardKitPro","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}],"url":"\/documentation\/keyboardkitpro\/autocomplete-article","type":"topic","title":"Autocomplete","role":"article","images":[{"identifier":"Page.png","type":"card"}],"kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis-Article":{"url":"\/documentation\/keyboardkitpro\/emojis-article","type":"topic","title":"Emojis","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"text":"This article describes the KeyboardKit emoji engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","kind":"article","role":"article"},"https://github.com/KeyboardKit/KeyboardKitPro":{"type":"link","url":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","title":"KeyboardKit Pro","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","titleInlineContent":[{"text":"KeyboardKit Pro","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards-Article":{"role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","url":"\/documentation\/keyboardkitpro\/external-keyboards-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"title":"External Keyboards"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Input-Article":{"title":"Input","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","url":"\/documentation\/keyboardkitpro\/input-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}],"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit input engine."}],"role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AI-Article":{"abstract":[{"text":"This article describes the KeyboardKit AI support capabilities.","type":"text"}],"role":"article","type":"topic","kind":"article","images":[{"identifier":"Page.png","type":"card"}],"url":"\/documentation\/keyboardkitpro\/ai-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","title":"AI Support"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"title":"Callouts","kind":"article","url":"\/documentation\/keyboardkitpro\/callouts-article","role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardStatusContext":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStatusContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardStatusContext"}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardStatusContext"}],"kind":"symbol","title":"KeyboardStatusContext","url":"\/documentation\/keyboardkitpro\/keyboardstatuscontext","abstract":[{"type":"text","text":"This class has observable, keyboard status-related state."}],"role":"symbol"},"Page.png":{"type":"image","alt":"Page icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png"}],"identifier":"Page.png"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"role":"article","url":"\/documentation\/keyboardkitpro\/localization-article","abstract":[{"text":"This article describes the KeyboardKit localization engine.","type":"text"}],"type":"topic","title":"Localization","images":[{"identifier":"Page.png","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp/HomeScreen":{"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HomeScreen","kind":"identifier"}],"navigatorTitle":[{"text":"HomeScreen","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/HomeScreen","url":"\/documentation\/keyboardkitpro\/keyboardapp\/homescreen","abstract":[{"type":"text","text":"This screen can be used as the main home screen in a"},{"type":"text","text":" "},{"type":"text","text":"keyboard app, and looks a bit like the Settings app."}],"title":"KeyboardApp.HomeScreen"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"images":[{"identifier":"Page.png","type":"card"}],"title":"Actions","url":"\/documentation\/keyboardkitpro\/actions-article","kind":"article","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"type":"topic"},"keyboardstatuslabel":{"type":"image","alt":"KeyboardStatus.Label","identifier":"keyboardstatuslabel","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/keyboardstatuslabel.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures-Article":{"type":"topic","images":[{"identifier":"Page.png","type":"card"}],"kind":"article","url":"\/documentation\/keyboardkitpro\/gestures-article","role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit gesture engine."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","title":"Gestures"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Device-Article":{"role":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","url":"\/documentation\/keyboardkitpro\/device-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit device utilities."}],"title":"Device Utilities"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/App-Article":{"url":"\/documentation\/keyboardkitpro\/app-article","type":"topic","kind":"article","role":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","title":"App Utilities"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation-Article":{"abstract":[{"text":"This article describes the KeyboardKit dictation engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/dictation-article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","type":"topic","images":[{"identifier":"Page.png","type":"card"}],"role":"article","title":"Dictation"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardStatus/Label":{"abstract":[{"text":"This label can be used to show the currently enabled","type":"text"},{"type":"text","text":" "},{"type":"text","text":"state for a keyboard."}],"title":"KeyboardStatus.Label","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Label","kind":"identifier"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardstatus\/label","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStatus\/Label","role":"symbol","navigatorTitle":[{"text":"Label","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback-Article":{"images":[{"identifier":"Page.png","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","url":"\/documentation\/keyboardkitpro\/feedback-article","type":"topic","role":"article","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"kind":"article","title":"Feedback"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Host-Article":{"kind":"article","role":"article","images":[{"identifier":"Page.png","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","url":"\/documentation\/keyboardkitpro\/host-article","type":"topic","title":"Host Application","abstract":[{"type":"text","text":"This article describes how KeyboardKit Pro can identify and use the host application."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUICore/View/keyboardStatusLabelStyle(_:)":{"title":"keyboardStatusLabelStyle(_:)","abstract":[{"type":"text","text":"Apply a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStatus\/LabelStyle"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/keyboardStatusLabelStyle(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardStatusLabelStyle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"KeyboardStatus","preciseIdentifier":"s:14KeyboardKitPro0A6StatusV","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"LabelStyle","preciseIdentifier":"s:14KeyboardKitPro0A6StatusV10LabelStyleV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/swiftuicore\/view\/keyboardstatuslabelstyle(_:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardStatus/SectionStyle":{"abstract":[{"type":"text","text":"This type can style a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStatus\/Section","isActive":true},{"type":"text","text":"."}],"navigatorTitle":[{"text":"SectionStyle","kind":"identifier"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardstatus\/sectionstyle","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStatus\/SectionStyle","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SectionStyle","kind":"identifier"}],"title":"KeyboardStatus.SectionStyle","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardStatus/Section":{"url":"\/documentation\/keyboardkitpro\/keyboardstatus\/section","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStatus\/Section","navigatorTitle":[{"kind":"identifier","text":"Section"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Section"}],"title":"KeyboardStatus.Section","abstract":[{"type":"text","text":"This section can be used to show keyboard status for"},{"type":"text","text":" "},{"type":"text","text":"a certain keyboard bundle ID."}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardStatus/LabelStyle":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LabelStyle","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardstatus\/labelstyle","abstract":[{"type":"text","text":"This style can be used to modify the visual style of"},{"type":"text","text":" "},{"type":"text","text":"the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStatus\/Label","isActive":true,"type":"reference"},{"text":" component.","type":"text"}],"role":"symbol","type":"topic","title":"KeyboardStatus.LabelStyle","navigatorTitle":[{"kind":"identifier","text":"LabelStyle"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStatus\/LabelStyle"},"keyboardstatussection":{"type":"image","alt":"KeyboardStatus.Label","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/keyboardstatussection.jpg"}],"identifier":"keyboardstatussection"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUICore/View/keyboardStatusSectionStyle(_:)":{"title":"keyboardStatusSectionStyle(_:)","abstract":[{"type":"text","text":"Apply a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStatus\/SectionStyle","type":"reference","isActive":true},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/keyboardStatusSectionStyle(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardStatusSectionStyle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"KeyboardStatus","preciseIdentifier":"s:14KeyboardKitPro0A6StatusV","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"SectionStyle","preciseIdentifier":"s:14KeyboardKitPro0A6StatusV12SectionStyleV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/swiftuicore\/view\/keyboardstatussectionstyle(_:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardStatus":{"title":"KeyboardStatus","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardStatus","kind":"identifier"}],"abstract":[{"text":"This namespace contains keyboard status-related types.","type":"text"}],"navigatorTitle":[{"text":"KeyboardStatus","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStatus","url":"\/documentation\/keyboardkitpro\/keyboardstatus","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"abstract":[{"text":"This article describes the KeyboardKit layout engine.","type":"text"}],"title":"Layout","kind":"article","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","url":"\/documentation\/keyboardkitpro\/layout-article","type":"topic","images":[{"identifier":"Page.png","type":"card"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"title":"Articles","generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article"],"anchor":"Articles"}],"path":"\/seeAlsoSections"}]}]}