{"metadata":{"modules":[{"name":"KeyboardKitPro"}],"roleHeading":"Article","role":"article","title":"Styling","images":[{"identifier":"Page.png","type":"card"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"article","seeAlsoSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article"],"title":"Articles","generated":true,"anchor":"Articles"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit styling engine."}],"primaryContentSections":[{"kind":"content","content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"inlineContent":[{"text":"While native iOS keyboards provide no way to customize the look & feel of the keyboard, KeyboardKit keyboards can be to great extent.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Most KeyboardKit views have a corresponding "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View","type":"reference"},{"type":"text","text":" modifier that lets you apply a custom style. You can also use a "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyleService","type":"reference"},{"type":"text","text":" to style more complex views, like the "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","type":"reference"},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"text":"👑 ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro"},{"text":" unlocks a theme engine and many pre-defined themes. Information about Pro features can be found further down.","type":"text"}],"type":"paragraph"},{"level":2,"anchor":"Namespace","type":"heading","text":"Namespace"},{"inlineContent":[{"type":"text","text":"KeyboardKit has a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyle","isActive":true},{"type":"text","text":" namespace that contains style-related types."}],"type":"paragraph"},{"level":2,"anchor":"Services","type":"heading","text":"Services"},{"inlineContent":[{"type":"text","text":"In KeyboardKit, a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyleService","isActive":true},{"type":"text","text":" can provide dynamic styles for different parts of a keyboard. Unlike static styles, a style service can vary styles depending on "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext","isActive":true},{"type":"text","text":", "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","isActive":true},{"type":"text","text":", etc."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"KeyboardKit injects a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyle\/StandardStyleService"},{"type":"text","text":" into "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services"},{"type":"text","text":" when the keyboard is launched. You can replace it at any time, as described further down."}],"type":"paragraph"},{"level":2,"anchor":"Color--Image-Extensions","type":"heading","text":"Color & Image Extensions"},{"inlineContent":[{"type":"text","text":"KeyboardKit defines additional, keyboard-specific "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/Color"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/Image"},{"type":"text","text":" extensions, like "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/Color\/keyboardBackground"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/Image\/keyboard"},{"type":"text","text":", etc. to make it easy to create keyboards that look like a native iOS keyboard."}],"type":"paragraph"},{"columns":[{"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"styling-images"}]}],"size":1},{"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"styling-colors"}]}],"size":1}],"type":"row","numberOfColumns":2},{"inlineContent":[{"text":"KeyboardKit defines contextual colors that take a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext","isActive":true,"type":"reference"},{"text":", like ","type":"text"},{"code":"SwiftUICore\/Color\/keyboardBackground(for:)","type":"codeVoice"},{"text":". These colors vary the color result based on the context. Prefer these context-based colors whenever possible.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"KeyboardKit defines variable-based icons like ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/Image\/keyboardNewline"},{"text":", which make it easy to use them as toggles and indicators.","type":"text"}],"type":"paragraph"},{"style":"important","name":"Important","content":[{"type":"paragraph","inlineContent":[{"text":"Some keyboard colors are semi-transparent to work around a system bug in iOS, where iOS defines an invalid color scheme when a keyboard is used with a dark appearance text field in light mode. iOS will say that the color scheme is ","type":"text"},{"type":"codeVoice","code":".dark"},{"text":", even if the system color scheme is light. Since dark appearance keyboards in light mode look quite different from keyboards in dark mode, this makes it impossible to apply the correct style. This has been ","type":"text"},{"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKit\/issues\/305","type":"reference","isActive":true},{"text":", but until it’s fixes, thse colors will stay semi-transparent.","type":"text"}]}],"type":"aside"},{"level":2,"anchor":"Type-Extensions","type":"heading","text":"Type Extensions"},{"inlineContent":[{"text":"Many types in the library define standard images, texts & colors. You can for instance get the standard image and text for a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","type":"reference","isActive":true},{"text":" with the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/standardButtonImage(for:)","type":"reference","isActive":true},{"text":" and ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/standardButtonText(for:)","type":"reference","isActive":true},{"text":":","type":"text"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["let context = KeyboardContext()","let image = KeyboardAction.command.standardButtonImage(for: context) \/\/ Command icon","let text = KeyboardAction.space.standardButtonText(for: context)     \/\/ KKL10n.space"]},{"inlineContent":[{"type":"text","text":"These values can be overridden at any time, e.g. with the various view styles, by defining a custom "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyleService"},{"type":"text","text":", etc."}],"type":"paragraph"},{"level":2,"anchor":"Style-Modifiers","type":"heading","text":"Style Modifiers"},{"inlineContent":[{"type":"text","text":"KeyboardKit defines custom styles for its various view. For instance, the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","isActive":true},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Button","isActive":true},{"type":"text","text":" view has a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ButtonStyle","isActive":true},{"type":"text","text":" that can be applied with the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/keyboardButtonStyle(_:)","isActive":true},{"type":"text","text":" view modifier."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Most views have static, standard styles that can be replaced by custom styles to change the global default style for that particular view."}],"type":"paragraph"},{"type":"thematicBreak"},{"level":2,"anchor":"%F0%9F%91%91-KeyboardKit-Pro","type":"heading","text":"👑 KeyboardKit Pro"},{"inlineContent":[{"overridingTitleInlineContent":[{"text":"KeyboardKit Pro","type":"text"}],"type":"reference","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","overridingTitle":"KeyboardKit Pro","isActive":true},{"type":"text","text":" unlocks additional image assets, and a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme","isActive":true},{"type":"text","text":" engine that makes easier to style keyboards with themes."}],"type":"paragraph"},{"level":3,"anchor":"Emoji-Icons","type":"heading","text":"Emoji Icons"},{"columns":[{"content":[{"inlineContent":[{"type":"image","identifier":"images-emojis"}],"type":"paragraph"}],"size":1},{"content":[{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro unlocks vectorized emoji assets for all ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiCategory"},{"text":"s, e.g. ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/Image\/keyboardEmoji"},{"text":" & ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/Image\/emojiCategory(_:)"},{"text":":","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Since these images are vectorized, they scale well when they are resized. They however do not support different font weights, so do not render them alongside SF Symbols that support such features.","type":"text"}]}],"size":1}],"type":"row","numberOfColumns":2},{"level":3,"anchor":"Themes","type":"heading","text":"Themes"},{"inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme"},{"type":"text","text":" engine that makes easier to style keyboards with themes, as well as a bunch of themes:"}],"type":"paragraph"},{"columns":[{"content":[{"inlineContent":[{"type":"image","identifier":"standard-green"}],"type":"paragraph"}],"size":1},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"swifty-blue","type":"image"}]}],"size":1},{"content":[{"inlineContent":[{"type":"image","identifier":"candyshop-cottoncandy"}],"type":"paragraph"}],"size":1}],"type":"row","numberOfColumns":3},{"inlineContent":[{"type":"text","text":"You can apply themes with a style-specific "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyleService"},{"type":"text","text":". Future versions of KeyboardKit will also let you apply themes with a view modifier. See the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"},{"type":"text","text":" article for more information."}],"type":"paragraph"},{"type":"thematicBreak"},{"level":2,"anchor":"How-to","type":"heading","text":"How to…"},{"level":3,"anchor":"create-a-custom-style-service","type":"heading","text":"…create a custom style service"},{"inlineContent":[{"type":"text","text":"You can create a custom style service to customize styles in any way you want. You can implement "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyleService","type":"reference","isActive":true},{"type":"text","text":" from scratch, or inherit and customize "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyle\/StandardStyleService","type":"reference","isActive":true},{"type":"text","text":":"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["class CustomKeyboardStyleService: KeyboardStyle.StandardStyleService {","    ","    override func buttonStyle(","        for action: KeyboardAction,","        isPressed: Bool","    ) -> Keyboard.ButtonStyle {","        let style = super.buttonStyle(for: action, isPressed: isPressed)","        if !action.isInputAction { return style }","        style.backgroundColor = .red","        return style","    }","}"]},{"inlineContent":[{"type":"text","text":"To use your custom service instead of the standard one, just inject it into "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services"},{"type":"text","text":" by replacing its "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Services\/styleService"},{"type":"text","text":" property:"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["class KeyboardViewController: KeyboardInputViewController {","","    override func viewDidLoad() {","        keyboardStyleService = CustomKeyboardStyleService()","        super.viewDidLoad()","    }","}"]},{"inlineContent":[{"text":"This will make KeyboardKit use your custom implementation instead of the standard one.","type":"text"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkitpro\/styling-article"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkitpro\/styling-article"]}],"sections":[],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Themes-Article":{"type":"topic","role":"article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article","url":"\/documentation\/keyboardkitpro\/themes-article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"text":"This article describes the KeyboardKit Pro theme engine.","type":"text"}],"title":"Themes"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardStyle":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardStyle"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyle","title":"KeyboardStyle","type":"topic","kind":"symbol","abstract":[{"text":"This namespace contains style-related types.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardstyle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardStyle"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardStyle/StandardStyleService":{"type":"topic","abstract":[{"type":"text","text":"This class provides a standard way to create dynamic"},{"type":"text","text":" "},{"type":"text","text":"keyboard styles."}],"url":"\/documentation\/keyboardkitpro\/keyboardstyle\/standardstyleservice","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyle\/StandardStyleService","kind":"symbol","title":"KeyboardStyle.StandardStyleService","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StandardStyleService"}],"navigatorTitle":[{"kind":"identifier","text":"StandardStyleService"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUICore/Color":{"type":"topic","navigatorTitle":[{"text":"Color","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/swiftuicore\/color","abstract":[{"text":"This extension extends ","type":"text"},{"type":"codeVoice","code":"Color"},{"text":" with codable capabilities.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/Color","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Color","preciseIdentifier":"s:7SwiftUI5ColorV","kind":"identifier"}],"title":"Color","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/services":{"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/services","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"services","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A0V","text":"Keyboard","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A0V8ServicesC","text":"Services","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Keyboard-specific services."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","role":"symbol","title":"services","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Services/styleService":{"url":"\/documentation\/keyboardkitpro\/keyboard\/services\/styleservice","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"styleService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardStyleService","preciseIdentifier":"s:14KeyboardKitPro0A12StyleServiceP"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Services\/styleService","type":"topic","abstract":[{"text":"The keyboard style service to use.","type":"text"}],"title":"styleService","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUICore/Image/keyboard":{"role":"symbol","type":"topic","title":"keyboard","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/Image\/keyboard","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboard","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI5ImageV","text":"Image","kind":"typeIdentifier"}],"abstract":[],"url":"\/documentation\/keyboardkitpro\/swiftuicore\/image\/keyboard"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUICore/Image/keyboardEmoji":{"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/keyboardkitpro\/swiftuicore\/image\/keyboardemoji","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/Image\/keyboardEmoji","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardEmoji"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI5ImageV","text":"Image"}],"title":"keyboardEmoji"},"standard-green":{"identifier":"standard-green","alt":"Standard Green Theme","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/standard-green.jpg"}],"type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","images":[{"type":"card","identifier":"Page.png"}],"role":"article","url":"\/documentation\/keyboardkitpro\/layout-article","title":"Layout","abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation-Article":{"kind":"article","url":"\/documentation\/keyboardkitpro\/dictation-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"title":"Dictation","type":"topic","images":[{"type":"card","identifier":"Page.png"}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUICore/Image":{"navigatorTitle":[{"text":"Image","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/Image","abstract":[],"kind":"symbol","title":"Image","url":"\/documentation\/keyboardkitpro\/swiftuicore\/image","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","preciseIdentifier":"s:7SwiftUI5ImageV","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"kind":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","title":"Emojis","role":"article","url":"\/documentation\/keyboardkitpro\/emojis-article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Button":{"abstract":[{"text":"This view can be used to create keyboard buttons for","type":"text"},{"text":" ","type":"text"},{"text":"various ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction"},{"text":"s.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Button","navigatorTitle":[{"text":"Button","kind":"identifier"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Button","kind":"identifier"}],"role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboard\/button","kind":"symbol","title":"Keyboard.Button"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardContext"}],"type":"topic","title":"KeyboardContext","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext","url":"\/documentation\/keyboardkitpro\/keyboardcontext","abstract":[{"text":"This class has observable states and persistent settings","type":"text"},{"text":" ","type":"text"},{"text":"for the core keyboard functionality.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardContext"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUICore/View/keyboardButtonStyle(_:)":{"title":"keyboardButtonStyle(_:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/keyboardButtonStyle(_:)","url":"\/documentation\/keyboardkitpro\/swiftuicore\/view\/keyboardbuttonstyle(_:)","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Apply a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ButtonStyle","isActive":true},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardButtonStyle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V","text":"Keyboard"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V11ButtonStyleV","text":"ButtonStyle"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","type":"topic","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"title":"Callouts","role":"article","images":[{"type":"card","identifier":"Page.png"}],"url":"\/documentation\/keyboardkitpro\/callouts-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/standardButtonText(for:)":{"role":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardaction\/standardbuttontext(for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standardButtonText","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"KeyboardContext","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A7ContextC"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"standardButtonText(for:)","abstract":[{"text":"The standard button text for the action.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/standardButtonText(for:)","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"title":"KeyboardKitPro","kind":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","abstract":[{"text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI.","type":"text"}],"url":"\/documentation\/keyboardkitpro","role":"collection"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUICore/Image/emojiCategory(_:)":{"title":"emojiCategory(_:)","kind":"symbol","role":"symbol","url":"\/documentation\/keyboardkitpro\/swiftuicore\/image\/emojicategory(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"emojiCategory"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"EmojiCategory","preciseIdentifier":"s:14KeyboardKitPro13EmojiCategoryO"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"s:7SwiftUI5ImageV"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/Image\/emojiCategory(_:)","abstract":[{"text":"An emoji category icon for the provided category.","type":"text"}]},"https://github.com/KeyboardKit/KeyboardKitPro":{"url":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","title":"KeyboardKit Pro","type":"link","titleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"url":"\/documentation\/keyboardkitpro\/localization-article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","title":"Localization","abstract":[{"text":"This article describes the KeyboardKit localization engine.","type":"text"}],"images":[{"identifier":"Page.png","type":"card"}],"role":"article","kind":"article"},"https://github.com/KeyboardKit/KeyboardKit/issues/305":{"url":"https:\/\/github.com\/KeyboardKit\/KeyboardKit\/issues\/305","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKit\/issues\/305","title":"reported to Apple","type":"link","titleInlineContent":[{"text":"reported to Apple","type":"text"}]},"swifty-blue":{"identifier":"swifty-blue","alt":"Swifty Blue Theme","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/swifty-blue.jpg","traits":["1x","light"]}],"type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardTheme":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme","navigatorTitle":[{"text":"KeyboardTheme","kind":"identifier"}],"abstract":[{"text":"This struct defines a keyboard-specific theme, which can","type":"text"},{"text":" ","type":"text"},{"text":"be used to define a bunch of styles at once.","type":"text"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardtheme","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardTheme","kind":"identifier"}],"kind":"symbol","title":"KeyboardTheme"},"candyshop-cottoncandy":{"identifier":"candyshop-cottoncandy","alt":"Cotton Candy Theme","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/candyshop-cottoncandy.jpg"}],"type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction":{"role":"symbol","abstract":[{"type":"text","text":"This enum defines keyboard-specific actions, and is also"},{"type":"text","text":" "},{"type":"text","text":"a namespace for keyboard action-related types."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardAction","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","navigatorTitle":[{"text":"KeyboardAction","kind":"identifier"}],"title":"KeyboardAction","url":"\/documentation\/keyboardkitpro\/keyboardaction"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUICore/View":{"abstract":[],"title":"View","url":"\/documentation\/keyboardkitpro\/swiftuicore\/view","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"View","kind":"identifier"}],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/App-Article":{"title":"App Utilities","url":"\/documentation\/keyboardkitpro\/app-article","role":"article","abstract":[{"text":"This article describes the KeyboardKit app-specific utilities.","type":"text"}],"kind":"article","images":[{"identifier":"Page.png","type":"card"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards-Article":{"images":[{"type":"card","identifier":"Page.png"}],"url":"\/documentation\/keyboardkitpro\/external-keyboards-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"type":"topic","role":"article","title":"External Keyboards","kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete-Article":{"url":"\/documentation\/keyboardkitpro\/autocomplete-article","abstract":[{"text":"This article describes the KeyboardKit autocomplete engine.","type":"text"}],"images":[{"type":"card","identifier":"Page.png"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","kind":"article","role":"article","type":"topic","title":"Autocomplete"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUICore/Color/keyboardBackground":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardBackground"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Color","preciseIdentifier":"s:7SwiftUI5ColorV"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/keyboardkitpro\/swiftuicore\/color\/keyboardbackground","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/Color\/keyboardBackground","title":"keyboardBackground","abstract":[{"type":"text","text":"The standard keyboard background color."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures-Article":{"type":"topic","kind":"article","abstract":[{"text":"This article describes the KeyboardKit gesture engine.","type":"text"}],"title":"Gestures","role":"article","url":"\/documentation\/keyboardkitpro\/gestures-article","images":[{"type":"card","identifier":"Page.png"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article"},"styling-images":{"identifier":"styling-images","alt":"Image Extensions","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/styling-images.jpg","traits":["1x","light"]}],"type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardView":{"url":"\/documentation\/keyboardkitpro\/keyboardview","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","role":"symbol","title":"KeyboardView","kind":"symbol","abstract":[{"text":"This view can be used to mimic a native iOS keyboard.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardView","kind":"identifier"}],"navigatorTitle":[{"text":"KeyboardView","kind":"identifier"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AI-Article":{"type":"topic","kind":"article","abstract":[{"text":"This article describes the KeyboardKit AI support capabilities.","type":"text"}],"images":[{"type":"card","identifier":"Page.png"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","title":"AI Support","url":"\/documentation\/keyboardkitpro\/ai-article","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","kind":"symbol","role":"symbol","abstract":[{"text":"This namespace contains essential keyboard-related types.","type":"text"}],"navigatorTitle":[{"text":"Keyboard","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Keyboard","kind":"identifier"}],"title":"Keyboard","url":"\/documentation\/keyboardkitpro\/keyboard","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Device-Article":{"kind":"article","url":"\/documentation\/keyboardkitpro\/device-article","title":"Device Utilities","abstract":[{"type":"text","text":"This article describes the KeyboardKit device utilities."}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","images":[{"type":"card","identifier":"Page.png"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUICore/Image/keyboardNewline":{"url":"\/documentation\/keyboardkitpro\/swiftuicore\/image\/keyboardnewline","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardNewline"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI5ImageV","text":"Image"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/Image\/keyboardNewline","abstract":[],"role":"symbol","title":"keyboardNewline"},"Page.png":{"identifier":"Page.png","alt":"Page icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png"}],"type":"image"},"styling-colors":{"identifier":"styling-colors","alt":"Color Extensions","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/styling-colors.jpg","traits":["1x","light"]}],"type":"image"},"images-emojis":{"identifier":"images-emojis","alt":"Asset-based Images","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/images-emojis.jpg"}],"type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"type":"topic","url":"\/documentation\/keyboardkitpro\/actions-article","kind":"article","title":"Actions","role":"article","images":[{"type":"card","identifier":"Page.png"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit action engine."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Host-Article":{"role":"article","kind":"article","url":"\/documentation\/keyboardkitpro\/host-article","type":"topic","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This article describes how KeyboardKit Pro can identify and use the host application."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","title":"Host Application"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback-Article":{"images":[{"type":"card","identifier":"Page.png"}],"role":"article","type":"topic","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/feedback-article","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","title":"Feedback"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Input-Article":{"url":"\/documentation\/keyboardkitpro\/input-article","role":"article","title":"Input","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","kind":"article","images":[{"type":"card","identifier":"Page.png"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit input engine."}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/EmojiCategory":{"url":"\/documentation\/keyboardkitpro\/emojicategory","kind":"symbol","abstract":[{"text":"This enum defines the standard emoji categories, as well","type":"text"},{"text":" ","type":"text"},{"text":"as their emojis.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EmojiCategory","kind":"identifier"}],"navigatorTitle":[{"text":"EmojiCategory","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiCategory","title":"EmojiCategory","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardStyleService":{"type":"topic","abstract":[{"type":"text","text":"This protocol can be implemented by any classes that can"},{"type":"text","text":" "},{"type":"text","text":"provide dynamic keyboard styles."}],"url":"\/documentation\/keyboardkitpro\/keyboardstyleservice","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardStyleService","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"KeyboardStyleService","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyleService","title":"KeyboardStyleService"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/ButtonStyle":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/ButtonStyle","kind":"symbol","title":"Keyboard.ButtonStyle","abstract":[{"type":"text","text":"This style can be used to modify the visual style of"},{"type":"text","text":" "},{"type":"text","text":"the various "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Button","isActive":true,"type":"reference"},{"text":" components.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"ButtonStyle","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ButtonStyle","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboard\/buttonstyle","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction/standardButtonImage(for:)":{"abstract":[{"type":"text","text":"The standard button image for the action."}],"url":"\/documentation\/keyboardkitpro\/keyboardaction\/standardbuttonimage(for:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction\/standardButtonImage(for:)","type":"topic","role":"symbol","kind":"symbol","title":"standardButtonImage(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"standardButtonImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14KeyboardKitPro0A7ContextC","kind":"typeIdentifier","text":"KeyboardContext"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:7SwiftUI5ImageV","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"title":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article"],"anchor":"Articles","generated":true}],"op":"replace"}]}]}