{"seeAlsoSections":[{"title":"Routing","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputComponent","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputView","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextField","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextView"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextInputProxy"}],"title":"TextInputProxy","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@KeyboardKitPro@objc(cs)TextInputProxy","modules":[{"name":"KeyboardKitPro"}],"navigatorTitle":[{"kind":"identifier","text":"TextInputProxy"}]},"abstract":[{"type":"text","text":"This class can be used to route text from an app to another"},{"type":"text","text":" "},{"type":"text","text":"text field, for instance in keyboard extension itself."}],"sections":[],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)NSObject","doc:\/\/com.keyboardkit.KeyboardKitPro\/s7CVarArgP","doc:\/\/com.keyboardkit.KeyboardKitPro\/s28CustomDebugStringConvertibleP","doc:\/\/com.keyboardkit.KeyboardKitPro\/s23CustomStringConvertibleP","doc:\/\/com.keyboardkit.KeyboardKitPro\/SQ","doc:\/\/com.keyboardkit.KeyboardKitPro\/SH","doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UIKeyInput","doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UITextDocumentProxy","doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UITextInputTraits"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/init(input:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/autocapitalizationType","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/autocorrectionType","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/documentContextAfterInput","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/documentContextBeforeInput","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/documentIdentifier","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/documentInputMode","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/enablesReturnKeyAutomatically","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/hasText","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/isSecureTextEntry","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/keyboardAppearance","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/keyboardType","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/returnKeyType","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/selectedText","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/smartDashesType","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/smartInsertDeleteType","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/smartQuotesType","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/spellCheckingType"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/adjustTextPosition(byCharacterOffset:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/deleteBackward()","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/insertText(_:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/setMarkedText(_:selectedRange:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/unmarkText()"]},{"title":"Type Aliases","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/TextInput"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/UITextDocumentProxy-Implementations"],"generated":true}],"variants":[{"paths":["\/documentation\/keyboardkitpro\/textinputproxy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/textinputproxy"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextInputProxy"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This class implements "},{"type":"codeVoice","code":"UITextDocumentProxy"},{"type":"text","text":", which lets you"},{"type":"text","text":" "},{"type":"text","text":"customize proxy-related features. The class also implements"},{"type":"text","text":" "},{"type":"codeVoice","code":"UITextInputTraits"},{"type":"text","text":", which lets you customize input-related"},{"type":"text","text":" "},{"type":"text","text":"features and behaviors like the return button type. Finally,"},{"type":"text","text":" "},{"type":"text","text":"it implements "},{"type":"codeVoice","code":"UIKeyInput"},{"type":"text","text":" to handle text insert and delete."},{"type":"text","text":" "},{"type":"text","text":"You can inherit and override this class to customize things"},{"type":"text","text":" "},{"type":"text","text":"further."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you use the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextField"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextView"},{"type":"text","text":" "},{"type":"text","text":"views in your keyboard, they will automatically replace the"},{"type":"text","text":" "},{"type":"text","text":"standard document proxy with this type as long as they have"},{"type":"text","text":" "},{"type":"text","text":"focus, then switch back when they lose focus. If you are to"},{"type":"text","text":" "},{"type":"text","text":"implement your own custom text fields or proxies, check out"},{"type":"text","text":" "},{"type":"text","text":"these views for inspiration."}]}]}],"references":{"doc://com.keyboardkit.KeyboardKitPro/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/s7CVarArgP"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/adjustTextPosition(byCharacterOffset:)":{"role":"symbol","title":"adjustTextPosition(byCharacterOffset:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adjustTextPosition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byCharacterOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Adjust the text position by a certain offset."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/adjustTextPosition(byCharacterOffset:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adjustTextPositionByCharacterOffset:"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/adjusttextposition(bycharacteroffset:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/init(input:)":{"role":"symbol","title":"init(input:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"input"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TextInput","preciseIdentifier":"s:14KeyboardKitPro14TextInputProxyC0dE0a"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Create a text input proxy instance."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/init(input:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/textinputproxy\/init(input:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/unmarkText()":{"role":"symbol","title":"unmarkText()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unmarkText"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/unmarkText()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unmarkText"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/unmarktext()"},"doc://com.keyboardkit.KeyboardKitPro/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/SH"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/selectedText":{"role":"symbol","title":"selectedText","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/selectedText","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectedText"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/selectedtext"},"doc://com.keyboardkit.KeyboardKitPro/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/s28CustomDebugStringConvertibleP"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputComponent":{"role":"symbol","title":"KeyboardInputComponent","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardInputComponent"}],"abstract":[{"type":"text","text":"This protocol can be used to create text inputs that can be"},{"type":"text","text":" "},{"type":"text","text":"used within a keyboard extension."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputComponent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardInputComponent"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputcomponent"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/keyboardAppearance":{"role":"symbol","title":"keyboardAppearance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardAppearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIKeyboardAppearance","preciseIdentifier":"c:@E@UIKeyboardAppearance"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/keyboardAppearance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"keyboardAppearance"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/keyboardappearance"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/keyboardType":{"role":"symbol","title":"keyboardType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIKeyboardType","preciseIdentifier":"c:@E@UIKeyboardType"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/keyboardType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"keyboardType"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/keyboardtype"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/documentIdentifier":{"role":"symbol","title":"documentIdentifier","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/documentIdentifier","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"documentIdentifier"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/documentidentifier"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/insertText(_:)":{"role":"symbol","title":"insertText(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insertText"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/insertText(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"insertText:"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/inserttext(_:)"},"doc://com.keyboardkit.KeyboardKitPro/objc(pl)UIKeyInput":{"type":"unresolvable","title":"UIKit.UIKeyInput","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UIKeyInput"},"doc://com.keyboardkit.KeyboardKitPro/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/s23CustomStringConvertibleP"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputView":{"role":"symbol","title":"KeyboardInputView","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardInputView"}],"abstract":[{"type":"text","text":"This protocol can be implemented by input views that should"},{"type":"text","text":" "},{"type":"text","text":"be used to insert text within a keyboard extension."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardInputView"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputview"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/spellCheckingType":{"role":"symbol","title":"spellCheckingType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"spellCheckingType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextSpellCheckingType","preciseIdentifier":"c:@E@UITextSpellCheckingType"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/spellCheckingType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"spellCheckingType"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/spellcheckingtype"},"doc://com.keyboardkit.KeyboardKitPro/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)NSObject"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/TextInput":{"role":"symbol","title":"TextInputProxy.TextInput","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextInput"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/TextInput","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TextInput"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/textinput"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy":{"role":"symbol","title":"TextInputProxy","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextInputProxy"}],"abstract":[{"type":"text","text":"This class can be used to route text from an app to another"},{"type":"text","text":" "},{"type":"text","text":"text field, for instance in keyboard extension itself."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TextInputProxy"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","title":"KeyboardKitPro","abstract":[{"type":"text","text":"KeyboardKit Pro helps you build custom keyboard extensions for iOS and iPadOS."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/setMarkedText(_:selectedRange:)":{"role":"symbol","title":"setMarkedText(_:selectedRange:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMarkedText"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"selectedRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@T@NSRange"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/setMarkedText(_:selectedRange:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setMarkedText:selectedRange:"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/setmarkedtext(_:selectedrange:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/smartDashesType":{"role":"symbol","title":"smartDashesType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"smartDashesType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextSmartDashesType","preciseIdentifier":"c:@E@UITextSmartDashesType"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/smartDashesType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"smartDashesType"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/smartdashestype"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/returnKeyType":{"role":"symbol","title":"returnKeyType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnKeyType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIReturnKeyType","preciseIdentifier":"c:@E@UIReturnKeyType"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/returnKeyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"returnKeyType"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/returnkeytype"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/deleteBackward()":{"role":"symbol","title":"deleteBackward()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteBackward"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/deleteBackward()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteBackward"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/deletebackward()"},"doc://com.keyboardkit.KeyboardKitPro/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(cs)NSObject"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardTextView":{"role":"symbol","title":"KeyboardTextView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardTextView"}],"abstract":[{"type":"text","text":"This text view can be used within a keyboard extension."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardTextView"}],"url":"\/documentation\/keyboardkitpro\/keyboardtextview"},"doc://com.keyboardkit.KeyboardKitPro/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/SQ"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/enablesReturnKeyAutomatically":{"role":"symbol","title":"enablesReturnKeyAutomatically","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enablesReturnKeyAutomatically"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/enablesReturnKeyAutomatically","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enablesReturnKeyAutomatically"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/enablesreturnkeyautomatically"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/documentInputMode":{"role":"symbol","title":"documentInputMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentInputMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextInputMode","preciseIdentifier":"c:objc(cs)UITextInputMode"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/documentInputMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"documentInputMode"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/documentinputmode"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/documentContextAfterInput":{"role":"symbol","title":"documentContextAfterInput","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentContextAfterInput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/documentContextAfterInput","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"documentContextAfterInput"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/documentcontextafterinput"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardTextField":{"role":"symbol","title":"KeyboardTextField","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardTextField"}],"abstract":[{"type":"text","text":"This text field can be used within a keyboard extension."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardTextField"}],"url":"\/documentation\/keyboardkitpro\/keyboardtextfield"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/autocorrectionType":{"role":"symbol","title":"autocorrectionType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autocorrectionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextAutocorrectionType","preciseIdentifier":"c:@E@UITextAutocorrectionType"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/autocorrectionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"autocorrectionType"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/autocorrectiontype"},"doc://com.keyboardkit.KeyboardKitPro/objc(pl)UITextInputTraits":{"type":"unresolvable","title":"UIKit.UITextInputTraits","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UITextInputTraits"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/UITextDocumentProxy-Implementations":{"role":"collectionGroup","title":"UITextDocumentProxy Implementations","abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/UITextDocumentProxy-Implementations","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/textinputproxy\/uitextdocumentproxy-implementations"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/hasText":{"role":"symbol","title":"hasText","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/hasText","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hasText"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/hastext"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/smartInsertDeleteType":{"role":"symbol","title":"smartInsertDeleteType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"smartInsertDeleteType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextSmartInsertDeleteType","preciseIdentifier":"c:@E@UITextSmartInsertDeleteType"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/smartInsertDeleteType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"smartInsertDeleteType"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/smartinsertdeletetype"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/isSecureTextEntry":{"role":"symbol","title":"isSecureTextEntry","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSecureTextEntry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/isSecureTextEntry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"secureTextEntry"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/issecuretextentry"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/smartQuotesType":{"role":"symbol","title":"smartQuotesType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"smartQuotesType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextSmartQuotesType","preciseIdentifier":"c:@E@UITextSmartQuotesType"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/smartQuotesType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"smartQuotesType"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/smartquotestype"},"doc://com.keyboardkit.KeyboardKitPro/objc(pl)UITextDocumentProxy":{"type":"unresolvable","title":"UITextDocumentProxy","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UITextDocumentProxy"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/documentContextBeforeInput":{"role":"symbol","title":"documentContextBeforeInput","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentContextBeforeInput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/documentContextBeforeInput","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"documentContextBeforeInput"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/documentcontextbeforeinput"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/autocapitalizationType":{"role":"symbol","title":"autocapitalizationType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autocapitalizationType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextAutocapitalizationType","preciseIdentifier":"c:@E@UITextAutocapitalizationType"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/autocapitalizationType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"autocapitalizationType"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/autocapitalizationtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"TextInputProxy"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TextInputProxy"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TextInputProxy"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/autocapitalizationType","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/autocorrectionType","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/documentContextAfterInput","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/documentContextBeforeInput","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/documentIdentifier","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/documentInputMode","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/enablesReturnKeyAutomatically","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/hasText","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/isSecureTextEntry","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/keyboardAppearance","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/keyboardType","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/returnKeyType","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/selectedText","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/smartDashesType","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/smartInsertDeleteType","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/smartQuotesType","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/spellCheckingType"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/adjustTextPosition(byCharacterOffset:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/deleteBackward()","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/insertText(_:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/setMarkedText(_:selectedRange:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/unmarkText()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UITextDocumentProxy"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"replace","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextInputProxy"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1adjustTextPosition(byCharacterOffset:)\/title","value":"adjustTextPositionByCharacterOffset:"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1adjustTextPosition(byCharacterOffset:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adjustTextPositionByCharacterOffset:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1unmarkText()\/title","value":"unmarkText"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1unmarkText()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unmarkText"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1selectedText\/title","value":"selectedText"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1selectedText\/fragments","value":[{"kind":"identifier","text":"selectedText"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1keyboardAppearance\/title","value":"keyboardAppearance"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1keyboardAppearance\/fragments","value":[{"kind":"identifier","text":"keyboardAppearance"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1keyboardType\/title","value":"keyboardType"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1keyboardType\/fragments","value":[{"kind":"identifier","text":"keyboardType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1documentIdentifier\/title","value":"documentIdentifier"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1documentIdentifier\/fragments","value":[{"kind":"identifier","text":"documentIdentifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1insertText(_:)\/title","value":"insertText:"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1insertText(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"insertText:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1spellCheckingType\/title","value":"spellCheckingType"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1spellCheckingType\/fragments","value":[{"kind":"identifier","text":"spellCheckingType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/title","value":"TextInputProxy"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/fragments","value":[{"kind":"identifier","text":"TextInputProxy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1setMarkedText(_:selectedRange:)\/title","value":"setMarkedText:selectedRange:"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1setMarkedText(_:selectedRange:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMarkedText:selectedRange:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1smartDashesType\/title","value":"smartDashesType"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1smartDashesType\/fragments","value":[{"kind":"identifier","text":"smartDashesType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1returnKeyType\/title","value":"returnKeyType"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1returnKeyType\/fragments","value":[{"kind":"identifier","text":"returnKeyType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1deleteBackward()\/title","value":"deleteBackward"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1deleteBackward()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteBackward"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1enablesReturnKeyAutomatically\/title","value":"enablesReturnKeyAutomatically"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1enablesReturnKeyAutomatically\/fragments","value":[{"kind":"identifier","text":"enablesReturnKeyAutomatically"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1documentInputMode\/title","value":"documentInputMode"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1documentInputMode\/fragments","value":[{"kind":"identifier","text":"documentInputMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1documentContextAfterInput\/title","value":"documentContextAfterInput"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1documentContextAfterInput\/fragments","value":[{"kind":"identifier","text":"documentContextAfterInput"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1autocorrectionType\/title","value":"autocorrectionType"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1autocorrectionType\/fragments","value":[{"kind":"identifier","text":"autocorrectionType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1hasText\/title","value":"hasText"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1hasText\/fragments","value":[{"kind":"identifier","text":"hasText"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1smartInsertDeleteType\/title","value":"smartInsertDeleteType"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1smartInsertDeleteType\/fragments","value":[{"kind":"identifier","text":"smartInsertDeleteType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1isSecureTextEntry\/title","value":"secureTextEntry"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1isSecureTextEntry\/fragments","value":[{"kind":"identifier","text":"secureTextEntry"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1smartQuotesType\/title","value":"smartQuotesType"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1smartQuotesType\/fragments","value":[{"kind":"identifier","text":"smartQuotesType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1documentContextBeforeInput\/title","value":"documentContextBeforeInput"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1documentContextBeforeInput\/fragments","value":[{"kind":"identifier","text":"documentContextBeforeInput"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1autocapitalizationType\/title","value":"autocapitalizationType"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1autocapitalizationType\/fragments","value":[{"kind":"identifier","text":"autocapitalizationType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}