{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Input-Article"},"variants":[{"paths":["\/documentation\/keyboardkitpro\/text-input-article"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkitpro\/text-input-article"]}],"sections":[],"abstract":[{"text":"This article describes the KeyboardKit text input engine.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"kind":"article","seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"title":"Articles","anchor":"Articles"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"content","content":[{"type":"heading","anchor":"overview","level":2,"text":"Overview"},{"inlineContent":[{"type":"text","text":"iOS keyboard extensions use a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/UIKit\/UITextDocumentProxy"},{"text":" to insert and delete text, move the text input cursor, etc. This proxy will by default point to the currently selected text field in the currently active app.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Standard keyboard extensions will by default only send text to this proxy, and will "},{"type":"emphasis","inlineContent":[{"type":"text","text":"not"}]},{"type":"text","text":" detect if you select a text field inside the keyboard. Even if you focus on a text field within the keyboard, text will still be sent to the text document proxy."}]},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit adds ways to make typing within the text field a lot easier. This makes implementing AI prompt-based features a breeze.","type":"text"}]},{"level":2,"type":"heading","anchor":"Text-Input","text":"Text Input"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit adds ways to make text routing easier. For instance, ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext","isActive":true},{"type":"text","text":" has a custom "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/textInputProxy"},{"type":"text","text":" that can be set to route text to any other text field or custom proxy."}]},{"type":"paragraph","inlineContent":[{"text":"Just set ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/textInputProxy"},{"text":" to start typing to that proxy, and set it to nil to resume typing into the active application. The controller’s ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textDocumentProxy"},{"type":"text","text":" will point to this property if set. You can access the original proxy with "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/originalTextDocumentProxy","type":"reference","isActive":true},{"type":"text","text":"."}]},{"anchor":"%F0%9F%91%91-KeyboardKit-Pro","type":"heading","level":2,"text":"👑 KeyboardKit Pro"},{"type":"paragraph","inlineContent":[{"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","isActive":true,"type":"reference"},{"type":"text","text":" unlocks a "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextField","type":"reference"},{"type":"text","text":" and a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextView","isActive":true,"type":"reference"},{"type":"text","text":" that both automatically register and unregister as input proxy when they get and lose focus."}]},{"text":"Views","type":"heading","anchor":"Views","level":3},{"tabs":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextField"},{"type":"text","text":" component wraps a native text field and can be used for single-line text input inside a keyboard extension."}]}],"title":"KeyboardTextField"},{"title":"KeyboardTextView","content":[{"inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextView"},{"type":"text","text":" component wraps a native text view and can be used for multi-line text input inside a keyboard extension."}],"type":"paragraph"}]}],"type":"tabNavigator"},{"type":"paragraph","inlineContent":[{"text":"Both views support ","type":"text"},{"type":"codeVoice","code":"@FocusState"},{"type":"text","text":", and have a custom "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/focused(_:doneButton:)","type":"reference","isActive":true},{"text":" view modifier that lets you provide a custom done button that slides in when the view is focused, and can be tapped to end editing:","type":"text"}]},{"code":["struct CustomKeyboardToolbar: View {","","    unowned var controller: KeyboardInputViewController","","    @State ","    private var text = \"\"","","    @FocusState ","    private var isTextFieldFocused","","    var body: some View {","        if hasFullAccess {","            KeyboardTextField(","                \"Type here...\", ","                text: $text, ","                controller: controller,","                config: configureTextField,","                onSubmit: handleReturnKeyPressed","            )","            .focused($isTextFieldFocused) {","                Image(systemName: \"xmark.circle.fill\")","            }","        }","    }","    ","    func configureTextField(_ view: UITextField) {","        \/\/ Configure the underlying view in any way you want.","    }","    ","    func handleReturnKeyPressed() {","        print(\"Return key pressed!\")","    }","}"],"syntax":"swift","type":"codeListing"},{"name":"Tip","style":"tip","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The default "},{"type":"codeVoice","code":".onSubmit { ... }"},{"type":"text","text":" view modifier doesn’t work for these text views. If you want to detect when the return key is pressed, you can instead pass in "},{"type":"codeVoice","code":"onSubmit:"},{"type":"text","text":" in the initializer."}]}]},{"name":"Important","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"These views require at least a ","type":"text"},{"code":"Silver","type":"codeVoice"},{"type":"text","text":" license. They also require Full Access, due to an iOS bug that causes a crash when using them while Full Access is disabled. They will automatically disable themselves when Full Access is disabled."}]}],"style":"important"}]}],"metadata":{"images":[{"identifier":"Page.png","type":"card"}],"modules":[{"name":"KeyboardKitPro"}],"roleHeading":"Article","title":"Text Input","role":"article"},"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Styling-Article":{"images":[{"type":"card","identifier":"Page.png"}],"title":"Styling","role":"article","type":"topic","kind":"article","abstract":[{"text":"This article describes the KeyboardKit styling engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","url":"\/documentation\/keyboardkitpro\/styling-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Device-Article":{"title":"Device Utilities","url":"\/documentation\/keyboardkitpro\/device-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit device utilities."}],"kind":"article","type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures-Article":{"abstract":[{"text":"This article describes the KeyboardKit gesture engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","images":[{"type":"card","identifier":"Page.png"}],"title":"Gestures","type":"topic","kind":"article","role":"article","url":"\/documentation\/keyboardkitpro\/gestures-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy-Article":{"abstract":[{"text":"This article describes the KeyboardKit proxy engine and its utilities.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","images":[{"type":"card","identifier":"Page.png"}],"title":"Proxy Utilities","type":"topic","kind":"article","role":"article","url":"\/documentation\/keyboardkitpro\/proxy-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Settings-Article":{"abstract":[{"text":"This article describes the KeyboardKit settings engine and its available settings.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","images":[{"type":"card","identifier":"Page.png"}],"title":"Settings","type":"topic","kind":"article","role":"article","url":"\/documentation\/keyboardkitpro\/settings-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/textInputProxy":{"abstract":[{"type":"text","text":"A custom text proxy to which text can be routed."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/textInputProxy","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"textInputProxy"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(pl)UITextDocumentProxy","text":"UITextDocumentProxy","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","title":"textInputProxy","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardcontext\/textinputproxy"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Navigation-Article":{"title":"Navigation","url":"\/documentation\/keyboardkitpro\/navigation-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","abstract":[{"text":"This article describes the KeyboardKit navigation engine.","type":"text"}],"kind":"article","type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/App-Article":{"title":"App Utilities","url":"\/documentation\/keyboardkitpro\/app-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}],"kind":"article","type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/textDocumentProxy":{"kind":"symbol","title":"textDocumentProxy","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textDocumentProxy"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textDocumentProxy","role":"symbol","abstract":[{"type":"text","text":"The text document proxy that is currently active."}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/textdocumentproxy","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textDocumentProxy"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(pl)UITextDocumentProxy","text":"UITextDocumentProxy","kind":"typeIdentifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis-Article":{"title":"Emojis","url":"\/documentation\/keyboardkitpro\/emojis-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"kind":"article","type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Host-Article":{"title":"Host Application","url":"\/documentation\/keyboardkitpro\/host-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","abstract":[{"type":"text","text":"This article describes how KeyboardKit Pro can identify and use the host application."}],"kind":"article","type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit action engine."}],"kind":"article","url":"\/documentation\/keyboardkitpro\/actions-article","title":"Actions","role":"article","type":"topic","images":[{"type":"card","identifier":"Page.png"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardContext"}],"abstract":[{"type":"text","text":"This class has observable states and persistent settings"},{"type":"text","text":" "},{"text":"for the core keyboard functionality.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardContext"}],"url":"\/documentation\/keyboardkitpro\/keyboardcontext","title":"KeyboardContext"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete-Article":{"abstract":[{"text":"This article describes the KeyboardKit autocomplete engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","images":[{"type":"card","identifier":"Page.png"}],"title":"Autocomplete","type":"topic","kind":"article","role":"article","url":"\/documentation\/keyboardkitpro\/autocomplete-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardTextView":{"kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardtextview","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"KeyboardTextView","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextView","title":"KeyboardTextView","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardTextView"}],"abstract":[{"text":"This view can be used to type within keyboard extensions.","type":"text"}]},"https://github.com/KeyboardKit/KeyboardKitPro":{"type":"link","titleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"url":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","title":"KeyboardKit Pro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"url":"\/documentation\/keyboardkitpro","abstract":[{"text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","kind":"symbol","title":"KeyboardKitPro","role":"collection"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Previews-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit preview engine."}],"url":"\/documentation\/keyboardkitpro\/previews-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","kind":"article","type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}],"title":"Previews"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","images":[{"type":"card","identifier":"Page.png"}],"title":"Layout","type":"topic","kind":"article","role":"article","url":"\/documentation\/keyboardkitpro\/layout-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/originalTextDocumentProxy":{"role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/originaltextdocumentproxy","type":"topic","title":"originalTextDocumentProxy","abstract":[{"text":"The original text document proxy.","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"originalTextDocumentProxy"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UITextDocumentProxy","text":"UITextDocumentProxy","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/originalTextDocumentProxy"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardTextField":{"url":"\/documentation\/keyboardkitpro\/keyboardtextfield","kind":"symbol","abstract":[{"type":"text","text":"This view can be used to type within keyboard extensions."}],"role":"symbol","title":"KeyboardTextField","navigatorTitle":[{"kind":"identifier","text":"KeyboardTextField"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"KeyboardTextField"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextField"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUICore/View/focused(_:doneButton:)":{"url":"\/documentation\/keyboardkitpro\/swiftuicore\/view\/focused(_:donebutton:)","kind":"symbol","abstract":[{"text":"Apply a ","type":"text"},{"type":"codeVoice","code":"FocusState"},{"text":" with a ","type":"text"},{"type":"codeVoice","code":"doneButton"},{"type":"text","text":" that slides"},{"type":"text","text":" "},{"text":"in and out as the view gets and loses focus.","type":"text"}],"role":"symbol","title":"focused(_:doneButton:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"focused","kind":"identifier"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"DoneButton"},{"kind":"text","text":">("},{"preciseIdentifier":"s:7SwiftUI10FocusStateV","text":"FocusState","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":">."},{"kind":"typeIdentifier","text":"Binding","preciseIdentifier":"s:7SwiftUI10FocusStateV7BindingV"},{"kind":"text","text":", "},{"text":"doneButton","kind":"externalParam"},{"kind":"text","text":": () -> "},{"text":"DoneButton","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP14KeyboardKitProE7focused_10doneButtonQrAA10FocusStateV7BindingVySb_G_qd__yctAaBRd__lFQO04DoneI0qd__mfp"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUICore\/View\/focused(_:doneButton:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards-Article":{"abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","images":[{"type":"card","identifier":"Page.png"}],"title":"External Keyboards","type":"topic","kind":"article","role":"article","url":"\/documentation\/keyboardkitpro\/external-keyboards-article"},"Page.png":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png","traits":["1x","light"]}],"alt":"Page icon","type":"image","identifier":"Page.png"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"abstract":[{"text":"This article describes the KeyboardKit localization engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","images":[{"identifier":"Page.png","type":"card"}],"title":"Localization","type":"topic","kind":"article","role":"article","url":"\/documentation\/keyboardkitpro\/localization-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback-Article":{"role":"article","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"kind":"article","title":"Feedback","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","url":"\/documentation\/keyboardkitpro\/feedback-article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Themes-Article":{"abstract":[{"text":"This article describes the KeyboardKit Pro theme engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article","images":[{"type":"card","identifier":"Page.png"}],"title":"Themes","type":"topic","kind":"article","role":"article","url":"\/documentation\/keyboardkitpro\/themes-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AI-Article":{"images":[{"identifier":"Page.png","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","title":"AI Support","abstract":[{"text":"This article describes the KeyboardKit AI support capabilities.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/ai-article","role":"article","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/UIKit/UITextDocumentProxy":{"title":"UITextDocumentProxy","url":"\/documentation\/keyboardkitpro\/uikit\/uitextdocumentproxy","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/UIKit\/UITextDocumentProxy","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","preciseIdentifier":"c:objc(pl)UITextDocumentProxy","text":"UITextDocumentProxy"}],"navigatorTitle":[{"text":"UITextDocumentProxy","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"title":"Callouts","url":"\/documentation\/keyboardkitpro\/callouts-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"kind":"article","type":"topic","role":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Status-Article":{"title":"Status","url":"\/documentation\/keyboardkitpro\/status-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit status engine."}],"kind":"article","type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation-Article":{"title":"Dictation","url":"\/documentation\/keyboardkitpro\/dictation-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"kind":"article","type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Articles","generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Status-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"anchor":"Articles"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1textDocumentProxy\/title","value":"textDocumentProxy"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1textDocumentProxy\/fragments","value":[{"kind":"identifier","text":"textDocumentProxy"}]}]}]}