{"metadata":{"modules":[{"name":"KeyboardKitPro"}],"title":"Themes","role":"article","images":[{"identifier":"Page.png","type":"card"}],"roleHeading":"Article"},"primaryContentSections":[{"content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has a style engine that makes it easy to customize the style of your keyboard. However, the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyleService","isActive":true},{"type":"text","text":" is a bit tricky to use if you need to easily apply many different styles."}]},{"type":"paragraph","inlineContent":[{"text":"👑 ","type":"text"},{"type":"reference","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","isActive":true},{"text":" therefore unlocks a theme engine that can be used to easily style your keyboard with different styles, and provides you with many predefined themes, templates, and theme-based views. You can easily create custom themes as well.","type":"text"}]},{"level":2,"type":"heading","text":"Namespace","anchor":"Namespace"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme","isActive":true},{"type":"text","text":" type that is also a namespace for theme-related types and views, like "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme\/Shelf","isActive":true},{"type":"text","text":" and "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme\/ShelfItem","isActive":true},{"type":"text","text":"."}]},{"level":2,"type":"heading","text":"Context","anchor":"Context"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has an observable "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardThemeContext","type":"reference"},{"type":"text","text":" class that can be used to handle themes and auto-persisted "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardThemeContext\/settings-swift.property","type":"reference"},{"type":"text","text":". It also has auto-persisted "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardThemeContext\/settings-swift.property","type":"reference"},{"type":"text","text":" that can be used to persist themes."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit automatically creates an instance of this class, injects it into "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state","isActive":true},{"type":"text","text":" and updates it whenever the theme changes."}]},{"level":2,"type":"heading","text":"Services","anchor":"Services"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In KeyboardKit, a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyleService\/themeBased(keyboardContext:themeContext:)"},{"type":"text","text":" style service can be used to apply a keyboard theme:"}]},{"syntax":"swift","type":"codeListing","code":["override func viewDidLoad() {","    super.viewDidLoad()","    setup(for: .myApp) { result in","        \/\/ Check result to see that setup was successful","        self.services.styleService = .themeBased(","            keyboardContext: state.keyboardContext,","            themeContext: state.themeContext","        )","    } ","}"]},{"type":"paragraph","inlineContent":[{"text":"You can inherit ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyle\/ThemeBasedStyleService","type":"reference"},{"text":" to customize themes even further, which lets you mix the benefits of themes and styles.","type":"text"}]},{"anchor":"Settings","type":"heading","text":"Settings","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardThemeSettings"},{"type":"text","text":" type with theme-related state & settings. The context "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardThemeContext\/settings-swift.property"},{"type":"text","text":" is used by default."}]},{"anchor":"Themes","type":"heading","text":"Themes","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme","isActive":true},{"type":"text","text":" can provide keyboard-related styles in a way that can be easily used and modified. A theme can also define style variations that can be used to customize a constrained set of theme properties."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks a bunch of themes and style variations, as well as a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyle\/ThemeBasedStyleService"},{"type":"text","text":" that lets you apply themes with the style service concept that is still used by the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks many standard themes, like "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme\/standard","isActive":true},{"type":"text","text":", "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme\/swifty","isActive":true},{"type":"text","text":" and "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme\/minimal","isActive":true},{"type":"text","text":". These themes also have style variations, that lets you vary their appearance, like the standard theme’s "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme\/StandardStyle\/blue","isActive":true},{"type":"text","text":" and "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme\/StandardStyle\/green","isActive":true},{"type":"text","text":" variations:"}]},{"type":"tabNavigator","tabs":[{"title":".standard","content":[{"numberOfColumns":3,"columns":[{"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"standard"}]}],"size":1},{"content":[{"inlineContent":[{"type":"image","identifier":"standard-blue"}],"type":"paragraph"}],"size":1},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"standard-green","type":"image"}]}],"size":1}],"type":"row"}]},{"title":".swifty","content":[{"type":"row","numberOfColumns":3,"columns":[{"size":1,"content":[{"inlineContent":[{"identifier":"swifty","type":"image"}],"type":"paragraph"}]},{"size":1,"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"swifty-blue"}]}]},{"size":1,"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"swifty-green"}]}]}]}]},{"title":".minimal","content":[{"columns":[{"size":1,"content":[{"type":"paragraph","inlineContent":[{"identifier":"minimal","type":"image"}]}]},{"size":1,"content":[{"type":"paragraph","inlineContent":[{"identifier":"minimal-blue","type":"image"}]}]},{"size":1,"content":[{"inlineContent":[{"type":"image","identifier":"minimal-sunset"}],"type":"paragraph"}]}],"type":"row","numberOfColumns":3}]}]},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro also unlocks other more expressive themes, which provide their own unique visual baseline:","type":"text"}]},{"type":"tabNavigator","tabs":[{"content":[{"columns":[{"size":1,"content":[{"inlineContent":[{"identifier":"aesthetic-boho","type":"image"}],"type":"paragraph"}]},{"size":1,"content":[]},{"size":1,"content":[]}],"numberOfColumns":3,"type":"row"}],"title":".aesthetic"},{"content":[{"type":"row","columns":[{"size":1,"content":[{"inlineContent":[{"identifier":"candyshop","type":"image"}],"type":"paragraph"}]},{"size":1,"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"candyshop-cuppycake"}]}]},{"size":1,"content":[]}],"numberOfColumns":3}],"title":".candyShop"},{"content":[{"numberOfColumns":3,"columns":[{"size":1,"content":[{"inlineContent":[{"type":"image","identifier":"colorful-blue"}],"type":"paragraph"}]},{"size":1,"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"colorful-green"}]}]},{"size":1,"content":[{"inlineContent":[{"identifier":"colorful-orange","type":"image"}],"type":"paragraph"}]}],"type":"row"}],"title":".colorful"},{"content":[{"numberOfColumns":3,"columns":[{"size":1,"content":[{"inlineContent":[{"identifier":"neon","type":"image"}],"type":"paragraph"}]},{"size":1,"content":[]},{"size":1,"content":[]}],"type":"row"}],"title":".neon"},{"content":[{"columns":[{"content":[{"inlineContent":[{"identifier":"tron","type":"image"}],"type":"paragraph"}],"size":1},{"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"tron-fcon"}]}],"size":1},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"tron-virus","type":"image"}]}],"size":1}],"type":"row","numberOfColumns":3}],"title":".tron"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can get a list of all predefined themes, as well as all pre-defined style variations, using the static "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme\/predefined","type":"reference","isActive":true},{"type":"text","text":" properties. You can create your own themes, as well as custom style variations for all predefined themes."}]},{"type":"heading","anchor":"Views","text":"Views","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks views in the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme","isActive":true},{"type":"text","text":" namespace, that make it easy to preview and present keyboard themes:"}]},{"type":"tabNavigator","tabs":[{"title":"Shelf","content":[{"type":"row","numberOfColumns":2,"columns":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"themeshelf","type":"image"}]}],"size":1},{"content":[{"inlineContent":[{"text":"A keyboard theme ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme\/Shelf"},{"text":" can be used to list themes in a vertical list of horizontally scrolling shelves.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"You can use the standard "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme\/ShelfItem","type":"reference","isActive":true},{"type":"text","text":" to show how a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Button","type":"reference","isActive":true},{"type":"text","text":" will look, or use completely custom views for the titles and items."}],"type":"paragraph"}],"size":1}]}]}]},{"type":"thematicBreak"},{"type":"heading","anchor":"How-to","text":"How to…","level":2},{"type":"heading","anchor":"create-a-custom-theme","text":"…create a custom theme","level":3},{"type":"paragraph","inlineContent":[{"text":"Since a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme","type":"reference"},{"text":" is just a struct, you can easily create your own custom themes by just defining new static theme value types.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For instance, this theme only changes the color of the primary button:"}]},{"type":"codeListing","syntax":"swift","code":["extension KeyboardTheme {","","    static var greenPrimary: Self {","        get throws {","            try? Self(primaryBackgroundColor: .green)","        }","    }","}"]},{"type":"paragraph","inlineContent":[{"text":"You can also use other themes as a base when creating your own custom themes, if you only want to change a small part of a theme.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"For instance, this theme starts with the minimal theme and changes the color of the primary button to pink:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["extension KeyboardTheme {","","    static var pinkPrimary: Self {","        get throws {","            var theme = try? KeyboardTheme.minimal","            theme.buttonStyles[.primary]?.backgroundColor = .green","            return theme","        }","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can also create custom themes that just tweak a style variation of another theme."}]},{"type":"paragraph","inlineContent":[{"text":"For instance, this custom theme is a standard theme that applies a black tint color style variation:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["extension KeyboardTheme {","","    static var standardBlack: Self {","        .standard(.init(tint: .black))","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"All these combinations make the theme engine very flexible and powerful."}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article","interfaceLanguage":"swift"},"sections":[],"kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit Pro theme engine."}],"seeAlsoSections":[{"title":"Articles","generated":true,"anchor":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article"]}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"variants":[{"paths":["\/documentation\/keyboardkitpro\/themes-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/themes-article"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"title":"Layout","abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}],"type":"topic","kind":"article","images":[{"type":"card","identifier":"Page.png"}],"url":"\/documentation\/keyboardkitpro\/layout-article","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"type":"topic","url":"\/documentation\/keyboardkitpro\/localization-article","abstract":[{"text":"This article describes the KeyboardKit localization engine.","type":"text"}],"title":"Localization","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"candyshop":{"identifier":"candyshop","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/candyshop.jpg","traits":["1x","light"]}],"alt":"standard","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardStyleService/themeBased(keyboardContext:themeContext:)":{"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyleService\/themeBased(keyboardContext:themeContext:)","role":"symbol","abstract":[{"text":"Create a dynamic ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyle\/ThemeBasedStyleService","type":"reference"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"themeBased"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keyboardContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardContext","preciseIdentifier":"s:14KeyboardKitPro0A7ContextC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"themeContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardThemeContext","preciseIdentifier":"s:14KeyboardKitPro0A12ThemeContextC"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"Self"}],"conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" is ","type":"text"},{"code":"KeyboardStyle.ThemeBasedStyleService","type":"codeVoice"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"title":"themeBased(keyboardContext:themeContext:)","url":"\/documentation\/keyboardkitpro\/keyboardstyleservice\/themebased(keyboardcontext:themecontext:)","type":"topic"},"neon":{"identifier":"neon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/neon.jpg","traits":["1x","light"]}],"alt":"standard","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardTheme/swifty":{"title":"swifty","abstract":[{"type":"text","text":"The standard "},{"type":"codeVoice","code":"Swifty"},{"type":"text","text":" theme."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"swifty","kind":"identifier"},{"text":": ","kind":"text"},{"text":"KeyboardTheme","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A5ThemeV"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme\/swifty","role":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardtheme\/swifty","kind":"symbol"},"colorful-blue":{"identifier":"colorful-blue","alt":"blue","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/colorful-blue.jpg"}],"type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardTheme/StandardStyle/blue":{"kind":"symbol","title":"blue","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardtheme\/standardstyle\/blue","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme\/StandardStyle\/blue","abstract":[{"text":"A blue standard style.","type":"text"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"blue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A5ThemeV","text":"KeyboardTheme","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A5ThemeV13StandardStyleV","text":"StandardStyle","kind":"typeIdentifier"}]},"standard-blue":{"identifier":"standard-blue","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/standard-blue.jpg","traits":["1x","light"]}],"alt":"blue","type":"image"},"themeshelf":{"identifier":"themeshelf","alt":"ThemeShelf","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/themeshelf.jpg"}],"type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/App-Article":{"role":"article","title":"App Utilities","kind":"article","images":[{"type":"card","identifier":"Page.png"}],"url":"\/documentation\/keyboardkitpro\/app-article","type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Device-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","images":[{"type":"card","identifier":"Page.png"}],"url":"\/documentation\/keyboardkitpro\/device-article","type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit device utilities."}],"kind":"article","title":"Device Utilities","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures-Article":{"url":"\/documentation\/keyboardkitpro\/gestures-article","type":"topic","role":"article","kind":"article","images":[{"type":"card","identifier":"Page.png"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit gesture engine."}],"title":"Gestures"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"kind":"article","type":"topic","title":"Actions","url":"\/documentation\/keyboardkitpro\/actions-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"role":"article","images":[{"type":"card","identifier":"Page.png"}]},"minimal-sunset":{"identifier":"minimal-sunset","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/minimal-sunset.jpg","traits":["1x","light"]}],"alt":"subset","type":"image"},"tron-virus":{"identifier":"tron-virus","alt":"virus","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/tron-virus.jpg"}],"type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardTheme/StandardStyle/green":{"type":"topic","role":"symbol","abstract":[{"text":"A green standard style.","type":"text"}],"title":"green","url":"\/documentation\/keyboardkitpro\/keyboardtheme\/standardstyle\/green","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"green"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A5ThemeV","text":"KeyboardTheme"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A5ThemeV13StandardStyleV","text":"StandardStyle"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme\/StandardStyle\/green"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardThemeContext/settings-swift.property":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardThemeContext\/settings-swift.property","role":"symbol","title":"settings","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardthemecontext\/settings-swift.property","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"settings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardThemeSettings","preciseIdentifier":"s:14KeyboardKitPro0A13ThemeSettingsV"}],"abstract":[{"text":"Theme-specific, auto-persisted settings.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardTheme/Shelf":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Shelf"}],"abstract":[{"text":"This view can be used to list theme collections in a","type":"text"},{"text":" ","type":"text"},{"text":"vertical list, with horizontally scrolling shelves.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardtheme\/shelf","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme\/Shelf","role":"symbol","type":"topic","title":"KeyboardTheme.Shelf","navigatorTitle":[{"kind":"identifier","text":"Shelf"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardThemeSettings":{"kind":"symbol","title":"KeyboardThemeSettings","role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardthemesettings","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardThemeSettings","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardThemeSettings","abstract":[{"text":"This type is used for theme-related settings.","type":"text"}],"navigatorTitle":[{"text":"KeyboardThemeSettings","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"images":[{"type":"card","identifier":"Page.png"}],"url":"\/documentation\/keyboardkitpro\/dictation-article","kind":"article","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","title":"Dictation","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"url":"\/documentation\/keyboardkitpro\/emojis-article","title":"Emojis","kind":"article","type":"topic","role":"article","images":[{"type":"card","identifier":"Page.png"}]},"tron-fcon":{"type":"image","alt":"fcon","identifier":"tron-fcon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/tron-fcon.jpg","traits":["1x","light"]}]},"https://github.com/KeyboardKit/KeyboardKitPro":{"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","titleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"title":"KeyboardKit Pro","url":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","type":"link"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AI-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","url":"\/documentation\/keyboardkitpro\/ai-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit AI support capabilities."}],"type":"topic","title":"AI Support","images":[{"type":"card","identifier":"Page.png"}],"role":"article","kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Input-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit input engine."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","role":"article","url":"\/documentation\/keyboardkitpro\/input-article","title":"Input","images":[{"type":"card","identifier":"Page.png"}],"kind":"article"},"candyshop-cuppycake":{"type":"image","alt":"cuppycake","identifier":"candyshop-cuppycake","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/candyshop-cuppycake.jpg","traits":["1x","light"]}]},"standard-green":{"identifier":"standard-green","alt":"green","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/standard-green.jpg","traits":["1x","light"]}],"type":"image"},"Page.png":{"type":"image","alt":"Page icon","identifier":"Page.png","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png","traits":["1x","light"]}]},"standard":{"identifier":"standard","alt":"standard","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/standard.jpg","traits":["1x","light"]}],"type":"image"},"swifty":{"type":"image","alt":"standard","identifier":"swifty","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/swifty.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardThemeContext":{"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardthemecontext","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardThemeContext","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardThemeContext"}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardThemeContext"}],"title":"KeyboardThemeContext","abstract":[{"type":"text","text":"This class has observable states and persistent settings"},{"type":"text","text":" "},{"type":"text","text":"for keyboard-specific themes."}]},"colorful-green":{"type":"image","alt":"green","identifier":"colorful-green","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/colorful-green.jpg"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards-Article":{"images":[{"type":"card","identifier":"Page.png"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit external keyboard engine."}],"role":"article","type":"topic","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","url":"\/documentation\/keyboardkitpro\/external-keyboards-article","title":"External Keyboards"},"aesthetic-boho":{"identifier":"aesthetic-boho","alt":"boho","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/aesthetic-boho.jpg"}],"type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback-Article":{"url":"\/documentation\/keyboardkitpro\/feedback-article","images":[{"identifier":"Page.png","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"kind":"article","type":"topic","title":"Feedback","role":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"title":"Callouts","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"url":"\/documentation\/keyboardkitpro\/callouts-article","role":"article","kind":"article","images":[{"identifier":"Page.png","type":"card"}],"type":"topic"},"swifty-green":{"type":"image","alt":"green","identifier":"swifty-green","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/swifty-green.jpg"}]},"minimal":{"identifier":"minimal","alt":"standard","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/minimal.jpg"}],"type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardTheme/minimal":{"kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardtheme\/minimal","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme\/minimal","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimal","kind":"identifier"},{"text":": ","kind":"text"},{"text":"KeyboardTheme","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A5ThemeV"}],"abstract":[{"text":"The standard ","type":"text"},{"code":"Minimal","type":"codeVoice"},{"text":" theme.","type":"text"}],"title":"minimal","role":"symbol","type":"topic"},"swifty-blue":{"type":"image","alt":"blue","identifier":"swifty-blue","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/swifty-blue.jpg"}]},"minimal-blue":{"identifier":"minimal-blue","alt":"blue","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/minimal-blue.jpg"}],"type":"image"},"tron":{"type":"image","alt":"blue","identifier":"tron","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/tron.jpg"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/state":{"abstract":[{"type":"text","text":"Keyboard-specific state."}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/state","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state","kind":"symbol","role":"symbol","type":"topic","title":"state","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A0V","text":"Keyboard","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A0V5StateC","text":"State","kind":"typeIdentifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardTheme/ShelfItem":{"title":"KeyboardTheme.ShelfItem","kind":"symbol","abstract":[{"type":"text","text":"This view can be used as a default shelf item within"},{"type":"text","text":" "},{"type":"text","text":"a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme\/Shelf"},{"type":"text","text":"."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ShelfItem"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme\/ShelfItem","url":"\/documentation\/keyboardkitpro\/keyboardtheme\/shelfitem","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShelfItem"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardStyle/ThemeBasedStyleService":{"abstract":[{"text":"This class inherits applies theme-based overrides to","type":"text"},{"text":" ","type":"text"},{"text":"standard styles.","type":"text"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardstyle\/themebasedstyleservice","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ThemeBasedStyleService","kind":"identifier"}],"kind":"symbol","title":"KeyboardStyle.ThemeBasedStyleService","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyle\/ThemeBasedStyleService","navigatorTitle":[{"text":"ThemeBasedStyleService","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction":{"title":"KeyboardAction","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardaction","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardAction","kind":"identifier"}],"navigatorTitle":[{"text":"KeyboardAction","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","abstract":[{"type":"text","text":"This enum defines keyboard-specific actions, and is also"},{"type":"text","text":" "},{"text":"a namespace for keyboard action-related types.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardTheme":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardTheme"}],"role":"symbol","abstract":[{"type":"text","text":"This struct defines a keyboard-specific theme, which can"},{"type":"text","text":" "},{"type":"text","text":"be used to define a bunch of styles at once."}],"title":"KeyboardTheme","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardTheme"}],"url":"\/documentation\/keyboardkitpro\/keyboardtheme","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}],"url":"\/documentation\/keyboardkitpro\/autocomplete-article","role":"article","title":"Autocomplete","type":"topic","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardView":{"abstract":[{"text":"This view can be used to mimic a native iOS keyboard.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardView","kind":"identifier"}],"navigatorTitle":[{"text":"KeyboardView","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardView","title":"KeyboardView","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardview","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardTheme/predefined":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"predefined"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A5ThemeV","text":"KeyboardTheme"},{"kind":"text","text":"]"}],"role":"symbol","title":"predefined","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme\/predefined","abstract":[{"type":"text","text":"Get all predefined themes."}],"type":"topic","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardtheme\/predefined"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Host-Article":{"type":"topic","images":[{"type":"card","identifier":"Page.png"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","role":"article","title":"Host Application","abstract":[{"type":"text","text":"This article describes how KeyboardKit Pro can identify and use the host application."}],"url":"\/documentation\/keyboardkitpro\/host-article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardStyleService":{"abstract":[{"type":"text","text":"This protocol can be implemented by any classes that can"},{"type":"text","text":" "},{"type":"text","text":"provide dynamic keyboard styles."}],"url":"\/documentation\/keyboardkitpro\/keyboardstyleservice","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStyleService","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardStyleService","kind":"identifier"}],"navigatorTitle":[{"text":"KeyboardStyleService","kind":"identifier"}],"title":"KeyboardStyleService","role":"symbol","type":"topic","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"kind":"symbol","url":"\/documentation\/keyboardkitpro","role":"collection","title":"KeyboardKitPro","abstract":[{"text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"},"colorful-orange":{"type":"image","alt":"standard","identifier":"colorful-orange","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKitPro\/colorful-orange.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardTheme/standard":{"url":"\/documentation\/keyboardkitpro\/keyboardtheme\/standard","title":"standard","type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standard","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A5ThemeV","text":"KeyboardTheme","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme\/standard","abstract":[{"text":"The standard ","type":"text"},{"code":"Standard","type":"codeVoice"},{"text":" theme.","type":"text"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Button":{"kind":"symbol","title":"Keyboard.Button","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Button"}],"navigatorTitle":[{"kind":"identifier","text":"Button"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Button","type":"topic","abstract":[{"text":"This view can be used to create keyboard buttons for","type":"text"},{"text":" ","type":"text"},{"text":"various ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction"},{"text":"s.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboard\/button","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/App-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article"],"title":"Articles","anchor":"Articles"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}