{"sections":[],"abstract":[{"text":"The bundle ID of the host application, if any, or if","type":"text"},{"text":" ","type":"text"},{"text":"within a host app, the bundle id of the main bundle.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hostApplicationBundleId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"The property uses technologies that may stop working"},{"type":"text","text":" "},{"type":"text","text":"in any future iOS version. Do not rely solely on the"},{"type":"text","text":" "},{"type":"text","text":"function, and design the app to be able to work even"},{"type":"text","text":" "},{"type":"text","text":"if this feature suddenly stops working."}],"type":"paragraph"}]}],"metadata":{"role":"symbol","extendedModule":"KeyboardKitPro","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hostApplicationBundleId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"externalID":"s:14KeyboardKitPro0A19InputViewControllerC23hostApplicationBundleIdSSSgvp","title":"hostApplicationBundleId","roleHeading":"Instance Property","modules":[{"name":"KeyboardKitPro"}]},"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/hostApplicationBundleId","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/hostapplicationbundleid"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/hostApplicationBundleId":{"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/hostapplicationbundleid","title":"hostApplicationBundleId","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hostApplicationBundleId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/hostApplicationBundleId","role":"symbol","abstract":[{"type":"text","text":"The bundle ID of the host application, if any, or if"},{"type":"text","text":" "},{"type":"text","text":"within a host app, the bundle id of the main bundle."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller","abstract":[{"text":"This is the input controller to use in KeyboardKit-based","type":"text"},{"text":" ","type":"text"},{"text":"keyboard extensions.","type":"text"}],"role":"symbol","title":"KeyboardInputViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardInputViewController"}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardInputViewController"}],"type":"topic","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"title":"KeyboardKitPro","url":"\/documentation\/keyboardkitpro","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","type":"topic","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"KeyboardInputViewController","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"KeyboardInputViewController"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments"},{"op":"replace","value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/navigatorTitle"}]}]}