{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mainTextDocumentProxy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextDocumentProxy","preciseIdentifier":"c:objc(pl)UITextDocumentProxy"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This stays the same even if a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textInputProxy"},{"type":"text","text":" is set,"},{"type":"text","text":" "},{"type":"text","text":"which makes "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textDocumentProxy"},{"type":"text","text":" return the custom one"},{"type":"text","text":" "},{"type":"text","text":"instead of the original one."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/maintextdocumentproxy"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/mainTextDocumentProxy","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The original text document proxy that was used to start"},{"type":"text","text":" "},{"type":"text","text":"the keyboard extension."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mainTextDocumentProxy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextDocumentProxy","preciseIdentifier":"c:objc(pl)UITextDocumentProxy"}],"title":"mainTextDocumentProxy","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:14KeyboardKitPro0A19InputViewControllerC21mainTextDocumentProxySo06UITextiJ0_pvp","modules":[{"name":"KeyboardKitPro"}]},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController"]]},"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"role":"symbol","title":"KeyboardInputViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardInputViewController"}],"abstract":[{"type":"text","text":"This class extends "},{"type":"codeVoice","code":"UIInputViewController"},{"type":"text","text":" with KeyboardKit"},{"type":"text","text":" "},{"type":"text","text":"specific functionality."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardInputViewController"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","title":"KeyboardKitPro","abstract":[{"type":"text","text":"KeyboardKit Pro helps you build custom keyboard extensions for iOS and iPadOS."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/textInputProxy":{"role":"symbol","title":"textInputProxy","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textInputProxy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TextInputProxy","preciseIdentifier":"c:@M@KeyboardKitPro@objc(cs)TextInputProxy"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A custom text input proxy to which text can be routed."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textInputProxy","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/textinputproxy"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/mainTextDocumentProxy":{"role":"symbol","title":"mainTextDocumentProxy","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mainTextDocumentProxy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextDocumentProxy","preciseIdentifier":"c:objc(pl)UITextDocumentProxy"}],"abstract":[{"type":"text","text":"The original text document proxy that was used to start"},{"type":"text","text":" "},{"type":"text","text":"the keyboard extension."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/mainTextDocumentProxy","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/maintextdocumentproxy"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/textDocumentProxy":{"role":"symbol","title":"textDocumentProxy","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textDocumentProxy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextDocumentProxy","preciseIdentifier":"c:objc(pl)UITextDocumentProxy"}],"abstract":[{"type":"text","text":"The text document proxy to use, which can either be the"},{"type":"text","text":" "},{"type":"text","text":"original text input proxy or the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textInputProxy"},{"type":"text","text":", if"},{"type":"text","text":" "},{"type":"text","text":"it is set to a custom value."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textDocumentProxy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textDocumentProxy"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/textdocumentproxy"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title","value":"KeyboardInputViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments","value":[{"kind":"identifier","text":"KeyboardInputViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1textDocumentProxy\/title","value":"textDocumentProxy"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1textDocumentProxy\/fragments","value":[{"kind":"identifier","text":"textDocumentProxy"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}