{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectionDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"textInput","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UITextInput","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UITextInput"},{"text":"?)","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectionDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UITextInput","text":"UITextInput"},{"kind":"text","text":"?)"}],"title":"selectionDidChange(_:)","roleHeading":"Instance Method","navigatorTitle":[{"text":"selectionDidChange:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"KeyboardKitPro"}],"externalID":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController(im)selectionDidChange:","role":"symbol"},"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/selectionDidChange(_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/selectiondidchange(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/selectiondidchange(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController"]]},"kind":"symbol","references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/selectionDidChange(_:)":{"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/selectionDidChange(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectionDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextInput","preciseIdentifier":"c:objc(pl)UITextInput"},{"kind":"text","text":"?)"}],"abstract":[],"title":"selectionDidChange(_:)","navigatorTitle":[{"kind":"identifier","text":"selectionDidChange:"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/selectiondidchange(_:)","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"title":"KeyboardKitPro","url":"\/documentation\/keyboardkitpro","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","type":"topic","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"role":"collection","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller","abstract":[{"text":"This is the input controller to use in KeyboardKit-based","type":"text"},{"text":" ","type":"text"},{"text":"keyboard extensions.","type":"text"}],"role":"symbol","title":"KeyboardInputViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardInputViewController"}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardInputViewController"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"selectionDidChange:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"selectionDidChange:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"selectionDidChange:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<UITextInput>","preciseIdentifier":"c:Qoobjc(pl)UITextInput","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"textInput","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1selectionDidChange(_:)\/title","value":"selectionDidChange:","op":"replace"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1selectionDidChange(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"selectionDidChange:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title","value":"KeyboardInputViewController","op":"replace"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments","value":[{"kind":"identifier","text":"KeyboardInputViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/navigatorTitle","value":[{"kind":"identifier","text":"KeyboardInputViewController"}],"op":"replace"}]}]}