{"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController"]]},"abstract":[{"type":"text","text":"Set up KeyboardKit Pro for the provided app."}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"app"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","text":"KeyboardApp","preciseIdentifier":"s:14KeyboardKitPro0A3AppV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/License","text":"License","preciseIdentifier":"s:14KeyboardKitPro7LicenseV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":" = { _ in })"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"app","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The keyboard app to setup the controller for."}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"The function to call when the setup operation completes.","type":"text"}]}]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Call this in "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewDidLoad()","isActive":true},{"type":"text","text":" to make sure that the"},{"type":"text","text":" "},{"type":"text","text":"keyboard is properly configured as early as possible."}],"type":"paragraph"},{"inlineContent":[{"text":"The completion block will either provide a validated","type":"text"},{"text":" ","type":"text"},{"text":"license or an error. This is where you can customize","type":"text"},{"text":" ","type":"text"},{"text":"your keyboard, if the license was properly validated.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"See "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started-Article","isActive":true},{"type":"text","text":" for information on"},{"type":"text","text":" "},{"type":"text","text":"how to properly set up an app and keyboard extension."}],"type":"paragraph"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"KeyboardKitPro"}],"role":"symbol","title":"setup(for:completion:)","symbolKind":"method","externalID":"s:14KeyboardKitPro0A19InputViewControllerC5setup3for10completionyAA0A3AppV_ys6ResultOyAA7LicenseVs5Error_pGctF","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14KeyboardKitPro0A3AppV","kind":"typeIdentifier","text":"KeyboardApp"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier","text":"Result"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:14KeyboardKitPro7LicenseV","kind":"typeIdentifier","text":"License"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"extendedModule":"KeyboardKitPro"},"kind":"symbol","variants":[{"paths":["\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/setup(for:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setup(for:completion:)","interfaceLanguage":"swift"},"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/License":{"url":"\/documentation\/keyboardkitpro\/license","abstract":[{"text":"This struct represents a software license and also works","type":"text"},{"text":" ","type":"text"},{"text":"as a namespace for license-related types.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/License","type":"topic","navigatorTitle":[{"text":"License","kind":"identifier"}],"kind":"symbol","title":"License","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"License","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/setup(for:completion:)":{"abstract":[{"type":"text","text":"Set up KeyboardKit Pro for the provided app."}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/setup(for:completion:)","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setup(for:completion:)","title":"setup(for:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardApp","preciseIdentifier":"s:14KeyboardKitPro0A3AppV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"License","preciseIdentifier":"s:14KeyboardKitPro7LicenseV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"title":"KeyboardKitPro","kind":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","abstract":[{"text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI.","type":"text"}],"url":"\/documentation\/keyboardkitpro","role":"collection"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp":{"title":"KeyboardApp","navigatorTitle":[{"text":"KeyboardApp","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","kind":"symbol","role":"symbol","abstract":[{"text":"This type can be used to define important properties for","type":"text"},{"text":" ","type":"text"},{"text":"your app, and is also a namespace for app-based features.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardApp","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardapp"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/viewDidLoad()":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/viewdidload()","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewDidLoad()","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"KeyboardInputViewController","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardInputViewController","kind":"identifier"}],"title":"KeyboardInputViewController","role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller","abstract":[{"text":"This is the main input controller in a KeyboardKit-based","type":"text"},{"text":" ","type":"text"},{"text":"keyboard extension.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Getting-Started-Article":{"type":"topic","role":"article","images":[{"identifier":"Page.png","type":"card"}],"abstract":[{"type":"text","text":"This guide describes how to get started with KeyboardKit."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Getting-Started-Article","url":"\/documentation\/keyboardkitpro\/getting-started-article","title":"Getting Started","kind":"article"},"Page.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKitPro\/Page.png"}],"identifier":"Page.png","type":"image","alt":"Page icon"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1viewDidLoad()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title","value":"KeyboardInputViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments","value":[{"text":"KeyboardInputViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/navigatorTitle","value":[{"text":"KeyboardInputViewController","kind":"identifier"}]}]}]}