{"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController"]]},"abstract":[{"text":"Set up KeyboardKit for a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","isActive":true},{"type":"text","text":"."}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"method","modules":[{"name":"KeyboardKitPro"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setup"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14KeyboardKitPro0A3AppV","kind":"typeIdentifier","text":"KeyboardApp"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","title":"setup(for:)","externalID":"s:14KeyboardKitPro0A19InputViewControllerC5setup3foryAA0A3AppV_tF"},"variants":[{"paths":["\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/setup(for:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setup","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"kind":"text","text":" "},{"text":"app","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"KeyboardApp","kind":"typeIdentifier","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","preciseIdentifier":"s:14KeyboardKitPro0A3AppV"},{"text":")","kind":"text"}]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"This will set up ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Settings","isActive":true},{"text":" to use an App","type":"text"},{"text":" ","type":"text"},{"text":"Group-synced store, if the app is configured with an","type":"text"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/appGroupId","isActive":true},{"text":". It will also set up your","type":"text"},{"type":"text","text":" "},{"text":"controller’s main ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state","type":"reference"},{"type":"text","text":" for the app."}]},{"inlineContent":[{"type":"text","text":"Call this in "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewDidLoad()","isActive":true},{"type":"text","text":" to make sure that the"},{"type":"text","text":" "},{"text":"keyboard is properly configured as early as possible.","type":"text"}],"type":"paragraph"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setup(for:)","interfaceLanguage":"swift"},"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/Settings":{"title":"Keyboard.Settings","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Settings","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/Settings","abstract":[{"type":"text","text":"This class can be used to setup a custom value store"},{"type":"text","text":" "},{"type":"text","text":"for all settings types in the library."}],"url":"\/documentation\/keyboardkitpro\/keyboard\/settings","navigatorTitle":[{"kind":"identifier","text":"Settings"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp":{"type":"topic","abstract":[{"text":"This type can be used to define important properties for","type":"text"},{"type":"text","text":" "},{"text":"your app, and is also a namespace for app-based features.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"KeyboardApp"}],"navigatorTitle":[{"text":"KeyboardApp","kind":"identifier"}],"kind":"symbol","title":"KeyboardApp","url":"\/documentation\/keyboardkitpro\/keyboardapp","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/setup(for:)":{"abstract":[{"type":"text","text":"Set up KeyboardKit for a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp","isActive":true,"type":"reference"},{"type":"text","text":"."}],"type":"topic","title":"setup(for:)","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/setup(for:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A3AppV","text":"KeyboardApp"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setup(for:)","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardApp/appGroupId":{"abstract":[{"text":"The app’s App Group identifier, if any.","type":"text"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appGroupId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"type":"topic","title":"appGroupId","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardApp\/appGroupId","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardapp\/appgroupid"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","abstract":[{"type":"text","text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI."}],"title":"KeyboardKitPro","type":"topic","url":"\/documentation\/keyboardkitpro","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/viewDidLoad()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewDidLoad()","title":"viewDidLoad()","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/viewdidload()","role":"symbol","type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/state":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Keyboard","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V5StateC","text":"State"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state","title":"state","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/state","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Keyboard-specific state."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"role":"symbol","type":"topic","abstract":[{"text":"This is the main input controller in a KeyboardKit-based","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"keyboard extension."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"KeyboardInputViewController"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","title":"KeyboardInputViewController","navigatorTitle":[{"kind":"identifier","text":"KeyboardInputViewController"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1viewDidLoad()\/fragments"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title","op":"replace","value":"KeyboardInputViewController"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments","value":[{"kind":"identifier","text":"KeyboardInputViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/navigatorTitle","value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"op":"replace"}]}]}