{"kind":"symbol","metadata":{"modules":[{"name":"KeyboardKitPro"}],"role":"symbol","externalID":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController(py)textDocumentProxy","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textDocumentProxy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextDocumentProxy","preciseIdentifier":"c:objc(pl)UITextDocumentProxy"}],"navigatorTitle":[{"kind":"identifier","text":"textDocumentProxy"}],"title":"textDocumentProxy","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController"]]},"sections":[],"variants":[{"paths":["\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/textdocumentproxy"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/textdocumentproxy"]}],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textDocumentProxy","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"textDocumentProxy","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UITextDocumentProxy","preciseIdentifier":"c:objc(pl)UITextDocumentProxy","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"The text document proxy that is currently active."}],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/textDocumentProxy":{"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/textdocumentproxy","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textDocumentProxy","abstract":[{"type":"text","text":"The text document proxy that is currently active."}],"title":"textDocumentProxy","navigatorTitle":[{"kind":"identifier","text":"textDocumentProxy"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textDocumentProxy"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(pl)UITextDocumentProxy","kind":"typeIdentifier","text":"UITextDocumentProxy"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"kind":"symbol","role":"symbol","abstract":[{"text":"This is the main input controller in a KeyboardKit-based","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"keyboard extension."}],"title":"KeyboardInputViewController","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"KeyboardInputViewController","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller","navigatorTitle":[{"kind":"identifier","text":"KeyboardInputViewController"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"title":"KeyboardKitPro","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","url":"\/documentation\/keyboardkitpro","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"textDocumentProxy"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"textDocumentProxy"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qoobjc(pl)UITextDocumentProxy","text":"id<UITextDocumentProxy>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textDocumentProxy"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"value":"textDocumentProxy","op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1textDocumentProxy\/title"},{"op":"replace","value":[{"kind":"identifier","text":"textDocumentProxy"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1textDocumentProxy\/fragments"},{"op":"replace","value":"KeyboardInputViewController","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title"},{"value":[{"kind":"identifier","text":"KeyboardInputViewController"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"KeyboardInputViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}