{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textWillChange"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"textInput"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UITextInput","kind":"typeIdentifier","text":"UITextInput"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController"]]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/textwillchange(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/textwillchange(_:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"textWillChange(_:)","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textWillChange"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UITextInput","text":"UITextInput"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"textWillChange:"}],"modules":[{"name":"KeyboardKitPro"}],"role":"symbol","externalID":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController(im)textWillChange:"},"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textWillChange(_:)","interfaceLanguage":"swift"},"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/textWillChange(_:)":{"title":"textWillChange(_:)","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textWillChange(_:)","type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/textwillchange(_:)","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"textWillChange","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(pl)UITextInput","text":"UITextInput","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"textWillChange:"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"navigatorTitle":[{"text":"KeyboardInputViewController","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"KeyboardInputViewController","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller","role":"symbol","kind":"symbol","type":"topic","title":"KeyboardInputViewController","abstract":[{"type":"text","text":"This is the main input controller in a KeyboardKit-based"},{"text":" ","type":"text"},{"type":"text","text":"keyboard extension."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","kind":"symbol","url":"\/documentation\/keyboardkitpro","title":"KeyboardKitPro","role":"collection","type":"topic","abstract":[{"type":"text","text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"textWillChange:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"textWillChange:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"textWillChange:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)UITextInput","text":"id<UITextInput>"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"textInput"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"textWillChange:","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1textWillChange(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"textWillChange:"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1textWillChange(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title","value":"KeyboardInputViewController","op":"replace"},{"value":[{"kind":"identifier","text":"KeyboardInputViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/navigatorTitle","value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}