{"metadata":{"modules":[{"name":"KeyboardKitPro"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"traitCollectionDidChange"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITraitCollection","text":"UITraitCollection","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"externalID":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController(im)traitCollectionDidChange:","symbolKind":"method","roleHeading":"Instance Method","title":"traitCollectionDidChange(_:)","navigatorTitle":[{"text":"traitCollectionDidChange:","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/traitcollectiondidchange(_:)"]},{"paths":["\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/traitcollectiondidchange(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/traitCollectionDidChange(_:)"},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"traitCollectionDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"previousTraitCollection","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UITraitCollection","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"navigatorTitle":[{"text":"KeyboardInputViewController","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"KeyboardInputViewController","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller","role":"symbol","kind":"symbol","type":"topic","title":"KeyboardInputViewController","abstract":[{"type":"text","text":"This is the main input controller in a KeyboardKit-based"},{"text":" ","type":"text"},{"type":"text","text":"keyboard extension."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","kind":"symbol","url":"\/documentation\/keyboardkitpro","title":"KeyboardKitPro","role":"collection","type":"topic","abstract":[{"type":"text","text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/traitCollectionDidChange(_:)":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/traitCollectionDidChange(_:)","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/traitcollectiondidchange(_:)","navigatorTitle":[{"text":"traitCollectionDidChange:","kind":"identifier"}],"title":"traitCollectionDidChange(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"traitCollectionDidChange"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITraitCollection","text":"UITraitCollection"},{"text":"?)","kind":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"traitCollectionDidChange:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"traitCollectionDidChange:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"traitCollectionDidChange:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITraitCollection","text":"UITraitCollection","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"previousTraitCollection"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title","value":"KeyboardInputViewController"},{"value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/navigatorTitle","value":[{"kind":"identifier","text":"KeyboardInputViewController"}]},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1traitCollectionDidChange(_:)\/title","value":"traitCollectionDidChange:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1traitCollectionDidChange(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"traitCollectionDidChange:","kind":"identifier"}]}]}]}