{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/viewsetup"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/ViewSetup"},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Type Alias","role":"symbol","title":"KeyboardInputViewController.ViewSetup","symbolKind":"typealias","navigatorTitle":[{"kind":"identifier","text":"ViewSetup"}],"platforms":[{"message":"This is no longer used.","deprecated":true,"unavailable":false,"beta":false}],"extendedModule":"KeyboardKitPro","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewSetup"}],"externalID":"s:14KeyboardKitPro0A19InputViewControllerC0E5Setupa","modules":[{"name":"KeyboardKitPro"}]},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewSetup","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":"> = (","kind":"text"},{"text":"KeyboardInputViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController"},{"text":") -> ","kind":"text"},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A19InputViewControllerC0E5Setupa1Txmfp"},{"text":" ","kind":"text"},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"This is no longer used.","type":"text"}]}],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"role":"symbol","type":"topic","kind":"symbol","title":"KeyboardInputViewController","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller","abstract":[{"text":"This is the main input controller in a KeyboardKit-based","type":"text"},{"text":" ","type":"text"},{"text":"keyboard extension.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardInputViewController","kind":"identifier"}],"navigatorTitle":[{"text":"KeyboardInputViewController","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"kind":"symbol","url":"\/documentation\/keyboardkitpro","role":"collection","title":"KeyboardKitPro","abstract":[{"text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/ViewSetup":{"title":"KeyboardInputViewController.ViewSetup","abstract":[],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/ViewSetup","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewSetup"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ViewSetup"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/viewsetup","deprecated":true,"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"KeyboardInputViewController","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title"},{"op":"replace","value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments"},{"op":"replace","value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}