{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"withEnvironment","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromController"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"KeyboardInputViewController","preciseIdentifier":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"},{"kind":"text","text":"\n"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"extendedModule":"SwiftUICore","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"withEnvironment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromController","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController","text":"KeyboardInputViewController"},{"kind":"text","text":") -> "},{"text":"some","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"role":"symbol","roleHeading":"Instance Method","title":"withEnvironment(fromController:)","modules":[{"relatedModules":["SwiftUICore"],"name":"KeyboardKitPro"}],"platforms":[],"externalID":"s:7SwiftUI4ViewP14KeyboardKitProE15withEnvironment14fromControllerQrAD0d5InputcJ0C_tF::SYNTHESIZED::s:14KeyboardKitPro9DictationV13BarVisualizerV"},"variants":[{"paths":["\/documentation\/keyboardkitpro\/dictation\/barvisualizer\/withenvironment(fromcontroller:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"View.withEnvironment(fromController:)"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/BarVisualizer","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/BarVisualizer\/View-Implementations"]]},"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/BarVisualizer\/withEnvironment(fromController:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation/BarVisualizer/View-Implementations":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/BarVisualizer\/View-Implementations","abstract":[],"title":"View Implementations","role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/keyboardkitpro\/dictation\/barvisualizer\/view-implementations"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation/BarVisualizer/withEnvironment(fromController:)":{"url":"\/documentation\/keyboardkitpro\/dictation\/barvisualizer\/withenvironment(fromcontroller:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withEnvironment"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController","text":"KeyboardInputViewController","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier","text":"View"}],"kind":"symbol","title":"withEnvironment(fromController:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/BarVisualizer\/withEnvironment(fromController:)","role":"symbol","type":"topic","deprecated":true},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","url":"\/documentation\/keyboardkitpro","abstract":[{"type":"text","text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI."}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","title":"KeyboardKitPro","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"type":"topic","title":"KeyboardInputViewController","kind":"symbol","role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"KeyboardInputViewController","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","navigatorTitle":[{"kind":"identifier","text":"KeyboardInputViewController"}],"abstract":[{"text":"This is the main input controller in a KeyboardKit-based","type":"text"},{"type":"text","text":" "},{"text":"keyboard extension.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation/BarVisualizer":{"abstract":[{"type":"text","text":"This visualizer visualizes dictation progress with a"},{"text":" ","type":"text"},{"type":"text","text":"horizontal list of animating bars."}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BarVisualizer"}],"navigatorTitle":[{"kind":"identifier","text":"BarVisualizer"}],"title":"Dictation.BarVisualizer","type":"topic","url":"\/documentation\/keyboardkitpro\/dictation\/barvisualizer","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation\/BarVisualizer"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Dictation","kind":"identifier"}],"abstract":[{"text":"This namespace contains dictation-related types.","type":"text"}],"navigatorTitle":[{"text":"Dictation","kind":"identifier"}],"title":"Dictation","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro\/dictation"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title","value":"KeyboardInputViewController"},{"value":[{"kind":"identifier","text":"KeyboardInputViewController"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments","op":"replace"},{"value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/navigatorTitle"}]}]}