{"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/adjustTextPosition(byCharacterOffset:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"method","modules":[{"name":"KeyboardKitPro"}],"externalID":"c:@M@KeyboardKitPro@objc(cs)TextInputProxy(im)adjustTextPositionByCharacterOffset:","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"adjustTextPositionByCharacterOffset:"}],"title":"adjustTextPosition(byCharacterOffset:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"adjustTextPosition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"byCharacterOffset","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}]},"abstract":[{"type":"text","text":"Adjust the text position by a certain offset."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adjustTextPosition","kind":"identifier"},{"kind":"text","text":"("},{"text":"byCharacterOffset","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"offset","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"https:\/\/stackoverflow.com\/a\/41023439\/495611 suggests","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"adjusting the text position (i.e. moving the cursor)"},{"text":" ","type":"text"},{"type":"text","text":"by adjusting the selected text range."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkitpro\/textinputproxy\/adjusttextposition(bycharacteroffset:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkitpro\/textinputproxy\/adjusttextposition(bycharacteroffset:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy"]]},"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy","abstract":[{"type":"text","text":"This class can be used to route typed text from the main"},{"text":" ","type":"text"},{"text":"app to text fields within the keyboard extension.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextInputProxy"}],"title":"TextInputProxy","navigatorTitle":[{"kind":"identifier","text":"TextInputProxy"}],"type":"topic","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","url":"\/documentation\/keyboardkitpro","type":"topic","title":"KeyboardKitPro","abstract":[{"type":"text","text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI."}],"role":"collection","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/adjustTextPosition(byCharacterOffset:)":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/adjustTextPosition(byCharacterOffset:)","title":"adjustTextPosition(byCharacterOffset:)","url":"\/documentation\/keyboardkitpro\/textinputproxy\/adjusttextposition(bycharacteroffset:)","abstract":[{"text":"Adjust the text position by a certain offset.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adjustTextPosition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"byCharacterOffset","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"adjustTextPositionByCharacterOffset:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"adjustTextPositionByCharacterOffset:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"adjustTextPositionByCharacterOffset:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"adjustTextPositionByCharacterOffset:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"offset"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/title","value":"TextInputProxy"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/fragments","value":[{"kind":"identifier","text":"TextInputProxy"}]},{"value":"adjustTextPositionByCharacterOffset:","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1adjustTextPosition(byCharacterOffset:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1adjustTextPosition(byCharacterOffset:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adjustTextPositionByCharacterOffset:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}