{"sections":[],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@KeyboardKitPro@objc(cs)TextInputProxy(py)autocapitalizationType","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autocapitalizationType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UITextAutocapitalizationType","text":"UITextAutocapitalizationType","kind":"typeIdentifier"}],"role":"symbol","title":"autocapitalizationType","modules":[{"name":"KeyboardKitPro"}],"navigatorTitle":[{"text":"autocapitalizationType","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/autocapitalizationType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"UITextInputTraits.autocapitalizationType","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autocapitalizationType","kind":"identifier"},{"kind":"text","text":": "},{"text":"UITextAutocapitalizationType","preciseIdentifier":"c:@E@UITextAutocapitalizationType","kind":"typeIdentifier"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy"]]},"variants":[{"paths":["\/documentation\/keyboardkitpro\/textinputproxy\/autocapitalizationtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/textinputproxy\/autocapitalizationtype"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy","abstract":[{"type":"text","text":"This class can be used to route typed text from the main"},{"text":" ","type":"text"},{"text":"app to text fields within the keyboard extension.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextInputProxy"}],"title":"TextInputProxy","navigatorTitle":[{"kind":"identifier","text":"TextInputProxy"}],"type":"topic","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/autocapitalizationType":{"abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"text":"autocapitalizationType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"autocapitalizationType","kind":"identifier"},{"kind":"text","text":": "},{"text":"UITextAutocapitalizationType","kind":"typeIdentifier","preciseIdentifier":"c:@E@UITextAutocapitalizationType"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/autocapitalizationtype","title":"autocapitalizationType","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/autocapitalizationType"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","url":"\/documentation\/keyboardkitpro","type":"topic","title":"KeyboardKitPro","abstract":[{"type":"text","text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI."}],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"autocapitalizationType"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"autocapitalizationType","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"UITextAutocapitalizationType","preciseIdentifier":"c:@E@UITextAutocapitalizationType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"autocapitalizationType","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"TextInputProxy","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/title"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/fragments","value":[{"text":"TextInputProxy","kind":"identifier"}],"op":"replace"},{"value":"autocapitalizationType","op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1autocapitalizationType\/title"},{"value":[{"text":"autocapitalizationType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1autocapitalizationType\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}