{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/keyboardkitpro\/textinputproxy\/documentidentifier"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/textinputproxy\/documentidentifier"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/documentIdentifier","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UITextDocumentProxy.documentIdentifier"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"}],"title":"documentIdentifier","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@KeyboardKitPro@objc(cs)TextInputProxy(py)documentIdentifier","modules":[{"name":"KeyboardKitPro"}],"navigatorTitle":[{"kind":"identifier","text":"documentIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy"]]},"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/documentIdentifier":{"role":"symbol","title":"documentIdentifier","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/documentIdentifier","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"documentIdentifier"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/documentidentifier"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy":{"role":"symbol","title":"TextInputProxy","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextInputProxy"}],"abstract":[{"type":"text","text":"This class can be used to route text from an app to another"},{"type":"text","text":" "},{"type":"text","text":"text field, for instance in keyboard extension itself."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TextInputProxy"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","title":"KeyboardKitPro","abstract":[{"type":"text","text":"KeyboardKit Pro helps you build custom keyboard extensions for iOS and iPadOS."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"documentIdentifier"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"documentIdentifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSUUID","preciseIdentifier":"c:objc(cs)NSUUID"},{"kind":"text","text":" * "},{"kind":"identifier","text":"documentIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1documentIdentifier\/title","value":"documentIdentifier"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1documentIdentifier\/fragments","value":[{"kind":"identifier","text":"documentIdentifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/title","value":"TextInputProxy"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/fragments","value":[{"kind":"identifier","text":"TextInputProxy"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}