{"kind":"symbol","abstract":[{"type":"text","text":"End the current sentence by removing trailing spaces,"},{"type":"text","text":" "},{"type":"text","text":"then injecting a dot and a space."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endSentence","kind":"identifier"},{"kind":"text","text":"("},{"text":"withText","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"text","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" = \". \")"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The text to end the sentence with, by default "},{"code":". ","type":"codeVoice"},{"text":".","type":"text"}]}],"name":"text"}],"kind":"parameters"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"endSentence","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withText"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"endSentence(withText:)","role":"symbol","symbolKind":"method","externalID":"s:So19UITextDocumentProxyP14KeyboardKitProE11endSentence8withTextySS_tF::SYNTHESIZED::c:@M@KeyboardKitPro@objc(cs)TextInputProxy","modules":[{"name":"KeyboardKitPro","relatedModules":["UIKit"]}],"extendedModule":"UIKit","roleHeading":"Instance Method"},"variants":[{"paths":["\/documentation\/keyboardkitpro\/textinputproxy\/endsentence(withtext:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/UITextDocumentProxy-Implementations"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/endSentence(withText:)"},"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/UITextDocumentProxy-Implementations":{"title":"UITextDocumentProxy Implementations","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/UITextDocumentProxy-Implementations","url":"\/documentation\/keyboardkitpro\/textinputproxy\/uitextdocumentproxy-implementations","abstract":[],"kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy":{"title":"TextInputProxy","navigatorTitle":[{"text":"TextInputProxy","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TextInputProxy","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/keyboardkitpro\/textinputproxy","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy","kind":"symbol","type":"topic","abstract":[]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/endSentence(withText:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endSentence","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withText","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"type":"topic","title":"endSentence(withText:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/endSentence(withText:)","abstract":[{"type":"text","text":"End the current sentence by removing trailing spaces,"},{"text":" ","type":"text"},{"type":"text","text":"then injecting a dot and a space."}],"role":"symbol","kind":"symbol","url":"\/documentation\/keyboardkitpro\/textinputproxy\/endsentence(withtext:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","url":"\/documentation\/keyboardkitpro","abstract":[{"type":"text","text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI."}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","title":"KeyboardKitPro","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/title","value":"TextInputProxy"},{"value":[{"text":"TextInputProxy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TextInputProxy"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}