{"metadata":{"role":"symbol","title":"fullDocumentContextAfterInput(config:)","symbolKind":"method","externalID":"s:So19UITextDocumentProxyP14KeyboardKitProE04fullB17ContextAfterInput6configSSAC0C0V04FullB13ConfigurationV_tYaKF::SYNTHESIZED::c:@M@KeyboardKitPro@objc(cs)TextInputProxy","roleHeading":"Instance Method","modules":[{"relatedModules":["UIKit"],"name":"KeyboardKitPro"}],"extendedModule":"UIKit","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"fullDocumentContextAfterInput","kind":"identifier"},{"kind":"text","text":"("},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Proxy","preciseIdentifier":"s:14KeyboardKitPro5ProxyV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro5ProxyV25FullDocumentConfigurationV","text":"FullDocumentConfiguration"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/UITextDocumentProxy-Implementations"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/fullDocumentContextAfterInput(config:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"fullDocumentContextAfterInput","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy","preciseIdentifier":"s:14KeyboardKitPro5ProxyV","text":"Proxy","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro5ProxyV25FullDocumentConfigurationV","text":"FullDocumentConfiguration","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy\/FullDocumentConfiguration","kind":"typeIdentifier"},{"text":" = .standard) ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The configuration to use, by default "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy\/FullDocumentConfiguration\/standard","isActive":true,"type":"reference"},{"text":".","type":"text"}]}],"name":"config"}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"text":"This will read the document by moving the text input","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"cursor as defined by the provided configuration."}],"type":"paragraph"},{"name":"Important","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This requires at least a Silver license."}]}],"style":"important"}]}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/keyboardkitpro\/textinputproxy\/fulldocumentcontextafterinput(config:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"Get the full document context after the text cursor.","type":"text"}],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/fullDocumentContextAfterInput(config:)":{"title":"fullDocumentContextAfterInput(config:)","url":"\/documentation\/keyboardkitpro\/textinputproxy\/fulldocumentcontextafterinput(config:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fullDocumentContextAfterInput"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14KeyboardKitPro5ProxyV","kind":"typeIdentifier","text":"Proxy"},{"kind":"text","text":"."},{"text":"FullDocumentConfiguration","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro5ProxyV25FullDocumentConfigurationV"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/fullDocumentContextAfterInput(config:)","kind":"symbol","abstract":[{"text":"Get the full document context after the text cursor.","type":"text"}],"type":"topic","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy/FullDocumentConfiguration/standard":{"url":"\/documentation\/keyboardkitpro\/proxy\/fulldocumentconfiguration\/standard","title":"standard","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy\/FullDocumentConfiguration\/standard","type":"topic","abstract":[{"text":"The standard full document reader configuration.","type":"text"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"standard"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14KeyboardKitPro5ProxyV","kind":"typeIdentifier","text":"Proxy"},{"kind":"text","text":"."},{"preciseIdentifier":"s:14KeyboardKitPro5ProxyV25FullDocumentConfigurationV","text":"FullDocumentConfiguration","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy":{"title":"TextInputProxy","navigatorTitle":[{"text":"TextInputProxy","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TextInputProxy","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/keyboardkitpro\/textinputproxy","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy","kind":"symbol","type":"topic","abstract":[]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy/FullDocumentConfiguration":{"url":"\/documentation\/keyboardkitpro\/proxy\/fulldocumentconfiguration","kind":"symbol","abstract":[{"text":"This configuration can be used to configure how to read","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"full document context of a "},{"type":"codeVoice","code":"UITextDocumentProxy"},{"type":"text","text":" ."}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"FullDocumentConfiguration","kind":"identifier"}],"title":"Proxy.FullDocumentConfiguration","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy\/FullDocumentConfiguration","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FullDocumentConfiguration"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy":{"title":"Proxy","url":"\/documentation\/keyboardkitpro\/proxy","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Proxy"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy","abstract":[{"type":"text","text":"This namespace contains proxy-related types."}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"Proxy","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","url":"\/documentation\/keyboardkitpro","abstract":[{"type":"text","text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI."}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","title":"KeyboardKitPro","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/UITextDocumentProxy-Implementations":{"title":"UITextDocumentProxy Implementations","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/UITextDocumentProxy-Implementations","url":"\/documentation\/keyboardkitpro\/textinputproxy\/uitextdocumentproxy-implementations","abstract":[],"kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TextInputProxy","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/fragments","value":[{"kind":"identifier","text":"TextInputProxy"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/navigatorTitle","value":[{"kind":"identifier","text":"TextInputProxy"}],"op":"replace"}]}]}