{"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/fullDocumentContextBeforeInput(config:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/UITextDocumentProxy-Implementations"]]},"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","extendedModule":"UIKit","modules":[{"relatedModules":["UIKit"],"name":"KeyboardKitPro"}],"title":"fullDocumentContextBeforeInput(config:)","externalID":"s:So19UITextDocumentProxyP14KeyboardKitProE04fullB18ContextBeforeInput6configSSAC0C0V04FullB13ConfigurationV_tYaKF::SYNTHESIZED::c:@M@KeyboardKitPro@objc(cs)TextInputProxy","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"fullDocumentContextBeforeInput","kind":"identifier"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Proxy","preciseIdentifier":"s:14KeyboardKitPro5ProxyV","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"s:14KeyboardKitPro5ProxyV25FullDocumentConfigurationV","kind":"typeIdentifier","text":"FullDocumentConfiguration"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"fullDocumentContextBeforeInput","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"text":"Proxy","kind":"typeIdentifier","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy","preciseIdentifier":"s:14KeyboardKitPro5ProxyV"},{"kind":"text","text":"."},{"text":"FullDocumentConfiguration","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy\/FullDocumentConfiguration","preciseIdentifier":"s:14KeyboardKitPro5ProxyV25FullDocumentConfigurationV","kind":"typeIdentifier"},{"text":" = .standard) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The configuration to use, by default ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy\/FullDocumentConfiguration\/standard","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}],"name":"config"}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"inlineContent":[{"text":"This will read the document by moving the text input","type":"text"},{"type":"text","text":" "},{"text":"cursor as defined by the provided configuration.","type":"text"}],"type":"paragraph"},{"content":[{"inlineContent":[{"type":"text","text":"This requires at least a Silver license."}],"type":"paragraph"}],"name":"Important","type":"aside","style":"important"}]}],"abstract":[{"text":"Get the full document context before the text cursor.","type":"text"}],"variants":[{"paths":["\/documentation\/keyboardkitpro\/textinputproxy\/fulldocumentcontextbeforeinput(config:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy/FullDocumentConfiguration":{"url":"\/documentation\/keyboardkitpro\/proxy\/fulldocumentconfiguration","kind":"symbol","abstract":[{"text":"This configuration can be used to configure how to read","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"full document context of a "},{"type":"codeVoice","code":"UITextDocumentProxy"},{"type":"text","text":" ."}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"FullDocumentConfiguration","kind":"identifier"}],"title":"Proxy.FullDocumentConfiguration","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy\/FullDocumentConfiguration","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FullDocumentConfiguration"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy/FullDocumentConfiguration/standard":{"url":"\/documentation\/keyboardkitpro\/proxy\/fulldocumentconfiguration\/standard","title":"standard","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy\/FullDocumentConfiguration\/standard","type":"topic","abstract":[{"text":"The standard full document reader configuration.","type":"text"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"standard"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14KeyboardKitPro5ProxyV","kind":"typeIdentifier","text":"Proxy"},{"kind":"text","text":"."},{"preciseIdentifier":"s:14KeyboardKitPro5ProxyV25FullDocumentConfigurationV","text":"FullDocumentConfiguration","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/UITextDocumentProxy-Implementations":{"title":"UITextDocumentProxy Implementations","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/UITextDocumentProxy-Implementations","url":"\/documentation\/keyboardkitpro\/textinputproxy\/uitextdocumentproxy-implementations","abstract":[],"kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/fullDocumentContextBeforeInput(config:)":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/fullDocumentContextBeforeInput(config:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"fullDocumentContextBeforeInput","kind":"identifier"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro5ProxyV","text":"Proxy"},{"kind":"text","text":"."},{"text":"FullDocumentConfiguration","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro5ProxyV25FullDocumentConfigurationV"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","title":"fullDocumentContextBeforeInput(config:)","url":"\/documentation\/keyboardkitpro\/textinputproxy\/fulldocumentcontextbeforeinput(config:)","kind":"symbol","abstract":[{"text":"Get the full document context before the text cursor.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy":{"title":"Proxy","url":"\/documentation\/keyboardkitpro\/proxy","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Proxy"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy","abstract":[{"type":"text","text":"This namespace contains proxy-related types."}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"Proxy","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy":{"title":"TextInputProxy","navigatorTitle":[{"text":"TextInputProxy","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TextInputProxy","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/keyboardkitpro\/textinputproxy","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy","kind":"symbol","type":"topic","abstract":[]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","url":"\/documentation\/keyboardkitpro","abstract":[{"type":"text","text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI."}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","title":"KeyboardKitPro","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/title","value":"TextInputProxy"},{"value":[{"text":"TextInputProxy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/navigatorTitle","value":[{"text":"TextInputProxy","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}