{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasUnclosedAlternateQuotationBeforeInput","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":" "},{"text":"locale","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/UITextDocumentProxy-Implementations"]]},"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/hasUnclosedAlternateQuotationBeforeInput(for:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Whether the last trailing quotation before the input"},{"type":"text","text":" "},{"type":"text","text":"cursor is an alternate quotation begin delimiter."}],"variants":[{"paths":["\/documentation\/keyboardkitpro\/textinputproxy\/hasunclosedalternatequotationbeforeinput(for:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"method","externalID":"s:So19UITextDocumentProxyP14KeyboardKitProE40hasUnclosedAlternateQuotationBeforeInput3forSb10Foundation6LocaleV_tF::SYNTHESIZED::c:@M@KeyboardKitPro@objc(cs)TextInputProxy","modules":[{"name":"KeyboardKitPro","relatedModules":["UIKit"]}],"role":"symbol","extendedModule":"UIKit","roleHeading":"Instance Method","title":"hasUnclosedAlternateQuotationBeforeInput(for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hasUnclosedAlternateQuotationBeforeInput"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation6LocaleV","kind":"typeIdentifier","text":"Locale"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"kind":"symbol","references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy":{"title":"TextInputProxy","navigatorTitle":[{"text":"TextInputProxy","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TextInputProxy","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/keyboardkitpro\/textinputproxy","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy","kind":"symbol","type":"topic","abstract":[]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","url":"\/documentation\/keyboardkitpro","abstract":[{"type":"text","text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI."}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","title":"KeyboardKitPro","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/UITextDocumentProxy-Implementations":{"title":"UITextDocumentProxy Implementations","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/UITextDocumentProxy-Implementations","url":"\/documentation\/keyboardkitpro\/textinputproxy\/uitextdocumentproxy-implementations","abstract":[],"kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/hasUnclosedAlternateQuotationBeforeInput(for:)":{"title":"hasUnclosedAlternateQuotationBeforeInput(for:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasUnclosedAlternateQuotationBeforeInput"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/hasUnclosedAlternateQuotationBeforeInput(for:)","type":"topic","url":"\/documentation\/keyboardkitpro\/textinputproxy\/hasunclosedalternatequotationbeforeinput(for:)","abstract":[{"type":"text","text":"Whether the last trailing quotation before the input"},{"type":"text","text":" "},{"type":"text","text":"cursor is an alternate quotation begin delimiter."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TextInputProxy","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/fragments","value":[{"kind":"identifier","text":"TextInputProxy"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/navigatorTitle","value":[{"text":"TextInputProxy","kind":"identifier"}],"op":"replace"}]}]}