{"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/returnKeyType"},"variants":[{"paths":["\/documentation\/keyboardkitpro\/textinputproxy\/returnkeytype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/textinputproxy\/returnkeytype"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"returnKeyType","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIReturnKeyType","preciseIdentifier":"c:@E@UIReturnKeyType","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"returnKeyType"}],"modules":[{"name":"KeyboardKitPro"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@KeyboardKitPro@objc(cs)TextInputProxy(py)returnKeyType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"returnKeyType","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIReturnKeyType","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIReturnKeyType"}],"symbolKind":"property","title":"returnKeyType"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UITextInputTraits.returnKeyType","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/returnKeyType":{"type":"topic","navigatorTitle":[{"text":"returnKeyType","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"returnKeyType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIReturnKeyType","text":"UIReturnKeyType"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/returnkeytype","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/returnKeyType","title":"returnKeyType"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy","abstract":[{"type":"text","text":"This class can be used to route typed text from the main"},{"text":" ","type":"text"},{"text":"app to text fields within the keyboard extension.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextInputProxy"}],"title":"TextInputProxy","navigatorTitle":[{"kind":"identifier","text":"TextInputProxy"}],"type":"topic","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","url":"\/documentation\/keyboardkitpro","type":"topic","title":"KeyboardKitPro","abstract":[{"type":"text","text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI."}],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"returnKeyType"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"returnKeyType","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"UIReturnKeyType","preciseIdentifier":"c:@E@UIReturnKeyType","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"returnKeyType","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"returnKeyType","op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1returnKeyType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1returnKeyType\/fragments","value":[{"kind":"identifier","text":"returnKeyType"}]},{"value":"TextInputProxy","op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/title"},{"value":[{"text":"TextInputProxy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/fragments","op":"replace"}]}]}