{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"smartInsertDeleteType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextSmartInsertDeleteType","preciseIdentifier":"c:@E@UITextSmartInsertDeleteType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/keyboardkitpro\/textinputproxy\/smartinsertdeletetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/textinputproxy\/smartinsertdeletetype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/smartInsertDeleteType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UITextInputTraits.smartInsertDeleteType"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"smartInsertDeleteType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextSmartInsertDeleteType","preciseIdentifier":"c:@E@UITextSmartInsertDeleteType"}],"title":"smartInsertDeleteType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@KeyboardKitPro@objc(cs)TextInputProxy(py)smartInsertDeleteType","modules":[{"name":"KeyboardKitPro"}],"navigatorTitle":[{"kind":"identifier","text":"smartInsertDeleteType"}]},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy"]]},"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/smartInsertDeleteType":{"role":"symbol","title":"smartInsertDeleteType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"smartInsertDeleteType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextSmartInsertDeleteType","preciseIdentifier":"c:@E@UITextSmartInsertDeleteType"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/smartInsertDeleteType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"smartInsertDeleteType"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/smartinsertdeletetype"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","title":"KeyboardKitPro","abstract":[{"type":"text","text":"KeyboardKit Pro helps you build custom keyboard extensions for iOS and iPadOS."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkitpro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy":{"role":"symbol","title":"TextInputProxy","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextInputProxy"}],"abstract":[{"type":"text","text":"This class can be used to route text from an app to another"},{"type":"text","text":" "},{"type":"text","text":"text field, for instance in keyboard extension itself."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TextInputProxy"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"smartInsertDeleteType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"smartInsertDeleteType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UITextSmartInsertDeleteType","preciseIdentifier":"c:@E@UITextSmartInsertDeleteType"},{"kind":"text","text":" "},{"kind":"identifier","text":"smartInsertDeleteType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1smartInsertDeleteType\/title","value":"smartInsertDeleteType"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1smartInsertDeleteType\/fragments","value":[{"kind":"identifier","text":"smartInsertDeleteType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/title","value":"TextInputProxy"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/fragments","value":[{"kind":"identifier","text":"TextInputProxy"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}