{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkitpro\/textinputproxy\/smartquotestype"]},{"paths":["\/documentation\/keyboardkitpro\/textinputproxy\/smartquotestype"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"smartQuotesType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UITextSmartQuotesType","preciseIdentifier":"c:@E@UITextSmartQuotesType"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","title":"smartQuotesType","navigatorTitle":[{"text":"smartQuotesType","kind":"identifier"}],"externalID":"c:@M@KeyboardKitPro@objc(cs)TextInputProxy(py)smartQuotesType","modules":[{"name":"KeyboardKitPro"}]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"UITextInputTraits.smartQuotesType","type":"codeVoice"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/smartQuotesType"},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"smartQuotesType"},{"kind":"text","text":": "},{"text":"UITextSmartQuotesType","preciseIdentifier":"c:@E@UITextSmartQuotesType","kind":"typeIdentifier"}]}]}],"kind":"symbol","references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy","abstract":[{"type":"text","text":"This class can be used to route typed text from the main"},{"text":" ","type":"text"},{"text":"app to text fields within the keyboard extension.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextInputProxy"}],"title":"TextInputProxy","navigatorTitle":[{"kind":"identifier","text":"TextInputProxy"}],"type":"topic","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","url":"\/documentation\/keyboardkitpro","type":"topic","title":"KeyboardKitPro","abstract":[{"type":"text","text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI."}],"role":"collection","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/smartQuotesType":{"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/smartQuotesType","url":"\/documentation\/keyboardkitpro\/textinputproxy\/smartquotestype","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"smartQuotesType"},{"kind":"text","text":": "},{"text":"UITextSmartQuotesType","preciseIdentifier":"c:@E@UITextSmartQuotesType","kind":"typeIdentifier"}],"title":"smartQuotesType","navigatorTitle":[{"text":"smartQuotesType","kind":"identifier"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"smartQuotesType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"smartQuotesType"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"UITextSmartQuotesType","kind":"typeIdentifier","preciseIdentifier":"c:@E@UITextSmartQuotesType"},{"text":" ","kind":"text"},{"text":"smartQuotesType","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"TextInputProxy","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/title"},{"value":[{"kind":"identifier","text":"TextInputProxy"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/fragments","op":"replace"},{"op":"replace","value":"smartQuotesType","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1smartQuotesType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1smartQuotesType\/fragments","value":[{"text":"smartQuotesType","kind":"identifier"}]}]}]}