{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"spellCheckingType","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UITextSpellCheckingType","text":"UITextSpellCheckingType","kind":"typeIdentifier"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/spellCheckingType"},"metadata":{"navigatorTitle":[{"text":"spellCheckingType","kind":"identifier"}],"title":"spellCheckingType","externalID":"c:@M@KeyboardKitPro@objc(cs)TextInputProxy(py)spellCheckingType","role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"spellCheckingType"},{"kind":"text","text":": "},{"text":"UITextSpellCheckingType","kind":"typeIdentifier","preciseIdentifier":"c:@E@UITextSpellCheckingType"}],"platforms":[],"roleHeading":"Instance Property","modules":[{"name":"KeyboardKitPro"}]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"UITextInputTraits.spellCheckingType","type":"codeVoice"},{"text":".","type":"text"}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"This is no longer used and will be removed in KeyboardKit 9."}],"type":"paragraph"}],"kind":"symbol","variants":[{"paths":["\/documentation\/keyboardkitpro\/textinputproxy\/spellcheckingtype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkitpro\/textinputproxy\/spellcheckingtype"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy"]]},"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/spellCheckingType":{"title":"spellCheckingType","navigatorTitle":[{"text":"spellCheckingType","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/spellcheckingtype","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/spellCheckingType","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"spellCheckingType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UITextSpellCheckingType","preciseIdentifier":"c:@E@UITextSpellCheckingType","kind":"typeIdentifier"}],"type":"topic","deprecated":true},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","url":"\/documentation\/keyboardkitpro","abstract":[{"type":"text","text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI."}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","title":"KeyboardKitPro","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy":{"title":"TextInputProxy","navigatorTitle":[{"text":"TextInputProxy","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TextInputProxy","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/keyboardkitpro\/textinputproxy","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy","kind":"symbol","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"spellCheckingType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"spellCheckingType","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UITextSpellCheckingType","kind":"typeIdentifier","preciseIdentifier":"c:@E@UITextSpellCheckingType"},{"text":" ","kind":"text"},{"kind":"identifier","text":"spellCheckingType"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1spellCheckingType\/title","value":"spellCheckingType","op":"replace"},{"value":[{"kind":"identifier","text":"spellCheckingType"}],"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1spellCheckingType\/fragments"},{"value":"TextInputProxy","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/fragments","value":[{"text":"TextInputProxy","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"TextInputProxy"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/navigatorTitle"}]}]}